### ISSUE TITLE
Global (or inherited) query arguments?

### ISSUE THREAD

**Issue by clader** [rmosolgo/graphql-ruby#1113]
(Apologies if this is a dup; I searched other issues and found a few close to this but not exactly)

I’m writing a graphql-ruby frontend to openldap. As we have multiple different ldap environments, I’ve created an argument field for all object/connections queries where you can choose which LDAP environment you want to run that query against. 

A single ldap objects (user or group) has various connections to other LDAP objects. (i.e a user object had many “memberOfs” which lead to various group objects, for instance)

I’m trying to figure out what best practice (if any) there is for referencing a query argument from the top level/parent query and having that “inherit” down to any/all sub/2ndary queries on the returned objects. 

Alternately if there’s some way to specify a “global” query argument that gets appended to all subqueries that could work too. 

My currently implementation requires the ”env” argument to be specified at the top level query as well as each connection/association sub query. 

Obviously i could use query variables to specify the same “env” query argument value in “all the places”, but I’d prefer to let the api client specify it once at the top level query and not have to remember to specify it at each sub-query (otherwise the env would revert to the default value, if they forgot to specify). 

I’ve found ways to reference the top level argument selections from the ctx.query object, but as pointed out in another issue, this breaks if query variables are used for the value of the argument, as the resolved value isn’t referanceable anywhere, just then”raw” value (which shows as the variable name)

Realize this is a long shot, but if there are any solutions I’d love to find out.

**Comment by rmosolgo** [comment]
Hi, thanks for the details about this issue! I think I understand what you're saying: you want to take some "environment" options at the top level query, then access those at later levels. 

I can think of a few options with different tradeoffs: 

- Write the "global" value to `ctx`. You can assign a value from the arguments like `ctx[:setting] = args[:setting]`, then call `ctx[:setting]` to read the value later. There's one downside though: if you're using any non-serial execution behavior (like `graphql-batch`) and there is _more than one_ setting in a query, you could get unexpected results, since the settings might override each other! If you want to guarantee there's only _one_ "root" field, you could assert that with a [query analyzer](http://graphql-ruby.org/queries/analysis.html). 
- It's possible to _backtrack_ the graphql query by using `ctx.parent` recursively (`.parent.parent.parent ... `)  and reach "backward" to previous fields. It's a bit of a hacky API, but you could get the parent arguments by using `ctx.parent.irep_node.arguments`. It would be tricky, but it would properly support multiple "roots" in a query. 
- Set the "env" _outside_ graphql: use query params to populate `context:` and access them inside the query. Not a great client experience since you mix GraphQL & non-GraphQL semantics. 

What do you think of those, do any of them sound like they're heading in the right direction?

**Comment by clader** [comment]
Thanks so much for the suggestions.  I think number 1 sounds the best to me and is most like what I was hoping to find.  

Big gotcha though: I just implemented graphql-batch for query reduction for this graphql LDAP front-end (which, btw works AMAZEBALLS in front of LDAP directory data and reduces multi-level association queries by several orders of magnitude).  

I think I can put some logic in my resolvers, however, to only take the env argument from the top level query and commit it to the ctx, and not do so from any of the others (since it's easy to check if the current resolver is for a top level query by seeing of 'if obj == false ).  Additionally the env arg is one of the arguments I pass to the BatchLoader 'for' function (along with the my LDAP connection object for that env, which hopefully should resolve any conflicts with Batch Loading.

I'll give this a try and let you  know how it works and look into query analyzer to prevent multiple root level queries with different env args.
Thanks again!

**Comment by rmosolgo** [comment]
I thought of another simple way to deal with mismatched values in `context`. If you can _require_ that all queries have only one env, you can check: 

```ruby 
if ctx[:env_setting].nil? 
  # set the value, continue
elsif ctx[:env_setting] == args[:env_setting] 
  # it's already set to this value, continue
else 
  # it's already set to a *different* value, this is invalid 
  raise GraphQL::ExecutionError, "Only one env_setting is allowed per query, a previous field used #{ctx[:env_setting]}, but this field passed #{args[:env_setting]}."
end 
```

Anyhow, glad you found something that looks promising, feel free to post here if you have issues along the way!
