### ISSUE TITLE
`BuildFromDefinition` Issue with overriding scalars.

### ISSUE THREAD

**Issue by xuorig** [rmosolgo/graphql-ruby#1123]
Currently it's in theory possible to override scalars and directives when providing an IDL to `BuildFromDefinition`

However, when it comes to scalars, there's weird behaviour happening when only overriding scalars and not directives.

If I provide this IDL:

```
scalar String
```

We'll see this error happen:

`RuntimeError: Duplicate type definition found for name 'String'`

This is because our schema uses the Built In directives, and these built in directives use the built in `String` scalar.

This causes a weird inconsistency where all other types use our overriden String scalar, and built in directives use `GraphQL::STRING_TYPE`.

### Solution?

I'm honestly not sure what the correct solution to this is. At first I thought that maybe we should raise when overriding built ins, but this test https://github.com/xuorig/graphql-ruby/blame/master/spec/graphql/schema/build_from_definition_spec.rb#L97 seems to say that it should be possible.

If it should be possible, then we should probably redefine built in directives using the overriden types in these cases.

**Comment by rmosolgo** [comment]
Wow, this is something I've put off for a long time because we never really quite needed it. 

When you're defining a schema, there's currently no way to say "This field returns a type _named_ `"X"`, within the current schema." You can use a Ruby reference to another type, or you can use a Ruby reference to one of the built-in types (like `STRING_TYPE`), but you can't say `"User"` and have it connect to `MyApp::Graph::UserType` or whatever. There's just no way to use `Schema.types[name]` lookup. 

The reason is because the schema doesn't _exist_ at the time that a type or field is defined. There's no schema where the lookup can be performed. 

What's more, a given type or field could be present on _multiple_ schemas, so however it was implemented, you'd have to take care to maintain the "within Schema _S1_, not _S2_" distinction. 

So, I'm open to implementing this somehow, where a field retains a _string_ for the "return_type", then the return type is looked up against the current schema. But I think it will be a bit tricky, since a field can be in multiple schemas!

**Comment by xuorig** [comment]
> "This field returns a type named "X", within the current schema." 

Ah! this is exactly what i was wondering about when I hit this issue. This is indeed really tricky. Glad Im not crazy and you've thought of that before though 😅

**Comment by rmosolgo** [comment]
> "This field returns a type named "X", within the current schema."

I did a quick-and-dirty private implementation of this here: 

https://github.com/rmosolgo/graphql-ruby/pull/1170/commits/f0649ae2b9b6ff53f985b10be75961f2da33f3e8#diff-40eb38de44bb575db6ed064da7e6535bR7

So, if we can find a good way to integrate it with the public API, we could support this 😬

**Comment by rmosolgo** [comment]
It doesn't seem like this has come up for almost 2 years, so I'm not going to consider it a problem.
