### ISSUE TITLE
Is there a way to define self-referential types

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#118]
I have a model called 'Page' that is hierarchical. It defined a 'pages' property that returns a collection of child Pages.  In representing this in GraphQL, I tried:

```
    page_type = GraphQL::ObjectType.define do
      name "Page"
      description "A page"

      field :id, !types.String
      field :name, !types.String
      field :content, !types.String
      #field :pages, -> { !types[!page_type] }, "Child Pages"
      field :pages do
        type !types[!page_type]
        resolve -> (obj, args, ctx) { obj.pages}
      end
    end
```
However, queries that return a page_type or list of page_types return the following error:

```
.../lib/graphql/definition_helpers/type_definer.rb:25:in `[]': undefined method 'to_list_type' for true:TrueClass (NoMethodError)

```

If I define the 'pages' field using the alternate syntax (shown commented out), it works.  Is this a bug or am I missing something?

**Comment by rmosolgo** [comment]
the `field do ... end ` block is _not_ lazy, so you'd need to use the proc inside there too, for example: 

```ruby
      field :pages do
        type -> { !types[!page_type] }
        resolve -> (obj, args, ctx) { obj.pages}
      end
```

>  Is this a bug ... ? 

Maybe -- I'm definitely trying to find a better way to support this case because it's quite common, especially when your load order is indeterminate. 

I thought of a few things but gave up: 

- Accept a string constant name (eg `type: "PageType"`). This is ok (and it's supported now) but if you're defining your schema programmatically, your types might not be named by global constants. 
- Accept a string type name (eg, `type: "Page"`). This is nice, but the challenge is, where do you look up that string? A type doesn't have access to its schema, and theoretically (at least for now) it could be a member of two different schemas. ("Two different schemas" is only partially supported -- maybe I should drop support for that and get on with it.)

So, I definitely _want_ a nicer API for that, but I'm not sure how to implement it!

**Comment by blevine** [comment]
Ah, I should have thought of that!  Defining the proc works fine.  And I can't think of a better way either.  Thanks for the help!
