### ISSUE TITLE
[pro] [authorization] practical application of fallback

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#1192]
## The problem(s)

I am trying to adopt the pro authorization framework and the cancan integration, but am running into serious problems, and since my use case seems pretty simple, I wanted to document it here.

Some background: We have a 100% private API that is about to become 95% private. To handle this transition, I am trying to utilize the `fallback` API with our CanCan config to make all fields private by default, unless I specify otherwise. This is simple enough with:

```ruby
authorization(:cancan, fallback: { view: :private_api })
```

And then overriding with `view: :public_api` on a per field / type basis. However, **I can't see a way to override authorization from default on generated Relay connection types**, so I end up with lots of "Field 'edges' doesn't exist on type 'BlahConnection'" in my public API responses, even when the field and connection's wrapped type are marked as public. This seems like a glaring omission so perhaps its just not documented?

Secondly, a major purpose of CanCan is to move the job of authorization out of your business logic, however the `view` and `access` authorizations don't really make this possible. Since they do not pass _anything_ to Ability, not even the field's return type, instead of having a common action and a differing resource, we have to have differing actions for all levels of authorization. To crib from the auth docs: `view: :logged_in` becomes `can? :logged_in, nil`. Whats cancan for in this instance? Instead of providing enough context to the Ability class, the required _role_ has leaked back into the application code.

So instead I tried runtime checks, even though I know at compile time what access levels I have, because at least then Ability has access to the object being authorized. But runtime checks have a problems of their own... When used with fallback, they are applied even to scalar fields. So now I need to add to my Ability `can :read, [String, Integer, Float, TrueClass, FalseClass]`, which seems ridiculous. The alternative is to add `authorize: {parent_role: ...}` to _every scalar field in the schema_. We've been graphql-ruby fans for a long time, so that's a lot of code :'(. 

## Thoughts

The smallest fix that would make my issues go away is I suppose using `fallback` with `authorize`, but changing the behaviour of `fallback` to _not_ be applied to scalar fields. Alternatively perhaps the behaviour of `allowed?(gate, value)` could be changed to include the parent object as `value` when the return type is a Scalar.

At a higher level the language of the authorization framework seems wrong to me. While it uses the term 'role', in practice this value is mapped to an "action" in CanCan terminology and a "query method" in Pundit. Perhaps a better term would be "action"?

**Comment by rmosolgo** [comment]
Hey @bessey, sorry I didn't write back sooner! I've been a bit busy with a new kiddo in the house. Thanks for putting together such a detailed issue, I'll address each point soon!

**Comment by rmosolgo** [comment]
Thanks again for spending time on such a great issue description. I've been stewing on the idea of adding a built-in authorization framework after releasing 1.8, and your use case is really informative for that. The framework in graphql-pro is better for "public by default, private by override", but your case is different, and it seems like it's not working well 😖  

> override authorization from default on generated Relay connection types

The feature doesn't exist, so I think that would put it in the "glaring omission" category 😓  

> `view` and `access` authorizations don't really make this possible

I totally see what you mean here: with _Pundit_, you have some information encoded in the form of policy class selection: when a policy class is initialized with `nil`, you can know that the value isn't available yet. But there's no analog with CanCan, since there's just one Ability class. 

So, here's a small patch to modify the behavior of the built-in CanCan auth: 

```ruby 
class GraphQL::Pro::Access::CanCanStrategy 
  def allowed?(gate, value) 
    if value.nil? 
      # `nil` is never authorized at runtime, so we can be sure that this is an ahead-of-time check 
      @ability.can?(gate.role, gate.owner)
    else 
      @ability.can?(gate.role, value) 
    end 
  end 
end 
```

In this case, `gate.owner` is sent to `can?` for ahead-of-time checks. The owner may be: 

- a `GraphQL::Field` instance, when fields have auth applied to them 
- an instance of one of `GraphQL::BaseType`'s child classes, when type definitions have auth applied to them (eg `GraphQL::ObjectType`, `GraphQL::ScalarType`)
- the `GraphQL::Schema` instance, when the `fallback` role is being applied 

Well, now I'm trying to think through it, and it's still not _quite_ there, because of the Relay issue you mentioned. With the patch above, you could apply a `fallback` rule and disallow access whenever `can?(anything, MySchema)` is called. But what about the Relay objects like `pageInfo`? Those will get the fallback rule, and there's no way to detect that the current field is a `relay?` field, since it's not accessible there. 

So... How to address that? You could introduce a concept for automatic fields specifically, something like: 

- If an automatic field is a "generic" (like `edges`), use the rule from the contained type. 
- If an automatic field is not a generic, apply some default rule. (Visible by default, in your case, right? If you can see a connection field, you can always see its `pageInfo`?) 
 
It feels like a game of whack-a-mole, but it might work.


> The smallest fix ... changing the behaviour of fallback to not be applied to scalar fields. 

Here's a quick monkey-patch to have that effect: 

```ruby 
class GraphQL::Pro::Access::Instrumentation 
  def instrument(type, field) 
    field_return_type = field.type.unwrap 
    # If a parent object has passed authorization, then its scalars may be accessed: 
    if field_return_type.is_a?(GraphQL::ScalarType) 
      field = field.redefine(authorize: :always) 
    end 
    super(type, field) 
  end 
end 
```

(It requires a `can(:always, :all)` rule.) 

That way, the fallback rule won't apply to scalars, since they all have their own rule (`:always`).

Want to give it a try and see how it goes?

**Comment by rmosolgo** [comment]
Ok, that last bit gave me an idea: how about applying authorization rules programatically, via an instrumenter? Similar to the monkeypatch above, but as a stand-alone instrumenter, for example:

```ruby 
class AllowScalarFields 
  def instrument(type, field) 
    field_return_type = field.type.unwrap 
    # If a parent object has passed authorization, then its scalars may be accessed: 
    if field_return_type.is_a?(GraphQL::ScalarType) 
      field = field.redefine(authorize: :always) 
    end 
    field 
  end 
end 
```

I think it would have to be in the schema definition _before_ the `authorize(...)` configuration, for example: 

```ruby
MySchema = GraphQL::Schema.define do 
  instrument(:field, AllowScalarFields)
  authorize(...)
end 
```

You could do something similar to programatically allow fields like `edges` and `pageInfo`: 

```ruby 
class AllowRelayFields 
  def instrument(type, field) 
    if field.name == "pageInfo" || field.name == "edges" 
      field = field.redefine(authorize: :always)
    end 
    field 
  end 
end 
```

In a case like that, we depend on the parent object for authorization: if the connection field is allowed, its `edges` and `pageInfo` fields will be allowed. If the connection field is _not_ allowed, then execution will halt before we reach its child fields.

**Comment by bessey** [comment]
Thanks for the detailed reply! I had great success with your two instrumenters. Its my first time using that API actually, very nice stuff.

That alone takes care of my issues, but I certainly have thoughts based on my use case on other parts too.

With respect to your suggested patch to the cancan strategy:
> In this case, gate.owner is sent to can? for ahead-of-time checks. The owner may be:
> [...]
> the GraphQL::Schema instance, when the fallback role is being applied

This behaviour seems surprising to me. I did try hacking on the CanCan strategy too, but this bit me. What is the reason for not returning the `GraphQL::Field` instance for fallback fields? I was anticipating being able to whitelist some fields on my query type for public visibility, but because the fields have to be authorized individiually, its not a true whitelist, in that other devs adding new fields would need to know that they must add an `authorize: {view: ...}` to each new field. That said, as you mention, this is only an issue with a private first API.

**Comment by bessey** [comment]
I've had some more time to experience this solution in the wild, and now I'm curious as to why _anyone_ would want the default behaviour of this API (scalars locked down, no access to parent type info). Could you give an example where this might come in handy?

Say I have a User type with a name field and a secret field. Clearly a user should be able to read their own name, and perhaps names of others, but should not be able to read anyone's secret but their own. The default behaviour when traversing a query like 
```gql
query AllUsers {
  users { # authorize: :read
    email # authorize: :read
    secret  # authorize :read_secrets
  }
}
```
Is to ask "Can I :read each user object?" thats useful. Perhaps I can only read non admins for example. But once we've traversed that layer, the next questions are "Can I :read the string 'a@b.com'" and "Can I :read_secrets the string 'password123'?". As far as I can tell no context is passed to CanCan to enable it to understand the context of the strings, so the only options are 

- Expect the user to define `can :read, String`
- Expect the user to add `authorize: {parent_role: :read}`

I'm just failing to see a legitimate use case for this default behaviour.

**Comment by rmosolgo** [comment]
There's a new CanCan integration for the class-based API that leverages the new built-in auth framework. It uses inheritance to pass along behavior, so I think it will work a lot better for this use case. You can read more here: http://graphql-ruby.org/authorization/can_can_integration#authorizing-objects

If you get a chance to try a migration, let me know! Happy to help out on any bumps along the way.
