### ISSUE TITLE
[1.8] Argument to_h

### ISSUE THREAD

**Issue by joshforbes** [rmosolgo/graphql-ruby#1281]
On 1.7 I am able to call args.to_h on an argument and any nested input objects will also be converted. On 1.8 this will only convert the top level object all the nested items will remain as objects. Not sure if this was an intentional change.

Specifically for me this is happening in the context of a graphql function but I suspect it would be true anywhere.

**Comment by rmosolgo** [comment]
No, it wasn't intentional, I noticed it myself too and just hacked around it 😖  

The problem is that in 1.8, `args` is converted to a real Ruby Hash, so `.to_h` calls `Hash#to_h`, not `GraphQL::Query::Arguments#to_h`. I don't really want to monkey-patch `Hash#to_h`, because that could have some unexpected side effects. 

🤔  I wonder what options we have for providing the same deep `to_h` behavior ...

**Comment by jturkel** [comment]
I hit this issue too and also hacked around it. Would it make sense to modify `GraphQL::Schema::InputObject#to_kwargs` to always do a "deep" `to_kwargs`?

**Comment by joshforbes** [comment]
With the way mutation and resolver objects handle arguments now. This is no longer a concern for me. I don't know if it is relevant for others?

**Comment by jturkel** [comment]
I'm still hitting this issue using the class based mutation API.
