### ISSUE TITLE
invalid enum value causes an exception

### ISSUE THREAD

**Issue by axos88** [rmosolgo/graphql-ruby#1285]
If a field returns a value that cannot be resolved to an enum value (or any other error occurs in the coerce_result field for that matter), an exception bubbles up, causing a 500:

Seems like this should be wrapped in a begin-rescue block:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/execute.rb#L156,L160

```
begin
  resolve_value(
            raw_value,
            field_ctx.type,
            field_ctx,
  )
rescue GraphQL::Error => e
  continue_resolve_field(e, field_ctx)
```

**Comment by rmosolgo** [comment]
Hi, sorry for the delay here. I think this error is intentional: 

https://github.com/rmosolgo/graphql-ruby/blob/344a965121a9c439a0d29b0f736fa9ff555780e8/lib/graphql/enum_type.rb#L125

When a resolver returns an invalid value, this is an application error which should be addressed by a developer. For this reason, I think the error should be escalated to the application's bug tracker so that application logic can be corrected. 

Maybe the best would be to raise the error _and_ return `nil` to the client, but I'm not sure how to implement. In my experience, this error is very rare in production so it's night high-priority to me.
