### ISSUE TITLE
result.context[:subscription_id] is nil

### ISSUE THREAD

**Issue by dpaola2** [rmosolgo/graphql-ruby#1325]
I am following the Pusher implementation guide here: http://graphql-ruby.org/subscriptions/pusher_implementation.html

When I inspect my `result.context` in the execution configuration, the `result.context[:subscription_id]` is `nil`. I've dug around a little bit in the code and can't quite figure out why this might be.

**Comment by mortik** [comment]
I'm having the same issue

Running on 1.9.3

**Comment by rmosolgo** [comment]
Hi! If you want to debug please help me by: 

- Your schema configuration with any Subscription-related code
- Showing the controller code where you check `result.context[:subscription_id]` 
- Showing a query which you _expect_ to set `context[:subscription_id]`
- The subscription field which corresponds to ☝️ that query
- Some debug output (like a Rails log) which shows that there's nothing in `context[:subscription_id]`

Then we can go from there!

**Comment by mortik** [comment]
I used the Subscriptions Guide here: https://graphql-ruby.org/subscriptions/subscription_classes.html
To move my Subscription field definition located in my SubscriptionType to Subscription Classes.

So instead of defining a field like this:
```
class Types::SubscriptionType < Types::BaseObject
   field :message_was_posted, Types::MessageType, null: false do
      argument :room_id, ID, required: true
   end
end
```
I changed it to this:
```
class Types::SubscriptionType < Types::BaseObject
  field :message_was_posted, subscription: Subscriptions::MessageWasPosted
end
```

And defined the MessageWasPosted Class like in the Guide.

I'm using ActionCable and setup the Channel like in the Documentation here: https://graphql-ruby.org/api-doc/1.9.3/GraphQL/Subscriptions/ActionCableSubscriptions

When i create a Subscription with this new setup ```result.context[:subscription_id]``` and ```context[:subscription_id]``` is always empty, which is not the case when i move back to the old setup without a Subscription Class.
