### ISSUE TITLE
Resolve not called in subscriptions

### ISSUE THREAD

**Issue by gastonmorixe** [rmosolgo/graphql-ruby#1341]
Digging into the code I see the instance variable but it's never used.

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions/instrumentation.rb#L42

Example: (resolve never called)

```ruby
Types::SubscriptionType = GraphQL::ObjectType.define do
  name 'Subscription'
  # field :personChanged, !Types::PersonType, "A person was updated"
  field :personChanged do
    argument :id, !types.ID 
    subscription_scope :current_person    
    type !Types::PersonType
    description 'A person was updated'
    resolve ->(obj, args, ctx) { 
      logger.debug " ---->>>> OBJ", {obj: obj, args: args, ctx: ctx}
      obj
    }
  end
end
```

**Comment by rmosolgo** [comment]
Yeah, I think I side-stepped this issue because, on the one hand, it isn't needed: 

- During the initial `subscription` query, we don't execute any fields, so we don't need to call the resolve function 
- During later updates, the `trigger` call already includes the `obj`, so we don't need to resolve anything 

Can you help me understand what you're hoping to do with `resolve` in this case? Maybe the design should be reconsidered, or maybe there's some work-around for now!
