### ISSUE TITLE
Enums not referenced in the schema but included in orphan_types are excluded from introspection

### ISSUE THREAD

**Issue by chanks** [rmosolgo/graphql-ruby#1351]
I have an issue - I've defined an enum type that's not used in the schema anywhere, but is helpful to the client, so I'd like it to appear in the introspection query. I had thought that including the type in the orphan_types array would make that happen, but unfortunately it seems that that's not the behavior (any longer?), and judging from #1224 and #919 it seems like that might have been an intentional change?

So I guess there are two issues here:
- If that's not the purpose of `orphan_types` then I think the documentation needs updating, and maybe some indication of how to get orphan types to appear in the schema.
- If that is the purpose of `orphan_types` then it seems that it was broken by the warden changes in #919.

I can put together a reproduction if it helps, but the problem seems to be that when I use a debugger to step through `Warden#visible_type?` (https://github.com/rmosolgo/graphql-ruby/blob/f6aab69afe53505f0bb4e0bf8fbae9e6152e4fd2/lib/graphql/schema/warden.rb#L138) with my enum, the `visible?` call returns true but the other checks all return false.

Thanks!

**Comment by rmosolgo** [comment]
Hmm, yes, it _is_ an intentional change, but sorry it broke your schema! 

I'm not sure quite what to say because I think the new behavior is a good one: types are hidden unless they're connected to the schema somehow. This is good because, if you're using schema hiding as a privacy tool, you don't want to "leak" things that aren't connected. 

As a work-around, what about adding a field somewhere that _does_ return that enum type? For example `Query.{whatever}Values: [WhateverEnum!]` that returns each possible value. Would something like that work for you? 

I imagine it's _possible_ to add some kind of visibility override, but I'm not yet convinced it's worth the complexity 😬

**Comment by chanks** [comment]
Hmm, ok, what's the point of the orphan_types configuration then? The docs read to me like the goal of it is to force things to appear in the schema when they wouldn't, otherwise.

That does seem like a decent workaround, I already have an array of all our enum types so I can just iterate over that.

**Comment by rmosolgo** [comment]
It's real raison d'etre is for interfaces: if `I` has implementation `O` but `O` is not the return type of any field in the schema, then it's impossible to find `O` simply by traversing the schema. In that case, you have to explicitly add it via `orphan_types`. That's what it's _for_, I didn't know it could have other uses 😆

**Comment by chanks** [comment]
Ah, ok, so the distinction is that it works for Object types but not Enum types? Or other types, I suppose.

**Comment by rmosolgo** [comment]
I think it will only work for Object types _if_ they implement an interface _and_ that interface is not hidden!

**Comment by chanks** [comment]
Hmm, ok. Well, I'll leave it up to you then, if you think that's the best purpose of the orphan_types setting, feel free to close this, I'm happy to just implement the workaround you mentioned (I'm most of the way through it now anyway). Or leave this open and think about it, either way :smile:
