### ISSUE TITLE
coerce_input called twice during execution.

### ISSUE THREAD

**Issue by phyllisstein** [rmosolgo/graphql-ruby#1376]
I've been trying to work with a scalar type that accepts nested JSON parameters, and I'm running into some trouble with its `coerce_input`. It seems as though the coercion is being called twice per execution, and I can't for the life of me figure out why.

To reproduce the issue, I created a mutation like this:

```rb
Mutations::UpdateNode = GraphQL::Field.define do
  name 'updateNode'
  description 'Updates the properties of a preexisting node.'

  type Types::Node
  argument :node, Types::CoercionTest
end
```

...and a scalar type like this:

```rb
Types::CoercionTest = GraphQL::ScalarType.define do
  name 'CoercionTest'

  coerce_result ->(value, _ctx) { value }
  coerce_input lambda { |value, _ctx|
    puts 'Called CoercionTest#coerce_input'
    value
  }
end
```

...and fired off a query:

```
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"mutation UpdateNode($node: CoercionTest) {\n  updateNode(node: $node)\n}", "variables"=>{"node"=>{"uuid"=>"f78d2a2a-89ab-4177-9c6f-9a0592f76019", "title"=>"Entitled", "type"=>"Hero"}}, "operation_name"=>"UpdateNode"}
Called CoercionTest#coerce_input
Called CoercionTest#coerce_input
Completed 200 OK in 33ms (Views: 0.1ms)
```

This is causing particular trouble with the GraphQL upload gem, since the attachment in the params is closed by the second time the request goes through. I think it may also be related to the duplicative error message in #1269, though I'm not totally sure.

If you have any thoughts or suggestions I'd be super grateful to hear them. In the meantime I'm going to see if I can't find any clues in the code.

**Comment by phyllisstein** [comment]
It appears that `validate_non_null_input` is calling `coerce_input` the first time: https://github.com/rmosolgo/graphql-ruby/blob/f68ca6870e0c38ed1d9beac28a103c697f11d69f/lib/graphql/scalar_type.rb#L115-L121

This doesn't feel quite right, but I take it the behavior is expected? If so I can certainly probably hack around the issue with uploads.

**Comment by rmosolgo** [comment]
Huh, yeah, I agree that it's not expected and should be the other way ... but it will take some work to fix! In the `GraphQL::Query` instance, we cache all the coerced arguments. But validation is supposed to be static, without access to the Query. But I agree it would be better to only call once, so maybe some of those assumptions have to be challenged.

**Comment by phyllisstein** [comment]
Just spitballing here, but what does guaranteeing that the coercion isn't `nil` get you in the rest of the framework? To my thinking, there's a world in which that gets handled exclusively in userspace, in the mutation's resolver; is there some other functionality that depends on having a warning in this `InputValidationResult`?

**Comment by rmosolgo** [comment]
I investigated this recently, and pushed a failing test back in #3678, but I'm going to give up. Here are my thoughts: 


1. It hasn't turned out to be a real problem. There _are_ performance problems in GraphQL-Ruby, but they're all related to resolving fields and building responses. I haven't heard any real-world problems caused by validating scalars. (If  anyone _does_ run into this, please open a new issue to let me know!)
2. It's hard to implement a fix. The problem is, there's nowhere in the gem _now_ that has access to _both_ the AST Node (which would be the cache key) _and_ the coerced value. So, having hunted for some easy place to put a cache, I missed it. On the one hand, the validator has the AST nodes, but, the actual coerced values don't appear until arbitrarily-deep call stacks (depending on non-null/list types), and by then the AST node isn't available. Yes, it'd be possible to build a cache out-of-bounds: something like, tuck away the AST node in `context`, then pull it back out when building the cache, but, ew! It sounds like a maintenance nightmare. Not worth taking on, given the first point above. 
3. If anyone _does_ run into this problem, they _could_ implement `def self.validate_non_null_input` in their custom scalars. The API for this is _not_ really nice at the moment, but it could be improved -- please let me know here or in a new issue if you're exploring that in your schema and we can pretty up the API some, and document. 

So, sorry to give up on this one but ... I give up! As mentioned above, if anyone runs into another problem like this one, please open a new issue and we can discuss it again.
