### ISSUE TITLE
[1.8] Problems with GraphQL::Function arguments and types

### ISSUE THREAD

**Issue by joshforbes** [rmosolgo/graphql-ruby#1409]
After upgrading an input object to the class based syntax I am no longer able to specify it as a  required argument in a graphql function 

![image](https://user-images.githubusercontent.com/3682518/38576817-338b7244-3ccd-11e8-9ef9-fab6850f2832.png)
results in:
![image](https://user-images.githubusercontent.com/3682518/38576858-4d9e55b6-3ccd-11e8-9ce9-fdb67797d5cb.png)

Changing to the new syntax in the function:
![image](https://user-images.githubusercontent.com/3682518/38576888-665d7014-3ccd-11e8-8dad-67276e6fbbca.png)
results in:
![image](https://user-images.githubusercontent.com/3682518/38576915-7d97b6b8-3ccd-11e8-835b-6783704f8f57.png)

A similar problem exists when trying to specify that the return type from the function is not null:
![image](https://user-images.githubusercontent.com/3682518/38578396-d50cbf48-3cd1-11e8-8dc8-46941927a479.png)

**Comment by rmosolgo** [comment]
This is because, by default, class-based definitions don't override `!`. There are a few options, documented here: http://graphql-ruby.org/schema/class_based_api.html#list-types-and-non-null-types

In short: 

- use `#to_non_null_type` instead of `!`  (eg `CreateAnnouncement.to_non_null_type`)
- load a refinement in the files where you want to use `!` (`using GraphQL::DeprecatedDSL`)
- Apply the override of `!` to definition classes _everywhere_ (`GraphQL::DeprecatedDSL.activate`)

**Comment by joshforbes** [comment]
Perfect! Overlooked that. Thank you!
