### ISSUE TITLE
[pro] Authorization problem with compile time checks + gate.parent_gate

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#1419]
As far as I can tell there is no way to work out the parent type of a field during compile time checks, because `gate.parent_gate` is not set for compile time checks

This is extremely useful for deciding an authorization level, and for debug messages.

For example, I currently have debug messages for a query:
```graphql
query {
  localSearch {
    localProperty {
      localChain {
        id
      }
    }
  }
}
```

that look like this:
`[GraphQL Auth] Authorize X.localChain (LocalChain) => can?(:access, LocalChain)`

I should be able to say that `X.localChain` is actually `LocalProperty.localChain`, but from my API exploration, I don't have access to this knowledge in my authorizer's `allowed?` method.

**Comment by rmosolgo** [comment]
Sorry about the trouble here. Authorization checks don't generally provide _too_ much context, because relying on it is an anti-pattern. That is, I've seen checks written that _assume_ object `O` can only appear as a child of parent `P`, but in fact, that assumption isn't true, then the auth check leaks data. So I've tried to make them less context-aware. 

The best bet for implementing this in GraphQL-Ruby these days is a custom analyzer, where you keep a stack of types and fields in the analyzer: 

https://graphql-ruby.org/queries/ast_analysis.html
