### ISSUE TITLE
[1.8] Field level testing broken in class based API

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#1447]
We do a fair amount of [field level testing](http://graphql-ruby.org/schema/testing.html#fields). It appears that given a type

```ruby
class Types::PropertyType < Types::BaseObject
  field :test_me, Boolean, null: false
  def test_me
    puts "HEY"
    true
  end
end
```
and a test
```ruby
MySchema.types["Property"].fields["testMe"].resolve(property, {}, {})
```
no "HEY" is printed, and an error is thrown indicating that graphql-ruby used the default resolver implementation:

```
undefined method `test_me' for #<Property:0x00007f90c18a0800>
   # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activemodel-4.2.10/lib/active_model/attribute_methods.rb:433:in `method_missing'
     # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-d256dd26bc78/lib/graphql/schema/field.rb:305:in `public_send'
     # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-d256dd26bc78/lib/graphql/schema/field.rb:305:in `public_send_field'
     # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-d256dd26bc78/lib/graphql/schema/field.rb:235:in `resolve_field'
     # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-d256dd26bc78/lib/graphql/field.rb:247:in `call'
     # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-d256dd26bc78/lib/graphql/field.rb:247:in `resolve'
```

This was tested with both pre10 and master. Actually pre10 gave a more cryptic error than master.

**Comment by rmosolgo** [comment]
Yeah, the new objects are pretty different. There's a way to get the old-style field: 

```ruby 
field = MySchema.find("Property.testMe")
field.resolve(...)
```

I hope that helps!

**Comment by bessey** [comment]
Thanks, would you like me to add that to the testing docs?

**Comment by bessey** [comment]
Even using the `find` API, I am still facing the same results, though I did have to provide more context to get the resolver to run at all.

```ruby
schema = DirectorySchema
query = GraphQL::Query.new(schema)
context = {account: account, ability: Ability.new(account), schema: schema}
context_obj = GraphQL::Query::Context.new(query: query, values: context, object: property)
args = {}
schema.find("LocalProperty.testMe").resolve(property, args, context_obj)
```


```
     NoMethodError:
       undefined method `test_me' for #<LocalProperty:0x00007fabcc56ae30>
     # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activemodel-4.2.10/lib/active_model/attribute_methods.rb:433:in `method_missing'
     # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-bb7627c5e43f/lib/graphql/schema/field.rb:310:in `public_send'
     # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-bb7627c5e43f/lib/graphql/schema/field.rb:310:in `public_send_field'
     # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-bb7627c5e43f/lib/graphql/schema/field.rb:240:in `resolve_field'
     # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-bb7627c5e43f/lib/graphql/field.rb:247:in `call'
     # /Users/matt/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-bb7627c5e43f/lib/graphql/field.rb:247:in `resolve'
     # ./spec/graphql/types/property_type_spec.rb:14:in `block (3 levels) in <top (required)>'
```

**Comment by rmosolgo** [comment]
Ahh right, I guess the schema would usually apply the proxy, but that's not done here. 

I'll leave this open until we have some API to support this kind of tests, thanks for the detailed error report there.

**Comment by bessey** [comment]
I feel bad opening so many issues so I'll waver a _little_ off topic here instead.

I am curious as to why "Don’t test the schema" is considered a best practice. I am surprised that others haven't run into the bug i documented here, so perhaps I'm doing something wrong, but I don't _feel_ like its wrong. I want to write tests that:

1. As a whole, exercise as fully as possible my GraphQL API
2. Avoid excessive boilerplate
3. As individual tests, have a narrow focus

I don't see a way to balance these factors without field testing. Using a decorator pattern or similar to separate resolution from the API layer, and testing just that, means we are no longer testing for errors in the schema, instrumentation, or resolvers. Executing full queries means I have to traverse from my root node down to the fields I wish to test, which is expensive in aggregate. This encourages writing broad tests that query a lot of fields at once, which I believe is bad practice. 

Whereas field tests allow me to write tests that test a single thing (one field of one type), do it with little boilerplate (no GraphQL in tests), while avoiding schema level breakage from say, a bad instrumenter. 

I would go as far as saying I am surprised that the docs do not _encourage_ field testing, and provide test helpers for it. I have a built a little something for RSpec that needs work but is working well for us so far:

```ruby
RSpec.describe "LocalResource" do
  subject { DirectorySchema.types["LocalResource"] }
  let(:resource) { create(:local_resource) }

  describe "name" do
    let(:field) { subject.fields["name"] }
    it "returns name" do
     # def resolve_field(object = nil, arguments = {}, context = {})
      expect(resolve_field(resource)).to eq resource.name
    end
  end
end
```

**Comment by cmatheson** [comment]
We have a similar wrapper to make field testing easier (which we do extensively).  I'm pretty happy with how it's going, but I do wish there were some way to opt-in to instrumentation, type-conversion, etc. (I've had a few bugs relating to the graphql arguments object not behaving like the hash I'm passing in in my tests).

**Comment by bessey** [comment]
Any progress here? This is the one thing holding us back from the greatness that is 1.8!

**Comment by rylanc** [comment]
I agree with @bessey here. If the field resolves an object type, executing a query means that we need to have knowledge of that object's fields, which feels like we're reaching outside the bounds of our current unit test.  With the authorization we have set up with `graphql-pro`, it becomes even more difficult to set up our tests. It would be great if we could more easily test the results of a custom resolver method.

**Comment by rmosolgo** [comment]
If you want to test some code _without_ API structure and _without_ API authorization, might it make sense to test the code _apart_ from the API? I mean, if you don't want to make selections and you don't want to use the API's authorization, why put the code in your application and test it in plain Ruby? Or, what advantage is there to using GraphQL in that case? 

@bessey, here's my opinion on these tests: 

1. Writing tests that poke around on library/schema internals is not panning out well, since those internals are hard to maintain while the library changes 
2. Writing tests that bypass _some_ of the GraphQL system isn't panning out well, since your tests don't match what actually runs in the app 

So, with those in mind, I'd want to build something that makes it _easy_ to run a snippet of GraphQL on a single object, and compare the result to your expectations. Something like: 

```ruby 
assert_graphql_result(blog_post, {
  title: "My Cool Post", 
  published_at: blog_post.published_at.iso8601
  related_posts: [other_post1, other_post2],
})
```

So a helper like that might: 

- Use `schema.resolve_type` to figure out the GraphQL type of the passed-in object 
- Use `schema.id_from_object` to get the passed-in object's unique ID 
- Start building a query to lookup the object via GraphQL, something like: 

  ```graphql
   query Test($id: ID) {
    node(id: $id) {
      ... on BlogPost { # determined via schema.resolve_type 
      }
    }
  }
  ```
- Use the _keys_ from the given hash to add selections to generated query string (probably converting them to camel-case)
- Run the query 
- Use the _values_ from the given hash to check whether the GraphQL response matches the expected value. 

There are a few more problems to solve: 

- Need some way of providing `context:` to the query that runs 
- It's easy to compare _scalars_ to the expected value, but what about _objects_? (Could we select `__typename` and `id` and make sure they match?) 

Anyhow, we have a ton of tests in GitHub that follow that flow, but it's all setup manually, I think an easier setup for something like that would be a big win (and since it's not tied to schema internal structure, just `.execute`, easier to maintain compatibility!).

**Comment by bessey** [comment]
Happy to say I completely agree with both your points! Your proposed solution seems good to me too. We don't have a `Query.node(id:)` field in our API, which in hindsight is why I resorted to field testing and internal mockery etc.  If I introduce such an API, with or without your proposed helpers, we can rewrite tests to just use GraphQL query syntax. Thanks for the inspiration! 

As for the helpers, we're an RSpec suite, and prefer isolated tests, so I think I'd be more likely to test one field at a time. Perhaps something like

```ruby
type_tester = type_tester_for(blog_post, context: my_special_ctx)
expect(type_tester.field(:title)).to eq("My Cool Post")
expect(type_tester.field(:related_posts, args: {first: 2})).to contain_exactly({id: 1}, {id: 2})
```

Anywho, I guess that can be created in user land from your proposition. 

Thank you for taking the time to explain how GH handles this. It made me realize we can perhaps upgrade to 1.8 after all.

**Comment by bessey** [comment]
Ok, for the benefit of others, I have taken a first pass at converting our field tests to proper query tests using the technique mentioned earlier. I've extracted the code and its mostly not specific to my company* here:

https://gist.github.com/bessey/91063148696633ba92204b7bfc750c5e

*One exception, references to `account`, refer to our internal authenticated user. You can ignore these as they're all optional, or replace with `user:` if thats your jam to save writing `context: {user: ...}` everywhere

**Comment by bessey** [comment]
@rmosolgo I have tried every combo of define / redefine I can think of, to no avail.

If I use define, I can see the line prior to query execution that `schema.query.fields.keys` has my test fields present. However the query fails claiming the field is missing, and the schema printer agrees, the fields are not in the schema.

```ruby
# testMyType will appear here...
puts schema.query.fields.keys
# but not in `type Query {` here!?
puts GraphQL::Schema::Printer.print_schema(schema)
```

I've tried using redefine (which seems cleaner, I'd rather not change the schema outside the scope of my test class), but this causes the `schema.redefine { query(new_query) }` block to raise:

> Duplicate type definition found for name '__Schema' at '__Schema' (GraphQL::Introspection::SchemaType, GraphQL::Introspection::SchemaType)

Any ideas? With this one change, I could definitely package this up as a reusable testing tool. 

This is the (currently hideous) broken code:

```ruby
def add_test_resolvers_to_schema(original_schema)
  original_schema.query.define do
    original_schema.types.to_a
      .select do |_, type|
        type.class == GraphQL::ObjectType &&
          ![original_schema, original_schema.query].include?(type)
      end.each do |type_name, type_klass|
        field(:"test#{type_name}", type_klass) do
          argument(:id, !types.ID)
          resolve ->(_, args, ctx) { schema_ref.object_from_id(args.id, ctx) }
        end
    end
  end
  original_schema
end
```

**Comment by DidiBear** [comment]
In our case, we want to unit test field resolve using something similar to:
```ruby
it "resolves the name field" do
  entity = create(:entity)
  name_field = GraphQL::EntityType.fields["name"]

  expect(name_field.resolve(entity, {}, {})).to eq(entity.name)
  # ^ resolve() require a `GraphQL::Schema::Object` and not the entity itself.
end 
```
Do you have some update on this issue ?
Thanks :)

**Comment by rmosolgo** [comment]
I'm sorry, I really don't have the bandwidth to maintain low-level APIs to schema primitives. My best suggestions are: 

- If you GraphQL layer contains a lot of logic, extract it to POROs and unit test them
- And, run queries against your schema to test the GraphQL layer 

I've heard of folks building systems that generate GraphQL queries against a schema (eg https://github.com/pocke/graphql-autotest), and I think that would be a really good way forward, if anyone wants to take it on. 

Imagine a testing library that, based on a type name and an object, generates a few queries and runs them, and makes assertions on the results. It would be a pretty thin abstraction over writing query strings by hand, but it would dry it up a lot. 

A big advantage to a "full-stack" approach is that it engages all the various instrumenters, tracers, authorization hooks, analyzers, etc -- so that the test result _really_ reflects the GraphQL layer. 

Another way to consider it is to compare a GraphQL object type to a Rails controller. Rails controllers are usually (always?!) tested with HTTP-like setups, provided by Rails test helpers. Personally, I've never manually initialized a controller and called methods on it. And, I don't think I'd _want_ to: part of my integration tests are routing, authorization, before_actions, etc, so I _want_ the test harness to run those things. If my controller action contains a lot of business logic, that should be _extracted_ so it can be unit tested. 

Anyways, sorry I can't help more here. If anyone takes a shot at a GraphQL testing library, please do share it!
