### ISSUE TITLE
Backend support request for OperationStore - Mongoid

### ISSUE THREAD

**Issue by jackburns** [rmosolgo/graphql-ruby#1460]
My company is interested in graphql-ruby pro for the OperationStore but we use Mongoid instead of ActiveRecord. We'll probably go ahead with the pro version either way but would be good to hear whether you're willing to support it.

Thanks for the great gem, been fantastic to use so far 🥇

**Comment by rmosolgo** [comment]
Hi! That's a nice suggestion and I bet we can make something work :) 

Under the hood, it's part way there -- access to storage is implemented through an `ActiveRecordAdapter`, but the adapter isn't pluggable yet. (That is, all the references to it are hard-coded). So, I think I just need to finish the job and parameterize it! 

Regarding Mongoid, my hesitation is that I can't develop a production-ready storage adapter because I don't know much about running MongoDB in production. So, if I do a bit of work to parameterize it, maybe we could work together to build the adapter, how does that sound?

**Comment by raptiq** [comment]
That'd be great! My company (Open Listings) signed up for pro this week and we're definitely down to help in any way with this.

**Comment by rmosolgo** [comment]
Cool, let me take a crack at the prep work and get back to you!

**Comment by rmosolgo** [comment]
Well, it's been a while ... but at last, the OperationStore supports different backends. I've just released 1.13.0 which includes an extracted ActiveRecordBackend as well as a RedisBackend. You could take a look at those for building a Mongoid backend. 

It turned out to be a lot of methods because, besides the basic operation store behavior, there's the dashboard, which maintains an index of which operations use which parts of the schema. You could skip those at first if you're not worried about the dashboard.

Alternatively, you could use the RedisBackend, since it doesn't use ActiveRecord. Anyways, if you get a chance to try it out, please let me know if you run into any trouble 🍻 !
