### ISSUE TITLE
1.8: Recommended way to implement a reusable mutation?

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#1474]
Scenario:

All of my "delete by id" mutations follow the same pattern.  So I'd like to define a single class that is parameterized with the model class whose resolve will eventually call `model.destroy`. What is the best way to accomplish this using the class-based API?  I'm thinking of something like:

`field :delete_foo, mutation: GenericDeleteMutation.new(Foo)`

I suppose I could just do some meta-programming and generate the mutation class dynamically, but I'm wondering if there's a better way.

**Comment by rmosolgo** [comment]
>  generate the mutation class dynamically

☝️  With the built-in mutations, this is the way to do it. Mutations are short-lived objects that get initialized each time they're called. 

Alternatively, you could build your own system _like_ `GraphQL::Schema::Mutation`, but works the way you want it too. If you take a look, I think you'll see it's not all to bad: the mutation generates a `GraphQL::Schema::Field` instance, which is attached to the mutation type, and references some generated payload and input types. You could use a similar flow for a custom mutation system, except it would use instances instead of classes.

**Comment by blevine** [comment]
Good ideas.  Thanks for being so responsive!
