### ISSUE TITLE
1.8 - adding a field to PageInfo using the class-based API

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#1488]
In 1.7, I added a 'count' field to PageInfo in my Schema subclass as shown below.  This still works in 1.8, but is there a better way using the class-based API?

```
      # Adds the 'count' field to PageInfo so that the caller
      # can request the total count of edges in a connection.
      count_field = GraphQL::Field.define do
        name 'count'
        type !types.Int
        description 'Total count of edges in this connection.'
        resolve ->(obj, args, ctx) {
          obj.nodes.count
        }
      end

      GraphQL::Relay::PageInfo.fields['count'] = count_field
```

**Comment by rmosolgo** [comment]
`GraphQL::Relay` hasn't been ported to class-based yet (but I will do it after releasing 1.8 sometime) but you can implement it yourself. I described my approach in "Porting Relay types" here: 

http://rmosolgo.github.io/blog/2018/04/09/updating-github-to-graphql-1-dot-8-0/

that includes connection and edge types; you could do something similar creating a `class PageInfo < Types::BaseObject` and hooking up that type to the `page_info` field, instead of `GraphQL::Relay::PageInfo`. But TBH, it's also just fine to leave it the way you have it for a bit!

**Comment by blevine** [comment]
Thanks again!
