### ISSUE TITLE
Provided arguments get passed as Hash

### ISSUE THREAD

**Issue by christophweegen** [rmosolgo/graphql-ruby#1560]
When i pass an Integer argument into a field like this:

```ruby
field :show, Types::CategoryType, null: true do
  description "Shows a category"
  argument :id, Integer, required: true
end
```

it gets passed as a hash to the underlying object resolve method, so it needs to be extracted first.

```ruby
def show(id)
  Category.find(id) # id == { id: 1 }                   
end
```
Is this expected behavior? Wouldn't it make much more sense if it would be passed directly as an Integer?

Thanks!

**Comment by rmosolgo** [comment]
You should use keyword arguments instead of positional arguments: 

```diff 
- def show(id)
+ def show(id:)
```

(Added a `:`) 

Under the hood, Ruby uses a Hash for keyword arguments. If you ask Ruby for a positional argument (without `:`), it will give you all the keyword arguments as a Hash. 

So, everything is "working", but I think you'll have a better time with keyword arguments!

**Comment by christophweegen** [comment]
Ah thanks. I knew about "kwargs". 

But i was just wondering. Now things are clear :-)
