### ISSUE TITLE
[1.8.2] 1.8.2 can't use empty "{}"

### ISSUE THREAD

**Issue by BoleLee** [rmosolgo/graphql-ruby#1573]
upgrade to 1.8.2, when the query include empty "{}", it will report error:
```
Parse error on "}" (RCURLY) at [x, x]
```

remove the empty "{}" will solve the problem.

in the former version, in this situation, we must use empty "{}", or it will report error.

**Comment by rmosolgo** [comment]
Sorry about the surprise! Yes, this is included in the "Breaking Changes" section of the changelog for 1.7.10: 

https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1710-13-feb-2018


This change was so that GraphQL-Ruby would conform to the specification. If you think we should reconsider this change, please add more details about your use case and reopen this issue!
