### ISSUE TITLE
GraphQL::Query::Context#path is empty in class-based Relay Mutation

### ISSUE THREAD

**Issue by obrie** [rmosolgo/graphql-ruby#1575]
Prior to 1.8, `GraphQL::Query::Context#path` used to contain the name of the selected operation and the name of the mutation.  After switching to the class-based API (using `GraphQL::Schema::RelayClassicMutation`), `GraphQL::Query::Context#path` is now an empty an array.  I can put together an example -- just wanted to get this issue logged while I was looking at it.

**Comment by rmosolgo** [comment]
Ah yeah, this is a result of the change of `context`, which was previously a field-level context and is now the query-level context. So, as you noticed, the field-level details are not there anymore. 

For the time being, you can get field-level context attributes via `extras:`: 

http://graphql-ruby.org/type_definitions/objects.html#extra-field-metadata

`extras: [:path]` is not documented there (because I forgot about it) but it should work fine, so you can add that to your file like: 

```ruby
field :my_stuff, ... extras: [:path]

def my_stuff(path:, **other_args)
  # ... 
end 
```

The reason that `context` switched to be query-level is because: 

- It's easier to use that way, and almost always good enough 
- Often, using field-level context attributes inside a resolver was an antipattern. Not always, but in a lot of cases I've seen, it's used to try to infer the field's location in a query in a way that is not robust, and prone to errors. 

So, I want to find a new way to support the previous uses of field-level context (for example, `includes`-ing relations which will be needed later in the query), but in the mean time, `extras: [...]` is there for compatibility.

Please reopen this if `extras:` doesn't work for you or if you think there's more to be done here. Feel free to add `path` to the docs there, too, if you want!

**Comment by obrie** [comment]
Got it, thanks for the quick follow-up!

**Comment by Mange** [comment]
I hit this in our mutations after upgrading to the class-based API. Will this be documented somewhere, or will there be a change in behavior?
