### ISSUE TITLE
Upgrader question/bug report

### ISSUE THREAD

**Issue by xpol** [rmosolgo/graphql-ruby#1606]
Please share: the source code you're trying to transfor

```ruby
  field :title, !types.String
  field :level,!types.String
```

will get transformed to:

```ruby
  field :title, String, null: false  # OK
  field :level,!types.String # unchanged
```

The different is the `level` fined has no whitespace between field name and type.

And there is more:

```ruby
field :learnTasks , function: Functions::LearnInfo.new
```

```ruby
field :learn_tasks, , function: Functions::LearnInfo.new # again, the whitespace cause bad result.
```

**Comment by rmosolgo** [comment]
Yeah, there are a few Regexes that use  `/, /` to separate arguments where they could use `/, */` instead, for example: 

https://github.com/rmosolgo/graphql-ruby/blob/c31e679d2c0118fbf5534b9c86480ae5e2944192/lib/graphql/upgrader/member.rb#L636

I'm going to close this because I don't plan on fixing it myself, but if you open a PR with failing tests (you can add examples to the files in `spec/fixtures/upgrade`), I'd be happy to help you hunt down the parts that need fixing!
