### ISSUE TITLE
Update to 1.8.4, breaking some old test.

### ISSUE THREAD

**Issue by zw963** [rmosolgo/graphql-ruby#1611]
Following is a mutation test example

```rb
#  ...
schema = Schema.types['Mutation'].fields['deleteChildFeed']
headers = {'X-Consumer-Custom-ID' => guardian.id}
inputs = {id: feed.id.to_s}

result = schema.resolve(nil, inputs, headers: headers)
```

deleteChildFeed mutation will get headers with:

```rb
user_id = ctx[:headers]['X-Consumer-Custom-ID']
```

or new 1.8

```rb
user_id = @context[:headers]['X-Consumer-Custom-ID']
```

all not work, get following error:

```sh

E

Error:
DeleteGuardianTaskTest#test_应该成功的删除一个_Guardian_Task:
NoMethodError: undefined method `schema' for {:headers=>{"X-Consumer-Custom-ID"=>15473}}:Hash
    test/graph/queries/mutations/delete_guardian_task_feed_test.rb:27:in `block in <class:DeleteGuardianTaskTest>'
```

**Comment by rmosolgo** [comment]
Sorry to hear it, 1.8 adds some wrappers around `resolve` functions so that returned objects can be wrapped with their `GraphQL::Schema::Object` classes. That kind of test won't work anymore (see also #1447), but I can make some suggestions on how to test the behavior: 

- Extract the mutation's behavior into a PORO and run unit tests on _that_ object instead of the GraphQL field 
- Use an "end-to-end" test, running an entire GraphQL query from string. Personally, I think if you're testing GraphQL behavior, that's the best way to do it anyways, since you can be sure the whole GraphQL "stack" is involved. 

I hope one of those is helpful, sorry it broke 😖 !
