### ISSUE TITLE
custom path posible?

### ISSUE THREAD

**Issue by ZeroSoulEater** [rmosolgo/graphql-ruby#1628]
if you have a lot of queries and mutations, it will get messy if you store them all in the query and mutation folder.

I would like to sort alle querys and mutations in a folder which represent the resource like for example /app/graphql/user. So I can put alle query like get the logged in user, get all friends for the user or get a user by id and all mutations e.g. userCreate userUpdate userDelete in a folder.

Thanks for the response 😄

**Comment by rmosolgo** [comment]
From GraphQL-Ruby's perspective, it doesn't matter what the classes are named or what files they're in. 

However, if you're using Rails, you have to make your filenames and constants match, so that Rails can autoload them. So if you move the files around, make sure to update the class names and modules, too. Try googling "rails autoloading" if you'd like to read more about it.
