### ISSUE TITLE
ArgumentError thrown when generating schema that has a field with property

### ISSUE THREAD

**Issue by ajkerr** [rmosolgo/graphql-ruby#1637]
The documentation at https://github.com/rmosolgo/graphql-ruby/blob/da1030ab152860a7dc28eda2405e04bf5b2ef3a0/lib/graphql/field.rb#L40 mentions that `property:` is a valid option for `field`. Indeed, this class references it throughout.

However, if you try to generate the schema when a field is defined this way, the schema generation code raises `ArgumentError: unknown keyword: property`.

It looks like the schema code is expecting `property:` to be named `method:`. 

Based on the upgrader code, it looks like `method` is the preferred new syntax, and that `/lib/graphql/field.rb` needs to be updated?

**Comment by rmosolgo** [comment]
Sorry for the confusion, but at the moment, there are _two_ ways to build a graphql schema: 

1. The first uses `.define` blocks, and it uses the class that you linked above. It uses `property:`
2. The second uses classes, it uses the `method:` option. See the docs for `GraphQL::Schema::Object` or `GraphQL::Schema::Field` for more about that API.

So, the docs you linked are for the legacy API. `method:` is the new API. They both work for the moment, but it's a bit confusing! The guides on graphql-ruby.org should all use `method:`, please open an issue if you see something otherwise.

**Comment by ajkerr** [comment]
Ah, that explains it. Thanks for the detailed explanation.
