### ISSUE TITLE
1.8.x [Feature Request]: Argument switch to control camelCase->snake_case for input hashes

### ISSUE THREAD

**Issue by clader** [rmosolgo/graphql-ruby#1673]
So, with 1.8 the `camelize: true/false` argument was made available to add to fields and arguments to control how those fields and arguments get presented in the API schema, and this works great.  It can either be set on particular arguments or fields, or can be setup as a default in a custom field/argument class and then associated to Object/Resolvers/Mutations to apply the default to all inherited classes.

However I've found that in 1.8.x if I declare an argument with a camelCase name, when I get that input class/hash back in the resolver, the key names in the hash are automatically converted to snake_case.

Example:
Given an input object:
```ruby
# frozen_string_literal: true

module Directory
  module Inputs
    # Define input object for modify User mutation
    class ModifyLdapUserInput < ::Types::BaseInputObject
      graphql_name 'ModifyLdapUserInput'
      description 'Input Object for modifying an LDAP User'
        argument :employeeType, String, "Modify LDAP User\'s employeeType Attr", required: false
        argument :comAcmeTeam, String, "Modify LDAP User\'s custom Team Attr", required: false
    end
  end
end
```
And a mutation that references that input Object...
```ruby
# frozen_string_literal: true

# Module to Modify attributes on an Ldap User
module Directory
  module Mutations
    class ModifyLdapUser < ::Types::BaseMutation
      null false
      description 'Modify attributes on an Ldap User'

      # Modify args passed for this object
      argument :input
               Directory::Inputs::ModifyLdapUserInput,
               'Input object for to specify the attrs to change on an LDAP User',
               required: true
      field :success, Boolean, 'Whether the Ldap user was modified successfuly, null: false

      def resolve(input:)
         # print out the input argument hash we have to work with
         puts input.to_h
         #.... do stuff...
      end
    end
  end
end
```

... this outputs the input hash as follows:
`{:employee_type=>"Employee", :com_acme_team=>"Marketing"}
`

I understand that Ruby standards prefer hash keys to be under_scored, but in my case I configured the input arguments such that the key exactly matches the keys of (in this case) of the net-ldap object that am making modifications to.  i.e. the object only reacts to  `object[:employeeType]` or `object [:comAcmeTeam]`, and not to the underscored versions of those.

I have been able to hack around it to convert the underscored keys back to camelCase with `key.to_s.camelize(:lower).to_sym` when referencing the key names. Or alternately I can even replace all the keys in the hash with:
`input.transform_keys!{|k,v|k.to_s.camelize.to_sym}`
... but this feels hack-ey, and likely to cause other unforeseen issues.

It would be fantastic to have an option that we can add to individual argument declarations that configure whether these argument names get forced to snake_case keys in the input hashes, as this has caused a lot of chaos for my upgrade to 1.8.x

Ideally the switch should be fully separate from the existing `camelize: true/false` switch as one would likely want to configure them independently as they would affect separate things.

**Comment by rmosolgo** [comment]
Personally, I'm not too convinced that making the kwarg style configurable is worth the overhead. It sounds like your use case is integrating with an external system (ldap), and I think the solution you proposed (`.transform_keys`) is a good one in this case. The method is called in Ruby style, then transformed to be LDAP-style. Even if GraphQL-Ruby put it camel-case for you, I'm not sure it would be an advantage, since the clarity might be _helpful_ for a reader. 

We had something similar in GitHub, where some values were being sent along to JavaScript. I used `.transform_keys` to return a new, camelized hash, just like the example you mentioned. 

TBH, the only reason I added `camelize: true/false` is for compatibility. Since previous GraphQL-Ruby supported both, I needed some way to support folks who used underscores in their GraphQL schema.   I'm not too interested in adding configurations to cover edge cases, but I might consider it if there's more to the story, for example, some reason that the occasional `.transform_keys` couldn't work. 

Additionally, there are probably ways to add `.transform_keys` calls in a programmatic way, for example, for a mutation:

```ruby 
module CamelizeMutationArguments 
  def resolve(**inputs)
    camelized_inputs = inputs.transform_keys { |k, v| k.to_s.camelize.to_s }
    super(camelized_inputs) 
  end 
end 

# ... then 

class MyMutation < BaseMutation
  prepend CamelizeMutationArguments 
end 
```

**Comment by rmosolgo** [comment]
Closed as stale
