### ISSUE TITLE
[1.8.5] Disagree to implicit, conventional authorizations (validations)

### ISSUE THREAD

**Issue by gfx** [rmosolgo/graphql-ruby#1676]
Authorization is inevitable for real-world applications, including our service and maybe yours.

However, the current implementation added in v1.8.5 (https://github.com/rmosolgo/graphql-ruby/pull/1609) makes me nervous because it's under the "convention over configuration" design. The association of a validation method and an argument is not explicit, meaning newbies cannot recognize it. I think it should be explicit like types, nullabilities, i.e.:

```ruby
# I prefer:
argument :foo, String, required: true, validate: :validate_foo
# or:
argument :foo, String, required: true, validate: -> (value) { ... }
```

Please re-consider the implicit association of validators.

**Comment by rmosolgo** [comment]
:+1: Maybe we can have both, for example: 

- The default behavior is `argument :foo, validate: :validate_foo` 
- If a custom method name is provided, it's used instead of `validate_foo`
- If `nil` is provided, no method is called 

That way, if you want to _require_ `validate:` configurations in your app, you can put `validate: nil` in your custom argument class, so that the default will be `nil` in your app. Would that work for you? Personally I won't be able to work on it for a while but I'm happy to help out on a PR if you want to take a try at it.

**Comment by gfx** [comment]
Thanks. `validate:` option seems good and I'll use it 👍 

However, I'd like to ways to disable the introspective, implicit default (i.e. `validate_#{name}`), which makes maintenance of the code harder.

Do you have a plan to disable those implicit default? I'd like disable even the implicit resolvers. This is because I have to know **all** the implicit associations to avoid the unintentional use of them.

**Comment by rmosolgo** [comment]
I don't have plans to work on this further, and I haven't heard much else about changing the current behavior, so I'll close this issue.
