### ISSUE TITLE
Graphql pagination connections with uuid

### ISSUE THREAD

**Issue by KevinColemanInc** [rmosolgo/graphql-ruby#1691]
I have my database ids be uuids instead of integers, because I wanted to hide the number of objects that I have for a given resource.

The problem I have is the `offset_from_cursor` does not handle uuids very well and simple converts them to an offset of `0`.  I think what it should be doing is finding the `created_at` and using a `where created_at > ? order by created_at`.

I think my 2 options are:

1. Use integers as ids, and use something more advanced than base64 encoding for my global ids
2. monkey patch (or fork & pr) something to handle uuid support better with pagination.

related lines of code:
```
def offset_from_cursor(cursor)
  decode(cursor).to_i
end
```

https://github.com/rmosolgo/graphql-ruby/blob/f6aab69afe53505f0bb4e0bf8fbae9e6152e4fd2/lib/graphql/relay/relation_connection.rb#L175

thoughts?

**Comment by rmosolgo** [comment]
Interesting question! I think the built-in connections _expect_ `cursor` to be an offset, not an ID, so I'm surprised that UUIDs get used as cursors. I haven't really looked into using IDs as cursors because, at least in the simplest case, it doesn't play nice with SQL. For example, given a table like this: 

ID | Name 
---|---
1 | Ruby 
2 | Python 
3 | TCL 
4 | Ada

If we make a query like this: 

```sql 
SELECT * FROM languages 
  ORDER BY name 
  LIMIT 2 
```

We'd get: 

ID | Name 
---|---
4 | Ada
2 | Python 

Then the next query, using an ID cursor, would be: 

```sql 
SELECT * FROM languages 
  WHERE id > 2
  ORDER BY name 
  LIMIT 2 
```


We'd get only one Result: 


ID | Name 
---|---
1 | Ruby 

We'd _expect_ `TCL` to be in the list, but it wasn't, because of its ID. 

I don't know how to work around that, since ID can't be used to filter since it's not related to the order-by values. 

The "fix" is to create cursors that embed order-by values in them, see [graphql-pro](http://graphql.pro)'s stable cursors for an example of that. 

Does that help? Did I understand the issue properly?

**Comment by rmosolgo** [comment]
Feel free to continue the conversation here if you'd like ,but I'll close this as it doesn't have any work to do in graphql-ruby
