### ISSUE TITLE
PageInfo#nodes method is now private in version 1.8.5

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#1697]
In order to add a `count` field to `PageInfo`, I did the following:

```
count_field = ::GraphQL::Field.define do
  name 'count'
  type !types.Int
  description 'Total count of edges in this connection.'
  resolve ->(obj, args, ctx) {
    obj.nodes.count
  }
  end

  # Add a 'count' field to PageInfo for connections.  This is the total number of
  # edges in the connection (nodes in the collection)
  ::GraphQL::Relay::PageInfo.fields['count'] = count_field
```
which worked fine until I upgraded to graphql-ruby 1.8.5.  Now I get a runtime error saying that `nodes` is a private method.

In debugging through this, I see that `PageInfo` now has an `@object `member which is a GraphQL::Relay::RelationConnection on which I can call `nodes`.  So I'm now doing this:

`obj.object.nodes.count`

which seems "wrong."

Is the fact that `PageInfo#nodes` is now private a bug?  Is there a better way for me to add a `count` field to `PageInfo`?

**Comment by rmosolgo** [comment]
Sorry about the breakage, I think it's a side-effect of migrating GraphQL-Ruby's built-in types to use the class-based API.

`PageInfo` was migrated to class-based, so: 

- `obj` is an instance of the `PageInfo` wrapper 
- `obj.object` is the wrapped object, probably an instance of `GraphQL::Relay::RelationConnection`
- `obj.object.nodes` calls `#nodes` on the connection 

I think you can continue to use `obj.object.nodes.count` for a while, but in the long run, type definitions should be migrated to the class-based API. (I wouldn't expect to _remove_ `.define` until winter, or maybe even 2019.) There is some documentation about class-based Relay types here: http://graphql-ruby.org/api-doc/1.8.5/GraphQL/Types/Relay.html

Using the class-based API, you could probably create a subclass of `Types::Relay::PageInfo` with a count field, and a custom connection base class which uses _your_ PageInfo type instead of the default one.

**Comment by blevine** [comment]
Wouldn't I also need to copy/implement my own subclasses of BaseConnection (RelationConnection, ArrayConnection, etc)? Although I guess those are actually subclasses of GraphQL::Relay::BaseConnection as opposed to GraphQL::Types::Relay::BaseConnection.

**Comment by rmosolgo** [comment]
No, I don't think you'd need subclasses of those. GraphQL-Ruby uses the same objects to wrap Arrays, Relations, etc, but uses different type definitions for the GraphQL layer

**Comment by blevine** [comment]
Understood.  Thanks.
