### ISSUE TITLE
Wrap nested field resolution

### ISSUE THREAD

**Issue by augustocravosilva** [rmosolgo/graphql-ruby#1702]
Imagine this simple schema
```ruby
{
  hero {
    name
    appearsIn
  }
}
```

I want to be able to wrap both `hero` and `name`/`appearsIn` resolution in **one** block, so, I can, for example, instrument the time it took to execute the whole 
```ruby
 hero {
    name
    appearsIn
  }
```
instead of `hero` and then `name` and `appearsIn`.

I have tried to use [Field Instrumentation](http://graphql-ruby.org/fields/instrumentation.html), but it seems that this only allows me to wrap the resolution of the parent field.

I might be missing something. Is there a way to archieve this?

Thanks

Version that I used for testing: v1.7.7

**Comment by rmosolgo** [comment]
No, there's not really a way to do this. Maybe you could use the [tracing module](http://graphql-ruby.org/api-doc/1.8.5/GraphQL/Tracing) to measure each field time, then add up the times based on their paths (`ctx.path`).

It's not so simple because queries aren't always executed top-to-bottom. For example, to support batched data access (like graphql-batch), some field resolutions may be deferred until later.
