### ISSUE TITLE
Batch delivery of subscription update events

### ISSUE THREAD

**Issue by jacob-s-son** [rmosolgo/graphql-ruby#1708]
Currently Pusher transport implementation triggers update to every user one-by-one, which very quickly ceases to be real-time, as there is quite a delay between the first and the last subscriber.
So far after discussing this with my colleague, we've decided to patch the `execute_all` method in the `GraphQL::Pro` `Subscription` class and prepare data for Pusher's `batch_trigger`. Any thoughts on this?

**Comment by rmosolgo** [comment]
Oh, that sounds like a great suggestion! Feel free to share your patch if you like, otherwise I'll work on getting into the gem soon.

**Comment by jacob-s-son** [comment]
This would evolve patching Pro parts of the gem. How this is done process and legal wise?

**Comment by rmosolgo** [comment]
Your Pro license allows you to modify the code any way you see fit; AFAIK you can share your own modifications under any terms you choose :)

**Comment by jacob-s-son** [comment]
I will paste the changes we did, in the next few days. Feel free to incorporate them into gem as you see fit.

**Comment by lostboy** [comment]
> I will paste the changes we did, in the next few days. Feel free to incorporate them into gem as you see fit.

Hi @jacob-s-son we'd be really interested in taking a look at your patch if you ended up implementing something

**Comment by rmosolgo** [comment]
Part of this was released in graphql-ruby 1.11.0 / graphql-pro 1.14.0. Since those versions, it's possible to recognize a "broadcast" and then evaluate it _once_ and send the result to any number of subscribers. It's not exactly what's mentioned here, because it still uses _n_ channels for _n_ subscribers, but it's something: https://graphql-ruby.org/subscriptions/broadcast.html

I think there's still room for improvement where messages are published over the _same channel_, but this would be a bit tough. Currently, we use a Pusher channel for two things: 

- sending updates to subscribed clients (via `publish`) 
- detecting whether client is online or not (the server uses `channel_vacated` webhooks to delete subscriptions)

If we were going to do it over _one channel_, we'd need some other way to detect whether clients are online. We _could_ use pusher `presence-` channels for this, but it would require authenticated all subscribed users. 

The other thing is, I'm not sure what _advantage_ it would have to use a `presence-` channel. It looks like Pusher bills by _messages_ and _connections_, but not channels. And it looks a "message" is data delivered to a connected client, regardless of channel. 

So, my takeaway is that `presence-` channels are not worth it: they would raise the barrier to getting started without any cost savings (or usability improvements, that I can tell).

If anyone is interested in looking into presence channels more closely, or sees some advantages that I've overlooked, please open a new issue to discuss it!

**Comment by rmosolgo** [comment]
I think I was wrong about the pricing difference with Pusher. In the current implementation, given _n_ subscribers, we use _2n_ messages: 

- _n_ `publish` calls 
- _n_ deliveries to clients 


Using a presence channel, you could use _n+1_ calls instead: 

- 1 publish 
- _n_ deliveries
