### ISSUE TITLE
Support for @defer

### ISSUE THREAD

**Issue by joshporter1** [rmosolgo/graphql-ruby#1710]
I know it's been an "experimental feature" since sometime in 2016, but I saw that Apollo Server finally officially supports it. It would be great to use this in graphql-ruby! 

https://blog.apollographql.com/introducing-defer-in-apollo-server-f6797c4e9d6e

I believe a similar feature exists in Relay Modern as well.

**Comment by thefliik** [comment]
The apollo team has published their WIP `@defer` spec, as a reference for other graphql server authors:

- https://github.com/apollographql/apollo-server/blob/defer-support/docs/source/defer-support.md

**Comment by joshporter1** [comment]
Any updates on this feature, and whether or not the Ruby implementation of GraphQL will support it?

**Comment by levibuzolic** [comment]
https://graphql-ruby.org/defer/overview

**Comment by joshporter1** [comment]
Shame this feature is paywalled as it is a part of the Apollo GraphQL spec.

**Comment by rmosolgo** [comment]
Hey @joshporter1, it's built on top of [custom directives](https://graphql-ruby.org/type_definitions/directives.html), so if you want to see a free version, feel free to take a crack at it! Also, Apollo _hardly_ supports `@defer`. The [initial PR](https://github.com/apollographql/apollo-client/pull/3686/) was created by an intern and has been untouched since August of last year. [My PR](https://github.com/apollographql/apollo-client/pull/4504) to fix it has been ignored since I opened it in February. 

If you're interested in seeing more adoption of `@defer`, I hope that gives you a few ideas for where you can pitch in!

**Comment by joshporter1** [comment]
Thanks, will definitely look into that!
