### ISSUE TITLE
default_value for nil arguments

### ISSUE THREAD

**Issue by pareeohnos** [rmosolgo/graphql-ruby#1770]
I've run into a bit of an issue and not really sure of the best way to get around this. In one of my inputs, I have an array argument, where I want the array itself to be required but the contents of said array to be optional. Initially I had defined the argument like so:

    argument :line_items, [Types::Inputs::Finance::Common::MarkupTypeLineItemInput], required: true

thinking this would work but noticed that due to Rails' `deep_munge` by empty array for the `line_items` argument was being converted to `nil` and I was then getting an error.

In an attempt to fix this, I changed the argument so it wasn't required, but instead set a default value to an empty array. Unfortunately this did not resolve it, as I assume graphql-ruby treats even a nil value as a supplied argument (which makes sense as it might actually be wanted). 

Unfortunately, I am stuck with Rails 3 so can't simply disable deep_munge, and for that matter would rather not due to the security issues it fixes, so I need another solution for this.

Is there a way to achieve what I'm after, or would I have to instead filter out the input in my client code to simply not send the value at all if it's empty? It's not ideal as I then lose out on the query checking that an argument that is required is not set, but if there's no other option then I guess I have no choice.

It might be nice to have another flag for the `argument` method which instructs it to use the default value if the supplied value is nil?

**Comment by nickblumenthal** [comment]
Made a simple PR with my idea: https://github.com/rmosolgo/graphql-ruby/pull/1827

**Comment by pareeohnos** [comment]
Nice one, will track that :)

**Comment by nickblumenthal** [comment]
Whoops, sorry @pareeohnos  commented on the wrong thread - I also had an issue with default_values in https://github.com/rmosolgo/graphql-ruby/issues/1826 and meant to comment on that one.

**Comment by pareeohnos** [comment]
Ah fair enough, no worries

**Comment by ngouy** [comment]
so is it a normal behaviour or should we change this ?

**Comment by rmosolgo** [comment]
Sorry, I really can't think of a consistent way to fix this in GraphQL-Ruby. It's come up a few times since this issue was opened: #2714, #2592, and previously #986 

I can share a few work-arounds for this Rails behavior: 

1. _Re-parse_ the given request body and extract the variables. In your GraphQL controller: 

  ```ruby 
  json_body = JSON.parse(request.body.read)
  raw_graphql_variables = json_body["variables"]
  MySchema.execute(..., variables: raw_graphql_variables)
  ```

2. Disable deep munge for GraphQL _only_, see https://github.com/rmosolgo/graphql-ruby/issues/2714#issuecomment-583702142

3. 👎 Disable deep munge for the whole app. This is a _bad idea_ because deep munge provides some defense against security issues. However, it's possible:

  ```ruby 
  # don't do this, for security reasons 
  config.action_dispatch.perform_deep_munge = false
  ```

Personally, I'd recommend the first option, but I hope one of these works for you!
