### ISSUE TITLE
Make context (aka. `ctx`) read-only in resolvers

### ISSUE THREAD

**Issue by chrisbutcher** [rmosolgo/graphql-ruby#1816]
I had a discussion with a coworker today about whether we should ever let resolvers write key-values in `ctx` for later use by child fields, when they are resolved. I discouraged this practice, since it seems like a dangerous introduction of a dependency on shared mutable state.

Then a follow-up question came to mind: is there any reason we shouldn't make `ctx` read-only from the perspective of all resolvers? I can't think of any use-cases where we should allow this.

As far as I can tell, strongly-typed server implementations provide an immutable context: https://graphql-rust.github.io/types/objects/using_contexts.html

cc: @rmosolgo @swalkinshaw @eapache

**Comment by rmosolgo** [comment]
😆  I totally agree, but I was finally talked down a long time ago. Around here, some per-query calculations are cached in `context`, but of course they could use an object _in_ context for that caching instead of context itself. 

It doesn't quite seem worth it for the breaking change in my opinion, but if you want to try out in your app, class-based schemas _do_ support [custom context classes](http://graphql-ruby.org/schema/definition.html#context-class). Want to give that a try?

**Comment by thefliik** [comment]
FWIW, I use `ctx` to pass some expensive info around in a few places. E.g. a simple version of graphql-batch.

**Comment by chrisbutcher** [comment]
Thanks @rmosolgo I'll give that a whirl! I suppose we can close this issue if it's not a worthwhile breaking change to make this the default, and if there's a way to opt in via custom context classes.

> but of course they could use an object in context for that caching instead of context itself.

I may also look at preventing interior mutability with https://github.com/dkubb/ice_nine as well.

**Comment by rmosolgo** [comment]
Please let me know if a custom context class doesn't suit your needs here!
