### ISSUE TITLE
lazy_resolve for a Concurrent::Future has problems with nil

### ISSUE THREAD

**Issue by andrewparmet** [rmosolgo/graphql-ruby#1820]
Hello,

I'm using MRI and in an attempt at a minimal-effort optimization I'm wrapping some resolvers in `Concurrent::Future.execute` calls paired with `lazy_resolve(Concurrent::Future, :value)`.

Unfortunately this did not go so well.  For one non-nullable value I seem to be getting a `nil` result (even when I know the value I'm returning from the `execute` block is not `nil`), but only on the first load.

For another field I get a `nil` result always, but not if I intersperse some `puts` statements inside the `execute` block (but the number of statements doesn't seem to matter as much as where I put them in the block).

Do you have any recommendations for where I should start to look for a solution?

**Comment by rmosolgo** [comment]
Hmm, it sounds like you've narrowed it down pretty well: the `#value` method is returning `nil` for non-null fields. But, it changes behavior when you add `puts` statements? How strange! What about other ways of "spying" on the block, for example, writing to a file or modifying a global variable?
 
I don't have many ideas, except maybe trying `#value!` instead, since it will re-raise any errors that occur in the block.

**Comment by andrewparmet** [comment]
`value!` revealed two problems that each explain the behavior I was seeing: The first was a circular dependency load which explains the first-time-failure, and the second was a deadlock to acquire a DB connection, which explains the consistent failure that was remedied by operations that took variable amounts of time.
