### ISSUE TITLE
1.8.7 (and master?) does not provide support for `return_interfaces`

### ISSUE THREAD

**Issue by fgrehm** [rmosolgo/graphql-ruby#1837]
Hey there,

We're in the process of converting our project to 1.8+ class based API and we noticed that there is no equivalent of `return_interfaces`: https://github.com/rmosolgo/graphql-ruby/search?q=%22return_interfaces%22&unscoped_q=%22return_interfaces%22

Our use case is to do exactly what's specified [here](https://github.com/rmosolgo/graphql-ruby/blob/73ac09cb95a0b03b3f00c09921b65534f66d0ae6/guides/relay/mutations.md#specifying-a-return-interface) (the `MutationResult` interface).

Not sure if it got intentionally removed and / or we should be doing things differently but this is the workaround I came up with:

```ruby
class BaseMutation < GraphQL::Schema::RelayClassicMutation
  field :success, Boolean, null: false
  field :errors, [ValidationError, null: true], null: true

  class << self
    def generate_payload_type
      super.tap do |payload_defn|
        payload_defn.implements MutationResult
      end
    end
  end
end
```

**Comment by rmosolgo** [comment]
Oh! It was definitely an accident that it's not supported. The solution you posted there looks good to me,  if you'd like to add it to graphql-ruby I'm happy to help out!

**Comment by fgrehm** [comment]
Sure! Thanks for the quick response :)

How do you see this working? Just `include MutationResult` in our mutations or something like `payload_interface MutationResult`?

**Comment by vala** [comment]
The migration task throws an error when migrating from the old `.define` mutation syntax to the new class based one. It seems that the `PATTERN` regex in `InterfacesToImplementsTransform` ([defined here](https://github.com/rmosolgo/graphql-ruby/blob/v1.9.0.pre1/lib/graphql/upgrader/member.rb#L604)) also catches the `return_interfaces` declarations.

What I did was to override the regex by adding a `\b` flag in front of the `(?:interfaces)` part to avoid `return_interfaces` to be catched : `PATTERN = /(?<indent>\s*)\b(?:interfaces) \[\s*(?<interfaces>(?:[a-zA-Z_0-9:\.,\s]+))\]/m`

Then redefined the `return_interfaces` class method in the `Mutations::BaseMutation` class and used the solution provided by @fgrehm to hook into the payload type generation.

Some default method like `payload_interface` would be nice, and could be used in the upgrader code too.

**Comment by cantino** [comment]
We need this as well in order to upgrade to 1.8 for our mutations.

**Comment by bjeanes** [comment]
Would there be a nice way to model a consistent mutation result similar to above but as a dynamic union type containing the fields defined as specific to the mutation and a re-used "mutation failure" type?

We have been using the above approach (incl the above `generate_payload_type` method) and it's working well, but one side-effect is that the mutation types end up all having a lot of nullable result fields to handle the error case.

A stronger type might be something that communicated it will *EITHER* be `{ success: false, errors: Error[] }` _or_ `{ success: true, mutation_specific_field: !Type }`. In fact, in that case, the `success` boolean is redundant because the query would have to do something like `... on MutationError { errors { message } } ... on MutationXYZResult { mutation_specific_field }`.

**Comment by rmosolgo** [comment]
The previous behavior of `return_interfaces` was to mix those interfaces into the generated payload object. With class-based mutations, you can achieve this by: 

- Creating a base payload which extends your base object. Add the interfaces you want to that base class. 

  ```ruby 
  class Types::BaseMutationPayloadType < Types::BaseObject 
    implements Types::PayloadInterface # <= your interface here 
  end 
  ```

- Hook up that base class as `.object_class(...)` in your mutation.

  ```ruby 
  class Mutations::BaseMutation < GraphQL::Schema::RelayClassicMutation 
    object_class(Types::BaseMutationPayloadType)
  end
  ```

Now, any mutation that extends `BaseMutation` will use `BaseMutationPayloadType` as the base class for its generated payload types. The generated payload times will get the same interfaces, due to inheritance. 


For _unions_, you can provide a union using `payload_type(...)`: 

```ruby 
class Mutations::DoSomething 
  payload_type(Types::DoSomethingPayloadUnion)
end 
```

That provided type will be used instead of generating a payload. 

Alternatively, you could override `generate_payload_type` to create unions on-the-fly, using the generated payload type as one member of the type: 

```ruby 
class Mutations::BaseMutation < GraphQL::Schema::RelayClassicMutation
  def self.generate_payload_type 
    # Get the generated object type: 
    payload_object_type = super 
    # but return a union made of the generated object _and_ the default error type 
    mutation_name = self.graphql_name
    Class.new(Types::BaseUnion) do 
      # assign graphql_name here since it can't be inferred from the class name
      graphql_name("#{mutation_name}Result")
      possible_types(payload_object_type, Types::MutationError)
    end 
  end 
end 
```

Then, each mutation would generate _both_ a payload object and a union containing the payload or an error. 

Sorry for the late response here. If you try one of those options and run into trouble, please open a new issue!
