### ISSUE TITLE
`loads:` should return `nil` when provided an ID of `nil`

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#1840]
Sometimes you want to pass `thingId: nil` as a way of saying "there should be no `Thing` here". `loads:` bombs on this right now, but it should probably inject `thing: nil` into `#resolve` instead.

**Comment by xuorig** [comment]
If i recall correctly, I've faced a similar issue in the past with a setup similar to `loads`. The problem is that it becomes hard to differentiate:

  - We tried loading the object and it didnt exist
  - There was nothing to load (thingId: nil)

If in your resolver you want to raise an error when the object is not found, this gets tricky. I guess maybe you simply don't use `loads` in these cases?

**Comment by cjoudrey** [comment]
> `loads:` should return `nil` when provided an ID of `nil`

I _think_ the behavior really depends on the nullability of the argument. I would also optimize for the most common use case, while making the rest still possible.

---

**If the argument is required**, I think we should not pass through `nil` and should :boom: as we do today. If we start passing through `nil` in cases where the argument is required, it'll be prone to errors as people will need to do `nil` checks in their resolver and will no doubt forget.

For example:

```ruby
argument :label_id, ID, "..", required: true, loads: Objects::Label

def resolve(label:, **inputs)
  # Currently people can assume `label` is always present.

  # If we let through, `nil` we'll need to do `nil` checks everywhere
  # and are bound to forget one at some point.
end
```

If someone really wants to the `nil` to make it to the `resolver` for required arguments, we can always add a option for this like `loads_allow_nil: true`.

---

**If the argument is optional**, I think it's a different story. I would do this:

- If the argument is optional and a `nil` value is provided, pass the `nil` to the resolver and use `inputs.key?(:thing)` to differentiate between omitted and `nil`.
- If the argument is optional and omitted, the `inputs` hash will not have the value so we can use `inputs.key?(:thing)`.
- If the argument is optional and provided a non-empty invalid value, it should :boom: like we do today.

In this case, I think we should allow `nil` to make it to the `resolver` for optional arguments, since the user already expects this value to be `nil`.

---

> If in your resolver you want to raise an error when the object is not found, this gets tricky. I guess maybe you simply don't use `loads` in these cases?

I agree it would be tricky (today) to report these kind of errors as part of the mutation payload.

There is a hook called [`load_application_object_failed`](https://github.com/rmosolgo/graphql-ruby/blob/377747523b38b49d317525abc75b4f3342976c2a/lib/graphql/schema/resolver.rb#L228-L237), but I don't think it would be super helpful in this case, at least not in its current shape.

While I think it's important we have this discussion, I'm not sure it's a blocker to the current issue at hand.

**Comment by rmosolgo** [comment]
☝️  that sounds pretty good to me

**Comment by xuorig** [comment]
Sounds good!
