### ISSUE TITLE
How to return a list of all enums for an EnumType?

### ISSUE THREAD

**Issue by AndrewRayCode** [rmosolgo/graphql-ruby#1844]
I have a `CountryCodesEnum` I need the client to consume to show a dropdown. The definition is nothing special:

```ruby
CountryCodesEnum = GraphQL::EnumType.define do
    name 'CountryCodesEnum'

    country_abbreviations.map do |key, value|
        value value, key
    end
end
```

I'm trying to expose this as a query field so the client can know what data it's allowed to send. I've tried both:

```ruby
field :countries, types[EnumTypes::CountryCodesEnum] do
  resolve ->(_obj, _args, _ctx) { EnumTypes::CountryCodesEnum.values }
end
```
and
```ruby
EnumTypes::CountryCodesEnum.to_list_type
```

but both result in errors. I don't see an example of this pattern on https://www.rubydoc.info/github/rmosolgo/graphql-ruby/GraphQL/EnumType. Since the client needs both the `value` of the enum and the `description` for user display, I think I want a list of enums? But i'm having trouble figuring out how

**Comment by AndrewRayCode** [comment]
Oh nice I can get it through type introspection on the client. I'll close this if there's no "better" way
```graphql
__type(name: "CountryCodesEnum") {
    enumValues{
      name
      description      
    }
  }
```

**Comment by thefliik** [comment]
In general, think using an introspection query is the "graphql" way of exploring all parts of a graphql schema, including this issue here.  For example, the [apollo-cli](https://github.com/apollographql/apollo-cli#apollo-codegengenerate-output) has a tool for downloading a graphql schema and generating typescript types from it, which a client could use to type their queries.

This being said, in order to dynamically reflect on an enum type object's different values on the server side, using the [new, class-based API](http://graphql-ruby.org/type_definitions/enums), you could also subclass the `GraphQL::Schema::Enum` object and add in any functionality you want to accomplish this.

**Comment by rmosolgo** [comment]
Yes, I agree with @thefliik , introspection is the way to go!
