### ISSUE TITLE
types undefined?

### ISSUE THREAD

**Issue by rjrobinson** [rmosolgo/graphql-ruby#1881]
I'm very confused as to how to start here. 

I followed the front page tutorial, and then built my basic types host_type and a user_type. 

When I tried to wire them up to the back end, and get all of the resolvers working, I keep encountering this odd `types undefined`

So, here is where its gets really tricky. After following some tutorials, I noticed that my _types look way different then theirs. 

The class based style as listed below was throwing the aforementioned errors. 

```ruby
#../types/user_type.rb
# created by using a rails generator
module Types
  class UserType < Types::BaseObject
    field :name, Types::StringType, null: true
    field :login, Types::StringType, null: true
    field :email, Types::StringType, null: true
  end
end

```

However..... If I switch to this style. 

```ruby 
  #../types/user_type.rb
  Types::UserType = GraphQL::ObjectType.define do
    field :name, !types.String
    field :login, !types.String
    field :email, !types.String
  end
```
It works. Any idea what Im doing wrong?

**Comment by mmahalwy** [comment]
What version of the gem are you using? If 1.8 or above, this is not just `String` without `types.`

**Comment by rjrobinson** [comment]
I'm not sure what you mean by `this is not just String without types.`. 

I am using 1.8.10

Can you point me to some examples of this version showing how to use `*_type`  and the corresponding `query_type`

**Comment by rjrobinson** [comment]
Yea. I'm still missing something here. I went through the "Getting Started", all the way through again. I just want to present to you what I have, and the new errors that keep popping up 

We can start at the beginning

```ruby
#./
class MySchema < GraphQL::Schema
  query QueryType
end
```

```ruby
#types
/query_type.rb
class QueryType < GraphQL::Schema::Object
  description "The query root of this schema"
  graphql_name 'Query'

  # queries are just represented as fields

  field :users, [UserType], null: true do
    description 'A list of users'

    resolve -> (obj, args, ctx) do
      User.all
    end
  end
end
```

```ruby
#./types/user_type.rb
class Types::UserType < Types::BaseObject
  graphql_name 'User'
  description "The basic user of an application. can have flags attached to it for roles."

  field :name, String, null: true
  field :login, String, null: true
  field :email, String, null: true
  field :role, String, null: true
end
```

When i do this, I open graphiql, after i restart the server and run this query

```graphql
query {
  users{
    id
    email
    login
  }
}
```
and I now get back this error 

```json
{
  "error": {
    "message": "uninitialized constant GruSchema::QueryType",
	"backtrace": ...
}
```

So, I am really lost right now.

**Comment by rjrobinson** [comment]
I also noted that the PostType in the Getting Started states that the types need to have a _.graphql extension? 

example -> # app/graphql/post_type.graphql

**Comment by thefliik** [comment]
I see a few errors. It looks like you're combining pieces of the pre 1.8 api and the new 1.8 api--which you cannot do. Part of the issue is definitely that the docs are only partially updated to the new api.

Another problem is you appear to not be [following rails' autoloading expectations](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html).

Since `QueryType` is defined in `./types/query_type`, I don't think rails can automatically find the definition if the class itself is in the top level namespace. The class would need to be in the `Types` namespace for it to know to look in the `types` folder.

You also try and access the `UserType` within the `QueryType` class using the top level namespace, instead of the nested `Types::UserType` namespace, which it is in. You could just use `UserType` if the `QueryType` class was, itself, in the `Types` namespace, but it isn't in your code. These are just generic Rails issues (rather then graphql-ruby issues).

Also, graphql ruby will automatically remove the `Type` suffix from class names when defining graphql object names. I.e. by default `QueryType` will have the graphql object name `Query`.

Anyway, rather then call out individual errors. let me just put down what I think is the correct formatting:

```
#./my_schema.rb
class MySchema < GraphQL::Schema
  query Types::QueryType
end
```
```
#./types/query_type.rb
module Types
  class QueryType < GraphQL::Schema::Object
    description "The query root of this schema"

    # queries are just represented as fields

    field :users, [UserType], null: true do
      description 'A list of users'
    end

    def users(**args)
      User.all
    end
  end
end
```
```
#./types/user_type.rb
module Types
  class UserType < BaseObject
    description "The basic user of an application. can have flags attached to it for roles."

    field :name, String, null: true
    field :login, String, null: true
    field :email, String, null: true
    field :role, String, null: true
  end
end
```
Your controller looks fine.

I'll also point out that your UserType inherits from a custom `BaseObject` type, but, since you didn't include that definition here, it's unclear if you actually defined that `BaseObject` type anywhere (you would need to).

I haven't actually tested this code so I'm not sure it's 100% typo free, but hopefully you get the idea.

**Comment by rjrobinson** [comment]
Well, that actually got it working, so that good. I ended up just ripping out the entire thing and started from scratch. Seems as if the resolve method isn't being used on the query_tyoe anymore?

Better documentation on that would be helpful. Thanks for your help. 

The graphql rails generators also need to be updated as they are using the old style.

**Comment by rjrobinson** [comment]
Closing this issue as I have discussed this with the friends in the slack channel.
