### ISSUE TITLE
Objects and InputObjects shouldn't be allowed to have no fields

### ISSUE THREAD

**Issue by DamirSvrtan** [rmosolgo/graphql-ruby#1923]
Hi there! 👋 First of all, thank you for all of the work on this gem!

As much as I see, the gem allows for creation of query types & input objects that have no fields, but that seems to not be following the specification:
https://facebook.github.io/graphql/June2018/#example-dd904

_An Object type must define one or more fields._
_An Input Object type must define one or more input fields._

Are there any plans on getting the gem into parity with this schema?

Thank you!

**Comment by rmosolgo** [comment]
Hi! Oops, that sounds like a bug. I think we should have some way of checking a schema for that. But it's not currently prioritized!

**Comment by daemonsy** [comment]
For additional context, if you try to use any of the provided tools from `graphql-js` to parse the schema built by calling `Schema.execute(GraphQL::Introspection::INTROSPECTION_QUERY)` with empty objects, an error is thrown. 

One of the problems I faced in real life: 
1. someone new to GQL is trying to introduce an object into the system
2. starts off with an empty class definition
3. Tries to get "tactile" feedback from an IDE tool like GraphiQL
4. Gets confused because there's no Ruby error but the JS client is totally broken. 

I'll take a stab at this issue.

**Comment by swalkinshaw** [comment]
https://github.com/rmosolgo/graphql-ruby/pull/2462 addresses this old issue as well?

**Comment by daemonsy** [comment]
It looks like it! I’ll follow/contribute to that instead
