### ISSUE TITLE
Multiplex not running concurrently 

### ISSUE THREAD

**Issue by DamirSvrtan** [rmosolgo/graphql-ruby#1969]
Hi @rmosolgo! 👋First of all, thank you for your hard work!

The guides mention that the multiplex method executes queries **concurrently** however that is not what I am seeing (or I am maybe doing something wrong).

I am referencing this part of the guides: http://graphql-ruby.org/queries/multiplex.html#concurrent-execution

I've created a simple example:

```ruby
require 'graphql'

class MyQuery < GraphQL::Schema::Object
  field :sleeping, Integer, null: true

  def sleeping
     sleep 5
  end
end

class MySchema < GraphQL::Schema
  query(MyQuery)
end

query_string = <<~HEREDOC
  query {
    sleeping
  }
HEREDOC

puts MySchema.multiplex(
  [{ query: query_string }, { query: query_string }]
).to_json
```

I should be getting execution time somewhat over 5 seconds, not over 10 seconds.

```shell
time ruby bench-multiplex.rb
[{"data":{"sleeping":5}},{"data":{"sleeping":5}}]
ruby bench-multiplex.rb  0.36s user 0.12s system 4% cpu 10.523 total
```

Do you know what I might be doing wrong?

**Comment by DamirSvrtan** [comment]
If I perform the same thing with concurrent ruby & futures, I get concurrent execution:

```ruby
require 'graphql'
require 'concurrent-ruby'

class MyQuery < GraphQL::Schema::Object
  field :sleeping, Integer, null: true

  def sleeping
    Concurrent::Future.execute do
      sleep 5
    end
  end
end

class MySchema < GraphQL::Schema
  query(MyQuery)
  lazy_resolve(Concurrent::Future, :value)
end

query_string = <<~HEREDOC
  query {
    sleeping
  }
HEREDOC

puts MySchema.multiplex(
  [{ query: query_string }, { query: query_string }]
).to_json
```

I get a bit over 5 seconds:

```shell
time ruby bench-multiplex.rb
[{"data":{"sleeping":5}},{"data":{"sleeping":5}}]
ruby bench-multiplex.rb  0.33s user 0.11s system 8% cpu 5.473 tota
```

**Comment by rmosolgo** [comment]
Hi! I think it's a bit of confusion between _concurrent_ and _parallel_: 

> In programming, concurrency is the composition of independently executing processes, while parallelism is the simultaneous execution of (possibly related) computations.

(["Concurrency is not parallelism"](https://blog.golang.org/concurrency-is-not-parallelism)) 

With a multiplex, queries are evaluated breadth-first as if they were all members of one giant query. This helps with data fetching (batching and caching, eg with graphql-batch). And this is why they're described as _concurrent_: the independently executing queries are actually interleaved and run together, for a performance benefit.

As you noted, nothing about multiplexes is parallelized. Although the individual field resolutions are composed together, they are not _evaluated at the same time_. This is by design, in a way: it's not clear to me how parallelization can be implemented in a way that's general but also efficient. Maybe that can be a goal for the library later on, but I don't hear anyone requesting it, and I have enough on my plate already 😅 .

Let me know if that doesn't clarify things a bit!

**Comment by DamirSvrtan** [comment]
Hi! 

I know that concurrency is not parallelism, but I believe this needs better wording because it sounds misleading.  I would not say they are executed concurrently, they might be executed in isolation (I guess one can error, the other won't), but they are executed **sequentially**, one after the other, am I right?

If I am, I would avoid the word **concurrent** in the docs.

**Comment by onedal** [comment]
> If I perform the same thing with concurrent ruby & futures, I get concurrent execution:
> 
> ```ruby
> require 'graphql'
> require 'concurrent-ruby'
> 
> class MyQuery < GraphQL::Schema::Object
>   field :sleeping, Integer, null: true
> 
>   def sleeping
>     Concurrent::Future.execute do
>       sleep 5
>     end
>   end
> end
> 
> class MySchema < GraphQL::Schema
>   query(MyQuery)
>   lazy_resolve(Concurrent::Future, :value)
> end
> 
> query_string = <<~HEREDOC
>   query {
>     sleeping
>   }
> HEREDOC
> 
> puts MySchema.multiplex(
>   [{ query: query_string }, { query: query_string }]
> ).to_json
> ```
> 
> I get a bit over 5 seconds:
> 
> ```shell
> time ruby bench-multiplex.rb
> [{"data":{"sleeping":5}},{"data":{"sleeping":5}}]
> ruby bench-multiplex.rb  0.33s user 0.11s system 8% cpu 5.473 tota
> ```

Thx for help!
