### ISSUE TITLE
Difficulty determining if field is a connection via query analyzer

### ISSUE THREAD

**Issue by gjtorikian** [rmosolgo/graphql-ruby#201]
I have an analyzer in mind that deals with specifically connection fields. I can pick up whether or not a thing I'm traversing is a field:

```
if irep_node.ast_node.is_a?(GraphQL::Language::Nodes::Field)
...
end
```

But I can't seem to figure out any way to identify a `connection` versus a `field`. I can look at the `irep_node.ast_node.arguments` for "connection-like" arguments (`first`, `last`, etc), but that seems very hacky.

Is there a way to achieve what I'm after?

**Comment by rmosolgo** [comment]
Hmm... one option is to inspect the return type, like 

```ruby 
irep_node.return_type.name.end_with?("Connection")
```

But there there is no _sure-fire_ way to detect that the field was created with the `connection` helper, since it's just a "plain old" `GraphQL::Field`. 

I can think of two ways to support this (from easy to hard 😛 ) :

- Replace the proc in [`get_connection_resolve`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/connection_field.rb#L45-L51) with a resolver object like [`GlobalIdResolve`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/global_id_resolve.rb), then you can check for `irep_node.definitions.all? { |type_defn, field_defn| field_defn.is_a?(ConnectionResolve) }`
- Add field tags to `graphql-ruby` (as seen in Sangria, eg http://sangria-graphql.org/learn/#middleware-based-auth)

**Comment by gjtorikian** [comment]
If you're okay with it, I'd be happy to make a PR for the first change.

**Comment by rmosolgo** [comment]
:+1: yep!
