### ISSUE TITLE
Serialize/deserialize schema

### ISSUE THREAD

**Issue by stefanoverna** [rmosolgo/graphql-ruby#2026]
In our SaaS we have to generate a different schema for each of our users. 

Every time a new requests arrives, we have to rebuild a new schema from scratch. The slowest part is the `rebuild_artifacts` stage (https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema.rb#L1096), which on complex schemas, can take up to 3 seconds.

Is there any way we can serialize and save the generated schema, so that the next time the same user performs a request we can avoid all this useless processing and just load it from cache?

Any pointer would be much appreciated, thanks

**Comment by yy32ds33** [comment]
.. then

**Comment by stefanoverna** [comment]
@yy32ds33 ?

**Comment by stefanoverna** [comment]
Any feedback @rmosolgo :( ?

**Comment by stefanoverna** [comment]
Any pointer would be much appreciated @rmosolgo... we are more than willing to consider sponsoring this if needed! Thanks for your time

**Comment by rmosolgo** [comment]
Hey, sorry for the slow response. 

This library just isn't suited to build schemas on the fly for the reason you mentioned. It pre-builds caches and depending on the schema configuration, it can be really slow. I have a few thoughts to share: 

- This library does support a schema _filtering_ approach, that is, where different viewers can see a _subset_ of the whole schema. This is intended for something like an "admin" schema and a "public" schema, but I thought I'd share in case it helps: http://graphql-ruby.org/authorization/visibility.html
- I'm on my way to _removing_ the schema-level caches because they're hard to manage and slow to build. The alternative approach I have in mind is to build them incrementally, and only once. But even in my best case, this would be intended for use during `class MySchema < GraphQL::Schema ... end`, at application boot, so it might not be fast enough for truly dynamic schemas. 
- You mentioned caching. Have you tried any kind of caching yet? I really don't know whether `Marshal` would work in this case, but I suppose it's worth a try. 
- What about in-memory caching? Depending on how many unique schemas you need, it might be possible to retain the built schemas in Ruby's heap (for example, using a thread-safe Hash as a cache). Did you consider it? 

Finally, if none of those work, I'd love to hear more about your use case to see if there's a way to better support it. Maybe `Schema.build_from_definition(...)` could be improved to support it, or something.

**Comment by rmosolgo** [comment]
Closing as stale -- I don't have any plans to work on short-lived schemas right now.
