### ISSUE TITLE
[1.8.12] Validation error regressions

### ISSUE THREAD

**Issue by swalkinshaw** [rmosolgo/graphql-ruby#2030]
It looks like the new error bubbling feature introduced in https://github.com/rmosolgo/graphql-ruby/pull/2013 (and in 1.8.12) causes some regressions in validation errors even when its **not enabled** (I tried enabling/disabling to be sure).

Here's an example:

1.8.10:

```ruby
=> {:errors=>
  [{:message=>"Argument 'input' on Field 'productCreate' has an invalid value. Expected type 'ProductInput!'.",
    :locations=>[{:line=>2, :column=>3}],
    :fields=>["mutation M", "productCreate", "input"]}]}
```

1.8.12 `error_bubbling = false`

```ruby
{:errors=>
  [{:message=>"Argument 'foo' on InputObject 'ProductInput' is required. Expected type FooInput!", :locations=>[{:line=>2, :column=>52}], :fields=>["mutation M", "productCreate", "input", "foo"]},
   {:message=>"Argument 'bar' on InputObject 'ProductInput' is required. Expected type BarInput!",
    :locations=>[{:line=>2, :column=>52}],
    :fields=>["mutation M", "productCreate", "input", "bar"]}]}
```

1.8.12 `error_bubbling = true`

```ruby
{:errors=>
  [{:message=>"Argument 'input' on Field 'productCreate' has an invalid value. Expected type 'ProductInput!'.",
    :locations=>[{:line=>2, :column=>3}],
    :fields=>["mutation M", "productCreate", "input"]},
  [{:message=>"Argument 'foo' on InputObject 'ProductInput' is required. Expected type FooInput!", :locations=>[{:line=>2, :column=>52}], :fields=>["mutation M", "productCreate", "input", "foo"]},
   {:message=>"Argument 'bar' on InputObject 'ProductInput' is required. Expected type BarInput!",
    :locations=>[{:line=>2, :column=>52}],
    :fields=>["mutation M", "productCreate", "input", "bar"]}]}
```

cc @modosc as well

**Comment by modosc** [comment]
i don't think this is the error bubbling but rather the fix for #1967 - if i'm seeing this right you're now getting the individual errors for the missing fields (which wasn't available before). the error bubbling functionality seems to be working as your third example has all three errors (the two actual missing errors as well as the parent input object). i didn't gate this fix off of error bubbling because it seemed unrelated, it was something that _should_ have existed previously but didn't.

**Comment by rmosolgo** [comment]
Oh, I see now what you mean, how the old behavior was a _third thing_ where the parent error was present (on `productCreate(input: ...)`), but now the underlying errors on `productCreate(input: { foo: ..., bar: ...})` are present instead. 

I guess I think of this as a _feature_, since it gives clients more information about what went wrong. Is this a regression beyond the fact that it's _different_ than before? I mean, are there downsides besides being not-the-same?

**Comment by swalkinshaw** [comment]
> I guess I think of this as a feature, since it gives clients more information about what went wrong. Is this a regression beyond the fact that it's different than before? I mean, are there downsides besides being not-the-same?

Yeah correct. I meant regression as "unexpected change". I'm not sure this issues required any changes/action, but thought it would be useful for documentation purposes.

**Comment by modosc** [comment]
maybe we could add a changelog entry for this specific fix? it was merged in with the error bubbling but it's really a separate thing.

**Comment by swalkinshaw** [comment]
That would probably be useful 👍

**Comment by rmosolgo** [comment]
I added a changelog entry: https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1812-3-jan-2018 Feel free to PR if you'd like to improve it!
