### ISSUE TITLE
access to field context in authorized?

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#2036]
(see also #1805, #881, and #1809)

we'd like to know about the parent / grandparent field of a field in order to set visibility / access / authorization. right now the context passed to `authorized?` is `query_ctx` which doesn't allow us to go up the tree to see ancestors / neighbors. would you be open a to a pr to add an additional `field_ctx` param to `authorized?` (which would basically be the `ctx` passed into `resolve_field`)?

**Comment by rmosolgo** [comment]
Hi, sorry for the late reply here. 


I intentionally left out _field-level_ context from the new authorization API because in my experience, it was a foot-gun. It encouraged users to make assumptions about _where_ in a query an object might be authorized. But inevitably, as the schema grew, new contexts are created, and the code which makes those assumptions (about _where_) may get out-of-date. Since it's authorization, that stale code could become a security issue!

So, instead, I recommend performing context-specific authorization _in the context where it applies_ instead of at the object-level. For example, if a certain field has extra authorization, perform the authorization at field-level. 

If objects are _less restricted_ in some contexts than others, how about wrapping the object in a proxy, which could be detected later on? That way, the context is _encoded in the object itself_ and you can have more confidence that only _those proxies_ receive special treatment. 

I'm happy to talk more if you want to share more about your specific use case!
