### ISSUE TITLE
Schema#unauthorized_object hook doesn't seem to be called if `authorized?` is false for Mutations

### ISSUE THREAD

**Issue by pratik0809** [rmosolgo/graphql-ruby#2048]
I have an authorized method on my CreateMutation as described in the docs: http://graphql-ruby.org/authorization/authorization.html

```
#Inherits from a BaseMutation which inherits from GraphQL::Schema::Mutation 
def authorized?(object)
      super && #more auth logic
end
```
And added this on my schema:

```
class MySchema < GraphQL::Schema
  def self.unauthorized_object(error)
    raise GraphQL::ExecutionError, "An object of type #{error.type.graphql_name} was hidden due to permissions"
  end
end
```
I expected that if `authorized?` returns false it would call the Schema#unauthorized_object to return the error but that hook doesn't seem to be called at all.  Does it require an object to be loaded? if so, how can I load an object that doesnt exist yet (createMutation)?

**Comment by rmosolgo** [comment]
It might be a bug! Thanks for opening this issue, I agree that the error should be routed there. We did something similar with `unauthorized_field` lately: #1994

**Comment by lassiter** [comment]
I am also experiencing similar behavior. @pratik0809 did you ever find a solution?

**Comment by kryptonat** [comment]
+1 

Returning false within the `authorized?` instance method of a mutation does not call the `self.unauthorized_object` schema hook. 

This is confusing because it differs from the way object and field `self.authorized?` handles returning false i.e. it is successfully caught by the `self.unauthorized_object` schema hook.

Any updates on fixing this bug?

@lassiter you can raise a `GraphQL::UnauthorizedError` in the `authorized?` instance method and it will be caught by the `unauthorized_object` schema hook as a workaround but it's not ideal
