### ISSUE TITLE
modern js builds

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#2052]
are you open to a pr moving the current js client code to a more modern build setup (ie, with babel)? this way we could use es201* features in the code and also export es6 modules.

**Comment by rmosolgo** [comment]
I'm not immediately opposed to it, but I want to make sure we support various Node runtimes, too since [at least one person](https://github.com/rmosolgo/graphql-ruby/pull/1889#issuecomment-427843385) is using it that way. 

Also, since I'm primarily a Ruby developer, I want to keep the maintenance workflow simple and the JavaScript dependencies minimal.

Are there specific features you'd like to take advantage of in a workflow like that?

**Comment by vipulnsward** [comment]
Here's a good reference of how Rails did this for Action Cable recently: https://github.com/rails/rails/pull/34177/files

**Comment by modosc** [comment]
sure - you can compile it via babel for the lowest common denominator (for instance, ie11 + least recently supported node version). and the es6 module exports are exactly the same but with `import`/`export` instead of `require`/`module.exports`. but then in the actual code you can use `async` / `await`, `const` / `let`, destructuring. 

i do this in several of my repos, [here](https://github.com/modosc/react-responsive-redux) for instance. i'm happy to pick this up the next time i'm digging into the js code.
