### ISSUE TITLE
How to test subscriptions?

### ISSUE THREAD

**Issue by FrancisMurilloDigix** [rmosolgo/graphql-ruby#2163]
Hello, is there a way or guide in testing subscriptions?

**Comment by rmosolgo** [comment]
Hi! No, there's not a guide. 

For a web front end, I'd recommend something like Rails' system tests for integration testing, for example: 

https://github.com/rmosolgo/graphql-ruby/blob/master/spec/dummy/test/system/action_cable_subscription_test.rb

Depending on your implementation, you could also: 

- Test for side effects, eg, writes to redis 
- Set up a subscription client in Ruby and run subscriptions in the test suite 

hope that helps! Feel free to discuss specific issues if you give one of those approaches a try.

**Comment by FrancisMurilloDigix** [comment]
I am currently using API only though. I was using `action-cable-testing` but was unable to test the `update` method of a subscription.

At the moment, subscriptions don't have comfortable code coverage and I pray it works. Anyway, I understand but it would be really nice to have easier and pleasant unit tests as a feature. Thanks for the response.

**Comment by aub** [comment]
I've been struggling with this for a while, and I cannot figure out how to test the subscriptions at all. I'm also writing an API-only Rails app and using ActionCable as the service for the subscriptions. I'd like to at least validate that authorization is being done correctly within the subscriptions but can't figure out how to do that with rspec's tools.

**Comment by rmosolgo** [comment]
👋  Since this issue was opened (and closed), I added some unit tests to ActionCableSubscriptions: 

https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/subscriptions/action_cable_subscriptions_spec.rb

It uses a mock ActionCable implementation to intercept subscription updates. It's probably a bit brittle, since implementation changes will cause the test to break, but it's another option for API-only apps. 

(Other subscription tests use a similar mock setup, maybe it'd be advantageous to build a system like that into GraphQL-Ruby, to help with testing)

**Comment by aub** [comment]
Nice, thanks, that seems like a good place to start. There's a lot to grasp here, so it certainly would be nice to have it integrated into the tool, but in the meantime I bet I can get this running.

**Comment by bino98** [comment]
> https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/subscriptions/action_cable_subscriptions_spec.rb

it's works! Thanks so much!
