### ISSUE TITLE
Access underlying application `object` in field definition

### ISSUE THREAD

**Issue by laasem** [rmosolgo/graphql-ruby#2180]
I'm trying to generate a field dynamically and conditionally based on certain values of the underlying object, but the `object` method is inaccessible at the class level. Any idea how I can go about this?

e.g.:

```ruby
# app/models/underlying_object.rb
class UnderlyingObject < ApplicationRecord
  has_many :polymorphic_associations
  has_many :associated_objects, through: :polymorphic_associations, source: :associatable

  def associatable_type_graphql_key
    return unless associated_objects.present?
    associatable_type.downcase.pluralize.to_sym
  end

  def associatable_type_graphql_type
    return unless associated_objects.present?
    type_constant = "Types::#{associatable_type}Type".constantize
    if associated_objects.size > 1
      [type_constant]
    else
      type_constant
    end
  end
end


# app/graphql/types/base_object.rb
module Types
  class BaseObject < GraphQL::Schema::Object
    def self.conditional_field(condition, &block)
      yield if condition
    end
  end
end

# app/graphql/types/underlying_object_type.rb
class UnderlyingObjectType < Types::BaseObject
  conditional_field object.associated_objects.present? do
    field object.associatable_type_graphql_key, object.associatable_type_graphql_type, null: true
  end

  define_method object.associatable_type_graphql_key, object do
    AssociatedObject.where(object.associatable_ids)
  end
end
```

For context: I'm migrating from a JSON API that uses jbuilder where I could simply use `if` conditions and object methods in views to achieve this, so if there is a more GraphQL way of going about this do let me know.

Update: I've realized I can implement the conditional logic in the resolver; now I just need a way to dynamically generate the field name.

**Comment by rmosolgo** [comment]
It sounds like you're trying to make objects of the _same_ type have _different_ fields. That's not possible in GraphQL; in GraphQL, all objects of the same type have the _same_ fields. If you want objects with different fields, then you'd make _different_ types. I can suggested a few paths for brainstorming: 


- Make a separate object type for each set of fields you want to expose, then create a Union or Interface that includes all those object types 
- Using one object type, add a field for _every_ `associatable_type`, and implement it so that fields return `null` when `object` doesn't have that kind of associatable type. 

Hope that helps!

**Comment by laasem** [comment]
It does - I had ended up going for the second option but wasn't sure it was a good approach. Thanks a lot for your fast reply!
