### ISSUE TITLE
[pro] Pundit - naming of `pundit_role`

### ISSUE THREAD

**Issue by ajoneil** [rmosolgo/graphql-ruby#2181]
We're using the Pundit integration from GraphQL::Pro, but we've found the naming of the parameter `pundit_role` on fields to be counter-intuitive. The methods on our policies aren't roles such as `staff?`, but specific permissions such as `list_posts?` or `create?`, as is suggested by the Pundit documentation. I've aliased this to `pundit_permission` in our code-base, but would prefer to avoid patching over upstream - can this parameter be renamed or aliased to better reflect its use?

**Comment by ajoneil** [comment]
This is our `BaseField`:
```ruby
class Api::Types::BaseField < GraphQL::Schema::Field
  include GraphQL::Pro::PunditIntegration::FieldIntegration

  def initialize(**args)
    if args.has_key? :pundit_permission
      args[:pundit_role] = args[:pundit_permission]
      args.delete :pundit_permission
    end

    super(**args)
  end
end
```

**Comment by bjeanes** [comment]
Agreed. "role" doesn't make sense in the scope of Pundit policies. `permission` or `action` or anything like that would be more in-line with Pundit's approach. The policy examples in Pundit's README pretty much all use "verb" words.

> The class implements some kind of query method, in this case `update?`. Usually, this will map to the name of a particular controller _action_.

**Comment by rmosolgo** [comment]
Thanks for opening this discussion and for the link to those docs. I meant to pick something that matched Pundit conventions, but I might have gotten the wrong idea! I'll take another look and follow up here soon.

**Comment by bessey** [comment]
I would also like to vouch for "action", I think it semantically makes the most sense; 

You're either asking the pundit policy if the user...
1. is an [X]?. (role: e.g. admin)
2. can [X]?. (action / permission: e.g. view)
The way I and the pundit docs word Policy methods is as verbs, e.g. `show?` (we actually use `view?` for GraphQL since there's no need to map to REST verbs), so its clear role is wrong. I don't think it really _matters_ between action and permission, but i'd rather right `pundit_action` a bunch than `pundit_permission` haha, so my vote goes to action.

**Comment by martinemde** [comment]
+1  for `pundit_role:` being semantically awkward.

I like your default graphql ruby approach of `authorize: :create`. What was the rationale for adding the library name `pundit` to the keys?

**Comment by rmosolgo** [comment]
Sorry for the inconvenient name on this one ... in practice, I don't expect to change this in the library, given how long it's been in use, but if you'd like to use a different name in your application, I can recommend a patch as shared above: 

https://github.com/rmosolgo/graphql-ruby/issues/2181#issuecomment-471861735
