### ISSUE TITLE
Bubble errors up to return payload type

### ISSUE THREAD

**Issue by g-gaston** [rmosolgo/graphql-ruby#2185]
I'm trying to return application errors as data in my mutation return types (which are usually just a wrapper around a data type and the my `errors` field).

When the mutation resolver is the one returning the error, that's easy. But when it is one of the nested objects or fields that becomes a problem. I can raise an exception and that would add the error to the top level `errors`, but how do I add it to the return payload?

I was thinking I could use the context to store the errors (using the beginning of the path as a key to group them). And then maybe I can use a field extension over my `errors` field in the payload to add those errors in the `after_resolve` hook. But how do I make sure the rest of objects and promises have been already resolved? (hence, there won't be more errors)

I appreciate any ideas/suggestions. Thanks!

**Comment by rmosolgo** [comment]
Hey, it sounds like you want to use child fields (in a mutation's response data) to populate parent fields (the mutation's errors). I don't know of a way to do that. 

One possible suggestion is front-load the work to find any errors and run it _during_ the mutation's resolve method. That way, you'd have access to the errors right away instead of waiting for the payload to be resolved.
