### ISSUE TITLE
[pro] New Interpreter and AuthorizationStrategy do not work together

### ISSUE THREAD

**Issue by wakeless** [rmosolgo/graphql-ruby#2197]
I'm using the new Interpreter and have been using a customer AuthorizationStrategy.

```
class Admin::Graph::AuthorizationStrategy
  def initialize(ctx)
    @user = ctx[:current_admin_user]
  end

  def allowed?(gate, object)
    raise "This is never called"
  end
end
```

And the authorization strategy `allowed?` method is never called.

**Comment by rmosolgo** [comment]
Hey, thanks for raising this issue. Sorry it's not clearly documented, but the new interpreter _won't_ support this authorization strategy because this authorization strategy uses field instrumentation, which can't work with the new interpreter. 

I recommend either: 

- Building on the new built-in authorization system: http://graphql-ruby.org/authorization/authorization.html (It basically replaces these custom strategies) 
- Using the new pundit or cancan integrations (eg http://graphql-ruby.org/authorization/pundit_integration.html)

Please let me know if I can help in the transition!

I'll leave this open until I update the docs appropriately!

**Comment by rmosolgo** [comment]
(I removed the old docs ... which I guess you could say is the "appropriate update", since the replacement features have been out for a long time!)
