### ISSUE TITLE
graphql-errors vs rescue_From

### ISSUE THREAD

**Issue by sayduck-daniel** [rmosolgo/graphql-ruby#2201]
Should we use `rescue_from` as said in [this page]( https://graphql-ruby.org/schema/definition.html#execution-configuration) or the gem [graphql-errors)](https://github.com/exAspArk/graphql-errors) ?

**Comment by bbugh** [comment]
The built-in `rescue_from` only allows you to return an error message, which isn't as useful for client errors because handling them requires string matching. Common practice is to add a `code` to the error which can be handled by a client as an enum. It's much more likely that your error message would change (to be more user friendly, perhaps) but you likely don't ever need to change the `code` value.

This is especially important if your API is directly accessible to end users, so that their clients can handle errors more effectively.

**Build-in `rescue_from`**

```ruby
# no good way for client to determine the type of error
rescue_from ActiveRecord::RecordNotFound do |exception|
  "Not Found: #{exception.message}" 
end
```

```javascript
// yuck
if (error.message.match(/^Not Found:/)) { 
```

**graphql-errors**

```ruby
# standard practice to add a constant code
rescue_from ActiveRecord::RecordNotFound do |exception|
  GraphQL::ExecutionError.new("Not Found: #{exception.message}", extensions: { code: 'NOT_FOUND' })
end
```

```javascript
// yum
if (error.extensions.code === 'NOT_FOUND') {
```

One final note, `graphql-errors` also passes in extra context, arguments, and the base query object, which can be useful depending on the error. This is not available in `rescue_from` as far as I know.

**Comment by sayduck-daniel** [comment]
Ok I see.

I tried it but it seems it's not working as expected on my side. I created an issue at https://github.com/exAspArk/graphql-errors/issues/17

**Comment by sveredyuk** [comment]
I found that in version 1.9.8 `rescue_from` doesn't work at all. How I should handle `ActiveRecord::RecordNotFound` for now?

my schema:
```ruby
module Api
  class Schema < GraphQL::Schema
    mutation(Types::MutationType)
    query(Types::QueryType)

    rescue_from(ActiveRecord::RecordNotFound) do |ex|
      raise GraphQL::ExecutionError.new(ex.message)
    end
  end
end

```
my code:
`User.find(user_id)`

instead rescue_from I always got an error:
`ActiveRecord::RecordNotFound: Couldn't find User with 'id'=44002`

**Comment by sayduck-daniel** [comment]
I'm still looking for a solution or a working rescue_from

**Comment by rmosolgo** [comment]
Hi, sorry for the long turnaround here. I just merged some new error handling for the interpreter runtime which is more flexible: https://github.com/rmosolgo/graphql-ruby/pull/2458

I recommend using it to handle raised errors in field resolvers. If you give it a try and run into trouble, please open a new issue!
