### ISSUE TITLE
Adapter for subscriptions-transport-ws

### ISSUE THREAD

**Issue by sayduck-daniel** [rmosolgo/graphql-ruby#2210]
I had troubles while testing subscriptions with [Altair's GraphQL client](https://github.com/imolorhe/altair)

I opened an [issue](https://github.com/imolorhe/altair/issues/674) on their Github and it happens Altair and most GraphQL query clients use Apollo's [GraphQL subscription proposal](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md)  while graphql-ruby uses [its own](https://graphql-ruby.org/javascript_client/overview).

Any plans for graphql-ruby to have an adapter for `subscriptions-transport-ws `?

As a side question, what GraphQL clients do you use to test subscriptions at the moment?

**Comment by sayduck-daniel** [comment]
any thoughts on this matter @rmosolgo ?

**Comment by rmosolgo** [comment]
Sorry, I don't have plans to implement subscriptions-transport-ws. As a Rails user, I'm interested in Rails-oriented solutions, and I don't know how to run a websockets server alongside a Rails app. That's why I've worked with ActionCable and Pusher/Ably: I know how to use those with Rails! 

>  what GraphQL clients do you use to test subscriptions?

The javascript client developed with GraphQL-Ruby supports Apollo 1.x, Apollo 2.x (via Link), Relay Classic, and Relay Modern. But, as mentioned above, it supports different transports.

If you've had a chance to work on this in the meantime, please do share your findings!
