### ISSUE TITLE
Types::BaseField not auto-generated, documentation assumes so.

### ISSUE THREAD

**Issue by iamwhil** [rmosolgo/graphql-ruby#2215]
In the documentation for Mutation Classes in 1.9.3 it specifies that you should build a Base Mutation.

https://graphql-ruby.org/mutations/mutation_classes.html#example-mutation-class

In the example mutation class it specifies:

`field_class Types::BaseField`

My install of graphql-ruby did not create a Types::BaseField at types/base_field.rb.

Therefore it throws an error when attempting to load graphiql: 

```
uninitialized constant Types::BaseField
Did you mean?  Types::BaseInterface
```
The answer is no, no I did not.

If someone else comes across this adding types/base_field.rb thusly fixed the error:

``` 
module Types
  class BaseField < GraphQL::Schema::Field
    def resolve_field(obj, args, ctx)
      resolve(obj, args, ctx)
    end
  end
end
```

**Comment by rmosolgo** [comment]
Thanks for raising this issue. I agree we could generate a few more things: 

- BaseField 
- BaseArgument 

Maybe even some pagination scaffolding, like base connection  & edge types. I've tagged this as 1.10 because I'm going to target it for that release, but if someone else want to implement it sooner, please feel free to do so and I'll release it ASAP!

**Comment by rmosolgo** [comment]
BaseField was added by #2216 , but we should still add BaseArgument
