### ISSUE TITLE
AST analyzer bug with argument_definition

### ISSUE THREAD

**Issue by swalkinshaw** [rmosolgo/graphql-ruby#2217]
Testing out `on_leave_argument` and `on_enter_argument` I assumed that `visitor.argument_definition` should work and be the argument definition of the argument being visited however it was always `nil`. Looking at the source:  https://github.com/rmosolgo/graphql-ruby/blob/3e2c57b28cafd2d9555bb9e131399526002e43a7/lib/graphql/analysis/ast/visitor.rb#L221-L226

I tested this out and `@argument_definitions[-1]` seemed to give me what I'd expected. I didn't look into this enough yet to figure out if that's actually the proper solution. Just wanted to raise the issue for now at least.

cc @xuorig

**Comment by rmosolgo** [comment]
IIRC It's implemented as `-2` so that when you get a value, you can reach back to the argument that the value belongs to. 

But maybe it should be renamed and and a new method should be added, to be parallel with field definitions: 

https://github.com/rmosolgo/graphql-ruby/blob/3e2c57b28cafd2d9555bb9e131399526002e43a7/lib/graphql/analysis/ast/visitor.rb#L206-L214

I'm open to it, anyhow.
