### ISSUE TITLE
Reload schema during runtime

### ISSUE THREAD

**Issue by alhafoudh** [rmosolgo/graphql-ruby#2225]
Is it possible to reload schema during runtime?

**Comment by rmosolgo** [comment]
GraphQL-Ruby doesn't have any way to do it, but you might be able to use ActiveSupport::Reloader's approach: 

- undefine all the constants 
- reload the files that defined the constants in the first place 
- then use the reloaded constants 

This should work in development by default, and I don't recommend doing it in production, since building a schema adds a lot of overhead.

**Comment by Amnesthesia** [comment]
I needed to do this for tests, because I used `Enums` from values found from records in the database. After the classes have been initially loaded, if any records have been inserted in the database, the schema wont get them.

I solved this by triggering a reload after inserts (mainly for use in tests):

```
class ExampleSchema < GraphQL::Schema
  query(Types::RootQueryType)

  # Force reloading of schema with new Enum values
  # from the database
  def self.reload!
    @graphql_definition = nil

    Types.send(:remove_const, :BaseEnum) if defined?(Types::BaseEnum)
    Types.send(:remove_const, :RootQueryType) if defined?(Types::RootQueryType)
    Types::Category.send(:remove_const, :MyEnumType) if defined?(Types::Category::MyEnumType)
    load "#{Rails.root}/app/graphql/types/base_enum.rb"
    load "#{Rails.root}/app/graphql/types/category/my_enum_type.rb"
    load "#{Rails.root}/app/graphql/types/root_query_type.rb"
    query(Types::RootQueryType)

    graphql_definition
  end
end
```

Then, in the `before` hook in my tests, I just run `ExampleSchema.reload!` if any inserts have been performed

**Comment by alhafoudh** [comment]
I basically achieved it by calling `ActiveSupport::Dependencies.clear`, but yet, I dug into removing constants and it solved it.
