### ISSUE TITLE
add optional description to global_id_field

### ISSUE THREAD

**Issue by gjdame** [rmosolgo/graphql-ruby#2230]
Currently not possible to have a description on a global_id_field, which is causing unneeded errors using https://github.com/cjoudrey/graphql-schema-linter. I've implemented a workaround ignoring the fields but would prefer to be able to have a description on those fields. From my limited understanding it appears to be as simple as adding a field to the global_id_field method in has_fields.rb. Happy to open a pr for it if that is is easier.

**Comment by rmosolgo** [comment]
Hi, sorry for the slow response here! Yes, I think adding an optional `description:` parameter to `global_id_field` would be a nice improvement: 

https://github.com/rmosolgo/graphql-ruby/blob/7124873a489e21a5d81970cd0afc86e4e922578e/lib/graphql/schema/member/has_fields.rb#L77-L83

Another option is to override that method in your app so that when it calls `field ...`, it includes a `description:` of your choice. I don't plan to work more on this, but if you want to work on it, I'd be happy to review a PR!
