### ISSUE TITLE
proper way to localize errors

### ISSUE THREAD

**Issue by carlok** [rmosolgo/graphql-ruby#2237]
What is the proper way to localize `errors[i].message` strings generated by graphql-ruby?
Thanks.

**Comment by rmosolgo** [comment]
Sorry I never properly responded here. I imagined adding a way to leverage Rails localization but obviously never made it happen. I'm going to close this issue since I don't have any plans to work on anything particular. 

If there are specific errors that you'd like help localizing, please open a new issue describing the current behavior and the way you'd _like_ it to work, and we'll see what we can do!
