### ISSUE TITLE
How do you implement apollo tracing with Interpreter?

### ISSUE THREAD

**Issue by allenylzhou** [rmosolgo/graphql-ruby#2248]
https://github.com/uniiverse/apollo-tracing-ruby doesn't work with https://graphql-ruby.org/queries/interpreter.html

I've tried to implement another version of it using a custom Tracer, but I'm not able to access the context object from the trace function.

Is there a recommendation on how to add apollo tracing to extensions?

**Comment by rmosolgo** [comment]
Hi, I recommend looking at the other classes in https://github.com/rmosolgo/graphql-ruby/tree/master/lib/graphql/tracing, perhaps one could be added to support apollo-tracing.

**Comment by jturkel** [comment]
Note the apollo-tracing-ruby gem currently uses the deprecated [Apollo Engine Proxy](https://www.apollographql.com/docs/references/setup-analytics#engine-proxy-deprecated). I started working on a branch with support for their new reporting API (see https://github.com/salsify/apollo-tracing-ruby/tree/feature/new-apollo-api) but haven't had a chance to move it forward. It does work but it's probably not quite production ready and it doesn't yet support the interpreter. It would be very cool to see this folded in graphql-ruby gem but it's a little more complicated than the other tracers since there's no Apollo Ruby client.

**Comment by OzzieOrca** [comment]
Could you elaborate on the state of your https://github.com/salsify/apollo-tracing-ruby/tree/feature/new-apollo-api branch? Just curious what is working/what still needs to be done. Is the readme still the right way to use it? That'd be awesome if it just worked :) Thanks for your work on it!

**Comment by jturkel** [comment]
I've used the code locally but it's never been used in production so it at least works on my machine :) I think the following things are necessary to call it done:

1) Tests
1) Capture additional details in trace e.g. error information, sanitized variables, etc. 
1) Compatibility with the interpreter runtime
1) A Railtie to initialize the logger
1) Shutdown tracer threads when reloading code in Rails
1) Update README
1) Nice to have: Don't encoded traces twice
1) Nice to have: Smarter default query normalization/sanitization

**Comment by rmosolgo** [comment]
I hope you found something that works for you here! I don't have plans to work on this for now.
