### ISSUE TITLE
Allow for :method and :hash_key on fields

### ISSUE THREAD

**Issue by bbugh** [rmosolgo/graphql-ruby#2253]
I was surprised to see that this didn't work!

We have some models that have jsonb columns that we're adding to our GraphQL API. Rather than expose the json implementation detail to our endpoints, we're choosing to create types that expose these json key values as fields. The jsonb fields will always have a consistent set of key/value pairs for each type, so this is working quite well. Except for all of the boilerplate.

Given our json (hash) column is named `properties`, I expected this to work:

```ruby
field :name, String, method: :properties, hash_key: :name
```

but I get an `ArgumentError`: 

> ArgumentError - Provide `method:` _or_ `hash_key:`, not both. (called with: `method: :properties, hash_key: :name`)

Instead, we'd have to do this *a lot*:

```ruby
field :name, String, null: true
field :type, String, null: false
field :source_id, ID, null: false

def name
  object.properties['name']
end

def type
  object.properties['type']
end

def source_id
  object.properties['source_id']
end
```

It's possible to work around it with `define_method` loops, but it's less readable than just having the fields define the keys.

Is it possible to allow for `method` and `hash_keys` to work together, in cases where the `method` return is a hash and we want to dig into it with `hash_keys`?

**Comment by rmosolgo** [comment]
I'm not sold on making this change to the library, because it will be ambiguous whether `method: :a, hash_key: :b` becomes `object.a[:b]` or `object[:b].a`. That is, which one is first vs second? Instead, we just support one level of shortcut. 

Another approach to DRYing this up in your app is to make a `field(...)` wrapper method that creates shortcut methods, for example: 


```ruby 
def properties_field(name, *args, **kwargs, &block)
  field(name, *args, **kwargs, &block) 
  name_s = name.to_s 
  define_method(name) do 
    object.properties[name_s]
  end 
end 

# then 
properties_field :source_id, ID, null: false 
```

I hope something like that will help in  this case! 

If we hear more uses of multi-step shortcuts, we can explore more flexible options, but for now, I don't want to wade into that issue 😆.
