### ISSUE TITLE
Customize validation for fields

### ISSUE THREAD

**Issue by ExplosiveGM** [rmosolgo/graphql-ruby#2337]
I want to customize all my mutations. So, my mutation must return
```
{
data: ...
errors:[]
}
```
I have type User:
```
class Types::User < Types::BaseObject
  #first_name
  #last_name
end
```

I try generate mutation this way:
```
mutation_class = Class.new(GraphQL::Schema::Mutation)
init_arguments # no matter
mutation_class.field(name: :data, type: return_type, null: true) # return_type = Types::User
mutation_class.field(name: :errors, type: [String], null: false)
# some code ...
if success?
  {
    data: result,
    errors: []
  }
else
  {
    data: nil,
    errors: errors
  }
end
```

The main idea to **put dynamic type** to field **data**. 
```
mutation {
  signIn(email: "some_email", password: "qwerty") {
    firstName
    lastName
  }
}
```
Shortly, mutation have 2 fields: data, errors. So it dont see fields firstName and lastName and raise validation error.
What i must watch? InterfaceType, override get_field on type?

**Comment by bejczib** [comment]
Hi,

I'm not an expert on the subject, but I want to help you. 

`data` and `errors` are not fields on your mutation, they are root keys of your servers response. 

Since you said that your return type is `Types::User`, you could have a `user` field for example.

Your mutation:

```
mutation {
  signIn(email: "email", password: "password") { 
    user { 
      firstName
      lastName
    }
  }
}
```

And the response:

```
{ 
  "data" : {
    "user": {
      "firstName": "first_name",
      "lastName": "last_name"
    }
  }
} 
```

Although you can have fields named `data` and `errors` but they would be nested like:

```
{ 
  "data" : {
    "user": {
      "data": ....
      "errors": .....
    }
  }
} 
```
I think you don't want that.

You can find more information in the [GraphQL Spec](https://graphql.github.io/graphql-spec/June2018/) or this gems [documentation](https://graphql-ruby.org/guides).

Best,
Balint

**Comment by ExplosiveGM** [comment]
Thank you for your answer, it was very helpful
