### ISSUE TITLE
Advice: What would be the cleanest way to create a custom object type?

### ISSUE THREAD

**Issue by wahba-stripe** [rmosolgo/graphql-ruby#2351]
Hey @rmosolgo!
Thanks for all the work on graphql-ruby!
 
Right now trying to build a sorbet `T::Struct` aware `GraphQL::Schema::Object` https://sorbet.org/docs/tstruct to reduce duplicated code and add a layer of type safety. Unfortunately both `T::Struct` and `GraphQL::Schema::Object` require inheriting to use and ruby has no multiple inheritance.

I think there are two basic approaches that are possible to implement a class that unites the two:

1. Implement `self.graphql_definition` on the object class
2. Use the legacy `.define` api

Which approach would be most peaceful from a "not relying on deprecated features or internal private functions" perspective? Would also be interesting to know if a sorbet friendly object type (i.e. one that uses sorbet types and runs them through typed function calls) is the kind of thing you'd want in the gem itself or would rather keep external. 

Thanks again!

**Comment by rmosolgo** [comment]
Hey, sounds like a cool project! 

Unfortunately, as you noticed, GraphQL-Ruby has a pretty hard dependence on using its own classes for schema definition & query execution. 

What if, instead of trying to merge the classes together, you made a _generator_ that could take one kind of class (say, a `T::Struct`) and generate the _corresponding_ class (say, a `GraphQL::Schema::Object`)? Maybe the two classes could retain references to each other. In an arrangement like that, you'd have two different classes, but it might work since they'd be connected. 

What do you think?

**Comment by wahba-stripe** [comment]
Sounds workable, will give it a shot, thanks for the advice!

**Comment by telekid** [comment]
@wahba-stripe I'm curious, did you ever make any progress on this?

**Comment by wahba-stripe** [comment]
Hey @telekid the approach is sound, but it unfortunately comes with a lot of challenges around dealing with graphql unions for example. I'd recommend against it for the time being.
