### ISSUE TITLE
Schemaless validations

### ISSUE THREAD

**Issue by josh** [rmosolgo/graphql-ruby#237]
Hey @rmosolgo, wanted to run another idea by you.

To use the static validator, a schema needs to be present. This is pretty much always true server side, but maybe not always configured for clients. Theres a number of static rules that don't really need a schema and check basic correctness of queries. What do you think about providing an API such that these validations can be ran without a schema instance? 

``` ruby
# now
validator = GraphQL::StaticValidation::Validator.new(schema: Schema)
query = Query.new(Schema, document: document)
validator.validate(query)

# proposed validate document with schema
validator = GraphQL::StaticValidation::Validator.new(schema: Schema)
validator.validate(document)

# proposed validate document without schema
validator = GraphQL::StaticValidation::Validator.new
validator.validate(document)
```

Its a little weird too that you need to pass a query to validate, you can't just pass a document. Even the inline documents suggest it may work.

``` ruby
    # @example Validate a query
    #   validator = GraphQL::StaticValidation::Validator.new(schema: MySchema)
    #   document = GraphQL.parse(query_string)
    #   errors = validator.validate(document)
    #
```

https://github.com/rmosolgo/graphql-ruby/blob/afb9db2527c03a9ab4c7fca3c3d9feb9da5e1ec4/lib/graphql/static_validation/validator.rb#L8-L10

**Comment by rmosolgo** [comment]
I love the idea! Seems like a way to get more mileage out of some already-written code.

Personally I think the current validation implementation is a trainwreck (ok, it's _complete_ and it _works_ so I guess there's that) but I'd really like to rewrite it completely. Either: 

- You can modify the existing implementation to support this use case 
- Someone (you? me? I _want_ to do it but I haven't had a chance yet, and it's _hard_!) can rewrite it. 

I have a few goals for a rewrite: 

- Better error recovery: if a parent node has an error, there are many cases where we can continue to validate some child nodes. But the current implementation doesn't do that, it just gives up 
- Better internal structure: the "rules" are weirdly order-dependent. They're tested in isolation but that's not really useful because many of the bugs in this area have been unexpected interference between rules 
- As few passes as possible: Ok, it would be easy to traverse the tree over and over, but that's really inefficient. Currently, there's one "main" pass but several of the validators do their own traversals because 💫  reasons :dizzy:, I'd like to identify those and remove them if possible 
- :sparkles: __New__ ✨  Some independence from a schema: as described above, many of the rules can be run against an AST _alone_ (eg, variable usage, finite fragment nesting). Validation should "just work" if it's run without a schema. 

Since writing this the first time, I became aware of an interesting error handling technique for type checkers, I heard it from [this video](https://www.youtube.com/watch?v=mdbdE8tNqN0&list=PLFB9EC7B8FE963EB8&index=56). Maybe you've heard it before, but I'll describe my understanding to see if we're on the same page: 

What you do is, when some error causes you to lose "What type am I looking at?" (for example, a non-existent fragment type or non-existent field on an object), instead of throwing your hands up and turning back, you emit an error and insert a _magic_ type (called `AnyType`, perhaps) which has some _magic_ properties: 

- It has a field with _any_ name
- All its fields return `AnyType` 
- All its fields have arguments with _any_ name 
- All its field arguments accept `AnyInputType` which has similar properties: it has _any_ input fields which accept _any_ input value

In this way, it's a "false positive" for every kind of type-checking. However, it allows you to continue checking until some part of the query _restores_ "What type am I looking at?", for example, a fragment spread (that's actually the only one I can think of). Then, you can begin checking "like normal" again. If you lose type information again, you emit an error and inject `AnyType` again. 

In light of your suggestion here, this approach could yield double rewards: 

- on the one hand, it improves type checking for schema-aware validation 
- on the other hand, it provides a mechanism for using the _same_ validation stack _without_ a schema: it just uses `AnyType` _all the time_. 

What do you think? How would you like to go forward?

**Comment by josh** [comment]
Ah, I really dig that approach.

I may start hacking on this maybe next week or so. I've been able to work around the schema require by just using a blank schema and excluding all the rules that depend on the presence of types. So its not super urgent for me. But I'd still love to figure out a clean way to make it work in this core gem.

Roping in @charliesome, maybe he has some interest in some of this stuff.

**Comment by josh** [comment]
https://github.com/rmosolgo/graphql-ruby/pull/268 😀

**Comment by rmosolgo** [comment]
Sorry #268 never landed :S 

Do you still care about this after https://github.com/github/graphql-client/issues/46 ?

**Comment by josh** [comment]
> Do you still care about this after github/graphql-client#46 ?

Yeah, not super interested in this personally anymore. Thanks for checking! ❤️

**Comment by rmosolgo** [comment]
Ok, at first I was going to cover it in #495, but the catch was that the type stack and the path stack are tracked by the same object (`TypeStack`), so it wasn't super simple to separate those two. I'll keep an ear out for this in case someone else finds a good use for it!
