### ISSUE TITLE
Can't seem to make a GraphQL object from a regular Ruby array

### ISSUE THREAD

**Issue by armantark** [rmosolgo/graphql-ruby#2380]
We're trying to make a word-frequency table from our results to relay to the frontend for autocomplete. So basically just a huge hashmap of words to word counts. This hashmap is already created and working, but I'm having issues now hooking it into GraphQL.

This is what I have so far:

```
module Types
  class AutoSuggestType < Types::BaseObject
    description "A list of suggested words"
    field :words, [SuggestionType], "List of autosuggested words", null: false

    def words
      autosuggest = AutosuggestService.new
      autosuggest.suggestions
    end
  end
end
```
```
module Types
  class SuggestionType < Types::BaseObject
    description "A suggestion"
    field :word, String, "Word", null: false
    field :frequency, Integer, "Word count of the word", null: false
  end
end
```
```
require 'autosuggest'

class AutosuggestService
  def initialize
    # we might have to limit this to prefix matched words because right now we're just sending all the data to
    # the front end
    top_queries = Hash[WordFrequency.pluck(:name, :frequency)]
    @autosuggest = Autosuggest.new(top_queries)
  end

  def words
    result = []
    @autosuggest.suggestions.each do |suggestion|
      unless suggestion.nil?
        result.push Hash[suggestion[:query], suggestion[:score]]
      end
    end
    result
  end
  end
end
```

Basically, whenever I run the relevant GraphQL command, it says it's returning a null object. But the objects are being properly created, I believe, because when I do a `puts` it shows the right stuff.

Is there a better way to do this in general or is going with the ActiveRecord -> Autosuggest gem object -> Array of hashes -> GraphQL object approach fine and perhaps I'm just missing something?

EDIT: I would also like to mention that I tried making it into an array of arrays (rather than array of hashes), and still no luck.

**Comment by armantark** [comment]
Also wanted to mention that I did do an array of arrays as well, but that didn't work either.

**Comment by rmosolgo** [comment]
Hi! It sounds like you're on the right track. 

It's a bit hard to tell from the example to tell exactly what's going on. I see the GraphQL `def words` method calls `autosuggest.suggestions`, but I don't see that method in the `AutosuggestService` class above. Is it the same as the `def words` method there? 

If so, it looks like it returns an array of hashes like this: 

```ruby
[
  { "SomeWord" => 1 }, 
  { "AnotherWord" => 2}, 
]
``` 

Is that right? 

If so, you'll need to add behavior to SuggestionType so that "word" is the key in the hash while "frequency" is the value, for example: 

```ruby 
module Types
  class SuggestionType < Types::BaseObject
    description "A suggestion"
    field :word, String, "Word", null: false

    def word 
      object.keys.first # Return the only key in the hash 
    end 

    field :frequency, Integer, "Word count of the word", null: false

    def frequency 
      object.values.first # Return the only value in the hash 
    end 
  end
end
```


Does that help? 

If not, please reopen this with a bit of clarification: 

> run the relevant GraphQL command

Could you share what command you run that demonstrates this issue? 

>  it says it's returning a null object

Could you please share the full error message and any related info (backtrace, GraphQL response, ...)? 

Let me know what you find!

**Comment by armantark** [comment]
Sorry for late reply, I got off on Friday and didn't check for the weekend plus Monday. But either way, that worked! Thank you. I should've known it was something as simple as that.
