### ISSUE TITLE
always return array on nil / undefined?

### ISSUE THREAD

**Issue by lifeiscontent** [rmosolgo/graphql-ruby#2387]
in the JS Implementation of GraphQL you can do something like this:

https://stackoverflow.com/questions/53766939/graphql-how-to-return-empty-array-instead-of-null

how can I do the same in the graphql-gem? @rmosolgo

**Comment by rmosolgo** [comment]
When you implement a field, you can put custom logic in resolve methods, for example: 

```ruby 
field :posts, [Types::Post], null: false 

def posts 
  @object.posts || [] 
end 
```

That way, an empty array is returned instead of `nil`. 

Since GraphQL-Ruby calls methods on your application objects, you can also implement this at the application level by making your methods return empty values instead of `nil`. (For example, Rails `has_many` methods return empty relations when there are no child objects.) 

Feel free to share specific resolver code if you want to look into something!

**Comment by lifeiscontent** [comment]
@rmosolgo are there docs on how to tell the schema to return different concerns?

from the graphql spec there are the following: `String`, `String!` `[String]` [String!]` `[String]!` `[String!]!`

`[String]!` should always return an array even if nil at the resolver level is this currently implemented in the graphql gem?
