### ISSUE TITLE
NoMethodError (undefined method `line=' for #<GraphQL::Language::Nodes::Document:0x00007fe3f65ec6f8>

### ISSUE THREAD

**Issue by gkunwar** [rmosolgo/graphql-ruby#2398]
My Gemfiel looks like:
```

gem 'graphql', '~> 1.9.7'
gem 'graphql-libgraphqlparser', '~> 1.3'
```

**Comment by rmosolgo** [comment]
Hi, sorry, libgraphqlparser was broken since 1.9, when we made `Language::Nodes` immutable. See also https://github.com/rmosolgo/graphql-libgraphqlparser-ruby/issues/30

Personally, I don't think libgraphqlparser is worth the effort. The plain-Ruby parser in graphql-ruby is only a few times slower than libgraphqlparser, and it's much more stable, since it doesn't require a C extension. I recommend removing graphql-libgraphqlparser from your gemfile for that reason. 

If you want to _keep_ libgraphqlparser, please share your reasoning, along with benchmarks if applicable, and we can take a look!
