### ISSUE TITLE
GraphQL::Relay::RelationConnection offset failure

### ISSUE THREAD

**Issue by enthusiasmus** [rmosolgo/graphql-ruby#2425]
Assumed one has a table with two entities:

First entity has the id 999
Second entity has the id 1000

When using `after` for navigation with the value `999`, one would expect the result to include all entities with an higher id as 999 (the second entity). But the `GraphQL::Relay::RelationConnection` class with the method `offset_from_cursor` generates an sql query with an offset of **`999`**, so the result doesn't include any entity. 

```
def offset_from_cursor(cursor)
  decode(cursor).to_i
end
```
It seems to me, that there is mix-up of `id` and `offset`.

Best regards,
Lukas

**Comment by rmosolgo** [comment]
Hi, good question! This is working as intended. In order to support any kind of ordering, this connection implementation uses _offset_ to work through items in a relation. 

For example, if it used `id` as you suggest, what if items were sorted by name?

> `SELECT * FROM items ORDER BY name WHERE id > 999` 

☝️ That query would return some unpredictable results, since the ordering and `WHERE` clause aren't related. Using `OFFSET` is a simplistic but highly portable technique that Just Works :tm:. 

For performance- or stability-sensitive situations, graphql-pro includes another connection implementation that _detects_ the ordering of a relation and uses it to build stable cursors, similar to what you're asking about here: https://graphql-ruby.org/pro/cursors.html

**Comment by enthusiasmus** [comment]
@rmosolgo Yes, good explanation and you are totally right! 

However, other users may expect the navigation of the non pro version to work. This gem does does only provide a working navigation for entities which are sorted by id and have continuous ids without gaps. Shouldn't there be a warning about that in the documentation?

**Comment by rmosolgo** [comment]
Have you tried using the built-in connection implementation? I expect it to work for _any_ ActiveRecord relation, regardless of how it's sorted or what kind of primary key it has.  If you have any trouble using it with a relation, it's a bug, so please open an issue describing the relation (perhaps its `.to_sql` output), the query you're sending, the actual result, and the expected result. Then we can look into it!
