### ISSUE TITLE
How to add arguments to a query using custom connections

### ISSUE THREAD

**Issue by nratter** [rmosolgo/graphql-ruby#2442]
https://github.com/rmosolgo/graphql-ruby/blob/master/guides/relay/connections.md details lots of information on customizing connections but I don't see a way to add arguments to the query (in the same way that 'first', 'last', 'before', and 'after' arguments are automatically added). I'd like to add an 'offset' or 'skip' argument to the connection query for custom pagination. This can't be done in the query resolver because per the link above...

`
The field's method or resolver: should return a collection (eg, Array or ActiveRecord::Relation) without pagination. (The connection will paginate the collection).
`

Can anyone help me with this? I can also help to update the connections.md file based on this info. Thanks!

**Comment by rmosolgo** [comment]
Hi, if you want to mimic connection's automagical argument handling, you could create an extension, which is how it's implemented in graphql-ruby: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field/connection_extension.rb

Here are the docs for that feature: https://graphql-ruby.org/type_definitions/field_extensions.html

If that doesn't work for you, please share the code for what you tried and how it turned out for you. (And if it _does_ work, then write a blog post about it 🍻 !)
