### ISSUE TITLE
Tracing breaks on 1.9 with Query#result

### ISSUE THREAD

**Issue by Mange** [rmosolgo/graphql-ruby#2445]
We're doing our own validation step in our GraphQL APIs in order to do some custom management of the errors.

Our controllers follow this pattern:

```ruby
class SomeController
  def execute
    # Raise ParseError when query cannot be parsed
    SomeSchema.validate(graphql_query.query_string)

    result = graphql_query.result
    handle_execution_errors(result) if result["errors"].present?

    render json: result
  rescue GraphQL::ParseError => e
    render_error(e)
  rescue StandardError => e
    render_error(e)
    record_error(e)
  end

  private
  def graphql_query
    @graphql_query ||= build_graphql_query
  end

  def build_graphql_query
    GraphQL::Query.new(
      SomeSchema,
      query_body,
      operation_name: operation_name,
      variables: parse_graphql_variables,
      context: graphql_context,
    )
  end
end
```

We do this because of high volume of traffic, and we want to pre-process some errors to deal with logging and analytics, and some additional custom instrumentation.

After upgrading to GraphQL 1.9, the traces for our queries disappeared. Only the `#validate` call shows up in our analytics (we're using DataDog[1]).

I monkey patched `GraphQL::Tracing::PlatformTracing` to log the arguments it was called with. There is no call to it at all when using the `GraphQL::Query#results` method. If I change it to `SomeSchema.execute(query_body)`, then it is called with all the steps again:

```
# My validate call
[2019-08-27T08:55:27+02:00 ERROR] trace: ["validate", {:validate=>true, :query=>query ...}]

# The #execute call
[2019-08-27T08:55:27+02:00 ERROR] trace: ["execute_multiplex", {:multiplex=>#<…>}]
[2019-08-27T08:55:27+02:00 ERROR] trace: ["lex", {:query_string=>"…"}]
[2019-08-27T08:55:27+02:00 ERROR] trace: ["parse", {:query_string=>"…"}]
[2019-08-27T08:55:27+02:00 ERROR] trace: ["validate", {:validate=>true, :query=>query ...}]
[2019-08-27T08:55:27+02:00 ERROR] trace: ["analyze_multiplex", {:multiplex=>#<…>}]
[2019-08-27T08:55:27+02:00 ERROR] trace: ["analyze_query", {:query=>query ...}]
[2019-08-27T08:55:27+02:00 ERROR] trace: ["execute_query", {:query=>query ...}]
[2019-08-27T08:55:27+02:00 ERROR] trace: ["execute_field", {:context=>#<…>}]
[2019-08-27T08:55:27+02:00 ERROR] trace: ["execute_query_lazy", {:multiplex=>#<…>}]
```

Right now I'm working around it by repeating all the arguments for the execute method from the query object:

```ruby
    result = SomeSchema.execute(
      context: graphql_query.context,
      document: graphql_query.document,
      max_depth: graphql_query.max_depth,
      operation_name: graphql_query.operation_name,
      root_value: graphql_query.root_value,
      validate: true,
      variables: graphql_query.provided_variables,
    )
```

Is this the intended way to follow this pattern now? Do you foresee a problem with this pattern in the future?

---

[1]: DataDog instrumentation is installed like this, which I don't think should cause any issues:

```ruby
class SomeSchema
  use GraphQL::Tracing::DataDogTracing, service: "some-app-some-api"
end
```

[EDIT]: Need to call `query.provided_variables` and not `query.variables`; variables need to be unresolved when calling `execute`.

**Comment by rmosolgo** [comment]
Hi, thanks for the report. How weird! 

You shared the `puts` output when you use `Schema.execute`, could you share the same output when you use `query.result`? 

I expect it to be the same, but apparently it's not??

**Comment by Mange** [comment]
It's the upper half of the snippet, only the validate call is logged and then it is quiet. That line was identical.

**Comment by rmosolgo** [comment]
I finally got a chance to look into this. I added a test on master at #2735 and it worked OK. So, it must somehow be different in your setup. 

Could you try debugging `graphql_query.tracers`? Does it include the tracers you expect to see? 

If it doesn't, you could try debugging `SomeSchema.tracers`. Does it include the tracers you expect?

If it doesn't, you could try debugging `SomeSchema.graphql_definition.tracers`. What about that? 

My guess is that tracers were being added to the Schema _instance_ (`.graphql_definition`) but not the class. Under the hood, GraphQL-Ruby calls `.graphql_definition` as-needed, but you might have to do it yourself if you're initializing your own queries: 

```ruby 
Query.new(SomeSchema.graphql_definition, ...)
```

I bet it passes on master because, on 1.10+, schema instances aren't used anymore -- only classes -- so there isn't this weird split between the class-based configuration and the runtime singleton instance. 

I _bet_ that's the problem here, but if I'm wrong, please do let me know what you find debugging, and I'll reopen this issue and keep digging!
