### ISSUE TITLE
subscription event depend on arguments

### ISSUE THREAD

**Issue by gagalago** [rmosolgo/graphql-ruby#2474]
I am writing a graphql subscription through webhooks. My idea is that during the subscription the user must set the callback url where we will send events later. 
something like:
```graphql
subscription($callback: String!) {
  opportunitySubscription(callbackUrl: $callback) {
    opportunity { ... }
  }
}
```

this argument is only known at the subscribe and not at the update. I see https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions.rb#L35 that we trigger event only if there is already a subscription for the name and arguments by using https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions/event.rb#L33-L54 . In my case, as I can't know when I trigger the event the value of the argument used during the subscribe, I will never send any event.

To solve that, I just add a dirty monkey patch in my code:
```ruby
# HACK: event identifier depend only on the subscription event name and scope
module GraphQL
  class Subscriptions
    class Event
      # @return [String] an identifier for this unit of subscription
      def self.serialize(name, _arguments, _field, scope:)
        Serialize.dump_recursive([scope, name, {}])
      end
    end
  end
end
```

Is my understanding of graphql wrong in some point and sending the callback url at subscribe is not the right practice? If not, what do you propose? if yes, how to do it properly (without monkey patching) or what is the best changement to upstream to be able to do it?

**Comment by rmosolgo** [comment]
Is the callback URL something that you will use to deliver a payload to the subscriber? If so, won't you have to store the callback URL in order to deliver a payload to it? If you have the callback URL stored somewhere, maybe you could pass it to `.trigger`. 

Or, if I have misunderstood what `callbackUrl` is for, could you tell me more about what you're hoping to accomplish with it?

**Comment by gagalago** [comment]
indeed, the callback URL is used to know where to send the payload of each event. So I store it when I receive the subscription then I use it on each event to send the event payload to each callback URL of that kind of subscription.

For example, we can have multiple users that request to be notified of `opportunitySubscription` and each of them will send a different `callback_url`. When there is a change in an opportunity, I trigger an event with the opportunity and I want to send that event to each callback URL that user send during the subscription of `opportunitySubscription`.

If I want to follow the actual codebase of graphql-ruby, I have to trigger one event per callback URL. so it's the place where I trigger the event that have to know to who sent it (callback URL) and not the subscription adapter (subclass of `GraphQL::Subscriptions).

For me, we have to think subscription as an [event driven architecture](https://en.wikipedia.org/wiki/Event-driven_architecture).
Triggers can't know the consumer of the event and so triggers cannot know callback URL. Only the event channel (subclass of `GraphQL::Subscriptions) can know how to route event from producers to consumers. 
So it should be the role of the subscription adapter to manage the distribution of events to all subscribers and not the trigger, the trigger can only know the scope of it. That's why I change how to serialize an event to follow these previous principles.

Is it more clear?
If you had to, how would you have done?

**Comment by rmosolgo** [comment]
Thanks for all those details. Very interesting! 

> role of the subscription adapter to manage the distribution of events

Yes, I agree that makes sense. There are really two parts to a GraphQL subscriptions system: 

- The GraphQL schema (types, fields, arguments, etc) 
- The transport layer (ActionCable, Pusher, etc)

So, maybe you want to embed the callback url in the _transport layer_ instead of in the GraphQL schema. (In this case, you can think of the callback url as equivalent to the _channel_ in ActionCable subscriptions.) There's actually a nice blog post introducing this approach:  https://medium.com/@lemuelbarango/graphql-ruby-subscriptions-transport-webhooks-b79b12fd47a0

However, in that blog post, `{{WEBHOOK_CALLBACK_URL}}` is left for the user to implement 😅 . Depending on your situation, you might implement it as an HTTP header, a query param ( eg `&callbackURL=...`), or some other "out-of-band" mechanism. That way, you would work around GraphQL-Ruby's argument-based `.trigger`. Of course, you'd have to also implement a backend which associates each subscription with the callback url.  (That would be implemented with a custom `GraphQL::Subscriptions` subclass. 

I hope that helps put you on the right track! If you think of webhooks as the "transport layer" instead of part of the GraphQL schema, it might make it a little easier.

**Comment by gagalago** [comment]
thanks a lot. I was too focus to use GraphQL and I forgot that I can use HTTP headers or query param and then provide them to the transport layer through the context.

**Comment by pedro-pedrosa** [comment]
Sorry for grave digging this post, but if my understanding is correct, then I cannot achieve the following scenario:
- I have a list of movies in the database
- My front-end has a list page that lists most recent movies first. I want to listen to a movie updated event so I can show it at the top of the list, so I don't want to subscribe to updates to a specific movie
- This page can filter movies by category. If I'm filtering by a category,  Ionly want to listen to updates to movies that belong to that category.
- My front-end also has a movie details page. I want to listen to the movie updated event for that particular movie only, since I'm fetching a lot of data with the subscription query and I don't want to waste bandwidth listening to updates of movies I don't care about.

It would make sense to implement `id` and `category` as arguments to my `movie_updated` subscription. However, this forces me to trigger 3 events each time a movie is updated:
- `:movie_updated, arguments: {}`
- `:movie_updated, arguments: { id: id }`
- `:movie_updated, arguments: { category: category }`

If I can filter using more fields, then I'll have to trigger nCk combinations of events for this to work? Why can't I simply pass my arguments on the subscription and have the subscription class do the filtering and either return `object` or `:no_response`? Or do I have to use `context` for this like suggested above using querystring params or headers and lose all the benefits of the static typing provided by GraphQL? Am I missing something obvious here?

**Comment by rmosolgo** [comment]
Hey @pedro-pedrosa , Thanks for your detailed write-up. In short: 

>  Am I missing something obvious here?

No, it's just a shortcoming of the system. If you want to discuss improvements, I invite you to open a new issue for discussing them!
