### ISSUE TITLE
Custom connection type not working with a resolver.

### ISSUE THREAD

**Issue by mkonikowski** [rmosolgo/graphql-ruby#2494]
I've followed examples from [connection-types](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/relay/connections.md#connection-types) , but apparently this is not working for a resolver...

For this connection type
```ruby
# Make an edge class for use in the connection below:
class Types::PostEdgeType < GraphQL::Types::Relay::BaseEdge
  node_type(PostType)
end

# Make a customized connection type
class Types::PostConnectionWithTotalCountType < GraphQL::Types::Relay::BaseConnection
  edge_type(PostEdgeType)

  field :total_count, Integer, null: false
  def total_count
    # - `object` is the Connection
    # - `object.nodes` is the collection of Posts
    object.nodes.size
  end
end
```

Something like this is working fine:
```ruby
class Types::AuthorType < GraphQL::Schema::Object
  # Use the custom connection type:
  field :posts, PostConnectionWithTotalCountType, null: false, connection: true do
    argument :status, String, required: false
  end

  def posts(status:)
    status ? object.posts.where(status: status) : object.posts
  end
end
```

but as method `posts` is quite big, I've moved it to a resolver:

```ruby
class Types::AuthorType < GraphQL::Schema::Object
  field :posts, resolver: PostsResolver
end


class PostsResolver < GraphQL::Schema::Resolver
  type Types::PostConnectionWithTotalCountType, null: false
  
  argument :status, String, required: false

  def resolve(status: )
    status ? object.posts.where(status: status) : object.posts
  end
end
```

and this is not working... I get the error:
```

Failure/Error: field :posts, resolver: PostsResolver

ArgumentError:
  Failed to build return type for Author.posts from nil: Unexpected type input:  (NilClass)
```

Solution from [resolvers section](https://github.com/rmosolgo/graphql-ruby/blob/21398ec55a9e2468cdbfa04a5f4e9a665486bd3d/guides/fields/resolvers.md#nesting-resolvers-of-the-same-type) is not helping either - when I do 
```ruby
class PostsResolver < GraphQL::Schema::Resolver
  type 'Types::PostConnectionWithTotalCountType', null: false
  
  argument :status, String, required: false

  def resolve(status: )
    status ? object.posts.where(status: status) : object.posts
  end
end
```

 I cannot access `object.nodes`, because `object` now becomes `#<ActiveRecord::AssociationRelation` instead of `<GraphQL::Pro::OrderedRelation::OrderedRelationConnection`

Any suggestions how to solve this, would be appreciated.

Stack:

- graphql (1.9.8)
- graphql-batch (0.4.1)
- graphql-pro (1.10.7)
- rails (6.0.0)

**Comment by rmosolgo** [comment]
Hi, thanks for the detailed issue! It _seems_ like it must be some kind of load order issue. But then, the solution for that caused another issue. 

Since `"PostConnectionWithTotalCount"` doesn't end in `"Connection"`, GraphQL-Ruby didn't realize to automatically apply connection handling. Could you try adding `connection: true` to your field configuration? For example: 

```ruby 
  field :posts, resolver: PostsResolver, connection: true 
```

If that fixes it for you, maybe we can find a way to make auto-detection a bit better!

**Comment by rmosolgo** [comment]
Please let me know if that doesn't work for you!

**Comment by parse** [comment]
Just a follow-up question on this one.

Does the workaround @mkonikowski mentioned and that is mentioned in the docs https://graphql-ruby.org/fields/resolvers.html#nesting-resolvers-of-the-same-type not work on connection_types to solve cyclical dependecies? 

E.g. `type 'Types::WorkoutType.connection_type', null: false` It works when I'm using `type '[Types::WorkoutType]', null: false`

**Comment by rmosolgo** [comment]
Hey @parse, `.connection_type` doesn't work in strings because it hasn't been implemented manually here: 

https://github.com/rmosolgo/graphql-ruby/blob/d8eb11ee005f140e0a38ec7afd258c54618a15f4/lib/graphql/schema/member/build_type.rb#L28-L34

Feel free to add a clause there to extract `".connection_type"`, parse the rest of the string, then call `.connection_type` on the parsed result. That'd make it work fine, I just haven't had the need (or the time!) to do it myself.

**Comment by HavinLeung** [comment]
@rmosolgo I monkey patched it to parse `"Foo.connection_type"` properly, but it kinda just breaks everything. The arguments `after, before, first, last` are gone from the field, and the resolver gets a little whacky. E.g. I get an error `undefined method 'edge_nodes' for #<ActiveRecord::Associations::CollectionProxy [#<...`
