### ISSUE TITLE
Errors seem broken

### ISSUE THREAD

**Issue by lifeiscontent** [rmosolgo/graphql-ruby#2496]
https://github.com/rmosolgo/graphql-ruby/blob/94bbd55095941909c75d3c76538af1e4c42c451a/lib/graphql/execution_error.rb#L3

trying to add an error subclass, I've realized that only returning my error class will actually return the JSON output I'd expect.

The docs say to raise the error, but they're either confused, or this is a bug 🤷‍♂

**Comment by rmosolgo** [comment]
Hi! Sorry you're running into trouble, but this is not enough information to debug further. If you want to look into it, please share: 

- Any error messages and stack traces you encounter
- Source code from your application relevant to the issue 
- Description of expected behavior vs actual behavior 

If you're interested in sharing any of that information (or more, if anything else is relevant!), please reopen this issue and add it.

**Comment by lifeiscontent** [comment]
@rmosolgo the docs say to `raise` an ExecutionError, while the actual code says to `return` it

I've tried to `raise` a GraphQL::ExecutionError and it doesn't work the same way as when you `return` it.

I don't understand why you need more information, I'm just telling you, your documentation is out of sync with actual behavior.

**Comment by lifeiscontent** [comment]
ping @rmosolgo
