### ISSUE TITLE
[PRO] scope: false is not used for `nodes` field in a connection

### ISSUE THREAD

**Issue by michal-samluk** [rmosolgo/graphql-ruby#2497]
I am getting this error: 
```
"No policy found for:↵↵- Type: PostType↵- Runtime value: `#<ActiveRecord::AssociationRelation []>`↵↵Pundit error: Pundit::NotDefinedError, unable to find scope `PostPolicy::Scope` for `#<ActiveRecord::AssociationRelation []>`↵"
```
while querying like this: 
```
{
  posts {
    nodes {
      id
    }
  }
}
```

My field definition looks like this: 
```
field :posts, PostType.connection_type, null: false, scope: false
```

But while fetching edges I am not getting such error: 
```
{
  posts {
    edges {
      node { id }
    }
  }
}
```

It seems it is related to: https://github.com/rmosolgo/graphql-ruby/issues/1974

**Comment by rmosolgo** [comment]
Hi, sorry about the trouble! Since the `nodes` field belongs to the `PostsConnection` type in this example, it will require some customizations in the connection generation code. 

You can see how the base connection class generates its `nodes` field here: 

https://github.com/rmosolgo/graphql-ruby/blob/94bbd55095941909c75d3c76538af1e4c42c451a/lib/graphql/types/relay/base_connection.rb#L93-L97

So, you'll need to modify that for your _own_ base class (or just for a few specific subclasses) to include `scope: false`. For example: 

```ruby 
          def define_nodes_field
            field :nodes, [@node_type, null: true],
              null: true,
              description: "A list of nodes.",
              scope: false # <- ✨
          end
```

If you want to do that for _every_  connection type in the system, you could customize the base connection class and hook it up to your base object with `connection_type_class(...)` as shown here: https://graphql-ruby.org/type_definitions/extensions.html#customizing-connections

But if you just want to customize _one_ connection type, then you could make a concrete class for it, eg: 

```ruby 
class Types::PublicPostsConnection < Types::BaseConnection 
  # Set up edges field 
  edge_type(Types::Post.edge_type) 
  # Override the default nodes field with a `scope: false` one 
  field :nodes, [Types::Post, null: true],
    null: true,
    description: "A list of nodes.",
    scope: false # <- ✨
end 
```

Then, use that class for any field that should have unscoped `nodes`: 

```ruby 
field :public_posts, Types::PublicPostsConnection, null: false, # ... 
```

Does that seem like it might work ?

**Comment by michal-samluk** [comment]
It looks it should work. I will let you know when I will check it. Thanks.

**Comment by rmosolgo** [comment]
Please let me know if you run into any more trouble here!
