### ISSUE TITLE
Test helper: Generate a sample response based on a query

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#2500]
Hi,

I was wondering if it is possible to generate a sample response from a query. When testing views that are based on a complex graphql response, hitting the DB over and over again makes the tests real slow. So we mock the response from graphql.

But this became very unhandy, because you have this long fixtures in your tests. Most of the time we just pass dummy objects to the view that maintains the response structure (otherwise it would break the view), and we set one or two properties to unit test a certain behaviour. Furthermore, when a query changes, you always have to update the specs and the empty response skeletons.

So, I came up with the idea of generating basic empty skeletons based on a query. But the problem is, that purely based on a query, you can't decide if an object is a Hash or an Array.

So I was wondering, if there is a way to derive the types of a query and generate a skeleton `Hash` based on it. You can parse a query with `GraphQL::Language::Parser.parse(query)` and traverse all the children, but I haven't found a way to execute the query to get it's types.

**Comment by rmosolgo** [comment]
I think that's a great idea! But no, unfortunately there's nothing in this library to help with that. 

One thought I can share is, what if you _dumped_ your application's schema to the GraphQL definition language, then _reloaded_ the schema from that definition, but instead of calling application code, you returned faker data? For example: 

```ruby 
schema_defn_string = MySchema.to_definition 
faker_schema = FakerSchema.generate(schema_defn_string)
```

You'll find `Schema::BuildFromDefinition` and `Schema.from_definition(...)` are the built-in helpers for loading schemas from stringified definitions. You'd have to provide some default resolvers that generate fake data on demand. 

Sorry I don't have anything to offer, but if you do give it a try, please let me know how it goes!

**Comment by 23tux** [comment]
Thanks for your hints!

I already played around an afternoon and went for the approach where I traverse all selections of a node, check if it's a list to determine wether or not the parent object is a hash or an array with `field.type.list?` and so on.

It works so far, but it is a lot of code. So I'm eager to try your solution.

I had a look into the `GraphQL::Schema::BuildFromDefinition` class and tried to understand whats going on, but it's kinda hard when you're new to the gem. Could you provide some more guidance, on how you would approach this?
