### ISSUE TITLE
there should be an equivalent Query type that functions the same as Mutation

### ISSUE THREAD

**Issue by lifeiscontent** [rmosolgo/graphql-ruby#2511]
the mutation API for 1.9 is pretty nice,

however there should be an equivalent for Query

e.g. if I have a

```field :posts, query: Queries::Posts```

which should have literally the exact same API as mutation so then we have a simple way to break down each resolver.

in Apollo Server the way they've structured it is very simple.

e.g. typeDefs defines the schema, resolvers are used to resolve the data and its irrelevant if its a Query or a Mutation

in the docs of GraphQL Ruby, it seems like you would use Mutation and Resolver for what effectively should of been Mutation and Query

the issue with it, is the API for Mutation and Resolver differ from each other, e.g.

on a Resolver

```
type String, null: true
``` 

on a Mutation

```
null true
type String
```

can we please fix this?

**Comment by rmosolgo** [comment]
Thanks for the suggestion! How do you think the `Query` class would be different from `Resolver`? 

Regarding nullability syntax, I expect Resolver and Mutation to accept either one, since both are defined in `Resolver`:

https://github.com/rmosolgo/graphql-ruby/blob/a16ce4fa10c5113ab569071e48d89983f95ed4f9/lib/graphql/schema/resolver.rb#L217-L218

https://github.com/rmosolgo/graphql-ruby/blob/a16ce4fa10c5113ab569071e48d89983f95ed4f9/lib/graphql/schema/resolver.rb#L230-L233

Could you get the structure you're looking for by adding to your application: 

```ruby 
# app/graphql/queries/base.rb
class Queries::Base < GraphQL::Schema::Resolver 
end 
```

then going from there?

**Comment by rmosolgo** [comment]
Let me know if you have any trouble with the workflow described above!

**Comment by lifeiscontent** [comment]
@rmosolgo the `null true` doesn't work in a resolver.

**Comment by lifeiscontent** [comment]
ping @rmosolgo

**Comment by rmosolgo** [comment]
Hi @lifeiscontent, if you're interested in debugging, please open an issue with proper error details, for example: 

- the code you tried 
- what you expected it to do
- what it _actually_ did
- the full error message and backtrace, if there was an error 

hope that helps!
