### ISSUE TITLE
Timeout missing partial response

### ISSUE THREAD

**Issue by sayduck-daniel** [rmosolgo/graphql-ruby#2517]
I've issues to get timeout work as expected.

The [documentation](url) says:

> (...) Any already-resolved fields will be in the data key, so you’ll get a partial response.

When I set the timeout with:

```ruby
  use GraphQL::Schema::Timeout, max_seconds: 5
```

I'm testing it with these fields in my QueryType:

```ruby
    field :name, String, null: false

    def name
      "John Doe"
    end

    field :test, String, null: false do
      argument :seconds, Float, required: true
    end

    def test(seconds:)
      sleep(seconds)
      "waited #{seconds}"
    end
```

and the query

```graphql
query A ($s: Float!){
  name
  one: test(seconds: $s)
  two: test(seconds: $s)
  three: test(}seconds: $s)
}
```

----

with variables 

```json
{
  "seconds": 1
}
```

returns

```
{
  "data": {
    "name": "John Doe",
    "one": "waited 1.0",
    "two": "waited 1.0",
    "three": "waited 1.0"
  }
}
```

----

with variables 

```json
{
  "seconds": 3
}
```

returns

```
{
  "data": null,
  "errors": [
    {
      "message": "Timeout on Query.test",
      "locations": [
        {
          "line": 5,
          "column": 3
        }
      ],
      "path": [
        "three"
      ]
    }
  ]
}
```

It looksl ike the data payload is empty while it should return `name`, `one` and `two`?

**Comment by rmosolgo** [comment]
Hi, thanks for the very detailed report here! I think this is due to the GraphQL specification's "null propagation." When a non-null (`null: false`) field would return `nil`, GraphQL removes the _whole parent object_ from the response so that it doesn't return a `nil` that breaks type safety. 

To demonstrate, when I copied your schema but changed the fields to use `null: true`, I got: 

```ruby 
{"data"=>
  {"name"=>"John Doe", "one"=>"waited 3.0", "two"=>"waited 3.0", "three"=>nil},
 "errors"=>
  [{"message"=>"Timeout on Query.test",
    "locations"=>[{"line"=>5, "column"=>3}],
    "path"=>["three"]}]}
```

After I allowed `nil`, I got a partial response as expected. So, I think to get a partial response, you have to reconfigure those fields to use `null: true`. If that doesn't work for you, or if you run into more trouble, please reopen this issue!

**Comment by sayduck-daniel** [comment]
@rmosolgo this is not gonna work for us. We have those null fields set to false because we need to ensure they are either not null or returning an error.

Would it be possible to have it returning `nil` in case of a timeout or to exclude the field from it?

```{"data"=>
  {"name"=>"John Doe", "one"=>"waited 3.0", "two"=>"waited 3.0"},
 "errors"=>
  [{"message"=>"Timeout on Query.test",
    "locations"=>[{"line"=>5, "column"=>3}],
    "path"=>["three"]}]}```

This would behave like if we never even asked `three`.

**Comment by rmosolgo** [comment]
> any shortcomings

Yes, I'm not interested in implementing it because it's not the behavior described in the specification: 

> Since Non-Null type fields cannot be null, field errors are propagated to be handled by the parent field. If the parent field may be null then it resolves to null, otherwise if it is a Non-Null type, the field error is further propagated to it’s parent field.

(https://graphql.github.io/graphql-spec/June2018/#sec-Errors-and-Non-Nullability)

It sounds like you want a field that you can ensure doesn't return null, except that you want it to return null sometimes. I don't know of any mechanism for unifying those two behaviors: either it _can_ return null sometimes, or it can never return null. `null: true` and `null: false` are used to specify which behavior a field may have. If you want it to return null sometimes, `null: true` is what you're looking for!
