### ISSUE TITLE
Update associated model relationship through mutation

### ISSUE THREAD

**Issue by nathanielread** [rmosolgo/graphql-ruby#2563]
I'm new to GraphQL and RoR. I've read a bunch of the GraphQL-Ruby documentation, but can't figure out how to update an associated model through a mutation. 
Using graphiql-rails 1.7.0
Using graphql 1.9.14
Rails 4.2.11.1
ruby 2.3.8p459

For example, an Address has one BusinessTimeConfig. This works, but seems clunky:
# ./mutations/create_address.rb
```ruby
module Mutations
  class CreateAddress < Mutations::BaseMutation

    argument :name, String, required: true
    argument :raw_line_1, String, required: true, as: :raw_line_1
    argument :raw_line_2, String, required: false, as: :raw_line_2
    argument :raw_line_3, String, required: false, as: :raw_line_3
    argument :city, String, required: true
    argument :state, String, required: true
    argument :zip, String, required: true
    argument :country, String, required: true
    # more fields....

    argument :company_id, Integer, required: false
    argument :company_code, String, required: false
    
    # BusinessTimeConfig attributes
    argument :work_week, String, required: false
    argument :beginning_of_workday, GraphQL::Types::ISO8601DateTime, required: false
    argument :end_of_workday, GraphQL::Types::ISO8601DateTime, required: false

    type Types::AddressType

    def resolve(**attributes)
      if attributes[:work_week]
        attributes[:work_week] = attributes[:work_week].gsub(" ","").split(",")
        btc = BusinessTimeConfig.create(
          work_week: attributes[:work_week], 
          beginning_of_workday: attributes[:beginning_of_workday],
          end_of_workday: attributes[:end_of_workday]
        )
        if btc
          attributes.delete(:work_week)
          attributes.delete(:beginning_of_workday)
          attributes.delete(:end_of_workday)
          attributes.merge!({business_time_config_id: btc.id})
        end
      end
      if attributes[:company_code] && Company.with_edi_code(attributes[:company_code])
        attributes.merge!({company_id: Company.with_edi_code(attributes[:company_code])})
        attributes.delete(:company_code)
      end
      Address.create!(attributes)
    end

  end
end
```

Here's the post:
`mutation {
  createAddress(
    name: "A Place"
    rawLine1: "680 S Rand Road"
    city: "Lake Zurich"
    state: "IL"
    zip: "60047"
    country: "US"
    workWeek: "mon,tue,wed"
    beginningOfWorkday: "08:00"
    endOfWorkday: "17:00"
  )
  {
    id
    name
  }
}`

Is there a way to call another mutation within the CreateAddress mutation to create the BusinessTimeConfig record? I've tried a few different things, but without success.

I have this as well in ./mutations/create_business_time_config.rb
```ruby
module Mutations
  class CreateBusinessTimeConfig < Mutations::BaseMutation

    argument :work_week, String, required: true
    argument :beginning_of_workday, GraphQL::Types::ISO8601DateTime, required: false
    argument :end_of_workday, GraphQL::Types::ISO8601DateTime, required: false

    type Types::BusinessTimeConfigType

    def resolve(**attributes)
      attributes[:work_week] = attributes[:work_week].gsub(" ","").split(",")
      BusinessTimeConfig.create!(attributes)
    end

  end
end
```

Also curious how to handle create multiple related records. For example, Order has many Order Line objects. Creating and updating one to many order line objects in a single mutation call. If this needs to be a separate question, I can split this out with examples.

I appreciate any help.

**Comment by daemonsy** [comment]
Hi @nathanielread I think this question is better suited for the community such as at https://graphql.slack.com. There's a `#ruby` channel over there. 

I'm not very sure how your domain is structured, a few personal suggestions based on the code samples you provided. 

- GraphQL supports list arguments so your `work_week` argument can potentially just be a list of values,  e.g. `argument :work_week, [String], required: true`, less manual work splitting up the array. 

- If you have a set of attributes that belong to one logical interface (e.g attrs to create an address), they can be grouped into an InputObject. This makes it easier to define a mutation that accepts a list of objects too, such as `argument :addresses, [AddressInputObject], required: true`

- Since `BusinessTimeConfig` is an association of `Address`, you can instantiate an address and use something like `address.build_business_time_config(attrs)` (generally `build_<association>`) to make an in memory record, so you can save everything at one go when saving the address. This is probably more transaction safe. This also helps you clean up the resolver code a little. 

If you have further questions, I'm on GraphQL slack too and can try to help. Thanks.
