### ISSUE TITLE
Should I use visible? or authorized?

### ISSUE THREAD

**Issue by Li357** [rmosolgo/graphql-ruby#2565]
If I have certain queries that require a token for authentication, should I hide those parts of the schema to unauthenticated users altogether via `visible?` or should I use `authorized?` to make the client aware that the query exists but cannot be accessed without authentication? Is it preferable for security or performance reasons because `visible?` does not actually execute the query?

**Comment by rmosolgo** [comment]
It depends what kind of client experience you want to provide. 

If you use `.visible?`, it will appear to the client that unauthorized parts of the schema _don't exist at all_. 

If you use `.authorized?`, you can provide custom error messages for the client. Also, inside `authorized?`, you have access to the _actual objects_ being accessed by GraphQL. 

Personally, I recommend `.authorized?` because it's easier to understand and more flexible. But `.visible?` is a good choice if you need to _hide_ part of your schema from some clients. 

As for performance, I wouldn't worry about it. A general tradeoff of GraphQL is higher latency in exchange for a better client experience, and I think this case warrants that tradeoff too. 

Hope that helps!

**Comment by Li357** [comment]
@rmosolgo Thanks! I've decided to use `authorized?` but it never seems to be called. Currently I'm trying to use it in an interface with `definition_methods`:

```ruby
definition_methods do
  def resolve_type(object, context)
    # ...
  end

  def authorized?(object, context)
    puts "test"
    false # for testing
  end
end
```

And in `my_schema.rb` I do:

```ruby
  def self.unauthorized_object(error)
    raise GraphQL::ExecutionError, "Not authorized!"
  end
```

Yet I never get any logs nor do I get the `errors` object when I make the request.

**Comment by rmosolgo** [comment]
🤔 I honestly have no idea what `authorized?` would do in an _interface_! I only ever use it in Objects. It's always called on objects at runtime. 

I can imagine it would be possible to call `authorized` from interfaces _if_ the base object called `super`, but the default implementation doesn't do that: 

https://github.com/rmosolgo/graphql-ruby/blob/b30ea937e7945e9be87de4bc6441cefd74890e0e/lib/graphql/schema/member/base_dsl_methods.rb#L113-L118

So, you could try adding `super` to your own base object's `authorized?` method! But otherwise, I'm really not sure how interfaces play into `.authorized?` 😬

**Comment by Li357** [comment]
@rmosolgo If you don't mind–how else would you control authorization to the subtypes of an interface? I'm trying to use `self.authorized?` in an object type that  `implements Types::UserType` since `self.authorized?` is not called from an interface:

```ruby
class AdminType < Types::BaseObject
  implements UserType # interface

  def self.authorized?
    # never called, puts/returning false, nothing happens in console/errors object in response
    # but self.visible? works
  end
end
```
`self.visible?` works fine and errors correctly while `self.authorized?` is not called when swapped. The object type inherits from `Types::BaseObject` which inherits from `GraphQL::Schema::Object` which should call it. Any advice?
