### ISSUE TITLE
Sort arguments in introspection query.

### ISSUE THREAD

**Issue by piotrze** [rmosolgo/graphql-ruby#2568]
Right now arguments for the fields are in order that you defined in the code

```ruby
  argument :value_in, [String], required: false
  argument :starts_with, String, required: false
  argument :ends_with, String, required: false
```

It you have long list of arguments it's hard to rationale about arguments in autocomplete box in GraphiQL. It will be easier if arguments will be sorted by name.

We have similar PR for schema file https://github.com/rmosolgo/graphql-ruby/pull/775/files

For now I'm using this patch:

```ruby
module GraphQL
  class Schema
    class Warden
      alias_method :old_arguments, :arguments

      def arguments(*args)
        old_arguments(*args).sort_by(&:name)
      end
    end
  end
end
```

@rmosolgo Is that something worth changing in gem? If so then I can make PR.

**Comment by rmosolgo** [comment]
Hey, I'm a bit on the fence about it. I think I tried it once but it turned out to be really slow at large scale, because you end up sorting things over and over again. 

I'm open to a solution where the items are sorted ahead-of-time, and stored sorted. But I couldn't think of a way to implement it 😖 

(The nice thing about printing schema files is that it's not on a hot path for the application.)

**Comment by rmosolgo** [comment]
I don't have plans to work on this, so I'll close it for now. If anyone has a low-overhead solution here, please share it!
