### ISSUE TITLE
NoMethodError Exception: undefined method 'delete' for #<#<Class:0x00007f9682c998a0>

### ISSUE THREAD

**Issue by gastonmorixe** [rmosolgo/graphql-ruby#2575]
Happens on when using `ListingType.connection_type` am I doing something wrong?

<img width="610" alt="image" src="https://user-images.githubusercontent.com/637225/67888778-7addcd80-fb2c-11e9-9daa-dfe0c7dd2cf8.png">

<img width="409" alt="image" src="https://user-images.githubusercontent.com/637225/67888846-9648d880-fb2c-11e9-8c2c-6d20ccd64f0a.png">

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/637225/67889267-44548280-fb2d-11e9-9707-e729cd729ded.png">

https://github.com/rmosolgo/graphql-ruby/blob/a803b831df5bda434eaa9e0f95b0dee62a6fb565/lib/graphql/schema/field/connection_extension.rb#L17

**Comment by rmosolgo** [comment]
Hi, sorry for the hangup. 

It sounds like the dreaded 

```
def resolve_field(obj, args, ctx)
  resolve(obj, args,  ctx)
end 
```

issue. Although, it's hard for me to tell because instead of sharing the _full_ stack trace, you only shared the top few lines. 

Do you have code like ☝️ that in your `BaseField` class? Try removing it, it was part of the generator, but it's not _supposed_ to be there! 

If it doesn't fix it for you, please share the full stack trace.

**Comment by gastonmorixe** [comment]
@rmosolgo thank you! solved indeed

<img width="463" alt="image" src="https://user-images.githubusercontent.com/637225/67946272-c2616980-fbbf-11e9-87ee-1afba82a5142.png">

**Comment by DevUsmanGhani** [comment]
Thanks!
