### ISSUE TITLE
nullable options between mutations and resolvers should be consistent

### ISSUE THREAD

**Issue by lifeiscontent** [rmosolgo/graphql-ruby#2579]
@rmosolgo following up on #2511

this code does not work.

calling `null true` in a resolver does not work. which it should because a mutation and a query are technically the same exact thing (resolvers) in GraphQL.

``` ruby
# app/graphql/types/post.rb
class Types::Post < Types::Base
  field :id, ID, null: false
  field :body, String, null: false
  field :title, String, null: false
end

# app/graphql/create_post.rb
class Mutations::CreatePost < Mutations::Base
  class CreatePostPayload < Types::Base
    field :post, Types::Post
  end

  null true
  type CreatePostPayload

  argument :title, String, required: true
  argument :body, String, required: true

  def resolve(title:, body:)
    ::Post.create(title: title, body: body)
  end
end

# app/graphql/mutations/base.rb
class Mutations::Base < GraphQL::Schema::Mutation
end

# app/graphql/queries/post.rb
class Queries::Post < Queries::Base
  null true
  type Types::Post

  argument :id, ID, required: true

  def resolve(id:)
    ::Post.find(id)
  end
end

# app/graphql/queries/base.rb

class Queries::Base < GraphQL::Schema::Resolver
end
```

**Comment by rmosolgo** [comment]
Thanks for the writeup! Could you clarify something? 

>  does not work

Saying it "doesn't work" denotes a really wide range of scenarios, for example: 

- It raises an error at boot time 
- It raises an error at runtime 
- The software runs differently than I expect it to 
- The software runs differently than I want it to 

Could you clarify which of those four (or maybe something else!) you're talking about? You can help me debug by sharing details about those things, for example: 

- if an error is raised, share the full error message and stack trace 
- if the software doesn't run how you expect, share your expectation and then share the actual behavior 
- if the issue involves inputs and outputs, share an example input/output that demonstrates the behavior 
- if debug information is logged or printed out some way (for example, a schema dump), share the print-out 

If you can share context like that, it helps other debuggers understand what kind of problem they're looking at and how to approach it! With a lot of different bugs, features, discussion, etc, on this project, it really helps me use my time effectively when you share all the different context about an issue.

**Comment by lifeiscontent** [comment]
@rmosolgo sorry about that,

specifically this code here in the example:

```rb
class Queries::Post < Queries::Base
  null true
  type Types::Post

  argument :id, ID, required: true

  def resolve(id:)
    ::Post.find(id)
  end
end
```

the `null true` I would expect would work the same as when using it in a mutation e.g. allow the field to return null

but in order to make a Resolver nullable you're forced to specify it as a param on the type e.g.

`type Types::Post, null: true`

**Comment by rmosolgo** [comment]
Although I agree it's inconsistent, I don't have plans to change this because it's not a high priority and the work-around is trivial. 

If someone wants to make these consistent, it can be accomplished by: 

- Replacing this `alias` with a method whose signature matches `Resolver.type`: 

  https://github.com/rmosolgo/graphql-ruby/blob/377fd26bde60757d2fbd05f65191a70c4004bce8/lib/graphql/schema/resolver/has_payload_type.rb#L23
  
  (That alias becomes `Mutation.type`)
  
- Removing the requirement of `null: ...` here: 
  
   https://github.com/rmosolgo/graphql-ruby/blob/377fd26bde60757d2fbd05f65191a70c4004bce8/lib/graphql/schema/resolver.rb#L239
   
   But adding a means to ensure that the resolver's nullability is _somehow_ configured before the resolver is used to build a field.
