### ISSUE TITLE
OperationStore Ruby API

### ISSUE THREAD

**Issue by jimmybaker** [rmosolgo/graphql-ruby#2582]
I'd love a ruby api for this. We use review apps on heroku and it would be nice to be able to create graphql clients at build time.

**Comment by rmosolgo** [comment]
Thanks for sharing your use case. It's the first time I've read about Review Apps, very cool. It seems like you'd want something to run in the "postdeploy" script that would register the client with the app, then sync all the operations. Is that right?

**Comment by jimmybaker** [comment]
Yeah. I'm not sure how the operations would be created though since those live in other repos. The way we work currently is we use the rails app as just a backend for our front-end apps which live in other repositories.

These front-end apps and our ios apps can be pointed to different backends at runtime for testing purposes. For example, if we make server-side (rails) changes that we want to test against using a front-end app then we're able to do so without having to rebuild the frontend app. This leaves me confused on what's best to do regarding syncing the operations of a front-end client.

It may be better to not use stored operations at all in the review apps. If that's the case then I'll need to come up with a way to conditionally use/ignore the OperationStoreClient apollo link in our front-end apps and have the client just send the query like normal.

I'm open to suggestions. :)

**Comment by rmosolgo** [comment]
Oh, that's interesting. Yeah, I'm not sure how you'd get the operations into the backend. I can think of a few possibilities: 

- Copy operations to the Review App from the main instance (maybe add an HTTP API for that) 
- Somehow copy operations from the git repos of other projects, icky 
- Do like Apollo, where the operation store accepts incoming query strings and persists them in some cases. In that case, you don't get the guarantee that the operation store only contains whitelisted operations, which seems like a big downside to me. 

Alternatively, you could accept dynamic queries when running in Review App mode. The Ruby app could probably detect that it's in Review App mode, and bypass the operation store. In the client app, you'd need it to send the full query strings when it's pointed at a test server. 

You mentioned you're on a Link, you can see here the code that's generated: 

https://github.com/rmosolgo/graphql-ruby/blob/b30ea937e7945e9be87de4bc6441cefd74890e0e/javascript_client/sync/outfileGenerators/js.js#L54-L64

I can imagine extending that code in one of two ways: 

- Add a dynamic check for whether or not the string should be replaced with an ID, eg 

  ```js
  if (OperationStoreClient.isActive && operation.operationName)
  ```

- Instead of using `includeQuery: false`, use a dynamic call to determine that: 
 
  ```js 
  includeQuery: OperationStoreClient.includeQuery
  ```

Either one of those would support switching modes at runtime. Then, whatever mechanism you use to change the backend URL could also change the setting on `OperationStoreClient`. 

What do you think, would something like that work for you?

**Comment by rmosolgo** [comment]
Let me know if you don't thing something like that will work!
