### ISSUE TITLE
Mutation input default value cannot be complex enum

### ISSUE THREAD

**Issue by broskoski** [rmosolgo/graphql-ruby#2607]
Attempting to upgrade from version `1.8.2` to `1.9.15` and getting stuck on mutations with enums as input values where the enums represent objects.

For example, this enum:

```
ChannelVisibilityEnum = GraphQL::EnumType.define do
  name 'ChannelVisibility'
  description 'Privacy states for a channel'

  value 'PUBLIC', value: { published: true, open: true, status: 'public' }
  value 'CLOSED', value: { published: true, open: false, status: "closed" }
  value 'PRIVATE', value: { published: false, open: false, status: 'private' }
end
```

In this mutation:
```
CreateChannelMutation = GraphQL::Relay::Mutation.define do
  name 'CreateChannel'

  input_field :title, !types.String
  input_field :visibility, ChannelVisibilityEnum, default_value: ChannelVisibilityEnum.values['CLOSED'].value
  input_field :description, types.String
  input_field :group_id, types.ID

  return_field :channel, ChannelType
```

Throws this error:
```
Argument input on Mutation.create_channel is invalid: argument "visibility" default value {"published"=>true, "open"=>false, "status"=>"closed"} is not valid for type ChannelVisibility (Can't resolve enum ChannelVisibility for {"published"=>true, "open"=>false, "status"=>"closed"}) (GraphQL::Schema::InvalidTypeError)
```

**Comment by rmosolgo** [comment]
How odd! It seems like it converted the keys to strings. 

Does it work any better if you use a Hash literal instead? (That is, I wonder _where_ the keys are being stringified) 

```diff 
-  input_field :visibility, ChannelVisibilityEnum, default_value: ChannelVisibilityEnum.values['CLOSED'].value
+  input_field :visibility, ChannelVisibilityEnum, default_value: { published: true, open: false, status: "closed" }
```


I will say, I'm not really maintaining the old `.define`-based schema DSL anymore. If you haven't considered updating to class-based schema definitions, I really recommend it. There's an upgrader in the gem which I used to update some ~1000 files in GitHub's code base, so that might be an option too: https://graphql-ruby.org/schema/class_based_api.html#upgrader

**Comment by rmosolgo** [comment]
I hope one of those ideas helps!

**Comment by broskoski** [comment]
Thanks @rmosolgo, your idea solved the issue. Sorry for not responding!
