### ISSUE TITLE
Deserialization of arguments with numbers appears not to work

### ISSUE THREAD

**Issue by TomasBarry** [rmosolgo/graphql-ruby#2611]
Given the following input type:

```ruby
module Inputs
  class MyInput < Types::BaseInputObject
    argument :some_argument, String, required: true
    argument :some_argument_1, String, required: true
  end
end
```

The following mutation does not have the arguments deserialized as expected:

```ruby
module Mutations
  class MyMutation < BaseMutation
    argument :my_input, MyInput, required: true

    type Types::SomeType

    def resolve(my_input:)
      # my_input.some_argument is present, as expected
      # my_input.some_argument_1 is not present
      # instead, it takes the form of my_input.some_argument1
    end
end
```

The query being used is:

```graphql
mutation MyMutation(
  $myInput: MyInput!
) {
  myMutation(
    myInput: $myInput
  ) {
    ...
  }
}
```

Where the variables are:

```es6
const body = JSON.stringify({
  variables: {
    myInput: {
      someArgument: 'some string',
      someArgument1: 'some other string'
    }
  }
})
```

Is this a bug, or is it intended behaviour?

**Comment by TomasBarry** [comment]
Data was not actually being sent as expected. No bug present.

**Comment by TomasBarry** [comment]
@rmosolgo, any ideas on this one?

**Comment by rmosolgo** [comment]
Sorry, it's a bug! It should provide access using the same name as you give to `argument ...`. I don't really have the bandwidth to look into it right now, but I'd be happy to help review a PR if you want to give it go!

**Comment by TomasBarry** [comment]
Thanks for confirming @rmosolgo, could you point me in the right direction on where to start an investigation? Would love to have a look at it.

**Comment by rmosolgo** [comment]
Sure, the first step would be to add a failing test. Then the challenge is to find _where_ the hash is being built with the wrong keys. This is my first guess, if you're using the new interpreter runtime: 

https://github.com/rmosolgo/graphql-ruby/blob/ac2d2354607d39c2c18711e15489ff9d8314eca3/lib/graphql/execution/interpreter/runtime.rb#L458

Otherwise, it might be happening in this code: 

https://github.com/rmosolgo/graphql-ruby/blob/ac2d2354607d39c2c18711e15489ff9d8314eca3/lib/graphql/schema/input_object.rb#L15-L17

Which is a call to this method: 

https://github.com/rmosolgo/graphql-ruby/blob/ac2d2354607d39c2c18711e15489ff9d8314eca3/lib/graphql/query/arguments.rb#L113-L123

(If you're _not_ using the new interpreter runtime, I bet that call to `.underscore` is the culprit. I wonder if there's a way to reach for the `keyword`, like the interpreter code above uses. But I could be wrong!) 

Hope that helps. Please let me know what you find!
