### ISSUE TITLE
Remove invalid `prepare` documentation (wiki)

### ISSUE THREAD

**Issue by jgrau** [rmosolgo/graphql-ruby#2618]
AFAICT [this wiki article](https://github.com/rmosolgo/graphql-ruby/wiki/How-To:-Use-prepare-to-modify-or-validate-arguments-or-inputs) is incorrect as it suggests that you, in a mutation, can pass a symbol to `prepare` and it will invoke a method with that name in order to prepare. As far as I can tell only passing a `Proc` is supported. I am looking at https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/argument_spec.rb#L138 which only lists the proc option.

**Comment by jgrau** [comment]
I found https://github.com/rmosolgo/graphql-ruby/blob/982a75015da36088d97c2397580ef12d9bad4f32/spec/graphql/schema/argument_spec.rb#L114 which I assume is for field arguments that suggests that you for field arguments have the `symbol` option.

**Comment by vpetkar** [comment]
@jgrau I'm not sure this is true, it looks like [the method](https://github.com/rmosolgo/graphql-ruby/blob/734ad4bee373ec1c213f40fc65bab533da420f49/lib/graphql/schema/argument.rb#L130) accepts a string or a symbol, or any object that responds to #call. The tests are not exhaustive

**Comment by rmosolgo** [comment]
Sorry about the hangup -- I removed that page since it also includes `.define`-based examples. I agree that `prepare:` isn't well tested. Personally I don't use it and I find the behavior unpredictable, because it _has_ to run before analysis (and therefore runs before any execution). You'll find lots of issues on this repo about `prepare:` 😅
