### ISSUE TITLE
[PRO] Unexpected behavior when defining pundit_policy_class

### ISSUE THREAD

**Issue by thornomad** [rmosolgo/graphql-ruby#2619]
I am not sure if I am misunderstanding the expected behavior of `pundit_policy_class` or if this is a bug.  Am referring to specifying a [Custom Policy Class](https://graphql-ruby.org/authorization/pundit_integration#custom-policy-class-1) for a field.

_My expectation is, that when I specify `custom_policy_class` that graphql-ruby will _only_ use the specified policy and not attempt to access the policy based on the object's class introspection._  But it seems that `custom_policy_class` is simply adding another policy check in the chain and not replacing the object's policy.

Here is an example that demonstrates the behavior I am **not** expecting:

```ruby
class TestType < Types::BaseObject
  field :value, String, null: false
end

class TestPolicy < ApplicationPolicy
  def show?
    puts '--> [ TestPolicy#show? was called ] <--'
    true
  end
end

class Types::NoteType < Types::BaseObject

  pundit_role :show

  field :test, TestType, null: false,
    pundit_role: :show,
    pundit_policy_class: TestPolicy

  def test
    { value: 'this is a test' }
  end

end
```

### unexpected error: unable to find policy `HashPolicy` 
However, even though I am specifying the policy, it is still looking for a `HashPolicy` (because I am returning a `Hash`).  As you can see from the `puts` call in the output, the custom defined policy *is* being called ... but it is continuing to call the default policy.  

It's almost as if adding `pundit_policy_class` is appending an additional policy check and not replacing one.  I am expecting it to be replaced.

```text
Started POST "/v2" for ::1 at 2019-11-23 13:04:56 -0500
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"query($id: ID!) {\n    note(id: $id) {\n        test {\n            value\n        }\n    }\n}", "variables"=>{"id"=>"SUh3WS2Qojz6l8Y2m0CntbatG2ekTt0J7Pw"}, "graphql"=>{"query"=>"query($id: ID!) {\n    note(id: $id) {\n        test {\n
value\n        }\n    }\n}", "variables"=>{"id"=>"SUh3WS2Qojz6l8Y2m0CntbatG2ekTt0J7Pw"}}}
  Note Load (0.2ms)  SELECT  "notes".* FROM "notes" WHERE "notes"."id" = $1 LIMIT $2  [["id", 85802], ["LIMIT", 1]]
  ↳ app/models/application_record.rb:105
--------------------------------[ TestPolicy#show? ]---------------------------------------
Completed 500 Internal Server Error in 510ms (ActiveRecord: 15.8ms)



GraphQL::Pro::PunditIntegration::PolicyNotFoundError - No policy found for:

- Type: Test
- Runtime value: `{:value=>"this is a test"}`

Pundit error: Pundit::NotDefinedError, unable to find policy `HashPolicy` for `{:value=>"this is a test"}`
:
  graphql-pro (1.11.0) lib/graphql/pro/pundit_integration.rb:296:in `rescue in pundit_policy'
  graphql-pro (1.11.0) lib/graphql/pro/pundit_integration.rb:287:in `pundit_policy'
  graphql-pro (1.11.0) lib/graphql/pro/pundit_integration.rb:316:in `authorized_by_policy?'
  graphql-pro (1.11.0) lib/graphql/pro/pundit_integration.rb:109:in `authorized?'
```

Is this a bug or do I have the wrong expectations?

**Comment by rmosolgo** [comment]
Hey @thornomad , thanks so much for the detailed writeup. FWIW, it sounds like it _is_ working as intended 😅 . 

What's happening is: 

1. `NoteType`'s `:show` configuration is used to authorize the underlying object; then 
2.`NoteType.test`'s `TestPolicy#show` configuration is checked _before_ resolving the `test` field; then 
3. The returned `test` object (a Hash) is checked with `TestType`'s configuration. 

So, as you noted, the field's `pundit_role`/`pundit_policy_class` configurations are _additive_: they introduce a layer of authorization between the parent object and the child object, but the don't replace the child object's authorization. 

The authorization system doesn't include a way to disable authorization if an object came from a certain field. This is by design: in my experience, authorization checks that make assumptions about the possible contexts where they can be called often turn out _wrong_ 😖 . (That is, the dynamic nature of a GraphQL API means that objects can appear in _lots_ of different contexts, so better not to make assumptions about it!) 

If you want to skip authorization in this certain case, but _not_ other cases, your best bet is to encode that data on the object itself. For example, you could accomplish this by setting a flag on the object (ie, an instance variable) or wrapping the object in some kind of proxy that tells the GraphQL layer not to authorize it further. 

Does that help?

**Comment by thornomad** [comment]
Thanks for the detailed response.  That's really helpful and confirms what I am seeing!  Perhaps just update the docs slightly?  When I read:

> You can override the policy class for a field using pundit_policy_class

I didn't get the _additive_ take away that you describe.  I took it to mean _replace_.  Although after you've explained it, I agree with that decision to be more careful. 

If anyone else finds this, I ended up using the `instance variable/method` (above) and added an additional check for that variable in the Policy.
