### ISSUE TITLE
[v1.10.0.pre2] undefined method `target` for APISchema:Class (graphql-batch)

### ISSUE THREAD

**Issue by thornomad** [rmosolgo/graphql-ruby#2639]
Just tried moving up from `1.10-dev` to `v1.10.0.pre2` and am getting an error related to `graphql-batch`.  [This is the line in batch now causing the error.](https://github.com/Shopify/graphql-batch/blob/master/lib/graphql/batch.rb#L19) 

#### error
```text
|| Failure/Error: use GraphQL::Batch
|| 
|| NoMethodError:
||   undefined method `target' for ApiSchema:Class
|| # /Users/damon/.gem/ruby/2.6.3/gems/graphql-batch-0.4.1/lib/graphql/batch.rb:19:in `use'
|| # /Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-432465c39f72/lib/graphql/schema.rb:839:in `use'
|| # ./app/graphql/api_schema.rb:19:in `<class:ApiSchema>'
|| # ./app/graphql/api_schema.rb:3:in `<main>'
```

### diff of gemfile for revision reference

```diff
M Gemfile.lock
@@ -1,9 +1,9 @@
 GIT
   remote: git://github.com/rmosolgo/graphql-ruby.git
-  revision: 87942848cf1f01ca5a54d069da41e286cab137d0
-  ref: 1.10-dev
+  revision: 432465c39f72aa7fb108f9e66d94fea6b0e2d4af
+  tag: v1.10.0.pre2
   specs:
-    graphql (1.10.0.pre1)
+    graphql (1.10.0.pre2)
```

Let me know if you need more info or if maybe there is a new feature/setting I am missing with the upgrade.  Will go back down to `1.10-dev` for now.

**Comment by swalkinshaw** [comment]
This is an issue on graphql-batch if you want to open the issue there. But basically we just need to conditionally check for `target` here: https://github.com/Shopify/graphql-batch/blob/75bfef9b98faa15b59ee5df7f6ba1253083d7ee2/lib/graphql/batch.rb#L19

Either with an explicit version check or via `respond_to?(:target)`. Do you want to give that a try?

**Comment by thornomad** [comment]
@swalkinshaw - thanks.  I created a new issue there.  I'm not sure I understand what `target` is doing and how Graphql-batch should behave when it is not present ... but am happy to try and help.

**Comment by rmosolgo** [comment]
Thanks for reporting this, @thornomad.

This is a migration compatibility issue. Basically, when schemas were defined with the old `.define` API, the schema was actually _wrapped_ in a proxy that "helped" with the definition process. 

Previously, that _proxy_ was passed to `def self.use(schema_proxy)`, and to get the _real_ Schema class, you had to call `schema_proxy.target` (the "target" of the proxy was the Schema class). 

Now, there _is no_ proxy wrapper; instead, the schema class is passed _directly_ to `def self.use(schema)`. So, the call to `.target` is not necessary (and it's broken). 

The "fix" is something like:

```ruby 
def self.use(schema_or_proxy)
  schema = if schema_or_proxy.is_a?(Class)
    schema_or_proxy
  else 
    schema_or_proxy.target 
  end 
  # ... do stuff with `schema` 
end 
```

It's a pain to support _both_ systems, but since I maintain a _massive_ GraphQL API as part of my day job, I really _have_ to make the transition path as incremental as possible. Anyways, I hope that background is helpful! And I share it here because others will probably run into similar issues 🙈
