### ISSUE TITLE
GQL_CONNECTION_INIT

### ISSUE THREAD

**Issue by casiodk** [rmosolgo/graphql-ruby#2647]
Hi, we are using graphql on our server, and we have an android client that are trying to establish a subscription, but it seems that the GQL_CONNECTION_INIT message as described here, is not understood by the server.

https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#session-init-phase

Do you have any advice regarding this?

**Comment by rmosolgo** [comment]
Hi! GraphQL-Ruby doesn't implement Apollo's websocket transport. It provides a subscription implementation based on Rails's ActionCable library, and there are a couple non-Rails (third-party-based) implementations in GraphQL-Pro, too. But, I didn't try to implement websocket transport because I don't have a ton of experience with websockets in Ruby. I imagine it would be possible, but I haven't tried! 

I hope one of those other transports works for you. Or, if you give a try at implementing Apollo-style websockets support, please let me know how it goes, or if I can help at all!

**Comment by nlsrchtr** [comment]
Hi, @rmosolgo. Thanks for the work you do in the scope of this nice project and gem. It really helped us get something off the ground. @casiodk and I work on the same project.

Since we are not that keen in adding another dependency to our stack and keep the data-flow as direct as possible, we are not that much interested in letting the data flow through a 3rd-party.

Wouldn't it be great if there would be a direct support of Apollo's websocket transport? Can you maybe help us to know, what is missing to support this, so we could start working on that? Would you maybe also be available adding the support, if we would be able to pay for your work - so the contribution would be available for the rest of the community as well?

Thanks for your feedback.

**Comment by rmosolgo** [comment]
Sure, I appreciate the interest in keeping the stack simple. 

Is your application using Rails? If so, how about using ActionCable? 

To implement a backend for Apollo's websocket transport, I think we'd need: 

- A Ruby implementation of the server messages 
- A Ruby websocket layer for handling those messages
- A technique for hosting that websocket layer that goes well with a "normal" Ruby deployment and scales well 
- A backend for storing subscription state (ie, who's subscribed to what) 
- A pubsub system for broadcasting subscription updates, so that triggers can be pushed to the right clients, using the right websocket server process 


It's not _impossible_, but I'm not _excited_ about the work because it's basically re-implementing ActionCable. ActionCable already has a pubsub backend, a Rails integration, and a message-handling system for websockets -- all with a battle-tested deployment strategy and the support of Basecamp and the Rails community. I could build something that _works_, but not something that _good_!

**Comment by nlsrchtr** [comment]
Thanks for your fast answer!

Yes, we run a pretty normal Rails stack and could use ActionCable. And yes, we could send the communication over ActionCable, but with that, afaik we would lose the features coming from the native iOS and Android Apollo clients f.e. caching etc.

I saw your post on that over [here](https://github.com/rmosolgo/graphql-ruby/issues/2658#issuecomment-574150966) as well and was wondering, what our real option are? We could also wait for other implementation on the client side, like [this websocket based setup for Apollo client and server](https://github.com/apollographql/subscriptions-transport-ws), but those are not available for native Android and iOS (for now).

Thanks for your thoughts and clarification.
