### ISSUE TITLE
Adding custom execution_strategy causes `execute` to return a hash instead of Query::Result

### ISSUE THREAD

**Issue by bbugh** [rmosolgo/graphql-ruby#2664]
We're trying to add some custom behavior to the default execution strategy. The strategy itself is working fine, except `execute` now returns a `Hash` instead of a `Query::Result` for some reason. 

**Issue**

When calling `Schema.execute` in the default ActionCable `GraphQLChannel` [from the documentation](https://graphql-ruby.org/api-doc/1.9.17/GraphQL/Subscriptions/ActionCableSubscriptions), the standard return looks like this:

```ruby
>> result
=> #<GraphQL::Query::Result @query=... @to_h={"data"=>nil}>
```

When doing the same thing after customizing the execution strategies...

```ruby
class CustomExecutionStrategy < GraphQL::Execution::Execute # or < GraphQL::Schema.default_execution_strategy
  # This is not snipped - just simply subclassing it breaks
end

class MySchema < GraphQL::Schema
  query_execution_strategy CustomExecutionStrategy
  mutation_execution_strategy CustomExecutionStrategy
  subscription_execution_strategy CustomExecutionStrategy
end
```

The result of `execute` is a hash, which breaks a bunch of things because `result.subscription?` and `result.context` no longer exist.

```ruby
>> result
=> { "data" => nil }
```

Note, just sub-classing the execution strategy without any other code causes this issue.

**Expected**

Simply subclassing the default execution strategy should not modify the return result type.

**Comment by rmosolgo** [comment]
Thanks for the detailed bug report! I wonder why that happens 🤔 ...

**Comment by rmosolgo** [comment]
As I think about debugging this, I also consider _deprecating_ custom execution strategies. In the past `graphql-batch` was implemented this way, but it turned out to be really tough to avoid breaking it, because it depended on implementation details of GraphQL-Ruby's built-in execution strategy. 

In a future version (2.0!?), the new Interpreter runtime will be the only option in GraphQL-Ruby. Technically, it's still possible to write a custom execution by initializing `GraphQL::Query.new(MySchema, query_str, ...)`, and working with that object in order to build a result. 

Do you mind sharing what your custom strategy does? I'd love to know if GraphQL-Ruby is missing an extension option that might help you do what you need.

**Comment by rmosolgo** [comment]
I don't have the bandwidth to fix this, and it sounds like there's a good work-around. `GraphQL::Query::SerialExecution` (very old!) and `GraphQL::Execution::Execute` (kinda old) will both be deprecated in 1.12.0.
