### ISSUE TITLE
Directive for query

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#2670]
I hope this is no dumb question (maybe I misunderstood the use case of directives):

In my API a user can have multiple roles like admin or manager. Depending on this roles, I'm using CanCan's `accessible_by` to scope results to the users abilities.

Now the use case popped up, that I want results for a specific role, e.g. a manager. My first solution was to include an argument which I can use to create the right ability for this role

```
query {
  articles(role: "manager") { title }
}
```

The problem is, when I query multiple resources, I have to include the role argument multiple times

```
query {
  articles(role: "manager") { title }
  comments(role: "manager") { id }
}
```

My idea was to use a custom directive for this, that is defined for the whole query

```
query @ability(role: "manager") {
  articles { title }
  comments { id }
}
```

```
class Ability < Schema::Directive
  locations(GraphQL::Schema::Directive::QUERY)

  argument :role, String, required: true

  def self.resolve(object, arguments, context)
    # ...
  end
end
```

But this does not seem to work:

1. The `resolve` method is never called, only when I use `locations(GraphQL::Schema::Directive::FIELD)`
2. From the arguments of the `resolve` method I guess that it is too late to scope the result, as the objects are already loaded, am I right?
3. Is a directive the right tool for such an use case? Or are there any other ways to manipulate a context (e.g. `context.fetch(:current_ability)`) for a whole query?

**Comment by rmosolgo** [comment]
Hi! Good question. I'm afraid `Directive::QUERY` is not implemented yet, because I haven't had a use for it. But I think it would be a nice improvement for it to work like you expect! 

> Is a directive the right tool?

I'm not sure... Is `role` _supposed_ to match the role of the current user? If so, then it should probably be read from the current user instead, otherwise a malicious client could inject any value they want for that directive. 


> other ways manipulate a context

You can write to context at any time; for a query-level hook, you could try query instrumentation: https://graphql-ruby.org/queries/instrumentation.html

In fact, you could even implement your directive this way _now_: during a `before_query` hook, you could inspect the AST to determine whether the directive is present on `query.selected_operation`, and if it is, you could read the argument value and write it into context. For example: 

```ruby 
def before_query(q) 
  ast_operation = q.selected_operation 
  ast_operation.directives.each do |ast_directive| 
    if ast_directive.name == "ability" 
      ast_role_argument = ast_directive.arguments.find { |a| a.name == "role" }
      if ast_role_argument
        role_value = ast_role_argument.value 
        q.context[:current_ability] = role_value
      end 
    end 
  end 
end 
```

Something like that _should_ work! 

I hope that helps, please let me know how it goes if you get to give it a try.

**Comment by rmosolgo** [comment]
Let me know how things turn out! Happy to continue this discussion if you have further questions, but I'm going to close the issue since there's no outstanding work that I know of.

**Comment by 23tux** [comment]
@rmosolgo sorry for the delayed response, thanks for your answer! Works like a charm for the query!

**Comment by 23tux** [comment]
I'd like to use this for i18n too:

```
query @localize(locale: en) {
  article(id: "XJoNvgm5Fa")  {
    title
  }
}
```

Using this instrumentation
```
def self.before_query(query)
  return unless localize = query.selected_operation.directives.find do |directive|
    directive.name == "localize"
  end

  arg = localize.arguments.find { |arg| arg.name == "locale" }
  query.context[:locale] = arg.value.name
end
```

This works so far. The only inconvenience is, that every developer has to remember to wrap code inside an I18n block:

```
I18n.with_locale(context[:locale] || I18n.locale) do
  # ...
end
```

I could define a field extension class that wraps the call, but this only moves the problem: The next developer forgets to use this field class, or just uses `GraphQL::Schema::Object` where the field extension is not present or anything like that.

So, maybe there is some kind of around hook that could be wrapped with a `I18n.locale` block?

**Comment by rmosolgo** [comment]
I can think of two options: 

1. Instead of using `I18n.with_locale { ... }`, use `I18n.locale = ...` in `before_query`, then unset it in `after_query`. It's a little risky because it's not using the block, but GraphQL-Ruby will call the `after_query` hook even if the query raises an error, so I think it would be fine. 
2. You could add a tracer which applies that block: https://graphql-ruby.org/api-doc/1.10.10/GraphQL/Tracing  The only problem there is, I don't remember which comes first, `instrument(:query, ...)` or a tracer. So you might have to move your directive detection into the tracer too, so that the data is available at the right time. 

I think either one would work, let me know how it goes!

**Comment by 23tux** [comment]
Cool, thanks! I'm using `I18n.locale = ...` for now, but the Tracer looks interesting. I hope I get some time to play around with it!

One last question: We are currently exposing our translated fields in this fashion:

```
query {
  products {
    nodes {
      name { de en fr }
    }
  }
}
```

`name` is of type `TranslatedField`

```
type TranslatedField {
  de: String
  en: String
  fr: String
}
```

Is it possible to skip the selection of a specific language, if one uses a directive like this?

```
query {
  products {
    nodes {
      name @localize(locale: en)
    }
  }
}

# OR

query @localize(locale: en) {
  products {
    nodes {
      name
    }
  }
}
```

Background: We'd like to move to the `@localize` directive and supporting both versions on the same field would be a painless upgrade path. But I'm not sure if something like this is supported by the GraphQL specs.

**Comment by rmosolgo** [comment]
> supported by the GraphQL specs

no, it's not allowed by the spec: 

>  Leaf selections on objects, interfaces, and unions without subfields are disallowed.

(http://spec.graphql.org/June2018/#sec-Leaf-Field-Selections)

**Comment by ayumitamai97** [comment]
Maybe field argument is an alternative?

Although this doesn't seem elegant...

```graphql
query {
  products {
    nodes {
      name(locale: "en")
    }
  }
}
```
