### ISSUE TITLE
Guide: Action Cable Implementation

### ISSUE THREAD

**Issue by engwan** [rmosolgo/graphql-ruby#2683]
In https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions/action_cable_subscriptions.rb#L10 we say:

> Take care to reload context when re-delivering the subscription. (see {Query#subscription_update?})

But it's not clear what re-delivering means and where we should be reloading the context.

For example I had a `current_user` in my context, I think this means this will be saved in memory during subscription, and could be stale when an event is triggered.

Where's the best place to reload the context? Do I have to do this in the individual resolvers? Or maybe override `read_subscription` so that it applies to all subscriptions?

**Comment by rmosolgo** [comment]
Thanks for the detailed questions!

> re-delivering

I think I meant _delivering updates_ here. That is, after the initial subscription requests, context should be reloaded before delivering updates, for just the reason you pointed out above.

> best place to reload the context? 

Yes, I think overriding `read_subscription` would be a good place to do it. I was _expecting_ to find `load_context` and `dump_context` hooks, but it turns out those are only implemented by Pusher and Ably implementations (https://graphql-ruby.org/subscriptions/pusher_implementation#serializing-context), which _kinda_ makes sense because they actually write values to Redis. 

But, it might be a nice improvement to add those hooks to ActionCableSubscriptions, since they're useful for reloading data even though there aren't persistence operations going on!

Does that help?

**Comment by rmosolgo** [comment]
I hope you found something that worked for you!
