### ISSUE TITLE
modify list after authorization

### ISSUE THREAD

**Issue by stevecrozz** [rmosolgo/graphql-ruby#2684]
I have a situation like the following:

~~~ruby
class Foo < GraphQL::Schema::Object
  def self.authorized?(object, context)
    possibly_expensive
  end
end

class FooEdge < GraphQL::Types::Relay::BaseEdge
  node_type Foo
end

class FooConnection < GraphQL::Types::Relay::BaseConnection
  edge_type FooEdge
end

class QueryType < GraphQL::Schema::Object
  field :foo, Types::FooConnection, null: false
end
~~~

When I make a query it is possible that some of the Foo nodes will not be authorized and in that case I get a response where a list contains nils because I use this sane default behavior. Because I have not allowed my nodes to contain null values, that is an error. This makes sense.

But what I would like to achieve is to remove any unauthorized values from the results so that the results do not contain any null values. As suggested in #2169, I can accomplish this with list scoping. That works, but in my case the scoping operation is identical to the authorization operation. This is not optimal because now I effectively perform authorization twice on every authorized type.

So I implemented my own field_class, hoping there was some hook that I could use to add an argument to my fields to make them behave the way I want (something like `compact: true`). But I don't see any way for me to receive a callback after authorization where I can call `.compact` on the list.

So I looked into field extensions and they are very cool, but even the latest hook I could find `after_resolve` was not late enough to have already been through the authorization phase. No matter what I tried, authorization always did its job after anything I did within my field extension.

Is there any existing system I can use to accomplish what I'm after? If not, then this is a feature request :)

**Comment by rmosolgo** [comment]
Great question! 

>  existing system 

No, there's basically _not_ 😬 

I'm really torn about building context-sensitivity into the authorization system because my experience with context-based assumptions has been pretty bad. That is, some code is written with assumptions about what kind of GraphQL queries will be executed, but eventually, the system changes such that new queries are executed and the assumption no longer holds. The code which was written based on the assumption becomes a security hole, and eventually, it must be refactored without the assumption. I'd rather just skip the assumption! 

Alternatives I can think of are: 

- Implement whitelisting manually: is there some way to _manually_ tag objects as already-authorized? For example, after scoping the relation, add `relation.selects("*, true as graphql_authorized")`, then later, check for `object.attributes[:graphql_authorized]`
- Add caching to authorization checks: is there some work between `.scope` and `.authorized?` which could be shared instead of duplicated?

I know that it would be _possible_ to "flag" items which were authorized by `.scope`, then skip `.authorized?` for them, but I'm wary of that, because the current guarantee that `.authorized?` is _always called_ is so useful.

**Comment by stevecrozz** [comment]
I can find a way to preauthorize objects such that the second authorization pass becomes a no-op. And that's not a bad idea, but the way I see it, the feature I would like does not have much to do with authorization or scoping. I would like to add to my custom field type something like this where my custom field gets some kind of callback after auth has already happened, but before finishing up where I can modify the field object according to whatever domain logic exists inside my custom field implementation:

~~~ ruby
class MyField < GraphQL::Schema::Field
  def initialize(*args, compact: false, **kwargs, &block)
      @compact = compact
      super(*args, **kwargs, &block)
    end

    def some_kind_of_callback_post_auth(object, *args)
      return super unless @compact
      object.compact
    end
  end

**Comment by rmosolgo** [comment]
Thanks for the detail, but since the functionality can be accomplished another way, I don't think the new extension point is warranted. 

Practically speaking, one like that is problematic because `Object.authorized?` is only called _after_ field resolution is done -- by that time, the array returned by the field is being enumerated. I can't really imagine reaching backward to get the field again, and reconstruct the field's return value in order to call a hook on it. As you mentioned before, that's what `scope` is for.

**Comment by stevecrozz** [comment]
Thanks for the explanation @rmosolgo . Are you also opposed to directly supporting an option for list fields to enable a compact-like behavior? Like `compact: true`

**Comment by rmosolgo** [comment]
Yes, I'm opposed to `compact: true`.  If you want to remove unauthorized items from a list, I think you should use [list scoping](https://graphql-ruby.org/authorization/scoping.html). 

You mentioned performance issues about duplicated authorization checks, but in my opinion, it's generally better to keep the system simple and predictable, and optimize those checks instead.

**Comment by stevecrozz** [comment]
My solution to this is to add a default scope_items method to my BaseObject:
~~~ruby
def self.scope_items(items, context)
  items.select { |i| authorized?(i, context) }
end
~~~

And then in my custom field class, I force all of my Array types to use scope: true in the initializer:
~~~ruby
kwargs.merge!(scope: true) if kwargs[:type].class == Array
~~~

This seems to achieve what I want in that I never see arrays with nils in them and I can still use null: false on my array fields without getting errors when something was unauthorized. It is surprising to me that folks would generally want a different behavior, but different strokes I guess :)
