### ISSUE TITLE
1.10.0 Missing field for query returning interface, when orphan_types is called within the interface

### ISSUE THREAD

**Issue by liang3404814** [rmosolgo/graphql-ruby#2694]
I have a query that returns a type with an interface-typed field. All types of that interface `implements` that interface, and the interface declares the types through `orphan_types` on that interface itself. 

After upgrading to v1.10.0 from v1.9.18, when I tried to access the interface-typed field in my query, I got back an error saying the field doesn't exist. The schema dump doesn't include any types implementing the interface either.

I played around with it, and It seems this is only a problem when all of these three conditions are met:
1) using `GraphQL::Execution::Interpreter`
2) on v1.10.0
3) with `orphan_types` called from inside the interfaces instead of the schema.

Moving all the orphan_types to the schema works for now, but we prefer to have the `orphan_types` declared at each interface for better organization. I checked both the documentation and the changelogs, but didn't find any indication of the behavior of `orphan_types` changing.

I've read https://github.com/rmosolgo/graphql-ruby/issues/2674 as well as https://graphql-ruby.org/type_definitions/interfaces.html#orphan-types to make sure I'm not missing anything, but if I am, some kind of warning or verbose log would be really helpful.

**Comment by rmosolgo** [comment]
Thanks for the bug report! We must not be looking at the interface's orphan types. I think it should be added here: 

https://github.com/rmosolgo/graphql-ruby/blob/55265862420b545cbdac89c99383bf91261b4846/lib/graphql/schema.rb#L1807-L1827

I think we need an `if type.kind.interface?` block which enumerates `type.orphan_types...` and calls `add_type` with them.

Please give it a go if you want to, otherwise I'll try to find time myself!

**Comment by liang3404814** [comment]
@rmosolgo Thanks for the response! I'll try to fit this in my schedule, will let you know if/when get started.

**Comment by liang3404814** [comment]
Gonna take a look today
