### ISSUE TITLE
Support for Automatic Persisted Queries

### ISSUE THREAD

**Issue by fgrehm** [rmosolgo/graphql-ruby#2719]
Hey @rmosolgo!

We're happy users of GraphQL pro that were wondering if there are any plans to add support for Automatic Persisted Queries to this gem.

* https://www.apollographql.com/docs/apollo-server/performance/apq/
* https://blog.apollographql.com/improve-graphql-performance-with-automatic-persisted-queries-c31d27b8e6ea

Thanks in advance!

**Comment by rmosolgo** [comment]
Hi! I think this is the first I've heard of interest in Apollo's automatic persisted queries. But, I think it could work just fine with GraphQL-Pro's operation store, just with some helpers to write to it on the fly. 

Let me take a look and follow up here!

**Comment by rmosolgo** [comment]
So, I read up about Apollo's automatic persisted queries. I arrived at two thoughts: 

1. APQ is not a good fit for integrating with the operation store. I say this because:
  - They have very different persistence paradigms. The operation store is an append-only, long-lived repository of client-registered operations. As a feature, it never forgets anything that client gave it: that way, old versions of client code always find the operations they're looking for. On the other hand, APQ _needs_ an expiring cache: not only are the incoming queries subject to change, but it's even open to arbitrary user input. If the cache didn't expire, a malicious user could stuff it full of garbage. (AFAICT, that could _still_ happen, but the worst case scenario is constant cache misses.) 
- Along those lines, the two systems have different authorization and security considerations. The operation store is _meant_ to be a security feature: when clients can only run registered queries, you can be sure that third-party users aren't running arbitrary queries. (You can also inspect the usage of your schema's parts, since all queries are indexed.) On the other hand, APQ is open to ad-hoc user input, so you don't have any guarantees about what's in the cache or where they came from. 
2. It looks like @DmitryTsepelev  has already implemented APQ for Ruby: https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries. I took a quick look at the implementation and I thought it was good. I don't see anything that I would add or take away; the usage options and in-memory or Redis implementations seem like good choices. 

How about giving that other library a try? 

Or, do you see more reason for trying to integrate Apollo's automatic persisted queries with the operation store?

**Comment by fgrehm** [comment]
> How about giving that other library a try?

We definitely will if we want to explore APQ in the future but your points about security on `1.` gave me second thoughts. I think for now me and @Austio might just continue our experiments with the operation store, specially now that you shipped the ability to introduce caching as per https://github.com/rmosolgo/graphql-ruby/issues/2726#issuecomment-584331347

Thanks a lot for your time and insights!
