### ISSUE TITLE
Can't seem to create a connection type with limit and offset as arguments

### ISSUE THREAD

**Issue by lifeiscontent** [rmosolgo/graphql-ruby#2766]
**query_type.rb**
```rb
module Types
  class QueryType < Types::BaseObject
    field :articles, Types::ArticleConnectionType, null: false do
      argument :limit, Int, required: false, default_value: 10
      argument :offset, Int, required: false, default_value: 0
    end

    def articles(limit:, offset:)
      Article.limit(limit).offset(offset)
    end
  end
end
```

**article_connection_type.rb**

```rb
module Types
  class ArticleConnectionType < Types::BaseObject
    field :total_count, Int, null: false
    field :edges, [Types::ArticleEdgeType], null: false

    def total_count
      object.count
    end

    def edges
      object
    end
  end
end
```

`object` becomes a RelayConnection which is super confusing and unexpected.

**Comment by rmosolgo** [comment]
If you don't want a connection object, use `connection: false` in your field configuration. Otherwise, GraphQL-Ruby wraps list objects with connections. That behavior is described [here](https://graphql-ruby.org/relay/connections.html#connection-types) and [here](https://graphql-ruby.org/type_definitions/extensions#customizing-connections); I'm sorry you weren't expecting it! 

`connection: false` will also remove the arguments that are added by default, so if you still want `first`/`last`/`after`/`before`, you'll have to add them manually. You can see the defaults [here](https://github.com/rmosolgo/graphql-ruby/blob/120ec5e5fd6c9d485f57479cb3861ca1c4bb4a84/lib/graphql/schema/field/connection_extension.rb#L8-L11)

**Comment by lifeiscontent** [comment]
@rmosolgo thanks for the thorough feedback, the resources you provided were helpful!
