### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by KonstantinReido** [rmosolgo/graphql-ruby#2768]
In my Rails 6 project, during the compilation of js files by Webpacker I see the next warning

```
WARNING in ./node_modules/graphql-ruby-client/dist/sync/prepareRelay.js 41:22-47
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/graphql-ruby-client/dist/sync/generateClient.js
 @ ./node_modules/graphql-ruby-client/dist/sync/index.js
 @ ./node_modules/graphql-ruby-client/dist/index.js
 @ ./app/javascript/react/configs/apollo.js
 @ ./app/javascript/packs/application.js
```

In `appolo.js` I import `graphql-ruby-client@1.7.4` npm package in a next way:
`import { ActionCableLink } from 'graphql-ruby-client'`

Maybe I do something wrong.

**Comment by rmosolgo** [comment]
Thanks for reporting this. I don't think you're doing anything _wrong_ but I think it's complaining about the dynamic `require` call here: 

https://github.com/rmosolgo/graphql-ruby/blob/120ec5e5fd6c9d485f57479cb3861ca1c4bb4a84/javascript_client/src/sync/prepareRelay.ts#L29-L31

That code is only ever evaluated via CLI, so don't think it's a _real_ problem, but the warning makes me think we need some kind of "tree shaking" so that this dead code doesn't end up in client-side JS. I thought I was supporting that by using `import`/`export` everywhere.

It looks like webpack _supports_ tree shaking, but it's a lot of work: https://webpack.js.org/guides/tree-shaking/

**Comment by jscheid** [comment]
Is there anything speaking against moving the sync stuff into a separate package?

**Comment by rmosolgo** [comment]
From my standpoint, it's just a fear of increasing the maintenance burden. If I can help it, I'd rather not have another package to publish, maintain a changelog, fuss with CI, etc. But maybe it'd be the right approach 🤷‍♂

**Comment by nburt** [comment]
We're getting this for our app as well ever since we added websockets. I've been doing a little analysis with webpack-bundle-analyzer and I'm seeing that the entire package is included:

![image](https://user-images.githubusercontent.com/5788989/80617785-85601d80-8a10-11ea-9497-3ac4d2d6cd50.png)

It *seems* like this works: `import ActionCableLink from 'graphql-ruby-client/dist/subscriptions/ActionCableLink';`

Warning is gone and it reduces our bundle by 0.4mb by only including `ActionCableLink` and fewer files from `graphql` / other packages

![image](https://user-images.githubusercontent.com/5788989/80618035-d2dc8a80-8a10-11ea-8c1f-78a7dba62ae6.png)

I think this confirms that some work is needed to make tree shaking work properly. Is this something you / anyone else is actively working on? Next few weeks are tough but I can make some time mid-May to take a look if no one else is

**Comment by marlosirapuan** [comment]
Thank you, @nburt !

**Comment by anark** [comment]
Unfortunately, as of a recent `graphql-ruby-client` upgrade this workaround no longer fixes the large bundle issue.

Is there anything that can be done to fix this?

**Comment by rmosolgo** [comment]
Hey, sorry I've been slow on this. It seems like the "fix" is to support better imports for _each component_ in the package, instead of requiring (or suggesting) imports to go through `index.js`. I'm updating the build to remove `dist/` in #3329 . 

@anark, I'm surprised the work-around of importing specific files isn't working for you. Could you share some details about how you're using graphql-ruby-client and how you determined that your updated imports aren't changing bundle size?

**Comment by rmosolgo** [comment]
🚢  graphql-ruby-client which takes the individual files back _out_ of `dist/`, and I updated the docs to recommend importing that code directly from those files (instead of `index.js`). Hopefully that will address the bundle size and the warning mentioned above. Please open a new issue if you run into trouble on that new version!

**Comment by anark** [comment]
Thanks, I'll do a bit more investigation and open a new issue when I have a full understanding.

It is possible the bundle size is so big because I am using `graphql@15` in my project but that `graphql-ruby-client` requires `graphql@14` leading it to include an entire second version of the graphql package.

I'll see if I can figure out for sure the root cause and make a PR or a new issue.
Thanks!

**Comment by in15** [comment]
My mistake @rmosolgo . I created a separate issue. Thanks for all that you do!
