### ISSUE TITLE
authorized? is not called on abstract types

### ISSUE THREAD

**Issue by chrisbutcher** [rmosolgo/graphql-ruby#2769]
## Background / problem

When object types are resolved in graphql-ruby calls [`authorized?`](https://graphql-ruby.org/authorization/authorization.html) , providing the object as well as `context` to let developers decide whether the object should be returned to the caller.

It appears there's an important difference with authorization checks performed on abstract types. 

The gem only has integration for `authorized?` right now which is after field resolving of course. but its **only** implemented when resolving an object type, because objects get instantiated via `authorized_new`. Abstract types arent ever instantiated themselves ([source](https://github.com/swalkinshaw/graphql-ruby/blob/10a95a70111b17c312afff9548191f8d833efa8c/lib/graphql/execution/interpreter/runtime.rb#L297-L312)).

Here's an example schema and query to demonstrate the issue as I see it.

### Schema

```graphql
schema {
  query: QueryRoot
}

interface Food {
  price: Float!
}

type Pizza implements Food {
  price: Float!
  sliceCount: Int!
}

type QueryRoot {
  food: Food!
}
```

### Definition

```ruby
module Types::Food
  include Types::BaseInterface

  # field defs omitted
   
  def self.authorized?(value, context)
    # ...
  end
end

class Types::Pizza < GraphQL::Schema::Object
  implements Types::Food

  # field defs omitted
    
  def self.authorized?(value, context)
    # ...
  end
end
```

### Query

```graphql
{
  food {               # I expect that the authorized? method would get called
    ... on Pizza {     # on the Food interface, as well as the Pizza type, when
      price sliceCount # either is resolved.
    }
  }
}
```

## Expectated behaviour

When a Pizza object is resolved, I'd expect `Food.authorized?` to first be called. Once the Pizza object is resolved, I'd also expect `Pizza.authorized?` to be called.

## Current behaviour

 `Pizza.authorized?` is invoked, but `Food.authorized?` is not.

This matters, because authorization constraints may differ between abstract types and their concrete types. What do you think, @rmosolgo ?

**Comment by rmosolgo** [comment]
I'm torn -- it works the way _I_ expect, because I built it and documented it 😆 

I see your point though, for sure. 

One thing that's important to me is that query syntax concerns don't enter into authorization routines. for example, I think these two `Pizza`s should be authorized the _same way_: 

```graphql 
# fetched as a Node 
{ node(id: "123") { ... on Pizza { ... } } }
# fetched as a Food 
{ food(favorite: true) { ... on Pizza { ... } } }
```

Otherwise, you set people up for a foot-gun. They might think "Oh, I'll add authorization to `Node` since all my objects are nodes", when in fact, an attacker could discover that a craftier query could bypass authorization on `Node`. 

So, if abstract types's `authorized?` hooks come into play, then I think they should _always_ be check for objects that belong to those abstract types. 

In fact, for interfaces, it's really trivial to do now: 

```ruby 
class BaseObject < GraphQL::Schema::Object 
  def self.authorized?(object, context)
    self.interfaces.each do |interface_module| 
      if !interface_module.authorized?(object_context)
        return false 
      end 
    end 
  end 
end 
```

Then, other objects could call `super` for the default behavior. (For 1.9.x, I think you'd have to do `interface_module.type_class.authorized?`, because it might return legacy objects there.) 

How does that compare to what you have in mind? 

What about Unions?

**Comment by rmosolgo** [comment]
I don't have plans to work further on this because of the hangups I mentioned above. If anyone wants to keep discussing, feel free to leave your opinion and we can reopen this issue.
