### ISSUE TITLE
default_value not being used if `nil` is passed.

### ISSUE THREAD

**Issue by lifeiscontent** [rmosolgo/graphql-ruby#2864]
**Describe the bug**

given this example:

```rb
# frozen_string_literal: true

module Mutations
  class Example < Mutations::BaseMutation

    argument :should_be_false, Boolean, required: false, default_value: false

    type Boolean
    null false

    def resolve(should_be_false:)
      should_be_false
    end
  end
end
```

then in a test I pass `shouldBeFalse: nil` as variables I would expect the value to be false in resolve, but it is nil.

**Versions**

`graphql` version: 1.10.1
`rails` (or other framework): 5
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

N/A

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
mutation ExampleMutation($shouldBeFalse: Boolean) {
  example(shouldBeFalse: $shouldBeFalse)
}
```

```json
{
  "data": {
    "example": null
  }
}
```

**Steps to reproduce**

Create a test that has the variable set to false

**Expected behavior**

I'd expect `nil` to fall back to the `default_value` specified.

**Actual behavior**

returns `nil` instead of `default_value`

Place full backtrace here (if a Ruby exception is involved):

N/A

**Additional context**

With these details, we can efficiently hunt down the bug!

**Comment by rmosolgo** [comment]
Hi! I think this behavior is in keeping with the spec, see for example: http://spec.graphql.org/June2018/#sec-Null-Value

When `null` is provided, it is treated _as a value_. The default value is applied when _no value_ is given, for example, when an argument is not passed, or an optional variable is not passed. 

Here's a little example script: 

```ruby 
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "1.10.5"
end

class Query < GraphQL::Schema::Object
  field :echo, Boolean, null: true do
    argument :input, Boolean, required: false, default_value: false
  end

  def echo(input:)
    input
  end
end

class Schema < GraphQL::Schema
  query(Query)
end


pp Schema.execute(<<~GRAPHQL, variables: { nullVariable: nil }).to_h
query($nullVariable: Boolean, $emptyVariable: Boolean) {
  noValueGiven: echo
  nullLiteralGiven: echo(input: null)
  nullVariableValueGiven: echo(input: $nullVariable)
  emptyVariableValueGiven: echo(input: $emptyVariable)
}
GRAPHQL
```

That outputs the different values:

```
$ ruby test.rb
{"data"=>
  {"noValueGiven"=>false,
   "nullLiteralGiven"=>nil,
   "nullVariableValueGiven"=>nil,
   "emptyVariableValueGiven"=>false}}
```

When _no value_ is given, the argument defaults to `false`. When `null` is provided (as a literal `null`, or a `nil` variable value), then the field receives `nil` instead of the default value. 

Hope that helps!

**Comment by lifeiscontent** [comment]
@rmosolgo is there a way to force the argument to be `false` if `nil` is given?
