### ISSUE TITLE
Memory bloat due to Graphql 10.1.4 with Sidekiq

### ISSUE THREAD

**Issue by agyant** [rmosolgo/graphql-ruby#2883]
**Describe the bug**

I am seeing a big memory allocation for graphql gem when I got a heap dump for our Sidekiq process.

**Versions**

`graphql` 10.1.4:
`rails` (or other framework):Rails 5.2.4.1
`sidekiq`: sidekiq 6.0.5
other applicable versions (`graphql-batch`, etc)

**Steps to reproduce**
We have a dependency on a gem that uses graphql to query and update/delete data. 
At the moment there are some sidekiq workers that are running at a concurrency of 5 threads that uses the graphql api.
I have seen a big memory bloat in our pods after we started using graphql.

**Actual behavior**
This is a heap dump for one of the generations:
```
allocated by memory (4081982) (in bytes)
==============================
  1297248  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/define/instance_definable.rb:85
   819752  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/define/instance_definable.rb:106
   735496  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/query/arguments.rb:13
   219816  /usr/bundle/ruby/2.7.0/gems/graphql-client-0.16.0/lib/graphql/client/schema/object_type.rb:13
   137208  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/define/instance_definable.rb:131
   107352  /usr/bundle/ruby/2.7.0/gems/graphql-client-0.16.0/lib/graphql/client/schema/object_type.rb:14
    98400  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/schema/loader.rb:19
    61344  /usr/bundle/ruby/2.7.0/gems/graphql-client-0.16.0/lib/graphql/client/schema/object_type.rb:17

object count (40095)
==============================
  27026  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/define/instance_definable.rb:85
   1589  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/query/arguments.rb:13
   1230  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/schema/loader.rb:19
    852  /usr/bundle/ruby/2.7.0/gems/graphql-client-0.16.0/lib/graphql/client/schema/object_type.rb:17
    821  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/define/instance_definable.rb:106
    800  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/define/instance_definable.rb:131
    781  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/schema/loader.rb:58
    689  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/field/resolve.rb:16

High Ref Counts
==============================

  38888  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/define/instance_definable.rb:85
  15054  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/define/instance_definable.rb:106
   4620  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/define/instance_definable.rb:131
   3979  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/query/arguments.rb:13
   3690  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/schema/loader.rb:19
   2343  /usr/bundle/ruby/2.7.0/gems/graphql-client-0.16.0/lib/graphql/client/schema/object_type.rb:17
   1904  /usr/bundle/ruby/2.7.0/gems/graphql-1.10.4/lib/graphql/schema/traversal.rb:44
   1822  /usr/bundle/ruby/2.7.0/gems/graphql-client-0.16.0/lib/graphql/client/schema/object_type.rb:13
```

Could you help me to find out what we might be doing wrong to create such a memory bloat.
Can this be an issue with the queries?
Most if not all the memory is being allocated to `instance_definable.rb`
We tried updating to version 10.1.5, but that didn't help either.

**Comment by rmosolgo** [comment]
Thanks for the detailed report. Sorry about the trouble! Some thoughts: 

- It looks like you're using `graphql-client`, which builds a GraphQL schema under the hood. 
- It looks like it's building a schema from an introspection response (I see `schema/loader.rb` in there) 
- I'm not surprised to see high memory usage in `instance_definable`: it's a legacy API that I've been replacing as fast as I can _because of_ the memory consumption 😅  ! The replacement is called the "class-based API", and it uses plain Ruby classes instead of the custom object structure which hogs so much memory. 
- Yesterday, I released graphql-ruby 1.10.7 which modifies `schema/loader.rb`: in that version, `schema/loader.rb` builds a _class-based_ schema instead of a legacy schema (#2876) 

I _think_ graphql-client will support a class-based schema. Could you try again with graphql-ruby 1.10.7 and share the memory profile? 

Also -- since graphql-client builds a graphql schema under the hood, its memory footprint will be proportional to the size of the schema it's working with. If you're integrating with a _really big_ schema, graphql-client will hog a lot of memory 😬 

Anyways, please let me know what you find with 1.10.7!

**Comment by agyant** [comment]
Sure @rmosolgo I'll give a go

**Comment by rmosolgo** [comment]
Let me know if you find more trouble here!
