### ISSUE TITLE
Is it possible to eliminate/customise the top-level errors response?

### ISSUE THREAD

**Issue by ivawzh** [rmosolgo/graphql-ruby#2890]
**Is your feature request related to a problem? Please describe.**

Blahblahblah crazily opinioned theories in my head - top-level error responses are like exceptions. Their formats are not typed. And they break the promised GraphQL schema with no respect. 

Therefore, I want to move all the errors back to properly typed query responses. And I am only focusing on mutations because I am using Hasura for reads. Plus, my mutations only return ID after success, so no need to use `errors` for explaining null `!` field surprises. 

**Describe the solution you'd like**

I have tried really hard digging. Things like:

- GraphqlController `def execute { rescue }`
- Mutation `def resolve { rescue }`
- Schema `rescue_from(StandardError)`
- Schema `rescue_from(GraphQL::StaticValidation::Error)`
- Schema `def self.error_handler { ... }`

None of them work. 

After spending the whole night then I realized `GraphQL::StaticValidation::Error` are returned as value instead of raised. And many validations happen and shortcircuit before resolver. For example (I know there is also a more complicated multiplex version 🤦):

```ruby
def run_one_legacy(schema, query)
  query.result_values = if !query.valid?
    all_errors = query.validation_errors + query.analysis_errors + query.context.errors
    if all_errors.any?
      { "errors" => all_errors.map(&:to_h) }
    else
      nil
    end
  else
    GraphQL::Query::Executor.new(query).result
  end
end
```

I have a fuzzy idea instead of returning `{ "errors" => all_errors.map(&:to_h) }` from above, I can make it call `CustomExecutor.new(query, all_errors).result`.

I am just hoping you will have some magical ways to guide me to achieve that. 

Thanks in advanced 🙏

**Comment by rmosolgo** [comment]
My best suggestion is to process the _hash_ after GraphQL-Ruby returns it. As you noticed, the library itself has many mechanisms for handling errors -- however, all those mechanisms _eventually_ put errors in the `"errors"` key. Why not use that data as input for your transformation, eg: 

```ruby 
result = MySchema.execute(...) 
if result.key?("errors")
  type_checked_errors = reformat_errors(result["errors"]) 
  result["errors"] = type_checked_errors 
end 
render json: result 
```

?

(I'm closing this issue because I don't expect to follow it up with a PR -- please let me know what you think and we can continue the conversation here!)

**Comment by ivawzh** [comment]
Your suggestion makes sense. 
However, I am not sure how I could shape the top-level errors back into query fields. 
Is there any way I can reprocess the fields with given `result.errors` but skipping validation and resolver?
Or is there a way I could get the top-level query fields, and hopefully I can put the errors into according to the `error.path`.

**Comment by rmosolgo** [comment]
If you want to serve errors as part of the schema, I recommend adding error types to your schema, and returning error values like normal fields. Described briefly here and in the linked mutation guide: https://graphql-ruby.org/errors/overview.html#errors-as-data

**Comment by ivawzh** [comment]
Yes, that's exactly what I am doing. So far I am able to put all the errors from resolver into data. However, graphql-ruby by default puts all the validation errors such as type error, argument error, etc on the top level. This git issue's question is more for those `GraphQL::StaticValidation::Error`

**Comment by rmosolgo** [comment]
Oh, I see what you mean, I'm sorry I misunderstood. I don't know of any built-in way to change the default response for validation errors. Since that behavior is part of the GraphQL specification, I never bothered with a way to change it. I think your best bet is manually reformating them. I'm not sure what you mean by "reprocessing" fields, but if you're looking for other options for working with queries, I recommend checking out the API docs for GraphQL::Query: https://rubydoc.info/gems/graphql/1.10.7/GraphQL/Query

Hope that helps!
