### ISSUE TITLE
Union type specialization should be ok without fields

### ISSUE THREAD

**Issue by jscheid** [rmosolgo/graphql-ruby#2893]
**Describe the bug**

I'm getting this error with 1.10.7:

```
Possible type for MyUnionType is invalid: MySpecialization must define at least 1 field. 0 defined.
```

This was working fine with 1.9.4 (Relay 9.0.0 on the client side). The `__typeinfo` is a piece of information in itself, and I don't see a reason why I should have to add a bogus field. Could this  be made less strict again?

FWIW the use case here is the following: The union describes one of several states, some of which come with state-specific additional data, but some are just the state itself. So it's a bit like an enum, except that the enum wouldn't let me model the additional data for some of the enum values.

**Versions**

`graphql` version: 1.10.7

**GraphQL schema and query, steps to reproduce etc.**

I can provide these to you if needed.

**Comment by rmosolgo** [comment]
Sorry, GraphQL-Ruby previously allowed _invalid_ object definitions, but #2461 corrected that behavior and added this validation. See http://spec.graphql.org/draft/#sec-Objects.Type-Validation

> 1. An Object type must define one or more fields.

I don't plan to change this behavior since the current behavior implements the specification. I think you'll have to add a "dummy" field to the object! (Or migrate to Enum + Object for modelling the data)

**Comment by jscheid** [comment]
Oh, I see.. fair enough, thanks for explaining this.
