### ISSUE TITLE
1.10.7 docs link is broken

### ISSUE THREAD

**Issue by austinbiggs** [rmosolgo/graphql-ruby#2898]
**Describe the bug**

The 1.10.7 docs link is broken - found on the gem's website
[https://graphql-ruby.org/api-doc/1.10.7/](https://graphql-ruby.org/api-doc/1.10.7/)

**Versions**

`graphql` version: 1.10.7

**Comment by rmosolgo** [comment]
Sorry, I tried to fix this the other day, but then I ended up in filesystem hell: the GitHub action that publishes graphql-ruby.org is run on linux (case-sensitive), but I run on Mac (case-insensitive), and when I pull the `gh-pages` branch, I get a git conflict on `docs/GraphQL.html` which weirdly somehow conflicts with `docs/Graphql.html` (the namespace for the Rails generator). So I can't build it locally right now 😖 . I'll try to fix it pronto. 

In the meantime, it looks like https://rubydoc.info/gems/graphql/1.10.7 is up-to-date (sometimes it wouldn't build right, which is why I added  a custom build to graphql-ruby.org), so you can check there.

**Comment by austinbiggs** [comment]
Thank you so much!

**Comment by rmosolgo** [comment]
😆  Almost there, but not quite: 

![image](https://user-images.githubusercontent.com/2231765/80379273-dda9ea80-886b-11ea-8832-996dc6ad6469.png)

**Comment by rmosolgo** [comment]
Ok, got a successful build over at https://github.com/rmosolgo/graphql-ruby/actions/runs/89144397. It published 1.10.8, which I released this morning, and the link at the top of graphql-ruby.org is :+1:
