### ISSUE TITLE
Remove max_page_size via directive

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#2923]
Hi,

I'm not sure if the approach I'm taking is the right one, so every help is appreciated.

I want to write a custom directive where I can remove the `max_page_size` and implement some kind of auto-pagination:

```
query {
  articles  {
    nodes @autoPaginate {
      id
    }
  }
}
```

This directive should mark the path where I don't want to apply the `default_max_page_size` setting:

```
class AutoPaginate < GraphQL::Schema::Directive
  locations(GraphQL::Schema::Directive::FIELD)

  def self.resolve(object, arguments, context)
    path = context.namespace(:interpreter)[:current_path]
    (context[:auto_paginate] ||= []).push(path)
    yield
  end
end
```

But here I'm stuck: I don't know how to overwrite the `default_max_page_size` setting during runtime. Here https://graphql-ruby.org/pagination/using_connections.html#make-connection-fields you suggest that you could use a custom wrapper and pass the option:

```
def items
  relation = object.items
  Connections::ItemsConnection.new(relation, max_page_size: 10)
end
```

But I simply have a

```
class BaseConnection < GraphQL::Types::Relay::BaseConnection
end

# ...
field :articles, ArticleType.connection_type, null: false

def articles
  Article.all
  # here look if the current_path is inside context[:auto_paginate] and apply a max_page_size: nil
end
```

and I don't know how to apply those options during runtime.

**Comment by rmosolgo** [comment]
If you're looking for a programmatic option, here's a suggestion. Auto-connections are applied by `ConnectionExtension`:

https://github.com/rmosolgo/graphql-ruby/blob/da676d9f2e46f83ea2906098a770d9f928b1ac55/lib/graphql/schema/field/connection_extension.rb#L42-L44

It calls `schema.connections.wrap` to apply the connection object to application-provided collection. Here's that method: 

https://github.com/rmosolgo/graphql-ruby/blob/da676d9f2e46f83ea2906098a770d9f928b1ac55/lib/graphql/pagination/connections.rb#L66-L89

You could make a custom subclass of `Pagination::Connections` with your custom behavior: 

```ruby 
class AutoPaginateConnections < GraphQL::Pagination::Connections 
  def wrap(field, object, arguments, context, wrappers: all_wrappers)
    connection = super 
    if auto_paginate?(context) # somehow check for the condition
      connection.max_page_size = nil
      # do something else 
    end 
    connection 
  end 
end 
```

That way, you could hook into the auto-wrapping of connections. 

The only problem is, you can see in the code that this method is marked `@api private`. It's not documented as an extension point and it's not unit-tested, so it might break between versions. 

If you want to stabilize this behavior, you could add a test to this gem that demonstrates your use case. That way, we could keep an eye on it in the future. 

Alternatively, you could test your extension in your own application, so that if it breaks in graphql-ruby, you can modify your customization as-needed then. 

Hope that helps! Let me know if you run into any trouble.

**Comment by 23tux** [comment]
Thanks @rmosolgo for your answer!

I had to set

```
connection.max_page_size = -1
```

otherwise, it would fall back to `default_max_page_size`. I think it's caused by this line

https://github.com/rmosolgo/graphql-ruby/blob/431a25004d17327b5a8c32fae920af412a1eb1e6/lib/graphql/pagination/connections.rb#L83

But setting it to `-1` is fine with me.

I'm gonna try to implement it in my own app, and if it works, I try for a PR. Any suggestions where you would add this test?

**Comment by 23tux** [comment]
@rmosolgo One last thing:

It seems that the type of object changes, when using this approach:

```
# before
[1] pry(#<#<Class:0x000055d38da54838>>)> object.class
=> GraphQL::Relay::RelationConnection

# after
[1] pry(#<#<Class:0x000056140cb55ce0>>)> object.class
=> GraphQL::Pagination::ActiveRecordRelationConnection
```

This breaks some behaviour in my app, because `#nodes` was a relation before, and becomes an array when using AutoPagination:

```
# before
[1] pry(#<#<Class:0x00005612c558dfa8>>)> object.nodes.class
=> Article::ActiveRecord_Relation

# after
[2] pry(#<#<Class:0x000056140cb55ce0>>)> object.nodes.class
=> Array
```

How could I deal with that?

**Comment by 23tux** [comment]
nevermind, I found a comment from you

https://github.com/rmosolgo/graphql-ruby/issues/2829#issuecomment-600140916

```
  def total_count
+   object.items&.count
-   object.nodes&.count
  end
```

**Comment by Alex153** [comment]
> ... 
> otherwise, it would fall back to `default_max_page_size`. I think it's caused by this line
> 
> https://github.com/rmosolgo/graphql-ruby/blob/431a25004d17327b5a8c32fae920af412a1eb1e6/lib/graphql/pagination/connections.rb#L83
> ...

@rmosolgo I tried to use `max_page_size: nil` to override the schema default, but I came down to this same line of code as it always takes the schema default max_page_size 😕 

Is there a solution to this ?

**Comment by rmosolgo** [comment]
Seems broken, duplicate of https://github.com/rmosolgo/graphql-ruby/issues/2840
