### ISSUE TITLE
Correct way to extend the root query

### ISSUE THREAD

**Issue by bilby91** [rmosolgo/graphql-ruby#2928]
Hello,

I'm trying to get the [apollo-federation gem](https://github.com/Gusto/apollo-federation-ruby) working with the new interpreter and I'm trying to find the _right_ way to extend the Query type.

This is how it's currently working https://github.com/Gusto/apollo-federation-ruby/blob/master/lib/apollo-federation/schema.rb#L15. It basically overrides the `to_graphql` of the schema and adds the `_service` and `_entities` fields.

I'm thinking of changing the approach and start using the `use` api to setup the schema. 

This code lets me populate the `_Entitiy` union type with the different possible types.

```
    def self.use(schema)
      possible_entities = schema.types.values.select do |type|
        type = type.respond_to?(:to_graphql) ? type.to_graphql : type

        !type.introspection? && !type.default_scalar? && type.is_a?(GraphQL::ObjectType) &&
          type.metadata[:federation_directives]&.any? { |directive| directive[:name] == 'key' }
      end

      schema.types['_Entity'].possible_types(*possible_entities)
    end
```

What I'm looking for is figuring out a way in which the `use` call adds  the `_service` and `_entities` fields into the Query without having to manually add it myself.

Is there any public API to accomplish this ?

**Comment by bilby91** [comment]
@rmosolgo Would like to get your input on this.

When the Schema is built I need to do the following:

1) Add the `_service` field to the root query. If a root query doesn't exist, I need to create one.
2) Add the `_entities` field to the root query.
3) Add all possible types to the `_Entity` union type based on `schema.types` that have a given directive.

At first I tried to use the plugins API. The problems that I found is that the `use` API is strictly dependent on the order of the plugins. So, if the `use` method is called before the `query(Types::Query)` is set, the query is nil and I don't have a way to know if this happen because the user didn't provide a query or because the plugin was added before the query was set.

Assuming the order is not an issue, the other issue I found is that I don't have any public API that I can use to modify the schema after the root query is set. I can hack the ivars to get it working but it would be really fragile.

I was thinking if could be possible to add some "lifecycle" API to the schema that would basically let you hook to the building process of the schema. At that point I could make all the modification I need to the schema.

Do you think something like this would be useful ? Has anyone else needed something similar to this ?

Thanks before hand!

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed issue and sorry I'm a bit slow to respond. 

> Do you think something like this would be useful ? Has anyone else needed something similar to this ?

Yes, definitely, but I think it's hard to do in a way that supports all of: 

- Ruby's open classes (you never know when `class Schema < ...` is actually _finished_, it can be extended at any time) 
- Rails autoloading (avoiding stale references to constants) 
- Multithreaded server boot (different threads loading files at different times) 

The old `.define` API _did_ give some lifecycle hooks, but it added a lot of difficulty in those other areas, and a big performance hit besides. 

The best thing I could think of was to _require_ more from application code. Like you said, some things are order-dependent. It's trouble, but the advantage is you can make it work with plain Ruby, and it's more debuggable that way. 

Here are some thoughts about adapting Apollo Federation: 

- To extend the query type, I recommend using a Ruby module: 

  ```ruby 
  class Types::QueryType < Types::BaseObject 
    include ApolloFederation::QueryExtension
  end 
  ```

  Then using `def self.included(child_class)` to add fields to `QueryType` that way. 

  It doesn't address the problem of _adding_ a `Query` root. If a federated schema requires a `Query` root, it might be an _improvement_ to require that in the Ruby source code. It would make it more obvious to someone reading it how it works. 

- The `_Entity` union is pretty tricky. I think the best thing you could do is add it to `orphan_types` at the _end_ of the class definition, something like: 

  ```ruby 
  class MySchema < GraphQL::Schema 
    query(Types::QueryType)
    mutation(Types::MutationType) 
    # ...
    orphan_types(ApolloFederation.build_entity_union(self))
  end 
   
  # implemented like
  def build_entity_union(schema_class, union_base_class = GraphQL::Schema::Union)
    Class.new(union_base_class) do 
      possible_types(schema_class.types.keys)
    end 
  end 
  ```

  It introduces an order dependency, just like you said ... but I don't really know any better solution 😖 


Sorry I don't have a better suggestion, but I hope it helps anyways. Happy to continue the discussion here if there's anything I can help with, but I'll close the issue since there's no outstanding work on GraphQL-Ruby.

**Comment by bilby91** [comment]
@rmosolgo Thanks so much for the feedback! This is really valuable!

The only thing that I'm not sure I would be able to solve with this approach is the following:

If the user doesn't define any entity in the type system, I don't need to include the `_entities` field in the root query. 

So, If I go with the approach of having something like: 

```
class Types::QueryType < Types::BaseObject 
  include ApolloFederation::QueryExtension
end 
```

where I include the `_entities` field in the root query, I would need to find a way later on in the evaluation chain to potentially remove it IF the possible types for the Entity type are empty. If not I'm getting an error message indicating that the union type has zero possible types.

I guess I can deal with issues by doing something like this:

```
class Types::QueryType < Types::BaseObject 
  include ApolloFederation::QueryExtension

  define_service_field
  define_entities_field
end 
```

And give the user control on what they want to add.
