### ISSUE TITLE
Prepare proc not invoked with camelized InputObject arguments

### ISSUE THREAD

**Issue by kspector** [rmosolgo/graphql-ruby#2948]
Hey @rmosolgo - we're seeing an odd behavior where `InputObject` arguments are not invoking their provided `prepare` Proc. This behavior seems dependent on the camelization of the arg name. Our `BaseArgument` calls `camelize: false` for all `InputObject` arguments, so efffectively, this prepare proc is _not_ called:

```
 argument :memberId, ID, required: false, camelize: false, prepare: -> (member_id, _ctx) do...
```

while this prepare proc _is_ called:

```
argument :member_id, ID, required: false, camelize: true, prepare: -> (member_id, _ctx) do...
```

We're using rails 5.1.7 with graphql/graphql-pro 1.10.9/1.12.2 - a quick dig into the source code pointed me to [this line](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/input_object.rb#L30), which seemed to be false in the first case (no camelization) and true in the second case (yes camelization)

**Comment by rmosolgo** [comment]
Hey, sorry for the late response and thanks for the detailed report. 

I think the underlying cause is here: 

https://github.com/rmosolgo/graphql-ruby/blob/53f9b9804897a97ec698830012d679680ff65317/lib/graphql/query/arguments.rb#L115-L125

It underscores the configured argument name, regardless of the `camelize:` setting! 😖 

There are two options here: 

1. Make a breaking fix to properly respect the configured name. This would work fine (and there was recently a fix to the Interpreter runtime for a similar bug, https://github.com/rmosolgo/graphql-ruby/pull/2792), but it would _also_ change the key name in hashes passed to fields. 
2. Alternatively, you could help GraphQL-Ruby out by passing `as: :member_id`. That would work around the camelization issue. (example test: 1d1679181)

Personally, I recommend using `as:` in this case. Do you think that'd work for you? 

I'm hesitant to change the existing code in GraphQL::Query::Arguments because personally, I don't use it much anymore. And the thing is, if we change that, you'd have to either update your application code to use `input_object[:memberId]` (since the key would _not_ be underscored) or add `as: :member_id` (to preserve compatibility in with the input hash). 

So, the work-around code would be required even if we changed graphql-ruby's internals 😅 . What do you think, want to give it a try?

**Comment by kspector** [comment]
🙇 thanks for looking at this @rmosolgo - the `as :member_id` solution works fine for us, and is far less strange than the indirect `camelize: true` approach I noted above. I'll close this issue for now, since using `as:` to map camelized input arg names to keys seems like good practice anyway.
