### ISSUE TITLE
Allow Schema To Be Initialized Without Cached Type Information

### ISSUE THREAD

**Issue by netshade** [rmosolgo/graphql-ruby#3006]
**Is your feature request related to a problem? Please describe.**

Currently it appears there is no way to reload a `Schema` to take new factors into account; if a `Schema` is built from a `Traversal`, it will be built with the information that is valid at class load time of the `Traversal`. Runtime changes to any data in the type tree will not be taken into account in the future. This makes it difficult to have the `Schema` change at runtime based on specific events. My use case:

I have a subclass of `GraphQL::Schema::Enum` ( Type hierarchy: `GraphQL::Schema::Enum > Types::BaseEnum > Types::MyEnum` ). This particular subclass overrides `values` and `own_values` to provide a set of enumerated values based on an application runtime config:

```
class Types::MyEnum < Types::BaseEnum

  def self.own_values
    vklass = enum_value_class
    all_values = [
      vklass.new("all", "All of the things", owner: self), 
    ]
    if SomeConstant.include?("some")
      all_values += [
        vklass.new("some", "Just some of the things", owner: self)
      ]
    end
    Hash[all_values.map { |v| [v.graphql_name, v] }]
  end

  def self.values
    own_values
  end

end
```

My assumption based on reading the code would be that the type would be queried for its information any time the `Schema` would be asked to present itself, as well as during validation, etc. Usage shows that these methods are only called once, at file load time, as the `Traversal` is used to populate the `Schema`. I've tried some of the solutions mentioned [here](https://github.com/rmosolgo/graphql-ruby/issues/2225), however, none of them actually allow me to fully unload and reload the `Schema`. I've also used something to bust all the `@graphql_definition` caches ( using `ObjectSpace` ), but that seemed to create its own issues ( `Duplicate type found` ).

( Note: I need this functionality for `test` env, to test various permutations of the `Schema`. I'm aware that usage in `production` would not be advisable. )

**Describe the solution you'd like**

`Schema.reload!` or, barring that, `Schema.to_graphql` would consult the contributing types of the schema and regenerate them fully, rather than relying on information that was only correct at file load time.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by rmosolgo** [comment]
Hey, thanks for the suggestion. It might be possible in 1.11+, when using the new Interpreter runtime (https://graphql-ruby.org/queries/interpreter.html#installation). 

That runtime doesn't require the `.to_graphql` step. It _does_ traverse the type system during boot, because it has to know what types are in the system. But, I don't think the initial traversal includes enum values. I _think_ `enum_type.values` is called once per query in that case, and then the result is cached. 

Are you able to give it a try after turning on the interpreter? I don't think dynamic enum values are actually tested in the gem source, so depending what you find, we might just need to add some test cases to prevent regressions.

**Comment by rmosolgo** [comment]
Let me know if you give this a try with the interpreter & a class-based schema!
