### ISSUE TITLE
OperationStore docs should include deployment sequence notes

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#3067]
In order to release clients using stored operations, you have to: 

- Update the graphql schema and deploy the application, 
- Then, in the client code, sync operations to the newly-updated production server 
- Then, release the new client code which can use those persisted operations 

This isn't clearly called out in the docs yet, but it should be.

**Comment by justin808** [comment]
We've got a mono-repo using https://github.com/shakacode/react_on_rails.

1. Update the graphql schema and deploy the **backend-application** (running graphql ruby server). But we don't want the clients to use the new query ids since they won't exist until the IDs are added to the graphql ruby server. In other words, the client app has new IDs. _Could the new IDs be deterministic? and saved in the github repo? and then during the **release phase** of Heroku, we send the new queries to the DB. We need to ensure the client does not use any queries that are not yet on the server. In a mono-repo, the deploy happens for both the JS client and Ruby server.
2. Then, in the client code, sync operations to the newly-updated production server ==> this is already done in the Heroku release phase?
3. Then, release the new client code which can use those persisted operations ==> problem is that our app is one repo.

**Comment by justisb** [comment]
Another summary of our use-case that @justin808 mentioned:
- We deploy the client and server at the same time (Rails app running graphql-ruby, with frontend using Apollo via Rails' Webpacker in the same app)
- So we can't easily first deploy the backend with the new queries/schema before deploying the new bundles, unless we specifically commit the GQL schema first and deploy it, then commit the frontend JS changes later and deploy it afterwards- a clunky process for our full-stack developers who typically work on the API + frontend at the same time within the Rails app
- This could be solved if the operation IDs could either be 1. Specified by the client during sync, or 2. Are generated predictably, such as a hash of the gql query/mutation template- then the client could already know what the operation ID is going to be before the GQL schema is updated/synced, meaning the operation ID could be included in the JS bundle without talking to the server

**Comment by justin808** [comment]
GQL Change ==> Deploy updated server ===> Build operationStore.json (requires server deployed) ===> Build webpack bundles ==> Deploy client

Could the operationStore.json be stored in the git repo? So that changes to GQL files would always cause a change to some `operationStore.json`, like a change to schema.rb when a migration runs?

**Comment by rmosolgo** [comment]
Thanks for sharing these details about your situation. It sounds like, in the big picture, your system isn't a good match for what the OperationStore was designed for. What it's _for_ is: 

- A GraphQL server, managed in one repo, with its own deployment cycle 
- A client application, managed separately, with its own deployment cycle 

In that case, server support is _required_ to precede any client feature built on new GraphQL APIs. First, you'd add support to the server and release it. Then you'd add support to the client and release it. (Maybe you'd develop them simultaneously, but the releases would have to be sequential.)

However, in your case, it sounds like there's a GraphQL server and a client application which managed in the _same deployment cycle_. How could the OperationStore fit in there? I can basically think of two options: 

1. Even though the frontend and backend are in the same repository, split the deployment into two parts: first deploy the server, then sync operations and deploy the frontend. (That's what I described in the OP.) 
2. Try to integrate them into a single process which deploys the server process, syncs operations to the newly-deployed server process, then deploys the frontend. 

Although the second possibility might be _easier_, it presents some serious technical hurdles: 

- What happens when the client-server communication (syncing operations) _fails_? Do you roll back the deploy (including the server process?)? You can't _continue_ the deploy, because the frontend wouldn't have its operation IDs. If it was me, I wouldn't want to introduce that step into deploys because of weird ways it could fail (or prevent deploys when there's a production issue). 
- You mentioned using Heroku, and that shows the problem with deterministic deploys. If the deploy step involves writing new data to disk, then the code in the repo won't match what you deployed, and there's no guarantee that two deploys of the same git sha would actually end up running the same code on the server. (And if I understood right, Heroku specifically prohibits this by using fixed "slugs", right?) 

So although the first step requires more work to deploy, the separation of server support from client consumption makes deployment much simpler. 


That said, in your case, I could recommend two options: 

- Instead of using OperationStore, you could use Apollo-style persisted queries, where the client sends the full query the first time, but uses operation IDs after that (https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries). It has different trade-offs than OperationStore; most notably, you have to accept arbitrary queries in production. But if that's not a problem, you might look into it. 
- Roll your own filesystem-based OperationStore. Instead of reading stored queries from the database, read them from the project's files, for example:

  ```ruby 
  # app/controllers/graphql_controller.rb 
  graphql_query = if params[:static_operation_name].present? && params[:static_operation_name] =~ /[A-Za-z]/
    # use `params[:static_operation_name]` to name a file on disk, only allow letters
    filename = Rails.root.join("app/assets/graphql/static_operations/", "#{params[:static_operation_name}.graphql")
    # build up a cache as the application runs, TODO extract this
    @@static_operation_cache ||= {}
    if @@static_operation_cache.key?(filename)
      @@static_operation_cache[filename]
    elsif File.exist?(filename)
      @@static_operation_cache[filename] = File.read(filename)
    else
      # Don't set `@@static_operation_cache[filename]` in this case to avoid unbounded hash growth  
      nil 
    end
  else 
    params[:query]  
  end 
  ```

  That way, whenever you deploy production, the newly-running Ruby code would have everything it needs to server requests to newly-deployed client. 

  One big downside there is, any _previously-deployed_ JavaScript code that's still running in someone's browser would start getting _newly-deployed_ GraphQL operations from disk. You could mitigate this by adding version folders (manual or sha-based) or by making sure to only make _additive_ changes to existing static operations. When you have to make a breaking change, make sure you make a new file for it. 

  (Fun fact, an early GraphQL-Pro version had a feature called "GraphQL::Pro::Repository" which basically did this. It's probably still in the source, although to my knowledge, nobody ever used it!) 

What do you think of those approaches?

**Comment by haritonov2** [comment]
Thank you @rmosolgo for different options and detailed explanation. 

It looks like we have figured out the best way of how to deploy a client-side and a server-side in one deployment flow on Heroku (one PR).

[GraphQL OperationStore](https://graphql-ruby.org/operation_store/overview) generates `operationStore.json` file with structure:

```
{
	["queryName"]: ["operationHash"]
}
```

Example:

```
{
	"createUser": "ef4ab977b72bd75d7753e3102c348385"
}
```


The client-side uses this json to get "operationHash" by a query name. "operationHash" is generated based on a graphql query file body. "operationHash" will be the same if we don't touch a graphql file. It allows us to add "operationStore.json" file and commit all changes in the file.

Heroku deploy consists of two phases:
1. Build (a slug build)
2. Deploy (Release phase with deploy of the slug)


The build phase prepares a client-side bundle file that has `operationStore.json` file from the repository. We can't run a usual release phase and deploy it. The database does not have updated GraphQL operations new hashes. If a client tries to request a graphql query by a new "operationHash", a server-side returns an error message.

The deploy phase helps us to add new operation hashes to the database. Heroku release phase (a part of the deploy phase) allows running any command in the slug container.

Instead of:
* divide work to a client-side PR and a server-side PR;
* deploy the server-side PR. PR changes should be public because the application "/dashboard/sync" endpoint is used for adding operation hashes with query bodies to the database
* deploy the client-side PR
* synchronize the client-side graphql query with operation hashes (add it to the database)

We run "rails server" with new graphql server-side changes in the slug container. The rails server establishes the connection to the database of the public application. With "graphql-ruby-client" npm package, we add new graphql queries with operations hashes to the database through the localhost.

In the case of synchronization success, Heroku deploy phase releases the slug and makes it public.
If the synchronization returns an error, the deploy phase will be terminated and the slug won't be released.

With this flow, we can create just one PR for graphql changes in the client and server sides. These changes will be released with one deploy and without the application downtime.

**Comment by rmosolgo** [comment]
Thanks for sharing what you found here! If I hear other folks working through a situation like this, I'll consider adding it to the docs. In the meantime, if anyone else ends up using a flow like that, please let me know :+1:
