### ISSUE TITLE
Adding mutation or query instance to GraphQL::Query::Context

### ISSUE THREAD

**Issue by LucDelmon** [rmosolgo/graphql-ruby#3077]
Hi,

I have been running in a little problem while trying to use the GraphQL::Query::Context in mutations.

In this basic case. 

```
module Mutations
  class MyMutations < GraphQL::Schema::Mutation

    null false

    argument :name, String, required: true, prepare: ->(name, ctx) {
      # logic
      # being able to call instance.raise_specific_execution_error
    }

    def resolve(attributes)
      # logic
      raise_specific_execution_error
    end

    def raise_specific_execution_error
      raise ::GraphQL::ExecutionError.new('...')
    end
  end
end
```

I haven't been able to find my mutation instance or even class name in the GraphQL::Query::Context under ctx. But since at some point `instance.resolve` is called, this must be possible somehow.

The only hack I found was to inject it in the `ready?` function which is called before anything else
```
argument :name, String, required: true, prepare: ->(name, ctx) {
      # logic
      ctx[:mutation_instance].raise_specific_execution_error
    }

def ready?(_attributes)
   context[:mutation_instance] = self
end
```

but I know that this is not the goal of the `ready?` method at all !

I was wondering if you could direct me towards the way to my mutation instance from the context (maybe in context.query ?) or if you see a way to always have it referenced in my context (maybe with a  custom context https://graphql-ruby.org/schema/definition.html#context-class ?)

**Comment by rmosolgo** [comment]
Hi, great question and thanks for the detailed writeup. 

There's no way to access the mutation instance from `ctx`. That context contains query-level info, but not a reference to the currently-executing field or mutation. A work-around like the one you posted would be your best bet if you really need it. 

Alternatively, you might be able to change the way you build the error you're raising. For example, instead of building it inside `raise_specific_execution_error`, you could make a subclass of `GraphQL::ExecutionError`, like: 

```ruby 
class SpecificExecutionError < GraphQL::ExecutionError 
  # ... 
end 
```

And raise it by name, wherever you need it. 


Anyways, hope that helps! 

(Interesting trivia -- GraphQL-Ruby _used to_ create a custom "context" object for every field that was executed, and those objects had a `ctx.field` method to get the current field. That approach was very handy sometimes, but it added a lot of overhead and really hurt performance when building large responses. So now, `ctx` is one object, passed into every field.)

**Comment by LucDelmon** [comment]
Thanks for the answer.

your proposition could work on my `prepare` block but I also need it in the Schema.object_from_id  method and I can't be specific in that one since its defined once.

Thanks for the quick answer. It's useful to know that I will not be able to find the instance. Saves me a lot of searching time.
