### ISSUE TITLE
Better Error Handling For Required Arguments

### ISSUE THREAD

**Issue by kaka-ruto** [rmosolgo/graphql-ruby#3082]
**Is your feature request related to a problem? Please describe.**

When arguments are specified as `required: true`, GraphQL fails to execute and throws an unfriendly error when that argument is not provided.

For example

```
#<GraphQL::Query::Result @query=... @to_h={"errors"=>[{"message"=>"Variable $input of type PackageDeliveryAttributes! was provided invalid value for recipientId (Expected value to not be null)", "locations"=>[{"line"=>1, "column"=>10}], "extensions"=>{"value"=>{"quantity"=>2, "warehouseId"=>1, "packageId"=>1, "driverId"=>2, "recipientId"=>nil, "recipientOrganizationId"=>2}, "problems"=>[{"path"=>["recipientId"], "explanation"=>"Expected value to not be null"}]}}]}>
```

**Describe the solution you'd like**

When the same argument is changed to `required: false` and the argument is not provided, the error returned is very friendly and can actually be shown the user. This is because the validation will be done at the model or database level and the relevant error returned, for instance with `validates :recipient_id, presence: true` in Rails

For example 

```
#<GraphQL::Query::Result @query=... @to_h={"data"=>{"createPackageDelivery"=>{"packageDelivery"=>nil, "message"=>nil, "errors"=>["Recipient must exist"]}}}>
```

It would be nice if, in the same way, regardless of the flag `required`, that a friendly error that can be shown to the user is returned

**Describe alternatives you've considered**

When the error is likely to be caused by the user, I have considered changing the flag to `required: false` even though the argument is actually required. 

This way, I can catch the error and propagate it up to the user.

**Comment by rmosolgo** [comment]
Hi, sorry I missed this when you first reported it! 

I think `required: false` is your best bet here. `required: true` is a GraphQL semantic, and the error is handled at GraphQL-level. There's no way to currently customize that message. 

However, that feature _could_ be added. The message described above is currently created here: 

https://github.com/rmosolgo/graphql-ruby/blob/377fd26bde60757d2fbd05f65191a70c4004bce8/lib/graphql/static_validation/rules/argument_literals_are_compatible.rb#L50

`arg_defn`, in scope there, is a `GraphQL::Schema::Argument` instance. Instead of hardcoding the message above, the code be refactored to: 

- Move the message into a method like `GraphQL::Schema::Argument#invalid_value_message(...)`
- Call that method from the validation rule instead of using a hardcoded string 

That way, you could override the message logic in your own base Argument class. 

I don't have plans to work on that, but I'd be happy to help out by reviewing a PR if someone wants to give it a try.
