### ISSUE TITLE
Relay NodeField problem after upgrade

### ISSUE THREAD

**Issue by sayduck-daniel** [rmosolgo/graphql-ruby#3088]
I just upgraded the gem from`1.10.3` to `1.11.3` and my NodeField implementation stoped working.

I'm getting a bit confused how to add my field to the orphan_types. This is what I have that was working:

```ruby
# frozen_string_literal: true

module FieldTypes
  NodeField = BaseField.new(
    name: 'node',
    owner: nil,
    type: GraphQL::Types::Relay::Node,
    null: true,
    relay_node_field: true
  ) do
    argument :id,
             GraphQL::Types::ID,
             required: true

    def resolve(_obj, args, ctx)
      ctx.schema.object_from_id(args[:id], ctx)
    end
  end
end
```

```ruby
# frozen_string_literal: true

module FieldTypes
  class BaseField < GraphQL::Schema::Field
    def resolve_field(object, arguments, context)
      resolve(object, arguments, context)
    end
    # ...
  end
end
```

```ruby
module Types
  class QueryType < BaseObject
    add_field FieldTypes::NodeField
  end
end
```

All our types depend on:

```ruby
# frozen_string_literal: true

module Types
  class BaseCustomObject < BaseObject
    implements GraphQL::Relay::Node.interface
    connection_type_class ConnectionTypes::BaseConnection
    global_id_field :id

    field :uuid,
          ID,
          null: false

    field :created_at,
          ScalarTypes::DateType,
          null: false

    field :updated_at,
          ScalarTypes::DateType,
          null: false
end

```

In short, any idea how I could fix it?

related issue: https://github.com/rmosolgo/graphql-ruby/issues/2918

**Comment by sayduck-daniel** [comment]
@rmosolgo any ides for this scenario perhaps?

**Comment by rmosolgo** [comment]
> my NodeField implementation stopped working

What does it do, now that it stopped working? Does it return a GraphQL validation error? Does it raise an error in Ruby? Does it return the wrong value? Does the program crash before the GraphQL schema is even created?

**Comment by sayduck-daniel** [comment]
My bad. 

The `node(id:)` disappeared from my `QueryType`. I get the standard `can't find field node on query type`

**Comment by sayduck-daniel** [comment]
@rmosolgo actually its very similar to #2918 but I can't figure how to apply your proposition

**Comment by rmosolgo** [comment]
In that other issue, the problem was two things "working together": 

- If an interface doesn't have any implementers, graphql-ruby hides it from the schema
- If a field's return type is hidden, the field is hidden 

So, when there are no implementers of `Node` in the schema, then the `node` field is removed. 

To fix this, find (or create) an object type that implements `Node`. (In your case, a subclass of your BaseCustomObject should work.) Then, use `orphan_types` to attach that object type to the schema (https://graphql-ruby.org/type_definitions/interfaces.html#orphan-types). 

After that, `node` won't be hidden anymore (🤞). 

If it's still hidden, you could try switching `GraphQL::Relay::Node.interface` for `GraphQL::Types::Relay::Node`. I would have expected graphql-ruby to throw a descriptive error if it had a hard time with those two ways of referencing the `Node` interface, but maybe it's messing up 🙈 . 

Also, you might simplify the situation by defining `field :node ...` right inside `class QueryType` instead of a separate constant. (Is there any advantage to defining the field separately?) 

If that doesn't work, you could try replicating the issue in a stand-alone Ruby file. Then, you could share that file here, so I can debug further.

**Comment by sayduck-daniel** [comment]
Hum, @rmosolgo I was missing something on my code above.

If you add `use GraphQL::Execution::Interpreter` and `use GraphQL::Analysis::AST` then you get:

```ruby
{
  "errors"=>[
    {
      "message"=>"Field 'node' doesn't exist on type 'Query'",
      "locations"=>[
        {
          "line"=>1,
          "column"=>7
        }
      ],
      "path"=>[
        "query",
        "node"
      ],
      "extensions"=>{
        "code"=>"undefinedField",
        "typeName"=>"Query",
        "fieldName"=>"node"
      }
    }
  ]
}
```
Hope this can help you figure this out.

**Comment by rmosolgo** [comment]
Yes, that's really helpful, thanks. I copied your script and replicated the issue just like you said. Then I made these changes to make it work: 

1. Rename `def resolve_field` to `def resolve` (the interpreter uses `resolve` instead of `resolve_field`. For some reason, the Rails generators added this method to the base field, but it's really not part of GraphQL-Ruby's public API 🤷.) 

  ```diff 
  -   def resolve_field(_object, arguments, _context)
  +   def resolve(_object, arguments, _context)
  ```

2. Rename `GraphQL::Relay::Node.interface` to `GraphQL::Types::Relay::Node`:

  ```diff 
  -   implements GraphQL::Relay::Node.interface
  +   implements GraphQL::Types::Relay::Node
  ```

Here's the full script:

<details>
<summary>Modified script</summary>
<p>

```ruby
# frozen_string_literal: true

require 'graphql'

NodeField = GraphQL::Schema::Field.new(
  name: 'node',
  owner: nil,
  type: GraphQL::Types::Relay::Node,
  null: true,
  relay_node_field: true
) do
  argument :id, GraphQL::Types::ID, required: true

  def resolve(_object, arguments, _context)
    {
      id: arguments[:id],
      foo: :bar
    }
  end
end

class BaseNodeObject < GraphQL::Schema::Object
  implements GraphQL::Types::Relay::Node
end

class ObjectType < BaseNodeObject
  field :id, ID, null: false
  field :foo, String, null: false
end

class QueryType < GraphQL::Schema::Object
  add_field NodeField
end

class Schema < GraphQL::Schema
  query QueryType
  orphan_types ::ObjectType

  def self.resolve_type(*)
    ObjectType
  end

  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
end

query = 'query{node(id: 1){...on Object{id foo}}}'

p GraphQL::VERSION
p Schema.execute(query, context: {}, variables: {})
```

</p>
</details>

And the result I get is: 

```
 $ ruby test.rb
"1.11.1"
#<GraphQL::Query::Result @query=... @to_h={"data"=>{"node"=>{"id"=>"1", "foo"=>"bar"}}}>
```

I think what's going on is: 

- In 1.11+, the Interpreter doesn't work with legacy (`.define`-based) type definitions anymore 
- GraphQL::Relay::Node.interface is a `define`-based legacy type ([source](https://github.com/rmosolgo/graphql-ruby/blob/e7623c3edbf33fbf53c4b7cbc1acf064bd809f29/lib/graphql/relay/node.rb#L30-L33))
- The Interpreter is _supposed_ to raise an error when it encounters and unsupported type definition, but it _doesn't_ in this case 😖 . I bet it's because it found `GraphQL::Types::Relay::Node` _first_, and registered it, and then when it found `GraphQL::Relay::Node.interface`, it recognized that it was derived from the already-found `GraphQL::Types::Relay::Node` and _ignored_ it, rather than raising an error. 


Practically speaking, I probably don't have the bandwidth to hunt down and test a patch for this. But I think the error is here: 

https://github.com/rmosolgo/graphql-ruby/blob/e7623c3edbf33fbf53c4b7cbc1acf064bd809f29/lib/graphql/schema.rb#L1912-L1917

See how it checks if the interface is a `Module`, but silently skips any other kind of interface? I think that means that `GraphQL::Relay::Node.interface` is being skipped. If there was an `else` clause that raised an error, it probably would have caught this issue. 

Hope that helps. Please let me know if the diff I posted above doesn't fix it for you!
