### ISSUE TITLE
Convert `pageInfo` field of connection to underscore

### ISSUE THREAD

**Issue by hoangmirs** [rmosolgo/graphql-ruby#3105]
Do you offer any options to convert `pageInfo` field to underscore?

![GraphiQL](https://user-images.githubusercontent.com/7344405/91037287-f1573900-e632-11ea-93a9-81b7fa65deb5.png)

**Comment by rmosolgo** [comment]
If you're using the built-in connection support, then you'll get camelCase field names. 

If you want underscored field names, I recommend defining a PageInfo type in your application, and making a custom connection type class that uses your custom PageInfo type. Then hook up your connection type class to your other base classes, so all generated connection types will use your custom base class.

You'd use `connection_type_class`, as shown here: https://graphql-ruby.org/type_definitions/extensions.html#customizing-connections, but you don't want to use `GraphQL::Types::Relay...`, because those classes have camelized field names.

Hope that helps! If you run into trouble, please share the classes that you define and how you connect them to your other base classes, and tell me what went wrong when you tried it.
