### ISSUE TITLE
Field#authorized? does not raise an error when false

### ISSUE THREAD

**Issue by aaronmallen** [rmosolgo/graphql-ruby#3131]
**Describe the bug**

extended field `authorized?` doesn't raise execution error when false

**Versions**

`graphql` version: `1.11.4`
`rails` (or other framework): `6.0.3.2`

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
class RequiresCurrentUserExtension  < GraphQL::Schema::FieldExtension
  def apply
    field.define_singleton_method(:authorized?) do |_object, _args, context|
      context[:current_user].present?
    end
  end
end

class QueryType < GraphQL::Schema::Object
  field :me, UserType, 'The current authenticated user', null: true, extensions: [RequiresCurrentUserExtension]

  def me
    context[:current_user]
  end
end

class MySchema < GraphQL::Schema
  query(QueryType)

  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
  use GraphQL::Pagination::Connections

  def self.unauthorized_field(error)
    Rails.logger.error 'I am called!'
    super
  end
end

class GraphqlController < ApplicationController
  ...

  private

  def context
    @context ||= { current_user: nil }
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  me { id }
}
```

```json
{
  "data": {
    "me": null
  }
}
```

**Steps to reproduce**

1. Extend a field with the code illustrated above.
2. Verify that the method returns false

```ruby
irb(main):001:0> field = QueryType.fields['me']
=> #<Type::BaseField:0x000055d3b6012838 @original_name=:me, @underscored_name="me", @name="me", @description="The current authenticated user", @field=nil, @function=nil, @resolve=nil, @deprecation_reason=nil, @method_str="me", @method_sym=:me, @resolver_method=:me, @complexity=1, @return_type_expr=Type::Output::UserType, @return_type_null=true, @connection=false, @has_max_page_size=false, @max_page_size=nil, @introspection=false, @extras=[], @broadcastable=nil, @resolver_class=nil, @scope=nil, @trace=nil, @relay_node_field=false, @relay_nodes_field=false, @ast_node=nil, @method_conflict_warning=true, @owner=Type::Output::Root, @subscription_scope=nil, @extensions=[#<Extension::RequiresCurrentUser:0x000055d3b6011348 @field=#<Type::BaseField:0x000055d3b6012838 ...>, @options={}>]>

irb(main):002:0> field.authorized?({}, [], {})
=> false
```
3. execute the query outlined above.

**Expected behavior**

The error for an unauthorized field should be returned

**Actual behavior**

`MySchema.unauthorized_field` is never called and the expected authorized response is returned with a null value.

**Comment by aaronmallen** [comment]
As an aside... I have to be doing this wrong right?  Is there no way to set custom authorization on a field without defining a custom field class?  Not all fields on this particular class require the same authorization steps.

**Comment by aaronmallen** [comment]
Also I did go ahead and confirm the following also reproduces the bug:

```ruby
module Type
  module Field
    class AuthorizedUserField
      def authorized?(_object, _args, context)
        context[:current_user].present?
      end
    end
  end
end

module Type
  module Output
    class Root < Type::BaseObject
      graphql_name 'QueryRoot'
      
      add_field(
        Type::Field::AuthorizedUserField.from_options(
          :me,
          UserType,
          'The current authenticated user',
          null: true
        )
      )

      def me
        context[:current_user]
      end
    end
  end
end

class MySchema < GraphQL::Schema
  mutation(::Mutation::Root)
  query(::Type::Output::Root)

  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
  use GraphQL::Pagination::Connections

  def self.unauthorized_field(error)
    Rails.logger.error 'I am called!'
    super
  end 
end

class GraphqlController < ApplicationController
   ...

  private
 
  def context
    @context ||= { current_user: nil }
  end
end
```

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed writeup. It looks like there are a few things to address here...

- > `authorized?` doesn't raise execution error when false

  It sounds like it's behaving as intended. From the [Authorization Guide](https://graphql-ruby.org/authorization/authorization.html#handling-unauthorized-objects): 

  > By default, GraphQL-Ruby silently replaces unauthorized objects with `nil`

  If you want it to raise an error, add `raise GraphQL::ExecutionError, ...` as shown in that guide. 

- > `MySchema.unauthorized_field` is never called 

  That's odd, I extracted your replication into a stand-alone file (no Rails) and it worked as expected for me. Here's the script: 

  <details>
  <summary>Schema with unauthorized field</summary>
  
  <p>

  ```ruby  
  # auth_test.rb
  require "graphql"

  class AuthorizedUserField < GraphQL::Schema::Field
    def authorized?(_object, _args, context)
      !!context[:current_user]
    end
  end

  class QueryType < GraphQL::Schema::Object
    add_field(
      AuthorizedUserField.from_options(
        :me,
        String,
        'The current authenticated user',
        null: true
      )
    )

    def me
      "It me"
    end
  end

  class MySchema < GraphQL::Schema
    query(QueryType)

    use GraphQL::Execution::Interpreter
    use GraphQL::Analysis::AST
    use GraphQL::Pagination::Connections

    def self.unauthorized_field(error)
      pp 'I am called!'
      super
    end
  end

  pp GraphQL::VERSION
  pp MySchema.execute("{ me }")
  ```

  </p>
  </details>

  I get: 

  ```
  $ ruby auth_test.rb
  "1.11.1"
  "I am called!"
  #<GraphQL::Query::Result @query=... @to_h={"data"=>{"me"=>nil}}>
  ```

  Which looks like the expected behavior to me: 

  - `.unauthorized_field` is called, it outputs "I am called!"
  - The unauthorized value (`"It me"`) is not in the response; instead, it's `nil`

  Does that script output the same thing for you? 


- >  Is there no way to set custom authorization on a field without defining a custom field class?

  Don't forget, a single method can be the entrypoint for lots of different behavior. For example, if you wanted fields to have optional `context[:current_user].present?` checks, you could setup your base field like this: 

  ```ruby 
  class Types::BaseField < GraphQL::Schema::Field 
    def initialize(*args, **kwargs, require_logged_in: false, &block)
      @require_logged_in = require_logged_in 
      super(*args, **kwargs, &block)
    end 

    # Check for `context[:current_user]` if this field was configured with `require_logged_in: true`
    def authorized?(_obj, _args, ctx)
      @require_logged_in == false || ctx[:current_user].present? 
    end 
  end 
  ```

  Then you could opt in to checks when defining fields: 

  ```ruby 
  field :me, Types::UserType, null: true, require_logged_in: true 
  ```

  Beyond that, you could use `def authorized?` to call out to some kind of authorization system or convention, depending how much flexibility you need. 

Does that help?

**Comment by aaronmallen** [comment]
@rmosolgo **yes** that is **super** helpful thank you.  I missed the `nil` bit in that doc and think I hyper focused on the code block and expected that to be the default behavior and I do apologize for the invalid bug report.
