### ISSUE TITLE
Converting incoming ID to integer?

### ISSUE THREAD

**Issue by Aryk** [rmosolgo/graphql-ruby#3132]
Is there any "best practice" for converting ID types coming into the APi as integers. 99% of the time you want the incoming "strings" to be converted to an integer since these are ids in your database.

Obviously...we can do it manually, just curious if there was a non-hacky way to do it with the library.

**Comment by rmosolgo** [comment]
The built-in `ID` type is an implementation of [the spec](http://spec.graphql.org/draft/#sec-ID), so it always uses strings.

But, you could use a [custom scalar](https://graphql-ruby.org/type_definitions/scalars.html#custom-scalars) for this, for example: 

```ruby 
class Types::DatabaseId < GraphQL::Schema::Scalar 
  description "A numeric ID, transported as a String." 

  def self.coerce_input(val, ctx)
    val.to_i 
  end 

  def self.coerce_result(val, ctx)
    val.to_s
  end 
end 
```

Then, any argument or field using that type would convert incoming strings to integers, and any outgoing integers would be converted to strings. 

If you wanted to replace the built-in ID type, you could even do that. Just rename the type above to `Types::ID`, and use that in your schema instead of the built-in `ID`. 

Hope that helps! Let me know if you give it a try and run into any trouble with it.

**Comment by Aryk** [comment]
I needed the same graphql type name, so I just subclassed. So far seems to be working so long as I don't also use Graphql::Types::ID
```ruby
class Types::ModelId < GraphQL::Types::ID

  def self.coerce_input(val, ctx)
    val.to_i
  end

end
```
