### ISSUE TITLE
Skip timeout check on subscriptions

### ISSUE THREAD

**Issue by sayduck-daniel** [rmosolgo/graphql-ruby#3162]
We introduce a timeout off 20 seconds for our queries with the instruction `GraphQL::Schema::Timeout`. 

We ran into an edge case where we need to retrieve a bigger tree. We proceeded to move the `query` to a `subscription`. The logic behind is to queue a Worker to get the data and format, and stream back data to the client. We encounter the problem that `GraphQL::Schema::Timeout` applys to the `subscription` result as well. 

Is there a way for us too skip timeouts for `subscripton`?

As a side question, would the `defer` be a good solution and perform better than this approach?

**Comment by rmosolgo** [comment]
It's not possible as implemented, because `GraphQL::Schema::Timeout` doesn't look at the current `query` when determining `max_seconds`: 

https://github.com/rmosolgo/graphql-ruby/blob/8b77c12a105066a80e4827cc86cab518d55c20e3/lib/graphql/schema/timeout.rb#L52

But, I've just opened #3163  to improve that. 

> `defer` 

I don't think defer would allow overriding the timeout, it just changes the order of execution/delivery within that timeout window.

**Comment by sayduck-daniel** [comment]
> It's not possible as implemented, because GraphQL::Schema::Timeout doesn't look at the current query when determining max_seconds.

I'm not sure to understand. Are you saying `subscription` timeouts are by design. Therefore I can't avoid it at the moment?

> I don't think defer would allow overriding the timeout, it just changes the order of execution/delivery within that timeout window.

Regarding the `defer` my question was: If we upgrade to graphql-pro, and we would use a query with defer, would the defered "result" trigger a timeout as well?

**Comment by rmosolgo** [comment]
> would the defered "result" trigger a timeout as well?

Yes, I _think_ so (although I haven't tested 🙈 ). From an implementation standpoint, `defer` basically injects hooks for sending half-baked execution results. I expect it would still be subject to the same timeout. (IMO that makes sense -- `defer` still consumes server time, so I'd want my timeout to prevent clients from consuming too much server time.) 

> `subscription` timeouts are by design

I wouldn't say "by design", but I'd say, a shortcoming of the current implementation is that _all operations_ in a given schema are subject to the same timeout. Query, mutation, subscription, whatever -- the schema has a static number which is applied to everything it executes. 

I'm adding #3163 to support custom logic for picking a timeout on an operation-by-operation basis. (So, if you didn't want timeouts to apply to subscription updates at all, you could say `query.subscription? ? false : super`.)

**Comment by sayduck-daniel** [comment]
> IMO that makes sense -- defer still consumes server time, so I'd want my timeout to prevent clients from consuming too much server time.)

From a resources point of view it makes sense. We use it because our Heroku app will have its Heroku router triggering a `H-12 timeout` error after 30 sec of execution (but still let the server continue executing its code - it is just a middleware error it returns). So for us, we need a Timeout only on what is synchronous.

Thanks for the fix.
