### ISSUE TITLE
[PRO] graphql-batch and pundit scope

### ISSUE THREAD

**Issue by thornomad** [rmosolgo/graphql-ruby#3186]
We are using both the pro Pundit integration and graphql-batch; when a relation has been batched, the policy `Scope` is not called.  If we remove any batching, of course, the scopes are respected.

I haven't dug into it much yet, but thought I would just reach out for some help before I spend too much time on it: is there a best practice for getting graphql-batch and the pro pundit integration to work nicely together? 

Thanks in advance.

**Comment by rmosolgo** [comment]
Hey, sorry to hear it doesn't work! I would have expected promises to Just Work :tm: since https://github.com/rmosolgo/graphql-ruby/pull/3070. I also added another test in af617b985 to make sure list scoping properly waits for promises.

I wonder if it's because, inside the promise, the relation is being turned into an Array? There's a known limitation of the Pundit integration when it comes to arrays, described here: https://graphql-ruby.org/authorization/pundit_integration.html#scopes and a proposed work around (item number 1) here: https://github.com/rmosolgo/graphql-ruby/issues/3173#issuecomment-702736339

Can you add some `puts` debugging to check, at the end of the promise, is the object still an `ActiveRecord::Relation`, or has it been converted into an Array? 

A couple other thoughts: 

- Could you share the code that returns a promise-wrapped relation (batch loader and/or field)? Maybe it will yield some clues. 
- If you implement `def self.scope_items(items, ctx)` on the object type that you _expect_ to be scoped by Pundit, is it called? If you add `puts items`, what do you get there? 

Let me know what you find!

**Comment by thornomad** [comment]
So you are spot on: **my loader in this case is returning an Array**.  And I can understand how that would cause problems now that you have pointed it out.  

My brain though, is not landing on a way to do this _without_ converting them to an array and still achieve the N+1 performance glory I seek.  What I have is a little more complicated but here is the watered down version of a loader for has many relationships:

```ruby
module Loaders
  class HasManyLoader < Loaders::BaseLoader
    def initialize(model, foreign_key)
      @model = model
      @foreign_key = foreign_key
    end

    def perform(foreign_key_ids)
      results = @model.where(@foreign_key => foreign_key_ids)

      foreign_key_ids.each do |id|
        matches = results.select { |result| id == result.send(@foreign_key) }
        fulfill(id, matches)
      end
    end
  end
end

# used like:
Loaders::HasManyLoader.for(Person, :foreign_key_id).load(object.id)
```

This translates into a single database call of `Person.where(foreign_key_id: [all_those_ids])`.  But, the `select` call turns it into an array before parsing them back out.

If I change the fulfill block to this:

```ruby
      foreign_key_ids.each do |id|
        fulfill(id, results.where(@foreign_key => id))
      end
```
Then, as you _promised_, the scope is being called.  But this is destroying the N+1 mastery.

Is there some Rails magic that lets me both perform a single where query and break that query up into smaller relations?  This is all still a bit of learning for me.  Thanks!

**Comment by rmosolgo** [comment]
> ```ruby
> results = @model.where(@foreign_key => foreign_key_ids)
> # ...
> results.select { ... }
> ```

It looks like, given that code: 

- A set of objects will be loaded by foreign key 
- The _entire_ set will be loaded into memory when `select` is called  

That means that any "post-processing" on the list of loaded objects will have to be performed on the resulting Array. For example: 

- Pagination will happen _after_ the database query -- the _Array_ will be paginated after a complete load from the database
- Any authorization-related filtering will happen _after_ the database query 

AFAIK, there's no way to get database-level filtering _and_ batch loading. For example, consider this query: 

```
query {
  a1: author(id: $id1) { books(first: 20) { ... } }
  a2: author(id: $id2) { books(first: 50) { ... } } 
}
```

Either, you could run a batched query: 

```sql
SELECT * FROM books WHERE author_id IN(:id1, :id2)
```

And then, in Ruby, split the results by `author_id` and apply `first: 20` to part of the result and `first: 50` to another part of the result. 

Or, you could run two queries: 

```sql 
SELECT * FROM books WHERE author_id = :id1 LIMIT 20 
SELECT * FROM books WHERE author_id = :id2 LIMIT 50 
```

In that case, `first: ...` is applied at database-level. 

Which one of those will perform better? It depends. If `author(id: $id1)` has written a million books, then the first implementation will be terrible, because it will load all million records into Ruby and then throw away all but the first twenty. But if the author only has 15 books, then maybe the first implementation is better. 

Personally, I've always worked with the _second_ implementation, where has-many type queries are always executed separately. (I haven't even used batch loaders with them because they're so hard to batch-load properly when scopes are applied. How would the example above change if the list of books was scoped by permission, unless the viewer is the author? Tough!) 

I've heard of batching has-manys using Postgres window functions: https://pganalyze.com/blog/efficient-graphql-queries-in-ruby-on-rails-and-postgres . But I've never used Postgres for work, and I've never actually tried that approach.

**Comment by thornomad** [comment]
> AFAIK, there's no way to get database-level filtering and batch loading

Yea, hmm.  All right I will see about inserting some of those Pundit checks myself where needed.  Your explanations have been very helpful.  Thanks again for your time and effort.  Will have a close look at that article as well.  Onward!
