### ISSUE TITLE
Subscriptions are high risk for accidental data exposure

### ISSUE THREAD

**Issue by bmulholland** [rmosolgo/graphql-ruby#3209]
In any multi-user app that pushes information to individual users via subscription, the current implementation makes it easy to shoot yourself in the foot. If any developer ever forgets to pass the `scope` to a subscription trigger, graphql-ruby will happily send that update to _everyone_. There is no way to require scope to be set every time, and no way to double check that the user is authorized to receive that update.

Since the update will work as expected in the happy path, it will easily be missed by manual and automated testing: checking the "no update for another user" case requires conscious testing (automated or manual) on every individual subscription trigger. However, if one forgets to scope the subscription trigger, then it's almost certain they're not thinking to do that testing. Your QA team, if you have one, should catch this, but even they are uncomfortable with being the only backstop for a potential data exposure bug.

The existing subscription `authorize?` check doesn't inspect individual objects that are triggered. Even GraphQL Pro has no enhanced guarantees for subscription scope, such as from CanCan or Pundit.

**Describe the solution you'd like**

Anything that will blow up if this mistake is being made.

Some options that immediately come to mind:
1. If `subscription_scope` is set, require that any trigger include the scope. Non-breaking variation: add `subscription_scope` parameter to require this, default false.
2. Add an `authorize?` check for each individual subscription object.
3. An authorization-like filter method, such that a subscription trigger can be set to "everyone," with the filter defining who actually gets the subscription notification for that object.

#3 is actually my favourite, because then I don't need to pass in current_user to every subscription trigger. In that case, I'd write a simply filter method `object.user == context[:current_user]` that I could both test and trust at the subscription level (not the subscription trigger level).

Let me know if any of these approaches would be considered and I'll see if I can submit a PR.

**Describe alternatives you've considered**

Of course everything works as-is, so I can continue using the library, but it makes me uncomfortable. I work with sensitive data that, if exposed, could kill the company, so doing nothing isn't an option.

I'll probably write a wrapping service object that requires the user to be set, set the scope in there, and add a big scary warning never to copy the direct subscription trigger call. This mitigates, but does not remove, the risk.

As a small team, this workaround is okay. But if I was at a large company using GraphQL (the ones who are most likely to pay for Pro), I would be exponentially more uncomfortable, and this service on its own wouldn't be sufficient.

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed writeup including those suggestions. I definitely agree with your point, that it's easy to accidentally send data to the wrong client. A couple of quick thoughts: 

> If `subscription_scope` is set, require that any trigger include the scope. 

I think that's a great suggestion. I like the idea of changing the default behavior to be: 

- If `subscription_scope: ...` is configured, then: 
  - All subscriptions to that field must have a non-nil value at the configured `context[...]` key
  - All triggers to that field must have a non-nil value given as `scope:` 
- `allow_nil_subscription_scope: true` can be configured to retain the previous default behavior 

That way, at least you'd know GraphQL-Ruby was _helping_ you do the right thing, instead of silently failing when it didn't receive the expected data. 


> The existing subscription `authorize?` check doesn't inspect individual objects that are triggered.

I'd like to learn what you mean by that. The _intended_ behavior is to call `def authorized?` on subscriptions before the initial subscription and before each update. Here are the specs for that: 

- Initial subscription: https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/schema/subscription_spec.rb#L295-L314
- Before update: https://github.com/rmosolgo/graphql-ruby/blob/4fdfd1fd9e02c5d59ba9209003576103fb5119c0/spec/graphql/schema/subscription_spec.rb#L456-L463

Does your experience match that? Or did you have a different flow in mind? 

> add a big scary warning

Since I started working at GitHub, I found they use Rubocop for this, which is awesome. There are a bunch of cops that check for methods just like this, making sure people don't copy-paste stuff they shouldn't. (And it fails the build if they do, and outputs a helpful error message.) If you take that approach and you've got Rubocop in your project, I recommend it!

**Comment by bmulholland** [comment]
Hey! Thanks for considering the idea.

I like your specifics around `subscription_scope`. Do you have any concerns about this being a potentially-breaking change for existing usage?

At a glance, this change is mostly a few conditionals to raise an exception, plus some documentation. It that right? If so, I'll see if I can find some time to take a stab at it.

Regarding:

> authorize? check doesn't inspect individual objects that are triggered

I just meant that `authorize?` does not solve the problem I describe. I mentioned it because I spent some time considering that the method might be authorization for the objects returned by the subscription. Makes sense that it is authorization for accessing the subscription itself, as you say.

> Rubocop

That would definitely help with some scenarios. Though I don't think it would catch runtime bugs where the scope variable is nil by accident (e.g. "I forgot to pass in user_id"). Obviously there's checks for that stuff, too, but I do prefer a defense-in-depth approach.

**Comment by rmosolgo** [comment]
In graphql-ruby 1.13, when a subscription class has `subscription_scope(...)`, then a scope value will be _required_ for initial subscriptions and subsequent updates unless the subscription class has `subscription_scope(..., optional: true)` :+1: Thanks again for the suggestion!
