### ISSUE TITLE
How to structure mutation return object when using input objects

### ISSUE THREAD

**Issue by tbpeder** [rmosolgo/graphql-ruby#3250]
I can't figure out how to make this mutation accept the input object ContactType below. When I run the query against the code as shown below, I get the error message "Field 'firstname' doesn't exist on type 'ContactCreatePayload". Now, if I comment out the two field statements and instead add "type Types::ContactType", the mutation updates the database, but returns the error "Cannot return null for non-nullable field Contact.firstname". What am I doing wrong?

**Mutation**
```
module Mutations
  class ContactCreate < BaseMutation
    argument :attributes, Types::ContactAttributes, required: true
  
    field :contact, Types::ContactType, null: true
    field :errors, [String], null: false

    def resolve(attributes:)
      contact = Contact.new(attributes.to_h)
      contact.tenant_id = current_tenant.id
      
      if contact.save
        { 
          contact: contact, 
          errors: [] 
        }
      else
        { 
          contact: nil, 
          errors: contact.errors.full_messages 
        }
      end
    end
  end
end
```

**Input object**
  ```
class ContactAttributes < Types::BaseInputObject
    description "Attributes for creating and updating a contact"
    argument :firstname, String, required: true
    argument :lastname, String, required: true
    argument :email, String, required: true
    argument :salutation, String, required: false
    argument :title, String, required: false
    argument :phone, String, required: false
    argument :mobile, String, required: false
    argument :mailing_street, String, required: false
    argument :mailing_city, String, required: false
    argument :mailing_zip, String, required: false
    argument :mailing_state, String, required: false
    argument :mailing_country, String, required: false
    argument :description, String, required: false
    argument :account_id, Integer, required: false
  end
```

**GraphQL query**
```
mutation contactCreate($attributes: ContactAttributes!) {
  contactCreate(attributes: $attributes) {
    firstname
    lastname
    email
  }
}
  
{
  "attributes": {
    "firstname": "Joe",
    "lastname": "Jones",
    "email": "joe.jones@gmail.com"
  }
}
```

**Comment by rmosolgo** [comment]
Thanks for the details on this! 

> accept the input object ContactType below

This mutation doesn't accept `ContactType` as input. Judging by its usage in `field(...)`, it looks like `ContactType` is an _object_ type, which can be used for return values (but not input). Instead, this mutation accepts `ContactAttributes`. (I see that `ContactAttributes` is an _input object_ type :+1:.) This setup is ok, but I just want to confirm: this is a problem with _return_ types, not _input_ types, right? 

> What am I doing wrong?

The best thing here would be to use GraphiQL (or another GraphQL client) to inspect your schema. An "IDE" like that will provide autocomplete for the _actual_ fields supported by the schema. If you don't have a client like that handy, you can also use `puts MySchema.to_definition` to print out the schema definition. 

The problem here is that two approaches to mutation return types are getting mixed up. Here are the two approaches: 

- use `type Types::ContactType` to tell GraphQL that this mutation returns a `Contact`, then return `contact` from `def resolve`. When you do that, you can query the contact directly: 

  ```graphql 
  # This should work with `type Types::ContractType` 
  # _and_ `return contact` in `def resolve`
  mutation contactCreate($attributes: ContactAttributes!) {
    contactCreate(attributes: $attributes) {
      firstname
      lastname
      email
   }
  }
  ```
- __OR__, use `field(...)` to describe what the mutation returns, and return a Hash whose keys match the `field(...)` definitions in the mutation. When you configure the mutation that way, you can query those named fields on the mutation: 

  ```graphql 
  # This should work with `field(:errors, ...)` and `field(:contact, ...)`
  mutation contactCreate($attributes: ContactAttributes!) {
    contactCreate(attributes: $attributes) {
      # This nested selection corresponds to `field(:contact, ...)` and the `{ contact: ... }` key in the returned Hash
      contact {
        firstname
        lastname
        email
      }
     # Likewise, this one with `field(:errors, ...)` and `{ errors: ... }`
     errors {
       # whatever error fields here
     }
    }
  }
  ```
  
But, if you try to mix those, it won't work because the GraphQL configuration won't match the implementation.

So, how about trying _one_ of those approaches? Either: 

1. Return `contact` directly:
  - use `type Types::ContactType` 
  - and replace `{ contact: ..., errors: ... }` with just `contact` 
  - and query contact fields directly, eg `updateContact(...) { firstname lastname }`
2. Let the mutation generate a custom return type: 
  - use `field(:contact, ...)` and `field(:errors, ...)` 
  -  _keep_ `{ contact: ..., errors: ... }`
  - select those fields by name in GraphQL, eg `updateContact(...) { contact { ... } errors { ... } }`



When you use `field(:contact, ...)` in a mutation, then the mutation will generate a custom "payload" type with the fields you configure. In that case, the payload type will have fields based on your configuration (eg `contact { ... }` and `errors { ... }`). But if you use `type Types::Contact`, then you bypass the "payload" type generation, and GraphQL expects you to return an object that satisfies `Types::Contact`'s fields (like `contact` in your example above). 

Does that help? If you try one of those approaches but run into trouble, please share: 

- The mutation code that you tried
- The GraphQL query you tried 
- The response you received 

and we'll go from there!

**Comment by rmosolgo** [comment]
Ps, if you want to return errors, then you shold use the `field(:contact, ...)` + `field(:errors, ...)` style, and continue returning `{ contact: ..., errors: ...}`, but update your mutation to include the `contact { ... }` subselection: 

```diff 
  mutation contactCreate($attributes: ContactAttributes!) {
    contactCreate(attributes: $attributes) {
+     contact {
        firstname
        lastname
        email
+     }
    }
  }
```

**Comment by tbpeder** [comment]
This query seemed to solve the problem.  

```
mutation contactCreate($attributes: ContactAttributes!) {
  contactCreate(attributes: $attributes) {
    contact {
      firstname
      lastname
      email
    }
    errors
  }
}
```
