### ISSUE TITLE
Changelog notes for 1.9.19, 1.9.20 and 1.9.21

### ISSUE THREAD

**Issue by jasonkarns** [rmosolgo/graphql-ruby#3255]
We're looking to update from 1.9.17 to... something newer and are going through the release notes. Do a less conservative update to latest 1.9 jumps to 1.9.21 despite those versions not being listed as Releases on GitHub nor are there changelog notes for them.

Are there any details about the changes in these versions?

**Comment by rmosolgo** [comment]
Hey, sorry about the confusion there. Those changelog entries probably aren't on `master` because, after 1.10 was released, changes to 1.9.x would have been committed to `1.9.x` instead of `master`. The best changelog for those 1.9 versions is found on the `1.9.x` branch:

https://github.com/rmosolgo/graphql-ruby/blob/1.9.x/CHANGELOG.md

If you think those entries should be on master, that's fine with me; feel free to open a PR for it 👍
