### ISSUE TITLE
ActiveRecord pagination connection with before filter operates incorrectly

### ISSUE THREAD

**Issue by KieranP** [rmosolgo/graphql-ruby#3258]
Using before on pagination connections starts from the beginning of the collection instead of the page size amount before the given cursor. Example requests before, see request 4 for the failing example.

Example: Using Rails 6.1 & GraphQL 1.11.6 (brand new app, so AST, interpreter, etc the latest).

```ruby
class Post < ApplicationRecord
end

module Objects
  class Post < Types::Object
    field :id, ID, null: false
  end
end

module Types
  class Queries < Types::Object
    field :all_posts, resolver: ::Resolvers::Post::Index, max_page_size: 20
  end
end

module Resolvers::Post
  class Index < Types::Resolver
    type Objects::Post.connection_type, null: false

    def resolve(**args)
      Post.all
    end
  end
end
```

Setup:

```ruby
1.upto(100) do |i|
  Post.create(id: i)
end
```

### Request 1 (works, returns posts with ids 1 to 20, and endCursor is "MjA")

```graphql
{
  allPosts {
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    nodes {
      id
    }
  }
}
```

```
Post Load (0.2ms)  SELECT "posts".* FROM "posts" LIMIT ?  [["LIMIT", 20]]
```

### Request 2 (works, returns posts 21 through 40, and endCursor is "NDA")

```graphql
{
  allPosts(after: "MjA") {
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    nodes {
      id
    }
  }
}
```

```
Post Load (0.2ms)  SELECT "posts".* FROM "posts" LIMIT ? OFFSET ?  [["LIMIT", 20], ["OFFSET", 20]]
```

### Request 3 (works, returns posts 41 through 60, and startCursor is "NDE")

```graphql
{
  allPosts(after: "NDA") {
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    nodes {
      id
    }
  }
}
```

```
Post Load (0.2ms)  SELECT "posts".* FROM "posts" LIMIT ? OFFSET ?  [["LIMIT", 20], ["OFFSET", 40]]
```

### Request 4 (**FAILS**, returns posts 1 through 20 instead of 21 through 40 as would be expected)

```graphql
{
  allPosts(before: "NDE") {
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    nodes {
      id
    }
  }
}
```

```
Post Load (0.2ms)  SELECT "posts".* FROM "posts" LIMIT ?  [["LIMIT", 20]]
```

The query drops the offset completely. It would be expected to produce a query similar to request 2:

```
Post Load (0.2ms)  SELECT "posts".* FROM "posts" LIMIT ? OFFSET ?  [["LIMIT", 20], ["OFFSET", 20]]
```

Hope this was enough information to debug on your end.

**Comment by rmosolgo** [comment]
Thanks for the really thorough description. I _don't_ think this is a bug. 

Since neither `first` nor `last` are given, GraphQL-Ruby treats `allPosts(before: "NDE")` as `allPosts(first: $maxPageSize, before: "NDE")`. 

Here's a sketch of how GraphQL ruby sees the list of "all posts": 

```

the list:         [ * * * * * * * * * * * ]
the cursor:                   ^
items before:       ^ ^ ^ ^ ^
items after:                    ^ ^ ^ ^ ^

first item before:  ^
```

Implementation wise, two things happen. First, `before: "NDE"` is turned into `LIMIT 40` by: 

https://github.com/rmosolgo/graphql-ruby/blob/ef77d027a9d7545ecd067b0713050412560e027d/lib/graphql/pagination/relation_connection.rb#L125-L126

Then, GraphQL-Ruby applies `first: $maxPageSize` as `LIMIT 20`: 

https://github.com/rmosolgo/graphql-ruby/blob/ef77d027a9d7545ecd067b0713050412560e027d/lib/graphql/pagination/relation_connection.rb#L150-L153

(Since `LIMIT 20` is more restrictive than `LIMIT 40`, it overrides it.) 

So, the response is the _first 20_ items _before "NDE"_. 

Maybe you want `last: 20, before: "NDE"`? I think that would give you the offset and limit you expect: 

https://github.com/rmosolgo/graphql-ruby/blob/ef77d027a9d7545ecd067b0713050412560e027d/lib/graphql/pagination/relation_connection.rb#L157-L162

What do you think of that?

**Comment by KieranP** [comment]
Ok, thanks for the information. I can understand what you mean, and using last 20 has fixed this, but I don't feel this particular choice is intuitive for most users and it also means having to duplicate both max page size and last to the same value in each query when paging backwards through results.

To me, when neither first or last are sent, using `after` should default to `first: max_page_size` (as it currently does), but using `before` should default to `last: max_page_size`. If the user does indeed want the first 20 results before a cursor, then they could specify that first value. But for the majority of cases, I imagine people using `before` are using it in the context of a pagination system for results, and clicking previous should return the previous 20 before the cursor, not the first 20.

Thoughts?

**Comment by rmosolgo** [comment]
I don't plan to change the current behavior, because this is the first time I've heard of this particular issue and I don't want to change behavior for people who expect it to continue working as it currently does. 

The [Relay pagination docs](https://relay.dev/graphql/connections.htm#sec-Pagination-algorithm) don't have any `max_page_size` concept -- that was added to GraphQL-Ruby, so unfortunately, the Relay docs don't dictate anything here. 

If you want to change the behavior in your application, you could consider extending the [built-in connection extension](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field/connection_extension.rb) to apply default values to `arguments` when appropriate, and [hooking it up](https://github.com/rmosolgo/graphql-ruby/blob/207ae8fa1bbfff28107bab529494dab0e86d7fd2/lib/graphql/schema/field.rb#L158-L172) to your base field.

If you give it a try (or some other way of customizing this behavior) and run into trouble, please let me know!
