### ISSUE TITLE
Support connection wrapping for Schema-first implementations

### ISSUE THREAD

**Issue by rperryng** [rmosolgo/graphql-ruby#3283]
Instead of defining a schema using the class-based API, I am trying to use a schema-first approach with an "Implementation Object" as [described in the docs](https://graphql-ruby.org/schema/sdl.html#implementation-object).

My schema includes types that implement Relay's connection specification.  

When using the standard class-based API, and a field resolves to a connection type, the schema runtime takes care of wrapping the resolved iterable into its corresponding `GraphQL::Pagination::Connection` type (as defined in the schema intance's `@connections` mapping).

From what I can tell, this behaviour doesn't occur with the schema-first approach (try as I might, I wasn't able to understand why when going through the code, ).  e.g. if my schema implementation object is currently resolving a connection-type field, and it returns an `ActiveRecord::Relation` object, it does not automatically wrap into the `GraphQL::Pagination::ActiveRecord_Relation` object.

My naive approach was to implement this wrapping behaviour myself, by doing something like

```ruby
class SchemaImplementation
  def call(type, field, obj, args, ctx)
    result = ... # Some `ActiveRecord::Relation` object

    if field.connection?
      connection_class = ctx.schema.connections.wrapper_for(result)

      if connection_class.nil?
        raise StandardError "Didn't know how to wrap #{result.class} into connection"
      end

      constructor_args = args.merge({ context: ctx })
      connection_class.new(result, **constructor_args)
    else
      result
    end
  end
end
```

This works!  I can worry about just returning an iterable, and rely on this code wrapping it into the proper connection type.  Paginating arguments get applied and the baked-in cursor encodings get applied as well, great!

However, the issue becomes a little more complex once I want to combine the usage of lazy loading (to avoid N+1) and connection-style paging.  Specifically, I am using the [`batch-loader`](https://github.com/exAspArk/batch-loader/) gem, so I am resolving `BatchLoader::GraphQL` items (though I don't think that implementation detail really matters).

I _think_ the issue stems from the fact that the pagination wrapping can only occur _after_ the lazy object has performed its registered `lazy_resolve` function (in this case, `:sync` resolving to an `ActiveRecord::Relation`).  Since this (the proper timing of the `lazy_resolve` execution) is performed by the internals of `graphql-ruby`, I'm not sure how I can properly integrate this pagination wrapping with lazy objects from within my Schema Implementation's `call` method.

Using the class-based API these two functionalities seem to work seamlessly - I think because the `lazy_resolve` resolves into an `ActiveRecord::Relation` object, and then the pagination wrap is performed.  Or perhaps I missed something else entirely! Is there any path forward for supporting this in a schema-first implementation?

I've created a [small sample app](https://github.com/rperryng/graphql-lazy-connections-mvp) to demonstrate my problem, here are the important bits though:
- [GraphQL Schema](https://github.com/rperryng/graphql-lazy-connections-mvp/blob/main/app/graph/graph_schema.rb)
- [Implementation Object](https://github.com/rperryng/graphql-lazy-connections-mvp/blob/main/app/graph/schema_implementation.rb) (and the implementing ["resolver class" for the author type](https://github.com/rperryng/graphql-lazy-connections-mvp/blob/main/app/graph/resolvers/author.rb), the field names in the schema map to the method names of this class)
- [Crude specs for verifying behaviour](https://github.com/rperryng/graphql-lazy-connections-mvp/blob/main/spec/graph/graph_schema_spec.rb)

I hope this was clear!  Any help is highly appreciated.  Thank you for your time 🙇 .

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed writeup and sorry for my slow response here. 

A while ago, I _removed_ connection support because it only half-worked with SDL-parsed schemas (https://github.com/rmosolgo/graphql-ruby/pull/2782):

https://github.com/rmosolgo/graphql-ruby/blob/f88aa11da6ce6ff254cfa761dc8563d19bb6eb02/lib/graphql/schema/build_from_definition.rb#L410

To work around this issue, you could use an internal-ish method of graphql-ruby, [`Schema.after_lazy`](https://github.com/rmosolgo/graphql-ruby/blob/f88aa11da6ce6ff254cfa761dc8563d19bb6eb02/lib/graphql/schema.rb#L103-L117): 

```ruby 
def call(...)
  result = # call field 
  if field.connection?
    context.schema.after_lazy(result) do |resolved_result| 
      # apply wrapper to `resolved_result` here 
    end 
  else 
    result 
  end 
end 
```

That's not really a public API of GraphQL-Ruby, but practically speaking, it's not going anywhere. If you give it a try and run into trouble, please share the code you tried and what happened when you tried it.

Alternatively (or additionally), I'd welcome proper support for connections in SDL schemas (along with test to make sure it keeps working, and some way to opt _in_, so we don't break existing behavior). If you want to give it a shot, I'd be happy to review a PR as it comes along!
