### ISSUE TITLE
Allow usage of deprecated functionality to be treated as an error

### ISSUE THREAD

**Issue by haines** [rmosolgo/graphql-ruby#3290]
**Is your feature request related to a problem? Please describe.**

There are lots of deprecation warnings for v2.0, and I'd like to catch those in CI and migrate off the functionality now.

We use `config.active_support.deprecation = :raise` in the development and test environments in our Rails application to do this for Rails itself.

**Describe the solution you'd like**

Use a custom method to warn about deprecation, and allow configuration to raise an error rather than just warning.

**Describe alternatives you've considered**

Rather than implementing this entirely from scratch, it would also solve our problem if graphql-ruby used `ActiveSupport::Deprecation.warn` if it is defined, and otherwise fell back to `Kernel#warn`.

**Comment by rmosolgo** [comment]
Hey, thanks for the suggestion here. I agree, that could come in handy. How about something like this: 

- Add `GraphQL::Deprecation.warn` which calls `ActiveSupport::Deprecation.warn` if it's defined, otherwise`Kernel#warn`;
- Migrate existing `Kernel#warn` calls to `GraphQL::Deprecation.warn`

I think that'd do the trick. (And, anyone else who wants to hook into `.warn` could do it.) What do you think?

**Comment by haines** [comment]
That sounds like a good plan to me!

**Comment by rmosolgo** [comment]
🚢  in 1.12.1! Let me know if you have any trouble with it.

**Comment by haines** [comment]
Amazing, thank you!

**Comment by rmosolgo** [comment]
Unfortunately, I'm a bozo and forgot to merge #3292 before shipping 1.12.1. So, I just merged it and released 1.12.2, and updated the changelog 🍻

**Comment by haines** [comment]
Haha, no worries, thanks again!
