### ISSUE TITLE
How to instantiate a particular type to test it in isolation

### ISSUE THREAD

**Issue by gonzar11** [rmosolgo/graphql-ruby#3306]
I am trying to create tests for my custom objects without having to test the query that returns this specific object.
Is that possible? 
Suppose this is my type 
```
class Objects::GroupObject < Types::BaseObject
  field :id, ID, null: false
  field :logo_image, String, null: true
  field :name, String, null: false
  field :members, [Objects::UserObject], null: false do
    argument :limit, Int, required: false
  end
  field :members_count, Int, null: false
end
```

I would like to add test in this way:
```
class GroupObjectTest
   subject { Objects::GroupObject.new(object: create :group) }
   
   describe #members do
     #test stuff
   end
end

```

Thanks!

**Comment by rmosolgo** [comment]
Hey, thanks for asking, but I don't support a public API like this in GraphQL-Ruby. The contract of `Schema::Object` classes (`.authorized?`, methods for fields) is described in the docs, but they're initialized and managed by the GraphQL runtime. 

Instead, I recommend: 

- Extracting complicated code _out_ of GraphQL resolvers, so that it can be tested in isolation
- Or, using integration tests to test GraphQL behaviors (eg `MySchema.execute(...)`)

**Comment by gonzar11** [comment]
Thanks for your answer!
