### ISSUE TITLE
Relay docs missing from guides TOC

### ISSUE THREAD

**Issue by jpaas** [rmosolgo/graphql-ruby#3316]
The links to the relay docs in the Guides TOC https://graphql-ruby.org/guides#relay-guides seem to be missing

**Comment by rmosolgo** [comment]
Thanks for pointing this out. I removed most of them (Connections, Mutations) because the `Relay::` constants are deprecated, but I forgot to remove that section from the index page. 

In fact, I should really _leave_ it there, and add a `RangeAdd` doc. I'll keep this open til I get a chance to add that doc.
