### ISSUE TITLE
Error handlers are not handling errors inside dataloader sources

### ISSUE THREAD

**Issue by coding-chimp** [rmosolgo/graphql-ruby#3317]
**Describe the bug**

Errors raised inside dataloader sources are not being rescued by error handlers.

**Versions**

`graphql` version: current master

**GraphQL schema, query & steps to reproduce**

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "graphql", git: "git@github.com:rmosolgo/graphql-ruby.git"
end

class ErrorSchema < GraphQL::Schema
  class ErrorSource < GraphQL::Dataloader::Source
    def fetch(_)
      raise ArgumentError, "Nope"
    end
  end

  class Query < GraphQL::Schema::Object
    field :error, String, null: false
    field :dataloader_error, String, null: false

    def error
      raise ArgumentError, "Nope"
    end

    def dataloader_error
      dataloader.with(ErrorSource).load(123)
    end
  end

  use GraphQL::Dataloader
  query(Query)

  rescue_from(StandardError) { nil }
end

ErrorSchema.execute("{ error }")            # Error is being rescued
ErrorSchema.execute("{ dataloaderError }")  # Error isn't being rescued
```

**Expected behavior**

The error raised inside the source object should get handled.

**Actual behavior**

The error isn't handled and the script crashes.

**Comment by coding-chimp** [comment]
I wouldn't mind taking a look into this myself tomorrow, but so far, I've never checked how the error handlers are working. Some pointers would be appreciated. 🙂

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this. I agree it should work like you describe, although I'm not _exactly_ sure how to get us there. 

<details>
<summary>I started writing up an approach, but I think it can be much simpler</summary>
Here's where source batches are finally executed: 

https://github.com/rmosolgo/graphql-ruby/blob/345ebb2e3833909963067d81e0e8378717b5bdbf/lib/graphql/dataloader.rb#L200-L202

It calls this on a Source:

https://github.com/rmosolgo/graphql-ruby/blob/345ebb2e3833909963067d81e0e8378717b5bdbf/lib/graphql/dataloader/source.rb#L78-L90

My _guess_ is that ☝️ _that_ is where we need to add error handling.

Here's the method that currently does error handling: 

https://github.com/rmosolgo/graphql-ruby/blob/345ebb2e3833909963067d81e0e8378717b5bdbf/lib/graphql/execution/errors.rb#L38-L61

However, notice it expects a `Query::Context`. But Dataloader works on _multiplexes_ (sets of 1+ queries), not queries. You have to have the `Query::Context` to provide `context[:current_...]` values to the error handler. 

Additionally, that method does several things: 

- Wraps a block, rescuing any error that raises from it 
- Given a raised error, checks for a match among the schema's error handler 
- If there is a handler, pass that error to it, and return whatever the handler returns (or, re-raise it) 

I bet that method will have to be split up for proper use inside Dataloader / Dataloader::Source.

</details>

I think you'd have to do something like: 

- Rescue the error inside the source 
- Inside the source, instead of caching the loaded _value_ (there isn't one), set the _error_ in the source cache, similar to here: 

  https://github.com/rmosolgo/graphql-ruby/blob/345ebb2e3833909963067d81e0e8378717b5bdbf/lib/graphql/dataloader/source.rb#L87
  
- Then, when the waiting fiber resumes, instead of returning the loaded value, re-raise the error, probably from here: 

  https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/dataloader/source.rb#L42
  
  In fact, there are many places that do `@results[key]`, but all of them should be updated to raise an error if `@results[key]` contains an error. A good refactor would be to add a new method, `def result_for(key)` (or something) that _returns_ a non-error value, or raises an error if the result was an error. 
  
I think a refactor like that would _catch_ the error when it's raised by the dataloader (when there's no GraphQL runtime error handling), then re-raise it in a GraphQL runtime context.
