### ISSUE TITLE
Allow making Relay edges non-nullable

### ISSUE THREAD

**Issue by nirvdrum** [rmosolgo/graphql-ruby#3367]
**Is your feature request related to a problem? Please describe.**

Currently, all Relay edges are marked as nullable, even when that doesn't make sense for a given application. That means every client of the API needs to account for a situation that will never occur. At best, it's a bunch of wasted checks. At worst, the caller stops believing the schema and ignores that some items could ever possibly be `NULL`.

**Describe the solution you'd like**

I'd like a way to configure the edge type to be non-null and also a way to annotate that the edge consists of non-null values. By way of illustration, _graphql-ruby_ 1.12.5 will produce a schema definition for an edge like:

```graphql
edges: [InvitationEdge]
```

I'd like to be able to control that process so the schema could instead generate:

```graphql
edges: [InvitationEdge!]!
```

**Describe alternatives you've considered**

Currently, we override the `edge_type` method to guide the schema better. Unfortunately, that's relying on _graphql-ruby_ internals that are subject to change. Somewhere between 1.11.4 and 1.12.5, the internals changed in such a way that broke our override (the `edge_class` property on fields was removed). Having an official way of achieving such control over edge definitions would allow us to avoid brittle overrides.

**Comment by rmosolgo** [comment]
That'd be fine with me, how about adding an `edge_nullable` method similar to `node_nullable`? 

https://github.com/rmosolgo/graphql-ruby/blob/8e09a2bb5b615f76e4d18b4d2cfff38939808713/lib/graphql/types/relay/connection_behaviors.rb#L76-L84

Then, it could be applied here instead of the literal `true`: 

https://github.com/rmosolgo/graphql-ruby/blob/8e09a2bb5b615f76e4d18b4d2cfff38939808713/lib/graphql/types/relay/connection_behaviors.rb#L44

?

**Comment by nirvdrum** [comment]
Sorry, I somehow missed your question. I'll give that a try over the next day or two and see how it works.

**Comment by rmosolgo** [comment]
Fixed by #3376
