### ISSUE TITLE
Pro: GraphQL::Pro::PusherSubscriptions does not support broadcast

### ISSUE THREAD

**Issue by such** [rmosolgo/graphql-ruby#3375]
**Describe the bug**

Not sure if `GraphQL::Pro::PusherSubscriptions` is supposed to support the `broadcast: true` option but when I add it, subscriptions fails with: `NoMethodError: undefined method `size' for <ActionController::Parameters {} permitted: false>`

**Versions**

`graphql`: 1.12.5
`rails`: 6.0.3.4 
`graphql-pro`: 1.17.8

**Steps to reproduce**

`use GraphQL::Pro::PusherSubscriptions, redis: $graphql_subscriptions_redis, broadcast: true, default_broadcastable: true`

**Expected behavior**

Ideally `GraphQL::Pro::PusherSubscriptions` would support broadcasting subscriptions. Without that option I will be unable to use Pusher for my application. We have been using `GraphQL::Subscriptions::ActionCableSubscriptions, broadcast: true, default_broadcastable: true` for a while now and removing the broadcast option is not scalable.

If not possible, it should fail on initialization with a clearer message.

**Actual behavior**

<details>
<summary>Click to view exception backtrace</summary>

```
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/query.rb:302:in `variables_fingerprint'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/query.rb:292:in `fingerprint'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/subscriptions/event.rb:62:in `fingerprint'
/app/vendor/ruby/2.7.0/gems/graphql-pro-1.17.8/lib/graphql/pro/subscriptions/redis_storage.rb:40:in `map'
/app/vendor/ruby/2.7.0/gems/graphql-pro-1.17.8/lib/graphql/pro/subscriptions/redis_storage.rb:40:in `write_subscription'
/app/vendor/ruby/2.7.0/gems/graphql-pro-1.17.8/lib/graphql/pro/subscriptions.rb:91:in `write_subscription'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/subscriptions/instrumentation.rb:33:in `after_query'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/instrumentation.rb:82:in `public_send'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/instrumentation.rb:82:in `block in call_after_hooks'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/instrumentation.rb:80:in `reverse_each'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/instrumentation.rb:80:in `call_after_hooks'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/instrumentation.rb:74:in `call_hooks'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/multiplex.rb:187:in `instrument_and_analyze'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/tracing.rb:81:in `call_tracers'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/tracing.rb:83:in `block in call_tracers'
/app/vendor/ruby/2.7.0/gems/graphql-guard-2.0.0/lib/graphql/guard.rb:42:in `trace'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/tracing.rb:83:in `call_tracers'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/tracing.rb:83:in `block in call_tracers'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/tracing/appsignal_tracing.rb:19:in `block in platform_trace'
/app/vendor/ruby/2.7.0/gems/appsignal-2.11.5/lib/appsignal/helpers/instrumentation.rb:461:in `instrument'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/tracing/appsignal_tracing.rb:18:in `platform_trace'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/tracing.rb:83:in `call_tracers'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/tracing.rb:67:in `trace'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/multiplex.rb:60:in `run_queries'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/execution/multiplex.rb:50:in `run_all'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/schema.rb:1691:in `multiplex'
/app/vendor/ruby/2.7.0/gems/graphql-1.12.5/lib/graphql/schema.rb:1662:in `execute'
/app/app/controllers/graphql_controller.rb:40:in `execute_query
```

</details>

**Comment by rmosolgo** [comment]
Hey, sorry for the trouble on this! The problem here is that GraphQL needs free access to query variables, but `ActionController::Parameters` doesn't support this for security reasons. (In plain Rails, it wants to help you make sure you don't accept unvalidated input -- but GraphQL performs its own validations.) 

The GraphQL install generator provides a method to turn incoming variables into a plain Hash: 

https://github.com/rmosolgo/graphql-ruby/blob/efcedefd04d9e8d40ccdac99f867edb1cc3e667d/lib/generators/graphql/templates/graphql_controller.erb#L25-L43

How about adding something like that to your controller, would that be an option in your case?

**Comment by such** [comment]
Hello,

Thank you for you quick answer!
I trust that this solution would work out but in the meantime I realized Pusher might not be for us given the number of messages we currently send. After digging in a bit I realized `broadcastable` would not address that issue.
We've decided to try AnyCable to address the scalability issues of our subscription. Have you considered including https://github.com/anycable/graphql-anycable in this project or the Pro version? I've had to fork it (https://github.com/sorare/graphql-anycable) for it to support `broadcasted` subscriptions.

To come back to the exception, I setup `graphql-ruby` more than 2 years ago and I guess this part was not needed back then. It's been working fine with everything (including broadcastable ActionCable Subscriptions). It would not be an issue for us to add that to our controller at all.

**Comment by rmosolgo** [comment]
Thanks for following up. I'd love to know more about how you're using subscriptions and how `broadcastable` leaves something to be desired. There's a possible refactor that would reuse pusher channels for delivering payloads to the same subscription, I'm curious whether that'd improve the situation for you, too. (If you're willing to share, but don't want to share it here, I'd also welcome an email at rmosolgo@graphql.pro.)

Regarding AnyCable subscriptions, I haven't looked into it because I assumed it was maintained by Evil Martians.  Several of them are really active on their GraphQL-Ruby-related projects, I imagine they'd love to see the improvements you've worked on so far. 


I think the reason it choked on `ActionController::Parameters` _now_ is because, for Pusher subscriptions, the `subscription { ... }` query goes via `POST /graphql` instead of via ActionCable. Both ActionCable and Pusher use `Query#fingerprint` to deduplicate broadcasted subscriptions, but ActionCable didn't have that problem because the incoming params aren't `ActionController::Parameters`. It's the first I've heard of this incompatibility, but if it pops up again, I'll consider finding some way to handle `ActionController::Parameters` inside `Query#fingerprint`.

**Comment by such** [comment]
Basically, I think what would work for us would be to have one pusher channel per event fingerprint rather than one channel per user per event topic. Does that make sense? Is that what you had in mind?

But to be honest, if I end up making it work with AnyCable I don't see a very compelling reason to migrate to Pusher. Especially since during our tests we've been hit by the 10K limit even though we were using compression.

**Comment by rmosolgo** [comment]
> Is that what you had in mind?

Yes, that's just it. It complicates the implementation, but basically, for the way these services bill, it could save a lot of money 😅 . 

> hit by the 10K limit even though we were using compression

Thanks for sharing that, too. I added compression to support an existing user, with the understanding that it might not work for every case -- _chunking_ is probably the _best_ solution here. I'll keep it in mind. 

It sounds like the original issue is addressed here. If things don't work out with AnyCable and you're interested in exploring the improvements described above, please open a new issue!
