### ISSUE TITLE
A way to retrieve the order that input objects receive their arguments

### ISSUE THREAD

**Issue by thornomad** [rmosolgo/graphql-ruby#3407]
Am working on how to deal with some `orderBy` options for our resolver connections.  It seems like there is not necessarily a canonical way of implementing this so I was striking out with something like:
```graphql
enum OrderByEnum {
  ASC
  DESC
}

input LocationOrderBy {
  city: OrderByEnum
  state: OrderByEnum
}

type Query {
  locations(orderBy: LocationOrderBy)
}
```

Args passed like:

```json
{
  "orderBy": {
    "state": "DESC",
    "city": "ASC"
  }
}
```

Then, in the resolver it's easy enough to get the key/value pairs and craft my order stuff; just an example:

```ruby
def resolve(order_by: nil)
  return Location.all if order_by.blank?

  # ex "state DESC, city ASC"
  orders = order_by.map { |k,v| "#{k} #{v}" }.join(", ")

  Location.all.order(orders)
end
```
**Describe the problem**

The problem is _how do I communiate the order of the order by?_

Some way to retain the order of the `order by`.  It matters that we sort by `state` first and then `city` (in this example).  I've been googling around and not coming up with much.

The parameters are being sent as a JSON string which does have order but I am pretty sure that order is lost when it is converted to a `Hash` for the `.execute` method.

**Describe alternatives you've considered**

Building something much too complex!  Smile.  I suspect someone else has run into this problem before me.  Smile.

Thanks!

**Comment by rmosolgo** [comment]
> order is lost when it is converted to a `Hash`

_Maybe_ there are hacks that would work here, for example: 

- using `extras [:ast_node]` to inspect the AST and determine what order the AST nodes appear in. (This would work for literal arguments, but not for variables whose values come in the request body.) 
- Maybe, Ruby's order in the Hash would match the order in JSON. (Ruby's Hashes _are_ ordered, but I don't know if any JSON parsers guarantee to preserve that order.) 

To be _sure_ about priority of sorting, I recommend using a _list_ of sort inputs, for example: 

```graphql 
query {
  locations(orderBy: [{field: STATE, order: ASC}, {field: CITY, order: ASC}]) { 
    # ...
   }
 }
 ```
 
That way, it's easy to interpret the list of objects as sort priority. Interestingly, the GraphQL spec has a provision to make fields like this _easier_ to use: 

> If the value passed as an input to a list type is not a list and not the null value, then the result of input coercion is a list of size one, where the single item value is the result of input coercion for the list’s item type on the provided value (note this may apply recursively for nested lists).

(http://spec.graphql.org/draft/#sel-FAHjBJFCAACE_Gh7d)

So, if you defined a field like the one I gave an example of above, it's _also_ valid to query it like this: 

```graphql
query {
  locations(orderBy: {field: STATE, order: ASC}) { 
    # ...
   }
 }
```

Because, under the hood, it's converted to `[{field: STATE, order: ASC}]`. 

Those are all the options I can think of ... I hope one of them helps, and do let me know if you try something like that and it doesn't work out!

**Comment by thornomad** [comment]
Thank you for that tip about the array-vs-non-array input field!  I did not know that.  I will go your suggested route and be sure about sorting.  Have to define a few more things but that's the cost of explicitness I suppose.  Thanks again for the detailed help.
