### ISSUE TITLE
Allow passing of custom options to fields created by node_type and edge_type

### ISSUE THREAD

**Issue by cipater** [rmosolgo/graphql-ruby#3417]
The `node_type` and `edge_type` methods in `GraphQL::Types::Relay::EdgeBehaviors` and `GraphQL::Types::Relay::ConnectionBehaviors` don't allow custom options. And currently the best available option seems to be overriding those methods in a base class.

My particular use-case is for managing the visibility of fields. ie. 
```ruby
field :foo, public: true
```

It would be helpful to be able to do something like:

```ruby
edge_type(MyEdgeClass, field_options: { public: true })
```

Or perhaps just forward additional args?

```ruby
edge_type(MyEdgeClass, public: true)
```

Though the latter could open up the possibility for kwarg naming conflicts.

**Comment by rmosolgo** [comment]
Here's where a new `field_options:` keyword argument could be added:

https://github.com/rmosolgo/graphql-ruby/blob/ffec3b0b4b25a687342e5e5596c219022e31b756/lib/graphql/types/relay/connection_behaviors.rb#L38

https://github.com/rmosolgo/graphql-ruby/blob/ffec3b0b4b25a687342e5e5596c219022e31b756/lib/graphql/types/relay/edge_behaviors.rb#L19

The options given there should be passed along (and `**splat`ted) to the `field ...` call, so that they apply to the underlying field definition.

**Comment by bessey** [comment]
I am having a similar problem, but one layer deeper :sweat_smile:. The new edge_type / node_type tools are working nicely, but then I am still having to re-declare the cursor and page options to to add `public: true` to them, and in 1.13 this is invalid as it is seen as a 2nd definition with the same name rather than a re-declaration.

Is there a simple solution I am missing, or do we need `cusor_options` and `page_info_options` too?
