### ISSUE TITLE
Wisper doesn't find broadcasts when Dataloader is used

### ISSUE THREAD

**Issue by romariolopezc** [rmosolgo/graphql-ruby#3430]
**Describe the bug**

TBH I'm not sure what causes the bug, from my debug session it seems something related to threads and dataloader. The tests that are failling are all related to the `broadcast` assertion from the wisper-rspec gem, just upgrading the gem makes them fail. It seems that the side-effects of the broadcast doesn't finish

**Versions**

`graphql` version: 1.12.6
`rails` (or other framework): 6.0.2.1
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc? No

```ruby
module Gastown
  module Mutations
    class UpdateOrderStatusMutation < BaseMutation
      argument :hash_id, ID, required: true
      argument :business_id, ID, required: true
      argument(
        :status,
        Types::Gastown::OrderStatusEnum,
        required: true
      )

      type Types::Gastown::OrderType

      def resolve(args)
        order    = Order.find_by(hash_id: args[:hash_id])
        business = Business.find(args[:business_id])
        status   = args[:status]

        if order.update_status(status)
          # Here the broadcast is called succesfully (I verified)
          order.notify_order_status_changed(by_business: business)
        end

        order
      end
    end
  end
end

# Order class
class Order < ApplicationRecord
  include Wisper::Publisher

  ...
  def notify_order_status_changed(by_business:)
    email              = counterpart_contact_email(by_business)
    business_to_nofify = counterpart_business(by_business)
    locale             = counterpart_supported_locale(by_business)

    # Here is the broadcast
    broadcast(:order_status_changed,
              hash_id, business_to_nofify.id, email, locale)
  end
end

module Gastown
  class Schema < GraphQL::Schema
    include ::Concerns::ErrorHandling

    use GraphQL::Dataloader

    query    Gastown::QueryType
    mutation Gastown::MutationType

    orphan_types Types::Gastown::ContactType
  end
end

#### TEST
    let(:subject) do
      Gastown::Schema.execute(query, context: context)
    end

      it 'broadcasts the order changed status changed event' do
        expect { subject }.to broadcast(
          :order_status_changed,
          order.hash_id,
          order.seller_business.id,
          seller_contact.email,
          'es-MX'
        )
      end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
          mutation {
            updateOrderStatus(
              hashId: "ABC",
              status: CANCELED,
              businessId: "123"
           ){
            status
          }
```

```json
{"data":{"updateOrderStatus":{"status":"CANCELED"}}}
```

**Steps to reproduce**

Implement Wisper and broadcast

**Expected behavior**

The event to be broadcasted and asserted

**Actual behavior**

Event not being asserted, seems that the broadcast doesn't finish the execution

Place full backtrace here (if a Ruby exception is involved):

**Additional context**

There is no exception from GraphQL, seems that everything is working, it returns the response correctly.

This test was working before upgrading the gem and using dataloader. No other changes were made, the related models of this mutation were not modified

**Comment by rmosolgo** [comment]
Hey, I bet it has to do with the fact that, when `Dataloader` is used, execution happens in a fiber. I see at least _one_ use of `Thread.current[...]`, which would be broken by fibers: https://github.com/krisleech/wisper/blob/7cff5bca86cf0afa14cde20832bf4f0de6a52188/lib/wisper/temporary_listeners.rb#L27-L29

(Inside a fiber, `Thread.current` storage is all empty.) 

You could test this guess by adding a test like this one: 

```ruby 
expect { 
  Fiber.new { somehow_trigger_broadcast }.resume 
}.to broadcast(...)
```

You could see whether the `expect...to broadcast` finds triggers inside Fibers _at all_. 

If it doesn't, then some update would be required to `Wisper` in order to support events from inside Fibers. I'd love to hear what you find if you give it a try!

**Comment by romariolopezc** [comment]
Hello, thank you for the response! I used the code you proposed but it didn't work :/

I can make a PR there, can you point me in the right direction of Fibers / Threading? I don't have experience on that with Ruby

**Comment by rmosolgo** [comment]
I don't know of better docs for Fibers other than Ruby's own: https://ruby-doc.org/core-3.0.0/Fiber.html

I see you opened a PR with Wisper -- hopefully that's fruitful. If the test case I suggested above _failed_, then I suggest sharing it with the maintainer of Wisper as an example of what you'd like to work. If that test passes, then I bet GraphQL::Dataloader will work properly. But sharing that simplified example would probably make it easier for the Wisper maintainer to understand what you want it to do. 

I don't have any plans to modify graphql-ruby based on this issue, so I'm going to close it. If it turns out that an improvement to graphql-ruby would make it easier for Wisper to work properly, please let me know in a new issue!
