### ISSUE TITLE
Allow required argument declarations to allow null

### ISSUE THREAD

**Issue by cablett** [rmosolgo/graphql-ruby#3453]
**Is your feature request related to a problem? Please describe.**

I'd love to see graphql-ruby allow required arguments that accept null values. This allows mutations such as "set `foo` to value" where it would require an argument called `foo` that must be present, even if its value is `null`. This is similar to ActiveRecord's `:allow_nil => true`.

**Describe the solution you'd like**

I'd love to be able to do the following:

```
      argument :due_date,
               Types::TimeType,
               required: true,
               null: true,
               description: 'The desired due date for the issue, ' \
               'due date will be removed if set to null'
```

**Describe alternatives you've considered**

There are at least three solutions that come to mind that are workarounds:

 - set `required: false` on the arg and add `args.key?[:due_date]` to `ready?` to allow for required key but accepting any value (including null)
- set `required: false` on the arg and add `default_value: nil` so that leaving the arg off is the same as providing a null value
- add another mutation called "unset due date" which doesn't require a due date argument and makes it `nil`.

The first feels like a hack and the second feels like a strange abstraction. The third feels like extra code but I think is the least bad :)

@rmosolgo I'd be happy to raise a PR if you think this direction is worthwhile pursuing.

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed writeup. I'm not open to changing the semantics of non-null types and `null` because it would be a deviation from the GraphQL specification. It could create compatibility issues in the future. For example, if a project contains a bunch of queries that are _valid_ with GraphQL-Ruby, but invalid according to the GraphQL specification, then that project can't use validators or other tools written in other languages. That would be a bummer. 

Besides that, there are several decent work-arounds, as you mentioned. (I can't think of any others.) I find that I often add runtime validation _on top of_ GraphQL's type system. In fact, there's a whole validation system built on it: https://graphql-ruby.org/fields/validation.html. I'd say option number 1 above is not a _hack_, it's just plain business logic! 

Anyways, if you try one of those alternative approaches and run into trouble, please let me know. Thanks again for the suggestion!
