### ISSUE TITLE
GraphQL::Error for v1.12.11 and greater

### ISSUE THREAD

**Issue by 0215526** [rmosolgo/graphql-ruby#3510]
I am getting the following error after updating to  >= v1.12.11 but it works fine in v1.12.10

 GraphQL::Error:
      #   Second definition of `mutation(...)` (Types::MutationType) is invalid, already configured with Types::MutationType
      #   /home/virus/.rvm/gems/ruby-3.0.1/gems/graphql-1.12.11/lib/graphql/schema.rb:1050:in `mutation'

**Versions**

`graphql` version: v1.12.11
`rails`  :6.1.3.2

**Comment by rmosolgo** [comment]
Hey, sorry about the trouble! 

Sometimes this error happens when there were actually _two_ errors. If you start up your Rails app again, and scroll up in your console, is there a _different_ error that happened first? 

I've seen it where a _first_ error will cause schema initialization to fail part-way through, but then Rails will try to reload the file, but it won't quite work, since the schema was part-way loaded already. If you don't mind, sharing as much of the `rails server` output as possible (full error messages and backtraces, especially) would be really helpful here to understand what's happening and why it's going wrong.

**Comment by 0215526** [comment]
@rmosolgo Thanks for the quick response. 

I got the error, it was caused to due `ActionPolicy` gem. 

`FrozenError: can't modify frozen Array: []
from /home/virus/.rvm/gems/ruby-3.0.1/gems/action_policy-graphql-0.5.3/lib/action_policy/graphql/authorized_field.rb:158:in `add_extension!'`

**Comment by rmosolgo** [comment]
Ahhh interesting. I bet it was broken by this change: 

https://github.com/rmosolgo/graphql-ruby/compare/v1.12.10...v1.12.11#diff-fdbf285d34242cb3cb7b1e56e80f5d39bc600246e72b7bb32190e555432f156cR397

I can push a fix that doesn't pass that empty array when it's still empty.

**Comment by 0215526** [comment]
@rmosolgo Thank You
