### ISSUE TITLE
Ability to have inline subscribers?

### ISSUE THREAD

**Issue by fxn** [rmosolgo/graphql-ruby#3518]
**Is your feature request related to a problem? Please describe.**

In a GraphQL-based application, we are considering being able to configure webhooks using subscriptions.

The idea would be: You configure subscription queries, associate HTTP endpoints to them, and the subscriber is a simple forwarder that sends the "data" in the JSON payload to the endpoint (probably in an async manner).

This way, we can support both clients that want to setup their own WS subscribers, and clients that want to receive updates via webhooks in a uniform way. Also, we leverage the builtin support for configuring and getting data projections.

**Describe the solution you'd like**

Since the [GraphQL spec](https://spec.graphql.org/June2018/#sec-Subscription) does not mandate a serialization format or transport for subscriptions:

> GraphQL subscriptions do not require any specific serialization format or transport mechanism.

I _believe_ it would conform to the spec to have an inline subscriber, similar idea to Active Support notifications, if you know them.

So, you would setup a subscriber in the process that would have some method called. Or would configure a block. I _believe_ this would receive as an argument the configured projection serialized as a Ruby... hash?

In this vision, every relevant process in the system (think every Rails process, for example) has all subscriptions set up, and only receives events generated in its process.

**Describe alternatives you've considered**

* Having an internal web service that receives updates via WS. This has potential issues that I am exploring to avoid. Like, how to scale, authorization, it would not tolerate failures (webhook calls would be lost if the service does not get the update for whatever reason), and, well, it would be another moving part in the platform. With an inline subscriber we get all the power of GraphQL, uniform handling of update broadcasts, projections, scaling is trivially resolved, same for robustness, less moving parts, etc.

* In the context of a Rails application, instead of triggering a GraphQL event, you trigger an AS notification event that includes the GraphQL event name and arguments. A generic listener for that AS event triggers both a GraphQL subscription update, and custom code for webhooks to get the projection. This implies a separate/traditional webhook support implementation for getting the payload.

* Similar idea to the one in the previous item, but you configure GraphQL queries instead of subscriptions. In the AS listener, you perform the query. This one would work today, but it has overhead, since you need to run the query to get the projection, whereas a subscriber has it all computed already.

**Additional context**

If this is possible with the current contracts and you like the idea of an inline subscriber, maybe this issue could be addressed just with documentation.

**Comment by rmosolgo** [comment]
🤔 🤔  It _seems_ like this should be possible in some way with the existing system, but I might be wrong. I have been thinking about "multi-transport" subscription systems, but I've never seen one built. 

It seem like the `def deliver` hook would be the place to start: 

https://github.com/rmosolgo/graphql-ruby/blob/a176154a3c3c20d22a6991c42f17f33b260d038b/lib/graphql/subscriptions/action_cable_subscriptions.rb#L110-L115

That's where you've got the completely-executed result and GraphQL is getting ready to push the data over the channel. It seems like you'd need some way to determine _how_ to deliver the payload, but you could add a prefix to the subscription ID for that, or add a key to `context`. For example: 

```ruby 
def deliver(subscription_id, result)
  if subscription_id.start_with?("hook--") # Imagine the code adds this prefix when storing webhook data
    _hook_hint, hook_database_id, subscription_uuid = subscription_id.split("--")
    hook = Hook.find(hook_database_id) # look up the config for this subscription 
    hook.post_to_url(result.to_h)
  else 
    # It's not a webhook, keep delivering the way it used to 
    super 
  end 
end
```

But I guess there'd be other things to try to squeeze in there, for example: 

- Checking _two_ places to answer the question "who is subscribed to this event?" The ActionCable implementation doesn't have a great place to do this, since it's all managed in Ruby memory. You might have to extend `def execute_all` to take the given `event.topic` and check the database for any webhook configs that match it. 
- Some way to update the subscription ID to include a clue to the delivery channel. (Maybe that wouldn't be necessary if it was a different codepath.) 

Anyways, there'd be a lot of custom work to do that 😅 

------

> inline subscriber 

I think I _almost_ understand what you mean by this, but not quite. Do you mean, use a Ruby in-memory data structure to manage subscription state? For example, when receiving a `subscription { ... }` request, create an in-memory record of the subscription, along with some callback for when the event is triggered? 

It'd certainly _work_ (there's [something similar](https://github.com/rmosolgo/graphql-ruby/blob/a176154a3c3c20d22a6991c42f17f33b260d038b/spec/graphql/subscriptions_spec.rb#L5-L96) in the unit tests), but I have never considered publishing an implementation like that because of productionization issues: 

- What about multi-process deployments? For example, if two clients subscribe, and happen to hit Ruby process `1`, but then an event happens on Ruby process `2`, then a call to `.trigger` would _not_ find any subscribers. 
- What about re-deploys? If there's a lot of state in memory, and I redeploy, then it's all lost. We'd need some way to rebuild that state. 

ActionCable solves these by using a database for inter-process communications, and it forces all clients to reconnect after a redeploy, so that the in-memory parts of state are reconstructed. 

Or, did you have something in mind that addressed or avoided those issues somehow?

**Comment by fxn** [comment]
Heads up! Just to say that I am investigating this and will eventually come back.

**Comment by fxn** [comment]
Back!

So yes, as you suggested, some custom subscription class would work. And that answers my question.

You're right regarding broadcasting. This use case we explored is a bit odd, because by design, you know you need a subscription in the same process the trigger happens and there is no need to broadcast.

On boot, you fetch webhook configuration, and every process subscribes to the same set of events for as many webhook consumers as you have (conceptually, mod optimizations). In the subscriber, you just intercept, basically, no broadcast is needed for these ones. On trigger, schedule the webhook call with the given payload and done.

Arguably, that is totally coupling webhooks and subscriptions, which in the use case I was researching could make sense. In a general case in which the coupling was a bad idea, I believe you could still configure GraphQL queries per webhook/receiver, and have a regular webhook implementation (not tied to subscriptions) that computes the payload using said queries.

Since the doubt is resolved, we can close the issue. Thanks for your help! ❤️
