### ISSUE TITLE
IDL Dump Rake task adds trailing whitespace

### ISSUE THREAD

**Issue by acoffman** [rmosolgo/graphql-ruby#3528]
**Describe the bug**

Hi! Thanks so much for your work on this project, we've been really enjoying using it.

I am not sure this is a "bug" as such, but it bit us and I figured I'd report it.

We are running a test as described [in the guides/your blog post](https://graphql-ruby.org/testing/schema_structure.html#maintain-a-graphql-schema-dump) to ensure the schema dump file is up-to-date.

This has worked reliably up to this point, however it started failing recently. The issue appears to be here: https://github.com/rmosolgo/graphql-ruby/blob/a750b69733424b3af8808fc4c9e00cbee3511c5d/lib/graphql/rake_task.rb#L102

In the Rake task its adding a newline to the end of the dump while `MySchema.to_definition` does not and thus they won't be equal. 

Its straightforward enough to add `strip` to both before comparing so the test continues to pass, but I wasn't sure if it was a regression that the default behavior is now for the outputs of `to_defintion` and the rake task to not match. 

**Versions**

`graphql` version: 1.12.12
`rails` (or other framework): 6.1.3
`graphql-batch`: 0.4.3

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this. Someone else mentioned running into trouble on this. 


On the one hand, the rake task should definitely include a final newline, since it's writing to a file. (That was the logic in the original pull request, #3480.) 

But also, it'd be nice if the two still matched. 

Maybe it'd work fine just to include the newline in the `to_definition` output. That'd make them match, and it'd make sure there's a final newline in the output file. The only downside is, anyone who has done a local work-around will have to remove it after it's released 😖 Anyhow, I'll give it a shot and follow up here.
