### ISSUE TITLE
Different method signatures on Subscriptions.each_subscription_id

### ISSUE THREAD

**Issue by bdurand** [rmosolgo/graphql-ruby#3589]
**Describe the bug**

There is a discrepancy between the method signatures on `each_subscription_id` between `GraphQL::Subscriptions` and `GraphQL::Pro::Subscriptions`.

**Versions**

`graphql 1.12.13`
`graphql-pro 1.18.1`

**Expected behavior**

I would expect the method signatures to be the same since this is a public method and `GraphQL::Pro::Subscriptions` extends from `GraphQL::Subscriptions`.

**Actual behavior**

In `GraphQL::Subscriptions` the argument is documented as a `GraphQL::Subscriptions::Event`:

```ruby
    # Get each `subscription_id` subscribed to `event.topic` and yield them
    # @param event [GraphQL::Subscriptions::Event]
    # @yieldparam subscription_id [String]
    # @return [void]
    def each_subscription_id(event)
```

However, in `GraphQL::Pro::Subscriptions`, this method is delegated to `GraphQL::Pro::Subscriptions::RedisStorage` where the method is defined with a `topic` argument which is being passed in as a string:

```ruby
def each_subscription_id(topic)
```

**Comment by rmosolgo** [comment]
Yeah, I think this _looks_ like more of a problem than it is. The right thing here would be to use a different method name for that, since it's not actually called the same way as `#each_subscription_id` in the base class. 

Maybe you noticed, it's only used for listing subscriptions in the dashboard. Then, under the hood, `GraphQL::Pro::Subscriptions` actually overrides the subscription override flow at a higher level, in order to support backwards compatibility between pre-broadcast and post-broadcast subscriptions.

As far as I can tell, this is _awkward_, but not broken in a functional way. Do you agree, or is this causing some kind of misbehavior that I've overlooked?

**Comment by bdurand** [comment]
Yeah, I saw how the method is defined but not used in the open source gem. I stumbled on this because we have a couple of custom subscriptions classes and the documented behavior was not consistent between the two classes. I was able to solve my issue by just adding type checking for the arguments within the code.

Nothing is broken (unless you try to inject behavior in to `each_subscription_id` like I'm doing). It would make sense to me to either remove `each_subscription_id` from the public API or update the pro subscriptions to use a different method name.

**Comment by rmosolgo** [comment]
Ahh, yeah, that makes sense. I've taken a try at removing it in https://github.com/rmosolgo/graphql-ruby/pull/3595, but I wonder about compatibility. I might release it in 1.13.0 so it doesn't sneak into a patch release.

**Comment by bdurand** [comment]
Yeah, definitely not something I'd expect in a patch release.

**Comment by rmosolgo** [comment]
Sorry for the confusion -- this method will be removed from internals in 1.13.0 :+1:
