### ISSUE TITLE
Configure complexity on connection fields

### ISSUE THREAD

**Issue by crpahl** [rmosolgo/graphql-ruby#3591]
We're exploring rate limiting our API similar to how it's done at Shopify using a complexity based approach:

- Throttle the request if the requested cost is greater than the apps currently available complexity
- Reduce the apps available complexity for a resolved query based on the actual query cost

With every field having a default complexity of 1, the `edges` and `node` field are contributing to the cost calculated by `GraphQL::Analysis::AST::QueryComplexity`. For example, I'll get a total complexity of 15 from it for the following query when I was only expecting 5 (5 client nodes with a single `id` scalar):

```
{
  clients(first: 5) {
    edges {
      node {
        id
      }
    }
  }
}
```

Is there a way to set the complexity for the connection related fields to 0 other than redefining them in our class that extends `GraphQL::Types::Relay::BaseConnection`?

As for calculating the actual query cost, I've done this by adding a field extension to all of our fields that accumulates the total complexity of all resolved fields. This approach doesn't include the complexity cost of `edges` or `node` which is why I'm exploring setting them to 0. This also seems to be what Shopify is doing based on the values I'm getting in their throttle cost extension when experimenting with their API?

Any help would be very much appreaciated!

**Comment by swalkinshaw** [comment]
Shopify doesn't use the gem's connection interface (for legacy reasons) so unfortunately I can't really help with that part. But for calculating the actual cost, we use a tracer instead of field extensions.

**Comment by rmosolgo** [comment]
>  other than redefining them in our class...?

That's the only way I can think of, since that's where the fields are defined! I think you'd want to override these methods:

https://github.com/rmosolgo/graphql-ruby/blob/efd0711298bde27c7ff23cb6c70f675da564affc/lib/graphql/types/relay/connection_behaviors.rb#L121-L126

https://github.com/rmosolgo/graphql-ruby/blob/efd0711298bde27c7ff23cb6c70f675da564affc/lib/graphql/types/relay/connection_behaviors.rb#L46-L50

https://github.com/rmosolgo/graphql-ruby/blob/efd0711298bde27c7ff23cb6c70f675da564affc/lib/graphql/types/relay/edge_behaviors.rb#L23

**Comment by crpahl** [comment]
Thank you both!

After following both of your suggestions, I was able to consistently get an actual query cost that matches the expected cost when the returned number nodes matches the number requested in the query so that's great!

For the tracer, I ended up doing something like this:

```
module Tracers
  class ComplexityTracing
    def self.trace(key, data)
      if key == "execute_field" && data[:field].complexity.is_a?(Integer)
        # add to actual complexity
      end

      yield
    end
  end
end
```

I've added a proc to our connection fields to calculate the complexity which is why I'm checking if it's an `Integer` and skipping all proc based complexity values. Am I on the right track?

As for overriding the methods, that worked perfectly. I was thinking it would be great to configure the complexity values in similar way to how nullability can be configured with the singleton class methods: `node_nullable`, `edges_nullable`, `edge_nullable`. Would you be open to me creating a PR to add something like the following methods:

- `nodes_complexity`
- `node_complexity`
- `edges_complexity`

Or some sort of similar hook that will allow me to configure it in the subclass?

**Comment by swalkinshaw** [comment]
@crpahl yep that's basically it 👍 

For complexity procs, you can do this:

```ruby
data[:field].complexity.call(query.context, data[:arguments], 0)
```

**Comment by rmosolgo** [comment]
👋  Yeah, I think this is basically a limitation of the system here. 

"Scoped context" is only applied at runtime, so I don't think it will help here, in the analysis step.

I suppose the  _ideal_ behavior would be: 

- `totalCount` and `pageInfo` count for 1 each 
- `edges` and `nodes` multiply the child complexity by the `first:` or `last:` -- but if both are present, don't double the charge since they use the same data 

Does that sound right?

I don't think the current implementation can handle that, since `child_complexity` would be the sum of `totalCount`, `pageInfo`, `nodes` and `edges`. In theory, you could split it up after the fact, if you had access to the AST nodes for the query. But even that is quite complicated, because of merging fragments. (At runtime, you could use a `Lookahead` to do this, since the runtime has already merged fragments -- but the analyzer doesn't preserve that information.)

There's also no way to look "up" in the AST (or query structure) to check the arguments on parent fields.

Anyhow, I think that leaves two options: 

- Use the implementation you sketched above, which, although it's imperfect, it _works_, and it might be good enough. (How often do clients select `edges` _and_ `nodes`? How often with the "overcharge" of multiplying `pageInfo` by `first`/`last` make a difference?) 
- Or, improve the analyzer to support the ideal implementation described above. I'm pretty sure it could work. We'd have to accumulate `node`s here: 

    https://github.com/rmosolgo/graphql-ruby/blob/eae5f090d8c016b315bc31ef43d672865718d27f/lib/graphql/analysis/ast/query_complexity.rb#L82
    
    It currently tracks the first `node`, but you need _each_ `node` to reliably support a Lookahead. After that, I think you could implement something like this: 
    
    
    ```ruby
    ->(context, lookahead, child_complexity) {
      metadata_complexity = 0
      if lookahead.selects?(:total_count)
        metadata_complexity += 1 
      end 
      if (page_info_lookahead = lookahead.selection(:page_info)).selected?
        items_complexity += 1 # for `pageInfo`
        items_complexity += page_info_lookahead.selections.size # for child selections on pageInfo; assumes no nested selections
      end 
      
      items_complexity = child_complexity - metadata_complexity 
      max_items = lookahead.arguments[:first] || lookahead.arguments[:last]
      # TODO: should we could _both_ nodes and edges here? 
      # we could check if both are selected, and if they are, divide `items_complexity` by 2 to remove the cost of one of them.
      metadata_complexity + (items_complexity * max_items)
    }
    ```

What do you think of that "ideal" implementation? If you think it's worth a shot, I'll give it a try!

**Comment by crpahl** [comment]
> Does that sound right?

Yeah that sounds correct to me! In our case, we also have to handle the situation where neither `first:`, or `last:` are given since we're not making them required arguments. We have `default_max_page_size` set in our schema so when those arguments aren't supplied we're assuming the worst case and doing something like this for `max_items`:

```
args[:first] || args[:last] || max_page_size || context.schema.default_max_page_size
```

So in your example, would it make sense to calculate `max_items` like this, or should we be going about this (when first/last isn't supplied) a different way?

```
max_items = lookahead.arguments[:first] || lookahead.arguments[:last] || max_page_size || context.schema.default_max_page_size
```

> What do you think of that "ideal" implementation? If you think it's worth a shot, I'll give it a try!

I think this ideal implementation sounds great if you'd be willing to give it a try! Since you'd be passing in `lookahead` to the proc instead of `args`, would this be a breaking change for currently implemented complexity procs?

> Use the implementation you sketched above, which, although it's imperfect, it works, and it might be good enough. (How often do clients select edges and nodes? How often with the "overcharge" of multiplying pageInfo by first/last make a difference?)

Yeah that's a good question... we don't have any metrics in place yet to track something like complexity vs. server response time so I'm not sure how much of a difference it will make until we have something like that to look at. I do like the ideal solution more since it's ultimately more accurate and what I was originally expecting, but if what I sketched out is close enough, I don't want to waste your time.

Would the "ideal" solution be useful to others that need to compute complexity on connection types? I think I still like this solution since ultimately it allows you to calculate a more accurate expected complexity value.

One other thing I'm curious about, is if it would make sense to implement the complexity proc for connection types directly in the framework instead of having to implement it ourselves. For example, if we went with the ideal solution, could your example proc just be implemented directly in `GraphQL::Schema::Field::ConnectionExtension` so the default complexity value is correct for anyone that uses connection types?

**Comment by rmosolgo** [comment]
>  useful to others ...  directly in the framework

I'm open to it, though personally I'm not that convinced of complexity. In practice, I find it hard to guess exactly which fields / under which conditions they will be resource-intensive. And when implementations change, how to keep the complexity configuration up-to-date? We have a server process timeout that ends up terminating long-running queries 🙈...

Anyhow, I'll take a look soon and follow up here :+1:

**Comment by crpahl** [comment]
Thank you!

Fair enough. Ultimately, we just need a value that we can use for rate limiting purposes and complexity seemed like the best approach initially since an analyzer already existed. I see at Github you're rate limiting by counting the nodes. Would something like this be done by implementing a custom AST analyzer?

**Comment by rmosolgo** [comment]
> a custom AST analyzer?

Yes, it's basically the same as "complexity" in this gem, but it was implemented in-house, and because _reasons_, can't be migrated to the gem's analyzer 😖

**Comment by rmosolgo** [comment]
I took a try at it in https://github.com/rmosolgo/graphql-ruby/pull/3609, could you take a quick look and see if that looks like what you had in mind? 

I may have to touch it up in order to merge it to 1.12.x -- I don't want to change the default behavior on that until 1.13.0.

**Comment by rmosolgo** [comment]
(Oh, `nodes` and `edges` should probably count for `1` each, not `1 * page_size`)

**Comment by crpahl** [comment]
I tried it out and that's exactly what I had in mind 🎉 

Just this one change that you pointed out [here](https://github.com/rmosolgo/graphql-ruby/issues/3591#issuecomment-911835056) would need to be made.

**Comment by cheald** [comment]
I found myself needing the ability to break down queries to help understand where they're growing too complex, and in the process I found that it's very useful to be able to separate the page-multiplied scopes from the non-multiplied scopes, rather than trying to reverse it after the fact.

I've modified the QueryComplexity analyzer to track complexity for paged child keys (nodes and edges, by default, though it's configurable) separately from other keys, then those complexities get passed to `calculate_complexity`, which makes the actual complexity calculations quite a lot simpler.

The changes are here, for those that might find them useful. It breaks the `complexity_for` and `field_complexity` interfaces, so it wouldn't be super easy to pull back upstream, but it does work, and it's here if others might find it useful. There are probably more intelligent ways to do the paginated fields split, but nodes/edges works for my purposes.

https://gist.github.com/cheald/8c9be84ad0dbc80fb41a194f83e23b33

This gives me reliable calculations for tree costs and makes it very easy to reason about the complexity breakdowns:

```
puts Graphql::QueryComplexityWithFieldDetails.report(q)
```

`QueryComplexityWithFieldDetails#report` gives me a nice readable output for the query. So, for example here, I can see that `accountGrants` has a cost of 1907, which breaks down to a page size of 100 * a paged complexity of 19, plus a non-paged complexity of 6, plus the accountGrants complexity of 1.

```
account {                                  1909.00 (child complexity: 1908.00, paged child complexity: 0.00)
  accountGrants {                          1907.00 (max page size: 100, child complexity: 6.00, paged child complexity: 19.00)
    pageInfo {                                5.00 (child complexity: 4.00, paged child complexity: 0.00)
      endCursor                               1.00
      hasNextPage                             1.00
      hasPreviousPage                         1.00
      startCursor                             1.00
    }
    totalCount                                1.00
    nodes {                                  19.00 (child complexity: 18.00, paged child complexity: 0.00)
      accepted                                1.00
      account {                               3.00 (child complexity: 2.00, paged child complexity: 0.00)
        id                                    1.00
        name                                  1.00
      }
      createdAt                               1.00
      email                                   1.00
      id                                      1.00
      isSelf                                  1.00
      lastActivity                            1.00
      link {                                  8.00 (child complexity: 7.00, paged child complexity: 0.00)
        account {                             5.00 (child complexity: 4.00, paged child complexity: 0.00)
          boundingAccount {                   2.00 (child complexity: 1.00, paged child complexity: 0.00)
            id                                1.00
          }
          id                                  1.00
          name                                1.00
        }
        id                                    1.00
        name                                  1.00
      }
      roles                                   1.00
    }
  }
  id                                          1.00
}
```
