### ISSUE TITLE
How to design a schema with specific mutations and execute mutations as a transaction

### ISSUE THREAD

**Issue by joelzwarrington** [rmosolgo/graphql-ruby#3724]
Hello - Looking to get some feedback/suggestions when it comes to building a schema which has specific mutations, and how one might treat some mutations as transactions.

Following schema design ideas brought fourth in **Production Ready GraphQL**, we're implementing more specific mutations to provide a better experience with required arguments. However there is one piece which is still unclear: combining multiple mutations into a single transaction.

Ideal scenario would be able to run a mutation like this client side:

```
mutation {
  mutation1
  mutation2
}
```

Where mutation 1 and 2 must both succeed or a rollback is triggered. This doesn't come up often, but does happen when dealing with `has_many` relations which can be updated as the same time as the parent object.

The way we've avoided this has been with larger mutations with multiple branches and non-required arguments, even when updating multiple objects. Any thoughts on this?

**Comment by joelzwarrington** [comment]
@rmosolgo hey - wondering if you had any thoughts/suggestions for further research in this area?

**Comment by rmosolgo** [comment]
I honestly haven't thought of it before. Conceptually, GraphQL fields are isolated, so it'd be swimming upstream to try to coordinate side-effects from one to the other. I was about to suggest "larger mutations" as you described there at the end of your post, because in my experience, the most useful mutations are the ones that map closely to business operations (example: https://github.blog/changelog/2021-09-13-a-simpler-api-for-authoring-commits/). Clients shouldn't have to combine pieces together to perform common operations... but I can see how that'd be in tension with requiring more arguments. 

All that said, it'd probably be _possible_ to design a system using: 

- Ahead-of-time analysis to determine "should this operation be executed in a transaction?" (https://graphql-ruby.org/queries/ast_analysis.html)
- A tracer to wrap execution in a transaction (https://graphql-ruby.org/queries/tracing.html, https://graphql-ruby.org/api-doc/1.12.20/GraphQL/Tracing) 


I hope that helps!

**Comment by joelzwarrington** [comment]
Thank you! I'm going to close this issue for now as I feel like I should be able to look into a way to do this.

I think the better experience might be the larger mutations for actions which are done simultaneously as you've mentioned. As GraphQL is ultimately consumed by each client differently and the more mutations the merrier. It seems like the development flow, particularly in a public API is to start with the granular/smaller mutations and build out the more complex mutations with specific use cases once required by those public consumers.

That seems to be the nice balance of required arguments and then adding more complex logic for the clients which know what they're doing.
