### ISSUE TITLE
Provide mechanism to add "extensions" in response

### ISSUE THREAD

**Issue by NuckChorris** [rmosolgo/graphql-ruby#3766]
**Is your feature request related to a problem? Please describe.**

I'm maintaining a large, public API, which means I need to deal very carefully with deprecations. Right now, the `deprecation_reason:` annotation only affects introspection data, but many clients will never look at that again after they've finished developing their project, and will be caught by surprise when we eventually make the break.

I want deprecations to be logged for our own tracking (contacting app devs as the deadline looms, seeing if we need to delay a deadline, etc.) and to be highlighted in the GraphQL response. Logging them is easy: monkey-patch `GraphQL::Schema::Directive::Deprecated` and log it in `self.resolve()`

Highlighting deprecations in the response, however, is difficult. I found [an article](https://blog.logrocket.com/versioning-fields-graphql/#definingthedefaultversionforafield) which proposed putting this info under `extensions.deprecations` in the response, and that seems reasonable and in line with the spec.

**Describe the solution you'd like**

I'd like a way for a resolver (technically a directive's `resolve` method) to modify the `extensions` field of the query result.

Something like this:

```ruby
class GraphQL::Schema::Directive::Deprecated
  def self.resolve(_object, arguments, context)
    context.query.extension(:deprecations) ||= []
    context.query.extension(:deprecations) << arguments[:reason]
    yield
  end
end
```

**Describe alternatives you've considered**

- **Field errors** — I could raise a field error for a deprecation, but there's two wrenches in this: (1) poorly-coded clients might not handle this smoothly (2) because it raises, it won't ever resolve
- **throw/catch** — This is probably the hack I considered the most: I could `throw :deprecation` and catch it in my controller. But this would be messy and it would be difficult to report line/column/field/etc. in this (not that the proposed solution above can do this either, but I think it would be a LOT easier to do). I'd much rather have some way to directly modify the extensions field
- **Out-of-band communication with developers** — this is what I'm currently doing, and it's working alright for now, but I don't have contact info for every client developer, so some of them may never find out until I make a breaking change ☹️

**Comment by rmosolgo** [comment]
Thanks for the suggestion, I agree this would be a nice feature! Somehow we added `"extensions": ...` at my old job, so there must be _some_ way to do it, though I can't remember it. Happy to take a look and improve the interface and add some docs.

**Comment by rmosolgo** [comment]
I proposed an API for this in #3770 -- I'd love to know what you think of it!

**Comment by NuckChorris** [comment]
That looks *excellent*! Simple, succinct, works for what I need!

My only other question then is — can I get the location data during execution of a field directive?

Specifically I want these same fields that errors have:

```json
      "locations": [{ "line": 6, "column": 7 }],
      "path": ["hero", "heroFriends", 1, "name"]
```

**Comment by crpahl** [comment]
@rmosolgo I just wanted to add something here that I noticed with this change and wasn't really sure if it would be considered a new issue.

I noticed this change in the changelog and wanted to make use of it! We currently add some information to the `extensions` response in an instrumenter in a pretty hacky way:

```
        def after_query(query)
          return if query.context[:rate_limiter].blank?

          (query.result[:extensions] ||= {}).merge!(query.context[:rate_limiter].throttle_status)
        end
```

We're adding the status of an apps rate limiter to every query result here. We're adding the status here because at this point we'll have the actual query cost which has been accumulated in a tracer. I updated it to:

```
        def after_query(query)
          return if query.context[:rate_limiter].blank?
          
          query.context.response_extensions[:cost] = query.context[:rate_limiter].throttle_status
        end
```

But the `extensions` aren't showing up in the query response. It looks like it's because it's getting set before the `after_query` hooks in the instrumenters are getting called?

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/multiplex.rb#L155

So even though I'm adding to `response_extensions`, it's past the point where it will be added to `query.result_values["extensions"]`.
