### ISSUE TITLE
Tracing: Resource names for queries without operation names

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#3769]
I am happy to contribute this change btw, but thought I would start from an issue before whipping up a PR.

**Is your feature request related to a problem? Please describe.**

Datadog APM groups GraphQL traces by their operation name, this is fairly fundamental to making those traces useful, similarly to how a Rails controller tracer would not be useful if it combined all controller + actions into a single "controllers" trace.

However, for queries with no operation name associated, that's exactly what GraphQL Ruby does today.

**Describe the solution you'd like**

I could have sworn that some years ago the Datadog tracing behaviour in GraphQL Ruby was to fall back to the entire query string (or maybe truncated, but truncated very far along) as the resource name, with newlines removed. Perhaps that's my imagination.

I think that is a reasonable fall back mechanism. Another would be to has the query string, but this is more work and probably worse developer experience as they cannot be skimmed in a list

I assume such a solution just has to change this line a little:
https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/tracing/data_dog_tracing.rb#L23
That said, this seems like something all platform tracers would benefit from? Not that I am familiar with any other ones.

**Describe alternatives you've considered**

I tried faking an operation name in the `MySchema.execute(query, operation_name:)` API, however it reasonably raises an error that no query I am executing has that operation name.

**Comment by rmosolgo** [comment]
Thanks for opening this issue! A couple other suggestions: 

- Accept a custom value from context, for example, `context[:tracing_transaction_name]`, which is used by all platform tracers if it's present 
- Query string may disclose sensitive information, since it contains arbitrary user input. An alternative would be `query.fingerprint`, which is a hash of query string, operation name, and variable values. But for APIs receiving arbitrary queries, that will be a high-cardinality value, since it's different so often. 
- There's also `query.sanitized_query_string`, which has strings removed (maybe other cleanups, I forget). I think that could also be safely used as a transaction name. 

I'd welcome a change along the lines you suggest, I hope those other items are helpful 🍻

**Comment by bessey** [comment]
> Accept a custom value from context, for example, context[:tracing_transaction_name], which is used by all platform tracers if it's present

This should meet our needs and I like the flexibility it offers others. As you say there are drawbacks to inferring a name from the query string, this approach lets the users make the decision.

I'll work on that today.
