### ISSUE TITLE
GraphQL-Batch in connection field resolvers

### ISSUE THREAD

**Issue by crpahl** [rmosolgo/graphql-ruby#3775]
**Describe the bug**

We use GraphL-Batch, but we're seeing N+1 query results in `connection_type` field resolvers.

We currently use the GraphQL-Batch [association loader](https://github.com/Shopify/graphql-batch/blob/master/examples/association_loader.rb) in any resolvers returning data through Active Record relations. For example, we basically have something like the following in our emails resolver:

```
        def emails
          AssociationsLoader.for(Client, :emails).load(object).then(&:emails)
        end
```

If emails are returned as an array and we run the following query:

```
query {
  clients {
    nodes {
      emails {
        id
      }
    }
  }
}
```

this will work as expected: all clients will be batched together, the emails association will be preloaded onto all clients and all emails will be retrieved in a single query allowing us to avoid the N+1.

But if emails are returned as a `connection_type` and we run the following query:

```
query {
  clients {
    nodes {
      emails {
        nodes {
          id
        }
      }
    }
  }
}
```

the batch loader still works and loads all emails in a single query, but we noticed the following query getting run for every client:

![image](https://user-images.githubusercontent.com/506155/145650605-ec0c85b4-94ff-461b-b060-d4ee3efc0102.png)

After looking at the source, I found that was happening [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/pagination/relation_connection.rb#L106). The issue I'm seeing is that [limit](https://guides.rubyonrails.org/active_record_querying.html#limit-and-offset) won't use the preloaded results and will always fetch from the database. After experimenting with this a bit in the console, I found that [take](https://guides.rubyonrails.org/active_record_querying.html#take) will [use already loaded results](https://github.com/rails/rails/blob/a35a380c2cdc7fe032f927095545aee21a192f54/activerecord/lib/active_record/relation/finder_methods.rb#L524) from preload. Would a possible solution be to update `GraphQL::Pagination::RelationConnection` to use `take` instead of `limit` to paginate the results? I know `limit` returns an `ActiveRecord_AssociationRelation` while `take` returns a `Array` and the pagination implementation would have to be changed 🙈 but I can't think of any other way to prevent the N+1 for the preloaded association.

We can get around this for now by updating the resolver to return an array so it gets paginated through `GraphQL::Pagination::ArrayConnection` instead, but I'm not sure if this is the best approach:

```
        def emails
          AssociationsLoader.for(Client, :emails).load(object).then do |client|
            client.emails.to_a
          end
        end
```

**Versions**

`graphql` version: 1.13.0
`graphql-batch` version: 0.4.3

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report. 

I _bet_ `take` would work fine, thanks for the suggestion. (Honestly, I _thought_ `limit` returned an Array already. But it looks like I was confused.) I'll take a look, thanks. 

From the bigger picture, do you observe a performance or behavior difference between these two:

```diff
- AssociationsLoader.for(Client, :emails).load(object).then(&:emails)
+ object.emails
```

?

I ask because I've never seen effective batching for has-many relations. I would _expect_: 

- `AssociationsLoader.for(Client, :emails).load(object).then(&:emails)` would return an unbounded `AR::Relation`, just like `object.emails`
- The loader [doesn't cache between instances](https://github.com/Shopify/graphql-batch/blob/211b11a516f526e675dec78fbbd8aeac1d18d8e1/examples/association_loader.rb#L20-L23), so it doesn't provide any caching beyond instance-level caching and the AR query cache

That is to say, why use a batch loader here? (There might be a good reason -- I see this used all the time -- but I haven't figured it out yet!)

**Comment by rmosolgo** [comment]
Do any of those queries have `LIMIT`s? I think that's what I'm struggling with -- I wouldn't _want_ an unbounded query, because it might select a bazillion records from the database, loading them all into Ruby memory (via ActiveRecord) even though only a subset of them are actually required for the query.

**Comment by rmosolgo** [comment]
If that's the case -- that you want to load _all_ records, then paginate over them in memory, then I think the `.to_a` approach you mentioned previously is a good one. The whole _point_ of the `ActiveRecordRelationConnection` is to run the minimal queries to satisfy the needs of the GraphQL query. But if you want to serve a connection based on an in-memory list, then using an Array (instead of a Relation) seems ok to me. 

Otherwise, I'm not sure how to modify the relation connection to know "This is a relation, but you should treat it like an array" vs. "This is a relation, and you should run the minimal set of queries to fetch the required data" :S

**Comment by crpahl** [comment]
Sounds good, thanks! Do you still think trying to update `ActiveRecordRelationConnection` to use `take` instead of `limit` might be a good approach since I feel like that satisfies this:

> "This is a relation, but you should treat it like an array" vs. "This is a relation, and you should run the minimal set of queries to fetch the required data"

take is ultimately calling [this](https://github.com/rails/rails/blob/a35a380c2cdc7fe032f927095545aee21a192f54/activerecord/lib/active_record/relation/finder_methods.rb#L524):

```
      def find_take_with_limit(limit)
        if loaded?
          records.take(limit)
        else
          limit(limit).to_a
        end
      end
```

Which will use records from preload/includes if there are any (which there would be in our case), or still call `limit` if there aren't. Feels like it satisfies both of our cases, but I might be missing something 🤔

**Comment by rmosolgo** [comment]
Yeah, I suppose it's still worth a look!

**Comment by crpahl** [comment]
Thank you 🙏 

Just going to add a bit more context with the workaround we're doing for now. We have a pretty large schema and a large number of our fields are resolved through a `has_one`, or `has_many` association method (which leads to a _lot_ of potential N+1's). It would be pretty tedious to implement a resolver for _every_ field that is essentially just something like this:

```
        def emails
          AssociationsLoader.for(Client, :emails).load(object).then(&:emails)
        end
```

So we added a new keyword argument to the field definitions that takes the association(s) to be loaded as an argument. Here's an example of a `has_many` and a `has_one`:

```
field :emails, Types::EmailType.connection_type, preload: :emails
field :client, Types::ClientType, preload: :client
```

And we add this field extension to the field when the `preload` argument has been set:

```
      class AssociationLoader < GraphQL::Schema::FieldExtension
        def resolve(object:, arguments:, context:)
          AssociationsLoader.for(object.object.class, field.preload).load(object.object).then do
            yield(object, arguments, context)
          end
        end
      end
```

And to work around this for now I've updated it to:

```
      class AssociationLoader < GraphQL::Schema::FieldExtension
        def resolve(object:, arguments:, context:)
          AssociationsLoader.for(object.object.class, field.preload).load(object.object).then do
            resolved = yield(object, arguments, context)
            resolved.respond_to?(:to_a) && resolved.present? ? resolved.to_a : resolved
          end
        end
      end
```

I'm checking if it responds to `to_a` because it might just be a single record from a `has_one` association. And I'm checking `resolved.present` in the case where the `has_many` returns no records so I don't resolve an empty `ActiveRecord_Associations_CollectionProxy` as an empty array (which will cause errors because the object type on the field will try to resolve fields using the empty array).

But yeah, if `take` works we can go back to the simpler solution 😄
