### ISSUE TITLE
Guide: Type Errors

### ISSUE THREAD

**Issue by heflinao** [rmosolgo/graphql-ruby#3824]
Documentation for Type Errors contains links to API Doc pages that are no longer available.
Page in question: https://graphql-ruby.org/errors/type_errors.html 

Links point to API Doc, which returns 404s: https://graphql-ruby.org/api-doc/1.13.3/GraphQL 

However, https://graphql-ruby.org/api-doc/1.13.2/ works. I think it's just the version that is being pointed to hasn't been updated yet. 

Edit: after investigation, it seems that the top level "API" navigation on the website is also broken, and points to https://graphql-ruby.org/api-doc/1.13.3/GraphQL

**Comment by rmosolgo** [comment]
Derp! Thanks for letting me know. This happens sometimes when the GH Actions for building the docs and site clash with each other, pushing to `gh-pages`. I just re-ran the jobs, and it looks like everything is up to date now (it now links to 1.13.4's docs, since I just released that version). Please let me know if you have any more trouble with it!
