### ISSUE TITLE
GraphQL::Types::ISO8601DateTime.coerce_input strips hours/minutes/seconds for invalid formats

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#3827]
**Describe the bug**

When a `GraphQL::Types::ISO8601DateTime` is used as an argument, and a user forgets the seconds at the end (e.g. `2021-12-31T23:59` instead of `2021-12-31T23:59:00`), the hours / minutes / seconds are set to 0.

**Versions**

`graphql` version: 1.12.15
`rails` (or other framework): 6.0.4.4

**Steps to reproduce**

```
> GraphQL::Types::ISO8601DateTime.coerce_input("2021-12-31T23:59", nil)
=> "2021-12-31T00:00:00.000+01:00"
```

**Expected behavior**

Either throw an error, because the provided timestamp isn't a valid ISO8601 time OR be more flexible and set the seconds to 0.

**Actual behavior**

It sets the hours, minutes and seconds to zero. This is due to the rescue and parse the time using `Date.iso8601` inside the `.coerce_input` method:

https://github.com/rmosolgo/graphql-ruby/blob/b4f1f428dc7f6124e4a5205962c151471dbc9388/lib/graphql/types/iso_8601_date_time.rb#L53-L63

**Additional Context**
Is there a reason like backwards compatibility, that an invalid ISO8601 time is silently ignored and treated like a date? I also find it quiet strange to rescue an invalid date as `nil`, and don't tell the user about it.

I'm thinking about monkey patching the `GraphQL::Types::ISO8601DateTime` class, as introducing a new type would lead to a lot of changes in our code. Any advice?

**Comment by rmosolgo** [comment]
Agreed this is bad behavior and it would be better not to fall back this way. I don't remember if the `rescue` is for backwards compatibility or for something else, but maybe it could be removed in a future GraphQL-Ruby release. 

In the meantime, I can't really recommend monkey-patching built-in classes because if someone new starts working on the code, it might be an unpleasant surprise to find that, although the application code references constants from the graphql gem, those constants have been modified in the application. Instead, I'd recommend making a subclass of GraphQL-Ruby's definition and overriding the method you need. 

I'll take a look at correcting this behavior soon, thanks again for reporting it!

**Comment by 23tux** [comment]
Thanks @rmosolgo, you're one of the most committed maintainer I know :)

For reference, we went with the following approach:

```
class Iso8601Time < GraphQL::Types::ISO8601DateTime
  def self.coerce_input(str_value, _ctx)
    Time.iso8601(str_value)
  rescue ArgumentError
    raise GraphQL::Error, %(Invalid format: "#{str_value}", use YYYY-MM-DDTHH:mm:ss)
  end
end
```

- We are using it for "lesser than equal" filters, e.g. `shipments(lte: "2022-01-24")` would cause the argument to be converted into `2022-01-24T00:00:00`. And that somehow contradicts with the "equal" part of the argument name (IMO, I would assume, that I also get all shipments *including* the 24th of January)
- It forces the user to provide seconds, because that's what `Time.iso8601` wants, even if it doesn't follow the ISO8601 standard (you can see this here https://ruby-doc.org/stdlib-2.7.2/libdoc/time/rdoc/Time.html#method-i-iso8601 that it is only an alias for `#xmlschema`. I guess they refer to this standard https://www.w3.org/TR/xmlschema/#time). So I found that quiet confusing.)
