### ISSUE TITLE
Add extensions on Field class level.

### ISSUE THREAD

**Issue by gael-ian** [rmosolgo/graphql-ruby#3864]
**Is your feature request related to a problem? Please describe.**

Extensions can be passed to a single field declaration as a keyword argument or by calling the `GraphQL::Schema::Field#extension` instance method in field's declaration block, but there's currently no way to define global field extensions that will apply to all fields, to extend fields behaviors through extensions, the same way `ScopeExtension` or `ConnectionExtension` currently work.

For example, what I'd like to do is to extend all fields with a `DeprecationNotificationExtension` to automatically add a warning as response extension when a deprecated field is requested.

**Describe alternatives you've considered**

I know I can add my extension to all deprecated fields in my schema but what if someone deprecate another field and forget to add the extension to it? I'd like to do it so every deprecated field will generate warnings.

Monkey patching `GraphQL::Schema::Field` constructor to inject default extensions into the `extensions` keyword argument does not look like a good way to do it either. It accepts a lot of different argument and I don't want to have to maintain this patch on every release to ensure no new argument have been added and no default value has been changed.

**Describe the solution you'd like**

A simpler way to do it would be to be able to add a `GraphQL::Schema::Field.extension` class method to fill a default extensions set that will be applied to all fields when instanciated (instead of the current `EMPTY_ARRAY`).

**Comment by rmosolgo** [comment]
Hi! Thanks for the good question. I'd recommend taking queues from the gem's approach with connection and scope extensions (but maybe I'm biased): 

https://github.com/rmosolgo/graphql-ruby/blob/a7daf8fc1fc6e626a8597c4a5e978fddf1fdafb9/lib/graphql/schema/field.rb#L298-L313

I think a similar approach in your [`BaseField` class](https://graphql-ruby.org/type_definitions/extensions.html#customizing-fields) would address the issues you've described above:

```ruby 
class Types::BaseField < GraphQL::Schema::Field 
  def initialize(*args, **kwargs, &block)
    super 
    self.extension(DeprecationNotificationExtension)
  end 
end 
```

With that approach, _every_ field would have the extension added. (You could  also wrap the `self.extension(...)` call in `if self.deprecation_reason` to only attach the extension to fields configured with a `deprecation_reason` -- that would reduce the overhead since other fields wouldn't use the extension.) 

> Monkey patching 

About `BaseField` above, this is an essential API for GraphQL-Ruby and I expect it to keep working "forever" (I have no plans to change it and I don't know of any short-comings after adding it about 5 years ago).

How about giving that approach a try?

**Comment by gael-ian** [comment]
````ruby
def initialize(*args, **kwargs, &block)
  super 
end 
````

How did I not remember Ruby supports that kind of tricks? Of course it'll work. Sorry about that and thanks for your answer and pointing the right page in the documentation.  
By the way, maybe a link for [the extensions page](https://graphql-ruby.org/type_definitions/field_extensions.html) to [that one](https://graphql-ruby.org/type_definitions/extensions.html#customizing-fields) can prevent someone else to ask for the same thing?

Anyway, I think you can close this issue or keep it open if you think a `GraphQL::Schema::Field.extension` class method can be an interesting extension to the (already great) DSL.

**Comment by rmosolgo** [comment]
Thanks for the suggestion. I added an example and link to the field extensions doc in cd967a846. 

> `Field.extension`

I'm open to it, but I don't have plans to pursue it, so I'll close this out.
