### ISSUE TITLE
Subscriptions silently fails when query complexity is higher than max_complexity

### ISSUE THREAD

**Issue by penso** [rmosolgo/graphql-ruby#3890]
When using GraphQL subscriptions and requesting too many fields to trigger the `max_complexity`, there is no way to let the websocket client knows it requested for too much.

The only difference I see on the server-side logs is no `GraphqlChannel is streaming from graphql-event ...`. The client for the subscription response still get `more = true` (could have been a way to know there won't be any more output).

It would be nice to have a `def error` in the `GraphQL::Schema::Subscription` implemented class to choose to send something to the client in case of errors like `max_complexity` reached, or at least get `more = false` so the client knows it won't receive anything.

**Comment by rmosolgo** [comment]
Oops! I agree it should work like you expect... I wonder why it doesn't 🤔 I'll take a look soon!

**Comment by rmosolgo** [comment]
I took a look at this in #3904 and found that, runtime-wise, GraphQL is working as expected: when subscribing, if the initial subscription exceeds the max complexity, it returns an error. Could you confirm that you see an error in graphql `result` on your server? For example `pp result` in your ActionCable handler -- does it include `"errors" => [...]`? 

But maybe the example should be updated so that `more:` sent over action cable reflects those errors. Could you share the code where you prepare the `more: ...` value? (Perhaps something like: https://github.com/rmosolgo/graphql-ruby/blob/79ab2eadbd56602d12b989f3dc361b1212f9cddf/lib/graphql/subscriptions/action_cable_subscriptions.rb#L44-L47)

The simplest would be to update it to something like:

```ruby
payload = {
  result: result.to_h,
  more: result.subscription? && result.query.static_errors.empty?
}
```

If your code looks like the example in the gem, how about updating it to look like that? Let me know what you find!

**Comment by rmosolgo** [comment]
Please let me know if you're still having trouble with this issue, or if the code above helps!
