### ISSUE TITLE
Implementing GraphQL::Types::Relay::Node on an interface resets any inherited connection type

### ISSUE THREAD

**Issue by bubba** [rmosolgo/graphql-ruby#3960]
**Describe the bug**

I’m not sure if this intended behaviour or not.
When creating an interface and using it’s connection type, that connection type is based off of the default BaseConnection type that’s automatically generated, which is good.

However whenever you have that interface implement GraphQL::Types::Relay::Node, the connection type no longer seems to use the BaseConnection type.

I was seeing this whenever after implementing GraphQL::Types::Relay::Node, my edge and node types were suddenly nullable again, despite setting `edges_nullable false` etc.

**Versions**

`graphql` version: 2.0.1
`rails` (or other framework): 7.0.2
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

```ruby
module Types
  class BaseConnection < Types::BaseObject
    # add `nodes` and `pageInfo` fields, as well as `edge_type(...)` and `node_nullable(...)` overrides
    include GraphQL::Types::Relay::ConnectionBehaviors
    edges_nullable false
    edge_nullable false
    node_nullable false
  end

  module BaseInterface
    include GraphQL::Schema::Interface
    edge_type_class(Types::BaseEdge)
    connection_type_class(Types::BaseConnection)

    field_class Types::BaseField
  end

  class Foo
    include BaseInterface
    # commenting the line below restores the BaseConnection
    implements GraphQL::Types::Relay::Node
  end

  class QueryType < Types::BaseObject
    # Add `node(id: ID!) and `nodes(ids: [ID!]!)`
    include GraphQL::Types::Relay::HasNodeField
    include GraphQL::Types::Relay::HasNodesField

    # Add root-level fields here.
    # They will be entry points for queries on your schema.

    # TODO: remove me
    field :test_field, Foo.connection_type, null: false,
      description: "An example field added by the generator"
    def test_field
      "Hello World!"
    end
  end
end
```

**GraphQL query**

No query involved: just inspecting the type from the schema in graphiql.

**Steps to reproduce**

Fetch the types with the above schema

**Expected behavior**

What I would *expect* to happen is that the `Foo` interface’s connection_type is still `BaseConnection`, and the edges/node fields would be non-nil

**Actual behavior**

The `Foo` interfaces’ connection_type doesn’t seem to come from `BaseConnection` as the edges and nodes fields are nullable.

**Additional context**

I’ve attached a minimal repro repo here:
[repro.tar.gz](https://github.com/rmosolgo/graphql-ruby/files/8124522/repro.tar.gz)

It can be worked around by adding `connection_type_class Types::BaseConnection` again to the  `Foo` interface type.

**Comment by rmosolgo** [comment]
Thanks for the detailed bug report and the reproduction code. I downloaded your Rails app and I saw the same thing that you did, and I agree that implementing `Node` shouldn't clobber that configuration. 

What's happening is, `.connection_type_class` is checking `Foo`'s inheritance chain: 


```ruby
Types::Foo.ancestors
=>
[Types::Foo,
 GraphQL::Types::Relay::Node,
 GraphQL::Types::Relay::NodeBehaviors,
 Types::BaseInterface,
 GraphQL::Schema::Interface,
 GraphQL::Schema::Member::GraphQLTypeNames]
```

And `GraphQL::Types::Relay::Node` _does_ have a `connection_type_class`, which it gets from `GraphQL::Schema::Interface`: 

```ruby
GraphQL::Types::Relay::Node.ancestors
=>
[GraphQL::Types::Relay::Node,
 GraphQL::Types::Relay::NodeBehaviors,
 GraphQL::Schema::Interface,
 GraphQL::Schema::Member::GraphQLTypeNames]
 
GraphQL::Types::Relay::Node.connection_type_class
=> GraphQL::Types::Relay::BaseConnection
```

So, annoyingly, that "cuts off" the check to `Types::BaseInterface`. 

It'd be nice if it didn't work this way, and I think the implementation of `connection_type_class` should be updated to check each ancestor for a _directly_-configured class, instead of checking each ancestor's inheritance chain (https://github.com/rmosolgo/graphql-ruby/blob/bace1e4027900fc8779a5c2fd393ff6456046cea/lib/graphql/schema/member/relay_shortcuts.rb#L15-L21). 

In the meantime, you could make your own node interface: 

```ruby 
module Types::Node 
  include Types::BaseInterface
  include GraphQL::Types::Relay::NodeBehaviors 
end 
```

And _that_ interface would return the correct `connection_type_class`! 

Thanks again for the detailed report, I'll look at fixing this in the gem soon.
