### ISSUE TITLE
Cursors

### ISSUE THREAD

**Issue by devknoll** [rmosolgo/graphql-ruby#4]
Where do cursors fit in with GraphQL?

It seems like they are being used https://github.com/rmosolgo/graphql-ruby/blob/master/spec/support/nodes.rb#L115 and elsewhere to define the key that should be used in the JSON response, but everything that I've seen (like https://speakerdeck.com/relayjs/data-fetching-for-react-applications?slide=36), a "cursor" is just a field like any other, and keys are always just the name of the field requested (see https://facebook.github.io/react/blog/2015/05/01/graphql-introduction.html).

**Comment by rmosolgo** [comment]
Notice in this case, the cursor is actually _beside_ the fields of the object, not inside it:

![image](https://cloud.githubusercontent.com/assets/2231765/7482141/21740b9c-f32a-11e4-9e24-3ec7c707898b.png)


See also the use of `cursor` here as a "starting from" point:

![image](https://cloud.githubusercontent.com/assets/2231765/7482162/45cb9cb2-f32a-11e4-8053-73bb1810852e.png)

I think in a hangout with a couple FB guys I saw an example of `node(4, 6)` which returned multiple objects, using the `cursor` as key. 

I guess we'll see how things shape up in the proper spec.  They're changing the syntax in non-trivial ways since we saw the first examples, so I think I'll just wait until we get something more solid until I take action!
