### ISSUE TITLE
Custom Query Execution Strategy

### ISSUE THREAD

**Issue by AHBruns** [rmosolgo/graphql-ruby#4054]
**Is your feature request related to a problem? Please describe.**

It's more of a request for help. I have a very large query that, I've optimized with batch loader. This works, but the query is heavily nested. So, it only helps so much because the query is executed via a breadth-first traversal. For example:

```graphql
A1 {
  B1 {
    A2 {
      C2 -> needs [4, 5, 6] from table T
    }
  }
  C1 -> needs [1, 2, 3] from table T
}
```

This gets executed as:
- request A1
- load A1
- request B1
- request C1
- load B1
- load C1
- request A1
- load A1
- request C2
- load C2

In this situation, both Cs load from the same table, but they load different ids. The current implementation would execute 2 queries. This is generally fine, but if you add more levels of nesting is just gets worse. I'd like to have this just execute 1 query. To achieve this, I'd like to execute the query in a depth-first manner. E.g.

- request A1
- load A1
- request B1
- request C1
- load B1
- request A2
- load A2
- request C2
- load C2
- load C2

I'm wondering how I can get Ruby GraphQL to do this. I think I'll need to create a custom execution strategy, but I've read the docs and can't seem to figure out how, or even where to start. Any guidance would be appreciated.

**Comment by rmosolgo** [comment]
Wow, thanks for the great write-up. I think your analysis of _current behavior_ is spot-on.  How to make it do what you want... 🤔 . 

Any references to "execution strategies" are dead ends. In theory, GraphQL-Ruby used to support swapping runtimes. (I guess it _did_ for a while -- I rewrote the runtime using that mechanism, but it doesn't support swapping anymore. In reality, schema definition, execution, and Ruby-specific runtime features are all too interwoven to treat them like composable elements.) 

One detail to point out is that _GraphQL execution_ is depth-first, like you described in your ideal scenario. Without GraphQL-Batch, it'd evaluate `A1 -> B1 -> C1 -> C2`. But GraphQL-Batch (or GraphQL::Dataloader) puts a pause at each of those steps to try running other branches of the queries. So, one possible avenue would be to remove batch loading from the parent fields of `C1`, so that execution reaches it without pausing. I honestly can't _think_ of how that would help in practice, but I thought I'd mention it. 

Another possibility that I can't think is actually helpful would be pre-analyzing the query: https://graphql-ruby.org/queries/ast_analysis.html If your scenario allows you to know _ahead of time_ which IDs you'll need from "table T," you might be able to gather them at that step and pre-load your data. Lookaheads provide a similar option: https://graphql-ruby.org/queries/lookahead.html But, that only works if you can guess that data you need _before_ evaluating parent fields, which is probably not the case. But I thought I'd mention it. 

That's all that comes to mind right now. But if you give any of those a try, or if you think of other relevant details to share, please let me know and I'll try brainstorming again!
