### ISSUE TITLE
How to get GraphqlType class from String (graphqlName)

### ISSUE THREAD

**Issue by fameoflight** [rmosolgo/graphql-ruby#4111]
Not a feature or bug request, but not sure what is correct place to ask. 

What is best way to convert graphql name string  to graphql type class?

**Comment by fameoflight** [comment]
For anyone else looking for this in future 

```
context.schema.types[name]
```

**Comment by rmosolgo** [comment]
Calling `schema.types` builds a hash by merging the schema's own types, the introspection types, and any types inherited from the schema's superclasses. Since there's no reliable way to maintain a cache in this case, it builds a new hash every time. On hot codepaths, and with large schemas, this can get really expensive. 

Instead, I'd recommend `schema.get_type(name)` when you only need a single type. It performs a lookup without building the hash of types. Hope it helps!

**Comment by fameoflight** [comment]
thank you that helps. 

The code is beauty, I am learning so many patterns just reading the code. 

I closed the issue, since I didn't want to burden you, with any more issue than absolutely needed
