### ISSUE TITLE
Inconsistent `resolve_proc` behaviour

### ISSUE THREAD

**Issue by Krystosterone** [rmosolgo/graphql-ruby#413]
# The context

Calling the `resolve_proc` on a mutation yields different behaviour, depending on how many times it was called.

# The problem

I'm using ruby 2.3.1 with graphql-ruby 1.2.4.

Here's an easy way to reproduce the problem in a console:
```
irb(main):001:0> require 'graphql'
irb(main):002:0> MyAwesomeMutation = GraphQL::Relay::Mutation.define { resolve ->(*) { {} } }

irb(main):003:0> MyAwesomeMutation.field.resolve_proc.class
=> GraphQL::Field::Resolve::NameResolve
irb(main):004:0> MyAwesomeMutation.field.resolve_proc.call(nil, { input: {} }, nil)
TypeError: nil is not a symbol nor a string

irb(main):005:0> MyAwesomeMutation.field.resolve_proc.class
=> GraphQL::Relay::Mutation::MutationResolve
irb(main):006:0> MyAwesomeMutation.field.resolve_proc.call(nil, { input: {} }, nil)
=> #<#<Class:0x007f9450bc9800>:0x007f9450bc8428 @client_mutation_id=nil>
```

Note that when first accessing `MyAwesomeMutation.field.resolve_proc.class`, it returns `GraphQL::Field::Resolve::NameResolve` and produces an error as it's expecting an object with a method name of `field.name` to be called. (which I think is not the proper behaviour to begin with)

Upon calling that `resolve_proc`, it then becomes a `GraphQL::Relay::Mutation::MutationResolve` (which seems to be the intended behaviour). All subsequent attempts seem to keep the `resolve_proc` as a `GraphQL::Relay::Mutation::MutationResolve`.

# Why it's a problem

I'm trying to unit test my `resolve` procs on my mutations and can't get consistent behaviour in order to properly do so. As a workaround for now, I can run my entire test suite (which includes integration tests) and it works 99.999% of the time. The problem is that I can't run my mutation tests **only**.

I'm guessing that the reason why it works most of the time (when running the entire test suite) is that _somewhere_ in my integration tests, the `resolve_proc` is set properly on my mutations, thus making my unit tests pass.

**Comment by rmosolgo** [comment]
Thanks for the details on this! 

I think it's a problem with `GraphQL::Field` not triggering its definition block at the right time. 

The definition of `field` is deferred so that it can resolve circular dependencies. Most methods on its public API ensure that the definition has been executed (`#ensure_defined`) before doing their thing. 

However, `resolve_proc` doesn't do that! I really added it as a backdoor so that I could overwrite it for connection fields. 

The "workaround" is to use `Field#resolve` to test field resolution, instead of getting the proc, then calling it. For example, 

```ruby 
# instead of: field.resolve_proc.call(obj, args, ctx) 
field.resolve(obj, args, ctx)
```

Another work around is to extract the procs into standalone code and test _that_ instead of testing through `Relay::Mutation`. For example, 

```ruby
MyResolveProc = -> (o, a, c) { ... }
Mutation.define { resolve(MyResolveProc) } 
# Test: 
MyResolveProc.call(obj, args, ctx) 
```

Would any of those work in your case? 

(We _could_ modify `Field#resolve_proc` to call `ensure_defined`, but I'm not sure that's necessary!)

**Comment by Krystosterone** [comment]
@rmosolgo Thanks for the quick response! Both of these solutions work for my tests. I think part of the problem was my incomprehension on what the public interface for `Field` was. I realize now that looking at https://github.com/rmosolgo/graphql-ruby/blob/88330e6d2655e542f1394166a4a8c1090fe8f16d/spec/graphql/field_spec.rb#L44 would had given me a clue on how to properly test it.

As you said, I don't think `ensure_defined` is necessary in the case of `Field#resolve_proc`, so I'll be closing this issue. Thanks again!

**Comment by rmosolgo** [comment]
Glad it will work for you! Maybe I need to make a pass over the API documentation and call some things `@api private` 😬

**Comment by rmosolgo** [comment]
Backpedalling on this here: 

https://github.com/rmosolgo/graphql-ruby/pull/502

Now, instrumenters _have_ to pull out the resolve_proc in order to wrap it with custom behavior. When it doesn't `ensure_defined`, an instrumenter can get a stale value!

**Comment by Krystosterone** [comment]
🙇
