### ISSUE TITLE
Can't set default_value, prepare, etc. on argument block.

### ISSUE THREAD

**Issue by miyamotokenji** [rmosolgo/graphql-ruby#4141]
Good Day! It seems like a bunch of instance attributes for `GraphQL::Schema::Argument` has been set to readonly causing this syntax to raise a wrong number of arguments error.

```
argument :account_id, Integer, required: true, as: :account do
  description("The id of the account where the current user is requesting the card from.")
  prepare -> (account_id, _ctx) do
    return Account.find_by(id: account_id)
  end
end
```

Is this intentional? imo this looks cleaner than the proposed usage.

**Comment by rmosolgo** [comment]
Hi! No, it's not particularly intentional... Are you interested in improving it? This method would need to be updated to _receive_ new values as well as returning any previously-configured values: 

https://github.com/rmosolgo/graphql-ruby/blob/dac6685c5b28576a56b490effc3388cb379e9649/lib/graphql/schema/argument.rb#L99-L100

And we'd need a `def prepare(&block)` method  to configure a new prepare handler.
