### ISSUE TITLE
Guide: Triggers

### ISSUE THREAD

**Issue by alxx** [rmosolgo/graphql-ruby#4149]
There's no mention of `use ...` being required in the schema. I only found out about it via #2091. An example that also works with GraphiQL would also be appreciated.

**Comment by rmosolgo** [comment]
Sorry for the hangup! Glad you got to the bottom of it. Any of the implementations described in [the doc](https://graphql-ruby.org/subscriptions/implementation) have doc pages of their own which include `use ...` to set up subscriptions. I'm not sure how else to document it, since you have to _choose_ an implementation to provide to `use`.  Anyway, if you have a particular improvement in mind, please don't hesitate to open a PR using the links at the bottom of the pages :+1: 

I don't have work planned for graphiql compatibility, but since it's already discussed in #4094, i'll close this as a duplicate.
