### ISSUE TITLE
Retain order of field definitions in introspection query

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#4174]
**Is your feature request related to a problem? Please describe.**

We are building an editor that generates itself based on a GraphQL schema that is fetched using the introspection query from `GraphQL::Introspection::INTROSPECTION_QUERY`.

The problem: All the fields are sorted A-Z, so when defining fields in a particular order, this order is lost when fetching it in the introspection query.

Simple example:

```
field :title, String, null: false
field :body, String, null: false
```

Is returned as "body, title" in the introspection query.

**Describe the solution you'd like**

An option to retain the definition order of fields would be great. I was thinking about a schema directive that injects an `order` field, but I'm not sure how to do that. I've read https://graphql-ruby.org/type_definitions/directives.html and it looks like you can do schema directives, but only with fixed values?

Any help or idea is appreciated. If it is not possible, I think I have to do some in-memory tooling in Ruby to somehow inject or re-order the positions of the introspection query based on the schema.

**Comment by rmosolgo** [comment]
I added alphabetized introspection so that schema dumps would remain the same even when a project's Ruby code changed. I found that it added to much noise to code review when it wasn't normalized. 

That said, if you want to customize it, you'll find the sorting code here: 

https://github.com/rmosolgo/graphql-ruby/blob/8705c644470393d09c5cb69e0d9b631079d0b311/lib/graphql/introspection/type_type.rb#L92

https://github.com/rmosolgo/graphql-ruby/blob/8705c644470393d09c5cb69e0d9b631079d0b311/lib/graphql/introspection/type_type.rb#L78

https://github.com/rmosolgo/graphql-ruby/blob/8705c644470393d09c5cb69e0d9b631079d0b311/lib/graphql/introspection/type_type.rb#L60

https://github.com/rmosolgo/graphql-ruby/blob/8705c644470393d09c5cb69e0d9b631079d0b311/lib/graphql/introspection/schema_type.rb#L23

And there's similar code in the SDL generation module: 

https://github.com/rmosolgo/graphql-ruby/blob/8705c644470393d09c5cb69e0d9b631079d0b311/lib/graphql/language/document_from_schema_definition.rb#L62

https://github.com/rmosolgo/graphql-ruby/blob/8705c644470393d09c5cb69e0d9b631079d0b311/lib/graphql/language/document_from_schema_definition.rb#L83

https://github.com/rmosolgo/graphql-ruby/blob/8705c644470393d09c5cb69e0d9b631079d0b311/lib/graphql/language/document_from_schema_definition.rb#L280

And so on... 

To customize the order in introspection, you _could_ use the custom introspection feature: https://graphql-ruby.org/schema/introspection.html#customizing-introspection

Or, if you'd rather pursue some change to the library to support custom ordering, I'm open to helping out along the way.

**Comment by 23tux** [comment]
Thanks for the answer, I didn't know about the custom introspection queries, very cool! I'm gonna try it out and let you know the solution I've came up with. Maybe it's useful to others as well.

**Comment by rmosolgo** [comment]
I don't have any plans to work further on this issue, so I'm closing it, but if you find something that works for you, please let us know what you found!

**Comment by 23tux** [comment]
We now have the solution in production for a few weeks, and it seems to work pretty good:

```
# my_schema.rb
class MySchema < GraphQL::Schema
  introspection MyIntrospection
end
```

```
# my_introspection.rb
module MyIntrospection
  INDEX_FIELD = :__index

  class FieldType < GraphQL::Introspection::FieldType
    field INDEX_FIELD, Integer, "The fields index on the owner.", null: true

    def __index
      object.owner.fields.values.index(object)
    end
  end

  class EnumValueType < GraphQL::Introspection::EnumValueType
    field INDEX_FIELD, Integer, "The enums index on the owner.", null: true

    def __index
      object.owner.values.values.index(object)
    end
  end

  class InputValueType < GraphQL::Introspection::InputValueType
    field INDEX_FIELD, Integer, "The inputs index on the owner.", null: true

    def __index
      object.owner.arguments.values.index(object)
    end
  end
end
```
