### ISSUE TITLE
Easy way to access pagination arguments

### ISSUE THREAD

**Issue by vhiairrassary** [rmosolgo/graphql-ruby#4175]
**Is your feature request related to a problem? Please describe.**

Pagination arguments are delete as part of https://github.com/rmosolgo/graphql-ruby/blob/8705c644470393d09c5cb69e0d9b631079d0b311/lib/graphql/schema/field/connection_extension.rb#L15-L22
before passing them to a user method. We would like to access them to implement a simple cache only for our top resolvers. 

**Describe the solution you'd like**

A method in `GraphQL::Schema::Field::ConnectionExtension` (or maybe `GraphQL::Schema::Field` as it already contains `connection?`) allowing to get all arguments would be great. Since arguments are duplicated using `arguments.dup` before yielding, we think it should not be hard.

**Describe alternatives you've considered**

For now we rely on looking at `context.query.lookahead.ast_nodes` (i.e. we manually resolve the `GraphQL::Language::Nodes::VariableIdentifier` with `context.query.provided_variables` for example). This looks like a workaround (for example it does not support field aliases as we use `field.name` to find the corresponding selection).

Thank you for your hard work on this library. We are happy to open a PR if it sounds ok for you. Otherwise we will continue with our workaround, if you don't see a major issue with it.

Related issue: https://github.com/rmosolgo/graphql-ruby/issues/2822

**Comment by rmosolgo** [comment]
Hi! Great question. Here are a couple of possibilities that come to mind: 


1. If you only need this in a few cases, you could add `field ... connection: false` to completely disable automatic connection handling. To keep getting connection objects, you have to be sure to return an instance of a `GraphQL::Pagination::Connection` subclass from the field code, since it won't be added automatically. 

2. If you _always_ want this custom behavior, you can make a subclass of the built-in `ConnectionExtension` and configure it in your base field class: 

  https://github.com/rmosolgo/graphql-ruby/blob/8705c644470393d09c5cb69e0d9b631079d0b311/lib/graphql/schema/field.rb#L166-L180
  
  Then, it will use your own automatic connection handling behavior. (You could redefine `def resolve` in your subclass to _not_ delete arguments.) 
  
3. You could probably use `context[:current_arguments]` to access the whole set of arguments, including the once that were deleted with by the resolver. This isn't really well documented, but I'm pretty sure it would work! 

How about trying one of those approaches and letting me know what you find?

**Comment by vhiairrassary** [comment]
Thank you for your answer, `context[:current_arguments]` works very well 🥳 Do you want to add it in the documentation? Or it is an advanced use case?

**Comment by rmosolgo** [comment]
Glad it works for you! Feel free to add it to the documentation if you see a spot for it.

**Comment by mengqing** [comment]
@rmosolgo just wondering, with context[:current_arguments], how would I be able to convert `first`, `last`, `before` and `after` into `limit` and `offset`?

**Comment by rmosolgo** [comment]
You can't -- offset-based pagination is a separate approach to pagination from cursor-based pagination. See for example: 

- https://www.abhaynikam.me/posts/offset-based-pagination-in-graphql-ruby/
- https://gist.github.com/rmosolgo/da1dd95c297d8ed218a319ac83a05d91
