### ISSUE TITLE
Introspection Union TypeType

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#4227]
**Is your feature request related to a problem? Please describe.**

We're building an editor that is generated based on a GraphQL introspection query. To add more meta data to the introspection query, I've build a custom `GraphQL::Introspection::TypeType`, as documented here https://graphql-ruby.org/schema/introspection.html#custom-introspection-types.

The problem is, that every type get's the same introspection `GraphQL::Introspection::TypeType`, so they share all the same metadata. It would be very useful, to return specific child classes from `TypeType` based on the returned type.

**Describe the solution you'd like**
A union type like this would be super useful:

```
class Queries < GraphQL::Schema::Object
  field :my_field, String, null: false
end

module Introspection
  class FooType < GraphQL::Introspection::TypeType
    field :foo, String, null: false
  end

  class BarType < GraphQL::Introspection::TypeType
    field :bar, String, null: false
  end

  class TypeType < GraphQL::Schema::Union
    possible_types FooType, BarType

    def self.resolve_type(object, _context)
      return FooType if object.respond_to?(:foo)

      BarType
    end
  end
end

class Schema < GraphQL::Schema
  query Queries
  introspection Introspection
end

resp = Schema.execute(
  <<~GQL
    query {
      __schema {
        types {
          name
          ...on Foo { foo }
          ...on Bar { bar }
        }
      }
    }
  GQL
).to_h

puts JSON.pretty_generate(resp)
```

But it seems like when the `TypeType` class doesn't inherit from `GraphQL::Introspection::TypeType` it is somehow not picked up by the introspection system:

```
{
  "errors": [
    {
      "message": "No such type Foo, so it can't be a fragment condition",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "query",
        "__schema",
        "types",
        "... on Foo"
      ],
      "extensions": {
        "code": "undefinedType",
        "typeName": "Foo"
      }
    },
    {
      "message": "No such type Bar, so it can't be a fragment condition",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "query",
        "__schema",
        "types",
        "... on Bar"
      ],
      "extensions": {
        "code": "undefinedType",
        "typeName": "Bar"
      }
    }
  ]
}
```

**Comment by rmosolgo** [comment]
I don't have plans to support this specifically in the library since it's so far from the spec. Instead, I would suggest either: 

- Adding a `metadata` field to `TypeType` which includes your relevant metadata 
- Or, adding nullable fields to `TypeType` for the different kinds of metadata (this is how GraphQL's introspection system handles it) 

I suspect that the reason it doesn't work is because GraphQL-Ruby's code assumes that all introspection types are objects: 

https://github.com/rmosolgo/graphql-ruby/blob/f99f581a3d37112e3c003ebb2c1683108a2946ff/lib/graphql/schema/introspection_system.rb#L29-L32

It only includes `t` itself for `t`'s possible types -- but a union would have many possible types. Since the possible types aren't registered in the code above, they aren't considered to be part of the schema. 

Anyhow, if you want to add support for this usage in GraphQL-Ruby, I'd be happy to review a PR -- and I hope the link above is helpful -- but I don't plan to work further on this! Please let me know if you try one of the approaches suggested above and run into any trouble.
