### ISSUE TITLE
Broadcastable subscription's `update` method executing more than once

### ISSUE THREAD

**Issue by AaronJamesKing** [rmosolgo/graphql-ruby#4232]
**Describe the bug**

I am setting up subscription broadcasting according to [the official guide](https://graphql-ruby.org/subscriptions/broadcast.html) and it's mostly working as expected.

However, I noticed that the `update` method on my broadcastable subscription was sometimes running twice for a single trigger when multiple clients were subscribed. This would happen whether there were 2 _or more_ subscribed clients. The `update` method would not execute more than twice, though.

After a bunch of digging, I discovered that there were 2 separate instances of `GraphQL::Subscriptions::ActionCableSubscriptions`, and the 2 (or more) clients' subscriptions were divided between those instances' `@events` variables. 

There were 2 instance of `ActionCableSubscriptions` because our Puma server has 2 workers. Each worker evaluated the `NoticeSchema` class separately. When I changed the number of workers to 1 or 3 for example, I saw a corresponding change in the maximum number of times `update` ran for each trigger to the subscription.

**Versions**

`graphql` version: 2.0.14
`rails` version: 6.1.7
`actioncable` version: 6.1.7
`graphql-batch` version: 0.5.1
`redis` version: 4.8.0

**GraphQL schema**

```ruby

class Subscriptions::BaseSubscription < GraphQL::Schema::Subscription
  object_class Types::BaseObject
  field_class Types::BaseField
  argument_class Types::BaseArgument
end

class Subscriptions::Tester < Subscriptions::BaseSubscription
  subscription_scope :test_scope
  field :value, String, null: false

  def update
    Rails.logger.info "EXCUTING TESTER UPDATE"
    object
  end
end

module Types
  class SubscriptionType < Types::BaseObject
    field :tester, subscription: Subscriptions::Tester
  end
end


class NoticeSchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)
  subscription(Types::SubscriptionType)

  use GraphQL::Subscriptions::ActionCableSubscriptions,
      # See implementation of create_redis_connection further down, but probably not relevant to the issue
      redis:                 Notice::Application.create_redis_connection,
      broadcast:             true,
      default_broadcastable: true

  use GraphQL::Batch

  def self.resolve_type(abstract_type, obj, ctx)
    raise(GraphQL::RequiredImplementationMissingError)
  end
end
```

**Other app code**

```ruby

class GraphqlChannel < ApplicationCable::Channel
  def subscribed
    @subscription_ids = []
  end

  def execute(data)
    result = execute_query(data)

    payload = {
      result: result.subscription? ? { data: nil } : result.to_h,
      more:   result.subscription?,
    }

    @subscription_ids << result.context[:subscription_id] if result.context[:subscription_id]

    transmit(payload)
  end

  def unsubscribed
    @subscription_ids.each do |sid|
      NoticeSchema.subscriptions.delete_subscription(sid)
    end
  end

  private

  def execute_query(data)
    NoticeSchema.execute(
      query:          data["query"],
      context:        context,
      variables:      data["variables"],
      operation_name: data["operationName"],
    )
  end

  def context
    {
      current_user_id: current_user&.id, # Can be passed as a scope when triggering subscription updates
      current_user:    current_user,
      channel:         self,
      test_scope:      "ok",
    }
  end
end


# Notice::Application#create_redis_connection is used in NoticeSchema
module Notice
  class Application < Rails::Application
    # ...

    def self.create_redis_connection
      if !defined?(@redis_env_config)
        redis_yml_path = Rails.root.join("config/redis.yml")
        erbed_yml_file = ERB.new(File.read(redis_yml_path)).result
        config = YAML.safe_load(erbed_yml_file, aliases: true).symbolize_keys
        @redis_env_config = config[Rails.env.to_sym].symbolize_keys
      end

      Redis.new(@redis_env_config)
    end
  end
end
```

**puma.rb**

```ruby
max_threads_count = ENV.fetch("RAILS_MAX_THREADS", 5)
min_threads_count = ENV.fetch("RAILS_MIN_THREADS", max_threads_count)
threads min_threads_count, max_threads_count

worker_timeout 3600 if ENV.fetch("RAILS_ENV", "development") == "development"

port ENV.fetch("PORT", 3000)

environment ENV.fetch("RAILS_ENV", "development")

pidfile ENV.fetch("PIDFILE", "tmp/pids/server.pid")

# This line is definitely relevant to the issue! Changing the concurrency to 1, 3, etc. affected the maximum number of times that the Subscriptions::Tester#update method is called.
workers ENV.fetch("WEB_CONCURRENCY", 2)

preload_app!

plugin :tmp_restart
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
subscription Tester {
  tester {
    value
  }
}
```

**Steps to reproduce**

1. Start a Rails server with `bundle exec rails s`
2. Establish 2 or more `tester` subscriptions by opening the JS app in multiple tabs
3. Open up a Rails console with `bundle exec rails c`
4. Trigger the subscription: `NoticeSchema.subscriptions.trigger(:tester, {}, { value: "hello" }, scope: "ok")`
5. Look for the "EXCUTING TESTER UPDATE" log from `Subscriptions::Tester#update`. If there is only one, then reload a few of the tabs and try again.
6. Eventually the log will occur twice per trigger.

**Expected behavior**

The `update` method on the broadcastable subscription should only execute once per trigger

**Actual behavior**

The `update` method on the broadcastable subscription sometimes executes more than once (up to once per Puma worker)

**Additional context**

I understand why this might not technically be considered a bug and that you may not want to change any code to address this. But if you can suggest any workarounds to e.g. let the Puma workers share one instance of `ActionCableSubscriptions`, it would be greatly appreciated!

And of course thank you very much for your work on this library, it's been a pleasure to use in our app 😃

**Comment by rmosolgo** [comment]
Hi! Great question and thanks for the detailed report. I think this is expected with the current implementation, because: 

- `.trigger` sends the event out to other subscribers (https://github.com/rmosolgo/graphql-ruby/blob/f99f581a3d37112e3c003ebb2c1683108a2946ff/lib/graphql/subscriptions/action_cable_subscriptions.rb#L115)
- Each server instance receives the triggered event, checks to see if it has any active subscribers, and if it does, it prepares a payload to send to those subscribers (https://github.com/rmosolgo/graphql-ruby/blob/f99f581a3d37112e3c003ebb2c1683108a2946ff/lib/graphql/subscriptions/action_cable_subscriptions.rb#L162-L181)

So, each worker may end up running `update` one or zero times. 

There's _almost_ another possible implementation where the worker that receives the `.trigger` call prepares an update to send to clients, except that there's no guarantee that the `.trigger`-ed process will actually have any subscribers to the triggered events (but other processes _might_). In that case, it'd still have to send the event along (or somehow find a process with a subscriber?) so that an update could be prepared. 

Maybe that approach would work for broadcasted subscriptions, but it wouldn't do anything for non-broadcasted subscriptions, where an update has to be prepared for _each_ subscribed client anyways.

As far as sharing instances of ActionCableSubscriptions, I would actually expect the instance to be shared already. I would expect that, before Puma "forked" its workers, that the schema would be loaded, including the subscription instances. Could you share your debugging info that showed that there were two instances?

**Comment by rmosolgo** [comment]
Please let me know if you want to look into this further!
