### ISSUE TITLE
How to trigger a scoped subscription without the scope? or trigger to everyone

### ISSUE THREAD

**Issue by gastonmorixe** [rmosolgo/graphql-ruby#4271]
Let's say I have a particular subscription with scope `current_user_id` but there's one case I want to trigger that subscription where either I don't know who I want to target or more specifically I just want to target everyone subscribed.

If there's no way to do it, is there a workaround? 

Thank you

**Comment by rmosolgo** [comment]
Hey, great question. There's not an easy built-in way to do it, now but I think it's possible by returning `NO_UPDATE` from `def update`. In short, you'd make your `GraphQL::Schema::Subscription` subclass implement a parallel system _instead_ of `subscription_scope`. 

- Don't configure it with `subscription_scope ...`, since that doesn't support "trigger for everyone"

- When triggering, add a value to `context: ...`  (for example, `trigger_user_id:`) which indicates who should receive updates:

    ```ruby
    # Update one user, named by `user_id`:
    MySchema.subscriptions.trigger(field_name, {}, object, context: { trigger_user_id: user_id })
    # Update all users: 
    MySchema.subscriptions.trigger(field_name, {}, object, context: { trigger_user_id: "ALL_USERS" })
    ```
    
    (I _expect_ `trigger_user_id: ...` to be merged into the initial subscription context here: https://github.com/rmosolgo/graphql-ruby/blob/a6b8bf43391a3fc64fc386002606a6caf675c4ce/lib/graphql/subscriptions.rb#L129-L130)
    
- In `#update`,  check the context for a trigger-related value, and return `NO_UPDATE` if it doesn't match the current user:

    ```ruby
    def update(**arguments)
       if context[:trigger_user_id] == "ALL_USERS" || context[:trigger_user_id] == context[:current_user].id 
         # Update for this user, or update for all users 
         super 
       else 
         # This is an update for someone else 
         NO_UPDATE 
       end 
    end 
    ```

- When attaching this subscription, use `broadcastable: false`, since GraphQL-Ruby can't send the same payload to all subscribers in this case (it requires checking each subscriber individually)

Does that look like what you have in mind? Let me know how it goes if you give it a try!

**Comment by rmosolgo** [comment]
(Oh -- _you_ added that improvement for merging context ... nice! I just released it in v2.0.16.)

**Comment by gastonmorixe** [comment]
This is awesome! thank you so much @rmosolgo and happy holidays 🎄 ✨

**Comment by gastonmorixe** [comment]
(we may want to include this in the docs)

**Comment by rmosolgo** [comment]
I hope this worked alright for you 🍻

**Comment by gastonmorixe** [comment]
Yes thank you very much
