### ISSUE TITLE
Top Level Errors

### ISSUE THREAD

**Issue by Amnesthesia** [rmosolgo/graphql-ruby#4294]
According to the documentation on `Top Level Errors` at https://graphql-ruby.org/errors/execution_errors, we can add top level errors side-by-side with data, and to do that we can raise `GraphQL::ExecutionError` or a subclass of it. **However**, if a fields `resolve` method raises a GraphQL::ExecutionError, then that field will be set to nil, and the errors will be added to the array

I'd like to pass some errors along with the response as top level errors, and in my use-case these would be things such as `SessionStale`, `ModificationProhibited`, `InsufficientPermissions` — the reason I want to pass these as top level errors is that these errors don't necessarily stop the query, and could happen on any query from any part of the code base, and on the front-end we use Apollo with `errorPolicy: 'all'` to swallow these errors and display notifications to the user. 

One option would of course be to add an `errors` field to every query, but I feel like this would be a good use-case for `{ message: "You're missing one or more required permissions: :readBook, :readAuthor", extensions: { code: 'INSUFFICIENT_PERMISSIONS' } }`  or `{ message: "Your session is about to expire", extensions: { code: 'SESSION_STALE' } }` 

Would this be completely against the spec, or is there a way that I can `rescue_from(SessionStale) do |...|` and return these errors side-by-side with the query?

**Comment by rmosolgo** [comment]
Great question! The doc there _means_ to say that, even if one part of a query raises an error, the other parts of the query may still return values. 

> completely against the spec

Yes, returning data and errors from the same field is against the spec: 

> If a field error is raised while resolving a field, it is handled as though the field returned null, and the error must be added to the "errors" list in the response.

https://spec.graphql.org/draft/#sel-FANTNHCAACEWwsN

> or is there a way

🤫 There is also a way! 

https://github.com/rmosolgo/graphql-ruby/blob/016d0c9f8132466223a7837b3f0cc646277284c8/lib/graphql/query/context.rb#L14-L23


You could do: 

```ruby 
err = GraphQL::ExecutionError.new(...) # or a custom subclass of this error 
context.add_error(err) 
# continue resolution
```

That method has been available for a long time (maybe it wasn't in the spec before? Or maybe it was by accident?) and although I removed the docs for it, I don't plan to ever remove it because many people use it at this point. (Besides returning errors and data from the same field, that method is also the only way to return multiple errors from the same field, which is _also_ a violation of the spec 😅.) 

I hope that helps! Please let me know if you run into any trouble with it.

**Comment by Amnesthesia** [comment]
Haha this is exactly how I ended up solving it. I ended up creating a few application errors with a `to_graphql` method to make them into a `GraphQL::ExecutionError` and then `rescue_from(::SessionExpired)` and `context.add_error(error.to_graphql)`

Thank you!
