### ISSUE TITLE
Allow payload_type to be null in Subscription

### ISSUE THREAD

**Issue by such** [rmosolgo/graphql-ruby#4345]
I'm using what seems to be the canonical way of defining a subscription.

```
module Subscriptions
  # GameWasUpdated defines the subscription that keeps games up to date
  class GameWasUpdated < BaseSubscription
    payload_type Types::GameType
  end
end
```

This generates the following schema:

```
type Subscription {
  gameWasUpdated: Game!
}
```

This triggers an error in apollo on initial subscription because I don't attach a payload to the response of the initial subscription.

```
Missing field 'gameWasUpdated' while writing result {}
```

**Describe the solution you'd like**

Would it be possible to add an option to `payload_type`:

```
payload_type Types::GameType, null: true
```

so that it generates the following schema:

```
type Subscription {
  gameWasUpdated: Game
}
```

Thanks!

**Comment by such** [comment]
Thank you for your help. This helps achieve what I was after indeed.

That being said this does not fix the `Missing field 'gameWasUpdated' while writing result {}` because even when specifying the key can be nil it's still expected to be present in the message by Apollo.

**Comment by such** [comment]
This is fixed if I add:

```
def subscribe(*)
  { game_was_updated: nil }
end
```

To my Subscription Class. Should it be the default?

**Comment by such** [comment]
It works if I add to my Subscription class:

```
def subscribe(*)
  nil
end
```

Thank you!

**Comment by rmosolgo** [comment]
Glad it works for you -- thanks for sharing what you found!

**Comment by humphreyja** [comment]
@rmosolgo sorry to revive this issue, can spin up another one but I am curious on your thoughts here. Relay also raises errors when the initial "subscribe" returns an empty response. The solution above works but I think it should be documented as the correct way to handle this and potentially some changes to the returned payload ("no_response" should return the correct format instead of needing to implement the subscribe method). 

The biggest factor here is performance. Say you are rendering a table of like 100 items that also may contain a bit of slower data. Even just loading that page can be a lot but with pagination it isn't bad. But when you add a subscription, that initial subscription method also gets called for every single one of those 100 items. So the "default" behavior here actually ends up causing you to make a lot of extra database calls just to avoid errors from being logged from Relay (making it think we are programming it wrong) and can really back up systems just because we wanted to get notified if something changed without doing a full refresh (which is basically what the default behavior here is doing).

The solution above (shown in complete form below) will end up cutting waaaay down on database trips and satisfies how subscriptions are supposed to work. Another example would be a "on new item" subscription. You can't use the "payload_type" default behavior with that since the "subscribe" method should always return nil. 

I'm curious on your thoughts with this in case I'm missing something here and I can go forward with a PR that explores this. 

```ruby
type Types::GameType, null: true 

def subscribe(*)
  nil
end
```

---
we're running on graphql-pro (1.29.5)

**Comment by rmosolgo** [comment]
Hey @humphreyja, thanks for sharing your thoughts. IIUC the solution would be to change here: 

https://github.com/rmosolgo/graphql-ruby/blob/fa2ba4e489f8475b194f7c6985e0b25681a442c2/lib/graphql/schema/subscription.rb#L71-L72

So that it returns `nil` instead of `context.skip`. I'm open to this change -- the default behavior might even be older than Apollo and Relay -- but I'd have to think through the compatibility impact on this to avoid surprising people. 

Yes, please open a PR or new issue to propose this change. Maybe we'll get some chatter from other folks on there, thanks!
