### ISSUE TITLE
Can't rename already-named field

### ISSUE THREAD

**Issue by JonasFromell** [rmosolgo/graphql-ruby#439]
Following the docs on connections, it says to "Use a name to disambiguate...", however doing that throws an error saying "Can't rename already-named field". Not naming it throws the duplicate type definition error. At a loss here.

**Comment by rmosolgo** [comment]
Hi, sorry you hit an error! It sounds like an error coming from reusing `GraphQL::Field` objects, which is not well supported, but got a bit better in 1.2.6. 

Could you share a code sample to demonstrate the issue?

**Comment by JonasFromell** [comment]
```ruby
GraphQL::ObjectType.define do
    ...
    connection :departments, CategoryType.connection_type do
        name "DepartmentsConnection"
        ...
    end
end

GraphQL::ObjectType.define do
    ...
    connection :categories, CategoryType.connection_type do
        name "CategoriesConnection"
        ...
    end
end
```

It's taken straight from the docs, but i must be missing something.

**Comment by rmosolgo** [comment]
Oh my ... You're not missing something, it was just _wrong_! So sorry. I rewrote those in a hurry the a while back. I've removed the `name "..."` call, it's not necessary, and republished the documentation. 

Here are a few proper examples from the test fixtures:

https://github.com/rmosolgo/graphql-ruby/blob/master/spec/support/star_wars_schema.rb#L65
https://github.com/rmosolgo/graphql-ruby/blob/master/spec/support/star_wars_schema.rb#L76

The reason that error was popping up is because those `connection ... do ... end` blocks were defining a `GraphQL::Field`. `name "DepartmentsConnection"` was applied to that _field_, then `connection :departments` tried to _rename_ the field to `"departments"`. That's where the nonsense error came from! 

Sorry again, please feel free to reopen this if you have any trouble after removing those `name "..."` calls.
