### ISSUE TITLE
Directives allow MUTATION as a location, but don't allow adding to GraphQL::Schema::Mutation

### ISSUE THREAD

**Issue by ryanbahniuk** [rmosolgo/graphql-ruby#4414]
**Describe the bug**

I am attempting to add a custom directive that can be added to any mutation in my schema. My directive is a subclass of `GraphQL::Schema::Directive` and defines `locations MUTATION, QUERY`. This works no problem for adding the directive to queries because my Query root and child queries are all subclasses of `GraphQL::Schema::Object`. My base mutation is a subclass of `GraphQL::Schema::Object`, but the child mutations are subclasses of `GraphQL::Schema::Mutation`.

`GraphQL::Schema::Mutation` does not include `GraphQL::Schema::Member::HasDirectives` so it does not have a `directive` class method. If i try to manually extend HasDirectives in the mutation `assert_valid_owner` on `GraphQL::Schema::Directive` blows up.

I believe our setup of query/mutation roots mirrors the recommendations in this library's docs. Is this a bug or is our setup incorrect for a custom directive?

**Versions**

`graphql` version: 2.0.17
`rails` (or other framework): 6.0.6.1

**GraphQL schema**

```ruby
class Unauthenticated < GraphQL::Schema::Directive
  locations MUTATION, QUERY
end

class Mutation < GraphQL::Schema::Object
  graphql_name "Mutation"
  field sample_mutation, mutation: SampleMutation
end

class SampleMutation  < GraphQL::Schema::Mutation
  type SampleResponse 
  argument :input, SampleInput

  directive Unauthenticated # this blows up
  
  def resolve(input:)
  end
end

class ApplicationSchema < GraphQL::Schema
  mutation Mutation
  directives Types::Directives
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
mutation SampleMutation @unauthenticated {
  sample_mutation {
    ...
  }
}
```

**Steps to reproduce**

Add a `directive` to a `GraphQL::Schema::Mutation`.

**Expected behavior**

I would expect the method to be available. I would also expect the case statement in `assert_valid_owner` to allow Mutation as a location given that it's an available location constant in the Directive class.

**Actual behavior**

`directive` is an undefined method on `GraphQL::Schema::Mutation`.

**Comment by rmosolgo** [comment]
Hi! Great question. 

I think there's a bit of a misunderstanding because "mutation" can refer a few different different things. A mutation might be: 


- A GraphQL operation which is expected to produce side-effects in the host application. (It's in the same boat as queries and subscriptions in this regard.) This kind of mutation is a top-level entry in a GraphQL document and it looks like `mutation DoSomething { ... }`, like your example above. _This_ is the `MUTATION` directive location. 
- One of the entry points of a schema is usually called `Mutation`. It's a plain GraphQL object type, except that its fields may be referenced in the top level of mutation operations (described above). Also, it's expected that the fields on the `Mutation` type have side-effects in the host application.
- GraphQL-Ruby includes a Ruby class (`GraphQL::Schema::Mutation`) which is for defining GraphQL fields on the Mutation root type. Its analogous GraphQL concept is a _field_, and specifically, a field on the `Mutation` root type, which is expected to have side-effects.

In light of that, `@unauthenticated` in the example above might be used on mutation _operations_, like the example GraphQL string you shared. 


How do you _want_ to use `@unauthenticated`? Is it a static property of a field? If so, you could give it `locations FIELD_DEFINITION`, then attach it here: 

```ruby
field :sample_mutation, ... do 
  directive(Unauthenticated)
end 
```

That would output it in the schema definition file. Is that what you have in mind, or something else?

**Comment by ryanbahniuk** [comment]
Thank you for your thoughtful response here. I think `FIELD_DEFINITION` is exactly what we wanted here. We can close out this issue.
