### ISSUE TITLE
Extend introspection with a field that has an object type

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#4464]
**Describe the bug**

When I try to extend our introspection query with a field that has a custom object type, the field is not found when using the introspection endpoint.

**Versions**

`graphql` version: 2.0.21
`rails`: 7.0.4.3
`graphql-batch` version 0.5.2

**GraphQL schema**

```
class Queries < GraphQL::Schema::Object
  field :my_field, String, null: false
end

module Introspection
  class MyType < GraphQL::Schema::Object
    field :foo, String, null: false
    field :bar, String, null: false
  end

  class TypeType < GraphQL::Introspection::TypeType
    field :test, MyType, null: false

    def test
      {
        foo: "foo",
        bar: "bar"
      }
    end
  end
end

class Schema < GraphQL::Schema
  query Queries
  introspection Introspection
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
    query {
      __schema {
        types {
          name
          test {
            foo
            bar
          }
        }
      }
    }
```

```json
{
  "errors": [
    {
      "message": "Field 'test' doesn't exist on type '__Type'",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "query",
        "__schema",
        "types",
        "test"
      ],
      "extensions": {
        "code": "undefinedField",
        "typeName": "__Type",
        "fieldName": "test"
      }
    }
  ]
}
```

**Expected behavior**

The introspection query should return the data of the custom type `MyType`.

**Comment by rmosolgo** [comment]
Hi, thanks for the detailed report and sorry for the trouble with this! It looks like, when GraphQL-Ruby doesn't store `@references_to` for introspection types, so when it's determining which types are visible for the current query, it mistakenly ignores `MyType` since it hasn't taken note of how `MyType` is used by the introspection system.


As a work-around, you could add a reference to `MyType` in your schema: 

```diff 
  class Queries < GraphQL::Schema::Object
    field :my_field, String, null: false
+   field :__workaround, Introspection::MyType
  end
```

I realize that's probably not suitable for a public API, but I thought I'd share it just in case. 

----


This method is returning false, but should return true: 

https://github.com/rmosolgo/graphql-ruby/blob/18b0b72ce6102b663667218e16c24066640a4bf8/lib/graphql/schema/warden.rb#L327-L332

And its result _usually_ comes from here: 

https://github.com/rmosolgo/graphql-ruby/blob/18b0b72ce6102b663667218e16c24066640a4bf8/lib/graphql/schema.rb#L1193-L1195

But for introspection, it doesn't use `add_types_and_traverse` -- but maybe it should

**Comment by 23tux** [comment]
Thanks for the answer! I also think, that having a public field for this is not really suitable for our public API. I tried hiding the field like this

```diff
  class Queries < GraphQL::Schema::Object
    field :my_field, String, null: false
+   field :__workaround, Introspection::MyType do
+      def visible?(_ctx)
+        false
+      end
+    end
  end
```

Alas, this leads to the same error and the type is not found. When I put `true` in the method, it works again. Any idea, how to hide the field from my public api?

**Comment by 23tux** [comment]
Another weird behaviour I stumbled upon is this: When I have a second field on my custom introspection `FieldType` that uses an `Int` as type, the introspection query returns an error:

```
module Introspection
  class MyType < GraphQL::Schema::Object
    field :foo, GraphQL::Types::String, null: false
  end

  class FieldType < GraphQL::Introspection::FieldType
    field :test, MyType, null: false
    def test
      { foo: "foo", }
    end

    field :__index, GraphQL::Types::Int
    def __index
      0
    end
  end
end

class Queries < GraphQL::Schema::Object
  field :my_field, String, null: false
  field(:__workaround, Introspection::MyType)
end

class Schema < GraphQL::Schema
  query Queries
  introspection Introspection
end

resp = Schema.execute(
  <<~GQL
    query {
      __schema {
        types {
          fields {
            __index
            name
            test { foo }
          }
        }
      }
    }
  GQL
).to_h

puts JSON.pretty_generate(resp)
=> {
  "errors": [
    {
      "message": "Field '__index' doesn't exist on type '__Field'",
      "locations": [
        {
          "line": 5,
          "column": 9
        }
      ],
      "path": [
        "query",
        "__schema",
        "types",
        "fields",
        "__index"
      ],
      "extensions": {
        "code": "undefinedField",
        "typeName": "__Field",
        "fieldName": "__index"
      }
    }
  ]
}
```

When I change the type to use a string, it works

```diff
-    field :__index, GraphQL::Types::Int
+    field :__index, GraphQL::Types::String
```

Any idea what could cause this? I debugged a little bit and it seems that the type `GraphQL::Types::Int` is somehow not reachable:

```
From: /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/warden.rb:153 GraphQL::Schema::Warden#get_field:

    149: def get_field(parent_type, field_name)
    150:   @visible_parent_fields ||= read_through do |type|
    151:     read_through do |f_name|
    152:       binding.pry if f_name == "__index"
 => 153:       field_defn = @schema.get_field(type, f_name, @context)
    154:       if field_defn && visible_field?(field_defn, nil, type)
    155:         field_defn
    156:       else
    157:         nil
    158:       end
    159:     end
    160:   end
    161:
    162:   @visible_parent_fields[parent_type][field_name]
    163: end

[1] pry(#<GraphQL::Schema::Warden>)>
[2] pry(#<GraphQL::Schema::Warden>)> @schema.get_field(type, f_name, @context)
=> nil
[3] pry(#<GraphQL::Schema::Warden>)> Warden.from_context(@context).instance_variable_get(:@visible_and_reachable_type)
=> {#<Class:0x00007f55c3b830d8>=>true, #<Class:0x00007f55c3b82ef8>=>true, #<Class:0x00007f55c3b82d18>=>true, GraphQL::Types::Int=>false}
```

But this deep into the gem, I have no idea whats going on there 🙈

**Comment by rmosolgo** [comment]
Interestingly (sadly?) it's the same bug: 

- GraphQL-Ruby excludes any types that aren't used or referenced by the schema; 
- And, GraphQL-Ruby doesn't check introspection types to see what they reference (this is the real bug) 

So, `Int` is excluded because it's not referenced by the schema (except for introspection), but String works because `:my_field` returns String. (If `:my_field` returned `Int`, then `Int` would work in custom introspection.) 

IMO the fix is to make GraphQL-Ruby check types and fields in the introspection system, but the trick is to do it in a way that works with custom introspection and inheritance while still properly caching the result.

**Comment by 23tux** [comment]
Okay, now I got it and it makes sense.

Ok, I think for the time being, I fall back to defining the desired fields of my type directly on the schema types like `TypeType`, `FieldType` and `InputType`. The introspection query becomes a bit messy as I can't use fragments, and the namespace of the types get's a little bit cluttered, but I think that's ok for now. Extracting the definitions into a module at least drys up the code.

If you plan to support this, I'd be very happy if you give me a ping in this thread. Thank you so much for your help.
