### ISSUE TITLE
Inconsistent Behavior between 'One Of' Directive and Validator

### ISSUE THREAD

**Issue by danielkang674** [rmosolgo/graphql-ruby#4481]
**Issue Description**
When using the 'One Of' directive and the Validator in our application, I have encountered inconsistent behavior related to the acceptance of null values. The 'One Of' Directive does not allow null values, while the Validator allows them. This inconsistency can lead to confusion and unexpected behavior for developers using these features.
[Directive](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/directive/one_of.rb#L6)
[Validator](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/validator/required_validator.rb#L6)

**Steps to Reproduce**

1. Create a GraphQL schema that includes a field with the 'One Of' Directive and a Validator.
2. Configure the 'One Of' Directive to enforce a specific set of allowed arguments.
3. Configure the Validator to accept the same arguments.
4. Perform a mutation or query that includes the field with null as its value.
5. Observe the behavior of the 'One Of' Directive and the Validator.

**Expected Behavior**
I expect the 'One Of' Directive and the Validator to exhibit consistent behavior when it comes to accepting null values. If the 'One Of' Directive enforces a specific set of allowed values, the Validator should also enforce the same set of allowed values, including null if configured to allow it.

**Actual Behavior**
The 'One Of' Directive does not allow null values for the specified field. If a null value is provided, the directive throws an error, indicating that the value is not one of the allowed values. On the other hand, the Validator accepts null values for the same field without raising any error or validation failure.

**Impact**
The inconsistent behavior between the 'One Of' Directive and the Validator can lead to several issues:

1. Confusion for developers: The discrepancy between the behaviors can be confusing, especially for developers who rely on these features to enforce data integrity and consistency.
2. Unexpected application behavior: If developers assume that both the 'One Of' Directive and the Validator enforce the same set of allowed values, they may encounter unexpected behavior when null values are involved. This can result in data inconsistencies or logic errors in the application.

**Proposed Solution**
To address this inconsistency, I propose the following solutions:

1. Align the behavior of the 'One Of' Directive and the Validator to either both accept or both reject null values. This would provide a consistent experience for developers using these features.
2. Clearly document the behavior and limitations of the 'One Of' directive and the Validator regarding null values to avoid confusion and ensure proper usage.

**Volunteer for Solution Implementation**
I would like to volunteer to work on implementing the proposed solution for this issue, whichever solution is chosen.

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed writeup on this issue. I'm open to keeping these separate because of historical and practical considerations. 

- `required: { one_of: ... }` was added by request, specifically to allow `null` to be passed. The requested behavior was, "How can I ensure that the argument _is_ sent by the client, even if the provided value is `null`?" The GraphQL spec doesn't allow for this (at least -- not last time I checked!) so I added this Ruby-level validation to make it easy. This setting is allowed for fields, input objects, _or_ resolvers.
- `@oneOf` (in Ruby classes, `one_of`)  a proposal to the GraphQL spec and is only allowed on input objects. It has its own specification (er, _proposed_ spec?), but it can't be used with fields or resolvers.  I implemented it because people wanted to try out the proposed GraphQL specification feature. 

So, given that these features solve different problems, apply in different cases, and that changing them would introduce compatibility issues, I'm inclined to leave them as they are. However, I realize it leaves things in a tricky state. Maybe some improved documentation, clarifying the differences, would at least address the confusion between them. What do you think?

**Comment by rmosolgo** [comment]
I hope that background was helpful!
