### ISSUE TITLE
Performance slowdown when referencing large number of child records 

### ISSUE THREAD

**Issue by github0013** [rmosolgo/graphql-ruby#4488]
**Describe the bug**

When referencing a large number of child records (over 100,000) in a parent-child model relationship using the graphql-ruby gem, there is a significant performance slowdown. The issue occurs when the parent-child relation references thousands of records.

**Versions**

- graphql version: 2.0.22
- rails version: 5.2.4.1

**GraphQL schema**

```ruby
class ParentType < Types::BaseObject
  field :heavy_stuff, [ChildType], null: false

  def heavy_stuff
    # the point is you pull many records
    object.children.first(10000) # over 100K in the table

    # but only return a very tiny amount
    object.children.first(1)
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  parents {
    heavy_stuff {
      id
      name
    }
  }
}
```

```json
{
  "data": {
    "parents": [
      {
        "heavy_stuff": [
          {
            "id": "1",
            "name": "Dummy Child"
          }
        ]
      }
    ]
  }
}
```

**Steps to reproduce**

1. Set up a parent-child model relationship where the child records exceed 100,000.
1. Implement a method in the parent model, such as heavy_stuff, that fetches child records using the children association.
1. Create a GraphQL type for the parent model and define a field for heavy_stuff.
1. Execute a GraphQL query for the heavy_stuff field, requesting a significant number of child records.

**Expected behavior**

I expected the GraphQL query for the heavy_stuff field to perform well, even when dealing with a large number of child records. Since the actual data being returned is light, the response time should be reasonable.

**Actual behavior**

However, when querying for a significant number of child records (e.g., several thousand), I am experiencing a significant performance slowdown. Despite returning only dummy data in the heavy_stuff method, the GraphQL query takes a considerable amount of time to process and respond.

**Comment by github0013** [comment]
It seems it doesn't matter whether it's a query or mutation.   If you reference a large number of any records, no matter what you return, it gets super slow.

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble with this. 

My first guess would be that the slowdown was due to ActiveRecord loading the `.first(1000)` records from the database table and instantiating Ruby objects for each of the results. Did you do any profiling to identify where time is being spent? For example, my favorites are memory_profiler and stackprof: 


- https://github.com/SamSaffron/memory_profiler (tracking object allocations provides a _clue_ to what the code is doing)
- https://github.com/tmm1/stackprof

How about running your query with some profiling, then sharing the resulting artifacts? That would give us something to go on for further performance investigation.

**Comment by github0013** [comment]
https://github.com/flyerhzm/bullet

I had this gem in my project.  In my case, this gem was doing something weird after a graphql call was done.
Disabling this gem made everything smooth...
