### ISSUE TITLE
Scoped context is wrong inside lazy blocks

### ISSUE THREAD

**Issue by sj26** [rmosolgo/graphql-ruby#4522]
We're adding application-level database sharding. Our graphql schema means we can do a graphql query which traverses many tenants, and so many shards. Scoping sub-fields to the same shard/tenant felt like a perfect use of scoped context. So we've been doing something like this:

```ruby
class BuildEdgeType < BaseObject
  field :node, BuildType
  def node
    OrganizationLoader.for(...).load(object.node.organization_id).then do |organization|
      context.scoped_set(:organization, organization)
      object.node
    end
  end
end
```

then using this context to pass a shard into loaders resolving sub-fields, to use the right database connection.

But this has unexpected results. Outputting `current_path` makes it obvious:

```ruby
def node
  pp pre_loader_context_path: context.current_path
  OrganizationLoader.for(...).load(object.node.organization_id).then do |organization|
    context.scoped_set(:organization, organization)
    pp post_loader_context_path: context.current_path
    object.node
  end
end
```

With a query like this:

```graphql
query {
  # Can be across many shards
  builds(...) {
    edges {
      node {
        # Needs a shard selection
        pipeline { name }
      }
    }
  }
}
```

This will display something like:

```ruby
{:pre_loader_current_path=>["viewer", "builds", "edges", 0, "node"]}
{:pre_loader_current_path=>["viewer", "builds", "edges", 1, "node"]}
{:pre_loader_current_path=>["viewer", "builds", "edges", 2, "node"]}
{:post_loader_current_path=>["viewer", "builds", "edges", 0, "node"]}
{:post_loader_current_path=>["viewer", "builds", "edges", 0, "node"]}
{:post_loader_current_path=>["viewer", "builds", "edges", 0, "node"]}
```

The first three are the original resolve calls, and have the right path. Then the second three are after the promises have been resolved and have an incorrect path. Scoped context and lazy blocks seem to be incompatible.

Is this a bug? Should scoped contexts work across lazy blocks?

**Versions**

- `graphql v2.0.19`
- `graphql-batch v0.5.1`
- `graphql-pro v1.23.9`
- `rails v7.0.4.3`

**Comment by rmosolgo** [comment]
Aw man, this is tough ... I've done a lot of work to make scoped context _as_ compatible as possible with lazy resolution and `GraphQL::Dataloader` but I wouldn't be surprised if this is borderline unsolvable. 

The thing is, `def node` above returns a `Promise` from `Loader.for(...).load(...).then { ... }`, and GraphQL-Ruby sets aside the `Promise` until later. When GraphQL-Ruby is done with eager resolution, it starts calling lazy resolution handlers, so it hands off control to GraphQL-Batch. Before GraphQL-Ruby hands off control, it _tries_ to reset runtime context:

https://github.com/rmosolgo/graphql-ruby/blob/196e285de42d6e11c85eb05fb8a95e1aa489f3c9/lib/graphql/execution/interpreter/runtime.rb#L968-L983

And in this case, it _does_ reset runtime context for the _first_ lazy, which is `edges.0.node`. Then it hands off to GraphQL-Batch which calls the loader, then resolves the promises that were waiting on that loader. The problem is (I _think_) that control isn't passed _back_ to GraphQL-Ruby in between promise resolutions, so GraphQL-Ruby never gets a chance to update the runtime state in the `context` object. As a result, _all_ the promises are resolved after the _first_ update to runtime state (which has the wrong current path and the wrong scoped context -- er, at least, it _right_ for the first node, but wrong for the later nodes). 

Past GraphQL-Ruby versions (a long time ago, now) worked around this problem by creating a _new_ `context` object for every field in the result. That made this problem very easy: every field had its own `context` object and so there wasn't any resetting necessary for things like `current_path` (there wasn't scoped context at the time, but it would've worked the same way). However, it added a huge performance overhead since _every_ field resolution also instantiated a Context object. That design was replaced in order to improve performance. 

Now, it might be possible to have an opt-in per-field context which would provide stable field-specific context (like current path and scoped context) but wouldn't be created by default. 

For the time being, I can't think of a good work-around except for accessing scoped context _outside_ the lazy block... which is only possible if the value you're using _exists_ outside the lazy block 😖  

Another possible fix might be to accept a path for `scoped_set(...)`, so that if you grabbed `current_path` before the promise, you could pass it along later on. But this seems like an ugly solution because it exposes the implementation of scoped context and limits options for refactoring in the future. 

Speaking of exposing implementation details... there might be _one_ work-around that might work for now:

```diff
   def node
+   prev_current_path = context[:current_path]
     OrganizationLoader.for(...).load(object.node.organization_id).then do |organization|
+    # hack for GraphQL-Ruby scoped context bug, see https://github.com/rmosolgo/graphql-ruby/issues/4522
+     Thread.current[:__graphql_runtime_info][:current_path] = prev_current_path
       context.scoped_set(:organization, organization)
       object.node
     end
   end
```

I think that would _manually_ reset the necessary runtime context (it's different in 2.0.22, but I see you're on .19). Feel free to give that a try for now -- besides that I think the only way is a `field_context`-type object which _contains_ the necessary runtime state.

**Comment by sj26** [comment]
Thanks for diving in so quickly @rmosolgo, really appreciate it. And that all tracks with what we've been exploring.

> accept a path for `scoped_set(...)`

I did try hacking this into my local environment, and it worked a treat. But it felt like reaching too deeply into graphql from our own code.

> there might be _one_ work-around that might work for now

This looks pretty neat, but again is reaching pretty deeply into graphql internals. But it might be a practical short term solution.

I had a shower thought about this problem. The issue seems to be the eager resolution of promise chains. I wonder if there's a way to turn off that eager behaviour.

From my earlier example, we get to 

- field execute BuildEdge.node (0)
  - returns promise loader (0) with a chained block
- field execute BuildEdge.node (1)
  - returns promise loader (1) with a chained block
- field execute BuildEdge.node (2)
  - returns promise loader (2) with a chained block
- field execute lazy BuildEdge.node (0)
  - syncs promise loader (0)
    - runs the loader
      - resolves loader (0) and runs its chained block
      - resolves loader (1) and runs its chained block
      - resolves loader (2) and runs its chained block
    - returns the result of loader (0) and its chained block
- field execute lazy BuildEdge.node (1)
  - returns the already-synced result of loader (1) and its chained block
- field execute lazy BuildEdge.node (2)
  - returns the already-synced result of loader (2) and its chained block

Instead, I wonder if this could do:

- field execute BuildEdge.node (0)
  - returns promise loader (0) with a chained block
- field execute BuildEdge.node (1)
  - returns promise loader (1) with a chained block
- field execute BuildEdge.node (2)
  - returns promise loader (2) with a chained block
- field execute lazy BuildEdge.node (0)
  - syncs promise loader (0)
    - runs the loader
      - resolves loader (0) *but not its chained block*
      - resolves loader (1) *but not its chained block*
      - resolves loader (2) *but not its chained block*
  - syncs loader (0)'s chained block
  - returns the result of loader (0)'s chained block
- field execute lazy BuildEdge.node (1)
  - syncs loader (1)'s chained promise
  - returns the result of loader (1)'s chained block
- field execute lazy BuildEdge.node (2)
  - syncs loader (2)'s chained promise
  - returns the result of loader (1)'s chained block

That would mean the chained blocks are executed within the correct field execution context. But I think it requires mucking about in the bowels of graphql-batch, seeing if it can avoid doing eager chained promise synchronization.

What do you think?

**Comment by rmosolgo** [comment]
I can imagine that changing Promise resolution behavior might _work_, but it's definitely outside my wheelhouse 🙈 ! I bet it would actually be in promise-rb. For example, I think this is where a fulfilled promise updates any promises that are waiting on its value: 

https://github.com/lgierth/promise.rb/blob/a5314555fee77e8e1f566738d56b50eda0fff506/lib/promise.rb#L113

FWIW my favorite solution to Promises is GraphQL::Dataloader 😅 . But I think adding a `field_context` object would work in this case, too.

**Comment by sj26** [comment]
GraphQL::Dataloader looks really nice! We're keen to give it a try when we can explore it properly.

The graphql-batch/promise.rb route does feel like a bit of a rabbit's warren, and I was hoping someone here might have already encountered the issue or have strong advice so I could avoid jumping in. 😅 I might keep this in back pocket for the moment. It's a bit too tangential to our current project.

> But I think adding a field_context object would work in this case, too.

If there were a way to grab a persistent reference to the scoped context which would work inside the chained promise block then that would be perfect. We could hack in a backport for the moment.

Perhaps there could be a way to opt-in to a field-specific context, to exchange performance for specificity when required? Similar to the way fields without field extensions are optimised, I guess. Something like:

```
class BuildEdgeType < BaseObject
  field :node, BuildType, field_context: true
  def node
    OrganizationLoader.for(...).load(object.node.organization_id).then do |organization|
      context.scoped_set(:organization, organization)
      object.node
    end
  end
end
```

**Comment by rmosolgo** [comment]
An approach like`context.scoped` seems like a great API -- I'll take a crack at it soon and follow up here.

**Comment by sj26** [comment]
Amazing, thanks @rmosolgo!
