### ISSUE TITLE
GraphQL::Schema::DuplicateNamesError: Found two visible definitions for ...

### ISSUE THREAD

**Issue by remoteweb** [rmosolgo/graphql-ruby#4523]
Hi there people,

we are trying to modify a root level field through a changeset, and though the implementation works properly, a call to class function root_types brings the `GraphQL::Schema::DuplicateNamesError: Found two visible definitions ` error.

```
GraphQL::Schema::DuplicateNamesError:
       Found two visible definitions for `Query.chatMessages`: #<Types::BaseField Query.chatMessages: ChatMessagesResponse>, #<Types::BaseField Query.chatMessages: ChatMessagePage>
```

**Versions**
```
rails (7.0.5, 7.0.4.3)
graphql (2.0.19)
graphql-client (0.18.0)
graphql-enterprise (1.3.1, 1.2.0)
graphql-pro (1.24.6, 1.24.4)
rubocop-graphql (1.3.0, 1.1.1)
```

**GraphQL**
```ruby
class SomeSchema < GraphQL::Schema
  use GraphQL::Enterprise::Changeset::Release, changesets: [
    Changesets::Changeset20230701
  ]

  mutation(Types::Mutation)
  query(Types::Query)

  use GraphQL::Pro::OperationStore
  use GraphQL::Pro::Defer
  use GraphQL::Pro::Stream
  use GraphQL::Dataloader
  use GraphQL::Schema::Timeout, max_seconds: 25

  def self.releases
    [initial_release] + changesets.map(&:release)
  end

  def self.initial_release
    "2022-06-03"
  end
  ...
end
```

```ruby
module Types
  class Query < Types::BaseObject
    field :chat_messages, ::Types::ChatMessagesResponse
    field :chat_messages, ::Types::ChatMessage::Page, added_in: ::Changesets::Changeset20230701
  end
end
```

**Steps to reproduce**
Having a schema like this

```
class YourSchema < GraphQL::Schema
end
```

Add the changeset

```
class Changesets::Changeset20230701 < GraphQL::Enterprise::Changeset
  release "2023-07-01"
end
```

Introduce some changes in Query Type.

```ruby
module Types
  class Query < Types::BaseObject
    field :chat_messages, ::Types::Old
    field :chat_messages, ::Types::New, added_in: ::Changesets::Changeset20230701
  end
end
```

Introduce a root level query field modification in your schema, then call the YourSchema.root_types method of your schema to receive the error.

```
pry(main)> YourSchema.root_types.last.fields
```

**Expected behavior**

You should receive the fields of the Query of the default version

**Actual behavior**
```
GraphQL::Schema::DuplicateNamesError:
       Found two visible definitions for `Query.chatMessages`: #<Types::BaseField Query.chatMessages: ChatMessagesResponse>, #<Types::BaseField Query.chatMessages: ChatMessagePage>
```

**Documentation Reference**
https://graphql-ruby.org/changesets/definition.html

*You can also provide a replacement implementation by using added_in:. When a new definition has the same name as an existing definition, it implicitly replaces the previous definition in new versions of the API. For example:*

```
field :rating, Integer, "A 1-5 score for this recipe" # This definition will be superseded by the following one 
field :rating, Float, "A 1.0-5.0 score for this recipe", added_in: Changesets::FloatingPointRatings
```
*Here, a new implementation for rating will be used when clients requests an API version that includes Changesets::FloatingPointRatings. (If the client requests a version before that changeset, then the preceding implementation would be used instead.)*

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble and thanks for the detailed report. I bet we need to add some context to this introspection call so that the schema knows how to filter its members, or else, use a different method to inspect the schema so that it doesn't assert only one definition.

>  call the YourSchema.root_types method 

Just to double-check, is `#root_types` in the backtrace of the error you encounter? I wouldn't _expect_ that method to perform any assertions about types: 

https://github.com/rmosolgo/graphql-ruby/blob/978005d6bea542086893b7ee2565087865a39957/lib/graphql/schema.rb#L423-L425

Instead, I would _guess_ that the `.fields` call is raising this error. With that in mind, you could address it one of two ways: 

- If you want _all_ the field definitions, even the ones with duplicate names, you could use `.all_field_definitions` instead: 

    https://github.com/rmosolgo/graphql-ruby/blob/978005d6bea542086893b7ee2565087865a39957/lib/graphql/schema/member/has_fields.rb#L87-L97
    
    (For some reason, the [API doc](https://graphql-ruby.org/api-doc/2.0.23/GraphQL/Schema/Member/HasFields.html#all_field_definitions-instance_method) says this method is private, but it's _not_ 😖 )
    
- Alternatively, if you want to return _only_ the fields for a certain API version, you can add a context hash to the `.fields` call, for example: `MySchema.root_types.first.fields({ changeset_version: "..." })`. That way, the method would be able to reduce the set of field definitions to a single field per name. 

Want to give one of those approaches a try? Let me know what you find!

**Comment by rmosolgo** [comment]
Hi, I hope that was helpful for you! Please let me know if this error is still giving you trouble.
