### ISSUE TITLE
replacing function: with resolver

### ISSUE THREAD

**Issue by bigyansomethingfun** [rmosolgo/graphql-ruby#4530]
I am working on a project that uses graphql 1.9.9 and graphql-pro (for cancan authorization). We are upgrading to the latest version of graphql i.e 2.0.22. We have a legacy code that looks like this:
```
field "foobar", function: q
# q is a query
```
I am getting function: not found error. I read the docs and it mentions to use resolver instead. I modified it to 
```
field "foobar", resolver: q
```
but i get an error saying `undefined method type_expr `

I have looked at all the docs but couldn't get it to working. Any help would be appreciated. Thanks!

**Comment by rmosolgo** [comment]
Hi! That's right, `resolver:` is not a drop-in replacement for `function:`. A resolver is _like_ a function, but better in several ways, and has a different API (as that error points out). You should update `q` to be a Resolver class instead of a function. Did you try migrating that?

**Comment by bigyansomethingfun** [comment]
Hi! Thanks for the reply. That makes things a little clearer. Yes, the q which is a query class is now, 

```
module Api
  # A base query class for shared functionality. You should usually
  # not inherit from this class directly; instead, inherit from
  # SingularQuery or PluralQuery and use the idioms they provide.
  class Query < GraphQL::Schema::Resolver(this was GraphQL::Function)
      include Shared::SchemaMagic

    delegate :schema_id, :resolve_type, to: :class

    attr_reader :type, :description

    def initialize(&block)
      instance_eval(&block) if block
    end

    def call(_obj, _args, _ctx)
      raise "This must be implemented in each child class."
    end

    def arguments
      super().merge(@arguments || {})
    end
    # Used by the block that gets passed to the initializer
    # protected def argument(name, type, **opts)
    #   @arguments ||= {}
    #   @arguments[name.to_s] = GraphQL::Argument.define(
    #     **opts.merge(name: name.to_s, type: type)
    #   )
    # end
    protected def argument(name, type, **opts)
      @arguments ||= {}
      @arguments[name.to_s] = [type, opts]
    end
    class << self
      # Instead of polluting our modules with many different
      # subclasses of each Query for each schema, this approach
      # allows dynamically creating those subclasses based on
      # schema identifiers, such as :admin or 'Public'.
      def const_missing(schema_name)
        schema_id = schema_name.to_s.snakecase
        @schemas ||= {}
        @schemas[schema_id] ||= Class.new(self) do
          use_schema(schema_id)

          # Each Query has a definition block which exists in the
          # lexical scope of the queries_namespace, and cannot see
          # the included types without additional help:
          queries_namespace.include Shared::SchemaMagic
          queries_namespace.use_schema(schema_id)
        end
      end
      alias [] const_missing

      delegate :resolve_type, to: :base_union

      private def base_union
        schema_namespace::BaseUnion
      end
    end
  end
end
```
the main change is that GraphQL::Schema::Resolver. It's from here that I couldn't figure out the next steps.

**Comment by bigyansomethingfun** [comment]
Hi, based on your comment I rewrote the code to

```
field "foobar", q
```
Since q is a resolver class Query which i posted above. But I get  `Unhandled to_type_name input:` which comes from the `field.rb` file which probably doesn't accept class(at least that's what i figured out reading the `to_type_name` method). Am i heading in the right direction?

**Comment by bigyansomethingfun** [comment]
Hi, thanks for the reply. Sure, I will post it here with some changes in specific details.

I am using the Query class that I provided above and using it here for a SingularQuery class

```
# frozen_string_literal: true

module Api
  # A query for retrieving a single model object by ID.
  class SingularQuery < Query
    argument :id, GraphQL::Types::ID, required: true

    def initialize(model, type: nil, action: :show, &block)
      type ||= resolve_type(model).to_non_null_type

      @model = model
      @description = "Find one #{model.name} by ID"
      @action = action
      @type = type

      super(&block)
    end

    def call(_obj, args, ctx)
      @model.find(args[:id])&.tap do |result|
        ctx[:current_ability].authorize! @action, result
      end
    end
  end
end
```
The SingularQuery is used in queries for eg: abc_query

```
# frozen_string_literal: true

module Api
  module Admin
    module Queries
      # Query for a single abc
      abcQuery = SingularQuery::Admin.new(Abc)
    end
  end
end
```
And the file where I am getting no function method error is called base_schema.rb:

```
# frozen_string_literal: true

module Api
  module Schemas
    class BaseSchema < GraphQL::Schema
      use GraphQL::Tracing::NewRelicTracing

      class << self
        attr_reader :id

        def schema_id(id)
          @id = id
          schema = id.to_s.titleize.delete(" ")
          query    query_type_for(schema)
          mutation mutation_type_for(schema)
        end

        def authorize_with(klass)
          authorization Api::Strategies::CanCanStrategy, ability_class: klass
        end

        private def mutation_type_for(schema)
          fetch_or_define_in types_namespace(schema), :Mutation do
            mutations = mutations_for(schema)
            Class.new(GraphQL::Schema::Object) do
              mutations.each do |m|
                # e.g. field "fooBar", mutation: Api::Mutations::FooBar
                field m.name.split("::").last.camelcase(:lower), mutation: m
              end
            end
          end
        end

        private def query_type_for(schema)
          fetch_or_define_in types_namespace(schema), :Query do
            queries = queries_for(schema)
            Class.new(GraphQL::Schema::Object) do
              queries.each do |n, q|
                # e.g. field "fooBar", function: FooBarQuery
                field n.to_s.sub(/Query$/, "").camelcase(:lower), function: q
              end
            end
          end
        end

        private def mutations_for(schema)
          require_all_files_in schema.underscore, :mutations
          mut_mod = Api.const_get(schema)::Mutations
          extract_constants(mut_mod).select do |m|
            m.is_a?(Class) && m < GraphQL::Schema::Mutation
          end
        end

        private def queries_for(schema)
          require_all_files_in schema.underscore, :queries
          query_mod = Api.const_get(schema)::Queries
          Hash[query_mod.constants.zip(extract_constants(query_mod))]
            .select { |_, q| q.is_a? Api::Query }
        end

        private def types_namespace(schema)
          fetch_or_define_in(Api.const_get(schema), :Types) { Module.new }
        end

        # Returns all the *values* of the constants in a module.
        private def extract_constants(mod)
          mod.constants.map { |c| mod.const_get(c) }
        end

        # Require all files under the provided directory path within
        # lib/api. Does not traverse subdirectories.
        private def require_all_files_in(*path)
          path = %w[lib api] + Array(path).map(&:to_s)
          Dir[Rails.root.join(*path, "*.rb")].sort.each { |f| require f }
        end

        # If the constant exists in the module, return it; otherwise
        # set it to the value obtained by running the given block.
        private def fetch_or_define_in(mod, const)
          mod.const_set(const, yield) unless mod.constants.include?(const.to_sym)
          mod.const_get(const)
        end
      end
    end
  end
end
```

The error is at `query_type_for(schema)`, at  `field n.to_s.sub(/Query$/, "").camelcase(:lower), function: q`

This is called by schemas like admin_schema.rb

```
# frozen_string_literal: true

module Api
  module Schemas
    class AdminSchema < BaseSchema
      schema_id :admin
      authorize_with AdminAbility

      middleware Api::Middleware::ErrorMiddleware
    end
  end
end
```

Thanks!

**Comment by rmosolgo** [comment]
Hey, thanks for sharing those details. Before I dive into details, I want to ask about your upgrade, from 1.9.9 to 2.0.23. That's a very big range; it covers 4 years of releases, including _lots_ of breaking changes between 1.x and 2.x. What do you think of splitting the upgrade into smaller chunks, for example, 1.9 -> 1.13, then 1.13 -> 2.0? If you did it that way, you would benefit from all the deprecation warnings in the library that might help you migrate features one-by-one. What do you think? 

----- 

It looks like there's still some work to do on the migration. First, conceptually, Functions and Resolvers are not the same. 

- Functions were _instances_, re-used by GraphQL-Ruby during execution. They were created with `.new` and then given as `field ..., function:`.
- Resolvers are _classes_, defined in your application but initialized _only_ by GraphQL-Ruby during execution. They are given as `field ..., resolver:`. (I see that you're using GraphQL::Schema::Mutation in your code; that class is a subclass of GraphQL::Schema::Resolver, so its usage is an example of how resolvers work.) 


You'll have to re-write the `Function` as a `Resolver` class and update code to use this _other_ lifecycle. Don't initialize Resolvers -- GraphQL-Ruby will do that during execution instead. To customize a resolver, you have to create a new subclass.  

My suggestion is, before trying to update the library version, _first_ try migrating the Function system in your application to use Resolvers instead. Then, after that's working, try updating the library version. Doing them both at once will make it hard to tell whether errors are coming from the Function to Resolver migration or from the library update. 

You could even smooth the migration more by adding a _new_ Resolver class, leaving the old Function in place, and trying to make it work for just one use case first, before migrating every case. 

A few specific changes to the `Query` class: 

- Resolvers use `def resolve` instead of `def call`, and it's called with Ruby keyword arguments for each of the resolvers. 
- I'm curious to see how the `&block` was used for the old Query -- I see that `def argument` was mentioned for it. Resolvers have their own `argument ...` configuration method, just like GraphQL::Schema::Mutation, so I doubt this is necessary anymore. 
- `def initialize(&block)` should be removed because that's not the right signature for `Resolver#initialize`. 

```ruby
module Api
  # A base query class for shared functionality. You should usually
  # not inherit from this class directly; instead, inherit from
  # SingularQuery or PluralQuery and use the idioms they provide.
  class QueryResolver < GraphQL::Schema::Resolver # was GraphQL::Function
      include Shared::SchemaMagic

    delegate :schema_id, :resolve_type, to: :class

    def resolve(**kwargs)
      raise "This must be implemented in each child class."
    end

    class << self
      # Instead of polluting our modules with many different
      # subclasses of each Query for each schema, this approach
      # allows dynamically creating those subclasses based on
      # schema identifiers, such as :admin or 'Public'.
      def const_missing(schema_name)
        schema_id = schema_name.to_s.snakecase
        @schemas ||= {}
        @schemas[schema_id] ||= Class.new(self) do
          use_schema(schema_id)

          # Each Query has a definition block which exists in the
          # lexical scope of the queries_namespace, and cannot see
          # the included types without additional help:
          queries_namespace.include Shared::SchemaMagic
          queries_namespace.use_schema(schema_id)
        end
      end
      alias [] const_missing

      delegate :resolve_type, to: :base_union

      private def base_union
        schema_namespace::BaseUnion
      end
    end
  end
end
```

Then, SingularQuery might be like this: 

```ruby
module Api
  # A query for retrieving a single model object by ID.
  # 
  class SingularQueryResolver < QueryResolver
    argument :id, GraphQL::Types::ID, required: true
    
    class << self 
      # These properties of the _class_ will be assigned for subclasses 
      # then used at runtime. 
      attr_reader :model, :action 

      # Create a new subclass with the provided model and options.
      def create_resolver_class(model, type: nil, action: :show, &block)
        type ||= resolve_type(model).to_non_null_type
      
        Class.new(self) do 
          self.model = model # assign the model class to be used at runtime by #resolve
          self.action = action 
          self.type(type) # set the return type of the resolver class
          description("Find one #{model.name} by ID")
          class_eval(&block) # hand the block off to the resolver definition
        end 
      end 
    end 

    def resolve(id:)
      self.class.model.find(id)&.tap do |result|
        context[:current_ability].authorize! self.class.action, result
      end
    end
  end
end
```

You could use that class like this: 

```ruby 
# Create a resolver class that will look up a Post by ID
SingularPostQuery = Api::SingularQuery.create_resolver_class(Post) 

field :post, resolver: SingularPostQuery
```


Want to give a migration like that a try? If you run into any trouble with it, please share: 

- The source for all classes in the class hierarchy 
- The field configuration that uses one of the resolvers 
- The complete error message and backtrace you encounter, if there is one 

Then we can keep looking for next steps!

**Comment by rmosolgo** [comment]
I'm glad it was helpful! It's a tough climb to pay off tech debt, but baby steps is often the best way... 

`def resolve` is eventually called by GraphQL-Ruby during field execution. Each `field :something, ...` creates a GraphQL::Field instance. When `resolver: ...` is provided, then the GraphQL::Field instance stores a `@resolver_class = ...` variable with that class. At runtime, when the field is resolved, it creates an instance of the resolver and eventually calls `resolve` on it: 

https://github.com/rmosolgo/graphql-ruby/blob/28bccb5e68dffa95b8d8f452b15ee2ad3541fc0e/lib/graphql/schema/field.rb#L668-L673


https://github.com/rmosolgo/graphql-ruby/blob/28bccb5e68dffa95b8d8f452b15ee2ad3541fc0e/lib/graphql/schema/field.rb#L690C1-L698


`resolver_method` comes from here:

https://github.com/rmosolgo/graphql-ruby/blob/28bccb5e68dffa95b8d8f452b15ee2ad3541fc0e/lib/graphql/schema/field.rb#L36-L42

In fact, it defaults to `resolve_with_support`, because GraphQL::Schema::Resolver wraps the user-defined `def resolve` with some other stuff: 

https://github.com/rmosolgo/graphql-ruby/blob/28bccb5e68dffa95b8d8f452b15ee2ad3541fc0e/lib/graphql/schema/resolver.rb#L255-L261

In the end, whatever `def resolve` returns is used for the field value. Does that clarify its usage a bit? 

I took a look at `PluralQuery` and here is my suggested refactor: 

```ruby
module Api
  class PluralQueryResolver 
    DEFAULT_DIRECTION = :asc
    DEFAULT_LIMIT = 5
    MAX_LIMIT = 25

    # Not sure about this, it might not be necessary anymore, 
    # but I don't know how it's used
    delegate :types, to: :class

    argument :offset, Int, default_value: 0
    argument :limit,  Int, default_value: DEFAULT_LIMIT

    def create_resolver_class(model, type: nil, &block)
      Class.new(self) do 
        self.model = model 
        self.description("List many #{model.name} records")
        self.filters = {}
        self.facets = {} 
        super(&block) # Must occur before calling wrapper_for.
        self.type(wrapper_for(type))
      end 
    end

    def resolve(**kwargs)
      scope = prepare_scope(kwargs, context)
      meta = Metadata.new(scope, self.class.facets)
      scope = apply_pagination(scope, kwargs)
      scope = apply_sorting(scope, args)
      {
        items: scope.to_a, 
        meta: meta,
      }
    end 

    class << self 
      # prepare these accessors to receive class-level configuration 
      attr_accessor :filters, :facets, :module
      
      # Move definition-related methods here, so that they're class methods: 
      # - .base_scope
      # - .resolve_type
      # - .wrapper_for 
      # - .query_type_module_for
      # - .fetch_or_define 
      # - .filter 
      # - .facet
      # - maybe others -- if you get a NoMethodError during definition, try moving the method here 
    end 

    # Move runtime methods here, keeping them as instance methods. 
    # but, change instance variable accesses (like `@filters` and `@facets`)
    # to accesses to the class's reader methods `self.class.filters` and `self.class.facets`
    # - prepare_scope (but change `.base_scope` to `self.class.base_scope` since it's a class method)
    # - apply_filters
    # - apply_pagination
    # - apply_sorting

    # I think the `Metadata` class can stay just how it is.
  end 
end
```

I hope those notes are helpful. Let me know if you run into any trouble when you give the migration a try!

**Comment by bigyansomethingfun** [comment]
Hi, thanks for taking the time to go through. I just have a few questions:


Did you mean to put create_resolver_class inside `class << self` ? Because calling it 
```
PluralQuery::Admin.new.create_resolver_class(Conversation) 
```
gives me an error saying `object, context, field is required` which is true since you said `Resolver` requires the 3 arguments in it's `initialize`?

Also, shouldn't  `def resolve` method be called everytime when the `create_resolver_class` is called? If you indeed mean to put the create_resolver_class inside `class << self` then where would the `def resolve` be?   It is similar to `call` method but just of a resolver right? I don't know if that makes sense. 

Thanks!

**Comment by rmosolgo** [comment]
Ah, _yes_, I did mean to make `create_resolver_class` a class method, not an instance method. 

For `def resolve`, it should stay an instance method. When GraphQL-Ruby is running, it will create an instance of this class then call `.resolve` on it.

**Comment by bigyansomethingfun** [comment]
I think I figured it out,
```
      module FieldExtension
        def method(*args)
          
         anything here
        end
      end

      class GraphQL::Field
        class << self
          prepend FieldExtension
        end
      end
      
  ```
  
  All I needed was plain old Ruby.

**Comment by rmosolgo** [comment]
Glad to hear it's coming along smoothly! Keep me posted if anything else comes up that I can help with.
