### ISSUE TITLE
Performance of Ruby GraphQL vs. Node GraphQL

### ISSUE THREAD

**Issue by benhutton** [rmosolgo/graphql-ruby#4544]
**Describe the bug**

We've recently become curious about performance comparisons vs. node. We became curious enough to write a pair of benchmarking scripts, which you'll find here: https://gist.github.com/benhutton/3c3889b2b186d99f52725355a7b4471f

We're consistently seeing Node's performance about 5x faster than Ruby's performance.

Is this expected? We know Node tends to be faster, but we want to see if this is about what you’d expect for a performance difference.

**Versions**

`graphql` version: 2.0.24

**GraphQL schema**

See https://gist.github.com/benhutton/3c3889b2b186d99f52725355a7b4471f

Our test schema theoretically can nest infinitely. We wanted to test with something more than just a flat array.

**GraphQL query**

See https://gist.github.com/benhutton/3c3889b2b186d99f52725355a7b4471f

We're intentionally testing a pretty large query so that we can see the differences starkly.

**Steps to reproduce**

Run the two scripts in https://gist.github.com/benhutton/3c3889b2b186d99f52725355a7b4471f.

I think you need to run `npm install graphql` before running the node script

**Expected behavior**

Not sure!

**Actual behavior**

Node is 5x faster than Ruby.

**Comment by benhutton** [comment]
Some more info:

```
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
$ node -v
v18.13.0
$ npm -v
9.2.0
```

**Comment by rmosolgo** [comment]
Hey! Thanks for raising this issue. I'm definitely interested in making GraphQL-Ruby as fast as I can. 

Personally, I'd expect NodeJS to be faster than Ruby. My understanding is, when it comes to execution, NodeJS is just plain _faster_. Here are some comparison benchmarks: https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/ruby-node.html With a single exception (I think because `String#tr!` is implemented in C), NodeJS implementations outperform Ruby implementations -- and often, significantly. 

It's been a while since I compared GraphQL-JS and GraphQL-Ruby, but last I checked, GraphQL-Ruby included a lot of runtime features with no comparable GraphQL-JS feature (eg type-based authorization, list scoping, error handling, tracing, ahead-of-time analysis helpers, schema visibility (hiding types), resolver classes...). These all add overhead -- although I'm working hard to reduce it these days. 

So, with those two points in mind, a 5x difference doesn't surprise me. 

That said, if you have a different approach to comparing the runtime of these two languages, or ideas about where we might make further performance improvements to GraphQL-Ruby, I'd love to consider them. What do you think?

**Comment by benhutton** [comment]
thanks @rmosolgo. That's roughly what I suspected.

My main thought would be to see which of the "features with no comparable GraphQL-JS feature" could be made optional. We're already benefiting from #4442 and would love more options like that!
