### ISSUE TITLE
Executing mutations outside of the Graph

### ISSUE THREAD

**Issue by Amnesthesia** [rmosolgo/graphql-ruby#4552]
This isn't really a feature request or a bug report, but rather a question around using GraphQL mutations as _interactions_, and whether this is a good idea or not.

We use [ActiveInteraction](https://github.com/AaronLasseigne/active_interaction) extensively, and most things in the app are done through interactions. When we began using GraphQL, we wrote helper methods to hook mutations up to our interactions, but this has essentially lead to our mutations becoming boilerplate, where all they do is define arguments, pass them on to the interaction, check for errors, and format the response back. 

This isn't very DRY because it means we define arguments for the mutation, often the same as the arguments defined with a different DSL in the interaction, and then pass those arguments on to the interaction.

As I was looking into if there's a better way of doing this, I kind of realized that the main reason we use ActiveInteraction is because it's easy to validate arguments, add/merge errors, and compose multiple interactions (e.g calling child-interactions and merging their results). But, most of this is really just `ActiveModel::Validations` which, if we really wanted to, we could just add to our base mutation..

Calling a mutation in graphql-ruby would be `SomeMutation.new(object: {}, field: nil, context: our_graphql_context).resolve(..)`, and we could achieve pretty much the same result.

What we'd be missing then, would really just be short-hand methods for handling errors and executing mutations. 

As a test, I created something along the lines of:

```
class Mutations::Interaction < Mutations::BaseMutation
  include ActiveModel::Validations
  field :errors, [String], null: true,
        description: 'General errors, unrelated to fields'
  field :field_errors, [Types::Errors::FieldErrorType], null: true,
        description: 'Input field errors'
  field :success, Boolean, null: true,
        description: 'Whether or not this mutation was successful'

  class << self
    # Execute a mutation and return the result.
    # This doesn't coerce the results into the
    # payload as it directly calls #resolve,
    # which means Types::Errors::FieldError,
    # etc arent added do the response, which
    # is why this is merged into the response
    # hash here instead
    #
    # @param [Hash] args The arguments to pass to the mutation
    # @return [Hash] The result of the mutation
    def execute(current_user: nil, **args)
      instance = new(
        object: {},
        field: :errors,
        context: { current_user: current_user }
      )
      result = instance.resolve(**args)
      result.merge(
        success: instance.errors.empty?,
        field_errors: instance.errors.to_hash.except(:base).map { |field, messages| { field: field, messages: messages } },
        errors: instance.errors.full_messages_for(:base),
      )
    end
  end

  # Resolve another mutation but merge any errors back into
  # the current mutation before returning the results,
  # the same way compose works in ActiveInteraction
  #
  # @param [Class] other_mutation The mutation to call #resolve on
  # @param [Hash] args The arguments to pass to the mutation
  # @return [Hash] The result of the mutation
  def compose(other_mutation, current_user: nil, **args)
    instance = new(
      object: {},
      field: :errors,
      context: { current_user: current_user }
    )
    result = instance.resolve(**args)
    errors.merge!(result.errors) if result.errors.any?
    result.merge(
      success: instance.errors.empty?,
      field_errors: instance.errors.to_hash.except(:base).map { |field, messages| { field: field, messages: messages } },
      errors: instance.errors.full_messages_for(:base),
    )
  end
end
```

Then a test mutation like:

```
class Mutations::TestMutation < Mutations::Interaction
  field :message, String, null: true

  def resolve(arg1: nil)
    errors.add(:arg1, "is not ok") unless arg1 == "ok"

    return { message: "Should have errors" } if errors.any?
    { message: "OK" } 
  end
end
```

This now lets me run mutations like:

```
result = Payments::CreateInvoice.execute(...)
```

Now, my question is, while this is easily doable without a whole lot of code — is this against separation of concerns? I find that GraphQL Mutations and ActiveInteractions overlap so much that they are essentially the same thing, but one can be hooked up to the GraphQL schema and the other one cant. 

Would you rather define all business logic in mutations, **even if those mutations are not hooked up to the schema**, or would you just accept the boilerplate of creating mutations as "entrypoints" from the schema into an interaction?

**Comment by rmosolgo** [comment]
Hi, thanks for raising this great topic! 

Personally, I'd organize my application with two separate layers: 

- A business logic layer, which describes and executes the the core functions of the application 
- An interface layer, which receives inputs from the "outside world", translates them, hands them to the business logic layer, and formats the result into a client-ready result (eg, this might be JSON-API, GraphQL, a web page...) 

By isolating those two layers, I can adapt existing business logic to new interfaces (say, GRPC for internal service-to-service calls...) without bringing the baggage of a previous interface layer. Also, if needs of the business (or of the interface) change, I can modify either layer while implementing compatibility fixes in between the layers. (That is, I might change the types or names of inputs to the business logic layer to improve code consistency of the application, but in the API layer, I'd continue accepting _old_ parameters -- for compatibility -- and translate them to their new names.) 

From that standpoint, I'd make an effort to generate mutation classes _from_ ActiveInteractions, so that the business logic layer (not the API layer) remains the "source of truth." 

Besides that, there's no guarantee that `GraphQL::Schema::Mutation` will continue working outside GraphQL execution. It might work ok _now_, but there's a world of non-breaking changes to GraphQL-Ruby which _would_ break usages outside of the expected scope. So, you'd have to be ready to adapt as-needed when updating the library... 

I hope that opinion is helpful to you! If anyone else has thoughts to share, feel free to continue this conversation below.

**Comment by Amnesthesia** [comment]
Cool, that's kind of the thought that had me torn on this — and this is basically how we do it right now. We have a concern that lets us just add `mutate_with_interaction(SomeInteraction, :result_field_name, arg1: attributes[:arg1])`. May look into a way of dynamically creating input arguments based on the interaction's inputs instead, similar to how the mutations generate their payload type

Thanks for your time and quick response!
