### ISSUE TITLE
write_subscription(query, events) is confusing

### ISSUE THREAD

**Issue by sobrinho** [rmosolgo/graphql-ruby#4662]
**Is your feature request related to a problem? Please describe.**

It's not clear by the documentation in what scenarios events would have more than one event.

**Describe the solution you'd like**

Make it clear when/why/where that happens.

**Describe alternatives you've considered**

N/A

**Additional context**

When I'm writing my own implementation, I'm using a specific identifier for each event and I need to return that specific identifier on the response body so the user can connect to it:

```ruby
  def write_subscription(query, events)
    sub_user_id = user_id(query)

    sub_content = {
      query_string: query.query_string,
      variables: query.provided_variables,
      operation_name: query.operation_name,
      created_at: Time.current.to_f,
    }

    events.each do |event|
      query.context[:subscription_id] = sub_id = build_id
      query.context[:event_topic] = event.topic

      sub_content[:context] = query.context.to_h

      store.set(sub_id, GraphQL::Subscriptions::Serialize.dump(sub_content))
    end
  end
```

If there's more than one event, the second one would replace the previous one with a different identifier.

I tried a lot of different queries and I couldn't figure when events will have more than one event.

**Comment by rmosolgo** [comment]
Hi, thanks for the detailed question and sorry for the confusion! I think you're right about this being confusing. It was a long time ago, but I think I called it `events` because I was thinking, "what if the incoming `subscription { ... }` has more than one root-level selection`?" In that case, the client would subscribe to multiple events. But, the spec _forbids_ that specifically: 

> Subscription operations must have exactly one root field.

- https://spec.graphql.org/draft/#sec-Subscription-Operation-Definitions

So, this method is probably a mistake. It could have been `def write_subscription(query, event)`. 

In the subscriptions backends that I've written, `event.topic` and `event.fingerprint` are used to register with pubsub systems, as in: https://github.com/rmosolgo/graphql-ruby/blob/9eee764c074aad229ccf223de21b529dcfc0a2cd/lib/graphql/subscriptions/action_cable_subscriptions.rb#L148-L153


And that code calls `events.each`, but I think it's safe to assume there's only ever one object in `events`. 


In light of the fact that it's a mistake, I hope that makes some sense of it! Let me know if you have any further questions on it.

**Comment by sobrinho** [comment]
Roger that, thanks!
