### ISSUE TITLE
Complexity calculation is not respecting the value in the resolver

### ISSUE THREAD

**Issue by quadlol** [rmosolgo/graphql-ruby#4838]
**Describe the bug**
I have set the complexity on the resolver level, where I want to override the connection_type cost as this is a very expensive.
```
  class Schema < GraphQL::Schema
    max_complexity 100
    query_analyzer(::LogQueryComplexityAnalyzer) if Rails.env.development?
   end

  module Resolvers
    class Events < GraphQL::Schema::Resolver
      complexity 100

      type EventType.connection_type, null: false

      def resolve
        Event.all
      end
    end
  end
```
Whenever I execute the following query, the printed-out complexity is 3.

```
query {
  events(first: 1) {
    nodes {
     id
    }
  }
}
```

**Versions**

`graphql` version: 2.2.5
`rails` (or other framework): 7.1.3
other applicable versions (`graphql-batch`, etc)

**Expected behavior**

The complexity should probably be 101 or 102 (not sure how to count the nodes)

It works when I make the following changes.
```
  module Resolvers
    class Events < GraphQL::Schema::Resolver
      complexity 100

      type [Types::EventType], null: false

      def resolve
        Event.all
      end
    end
  end
```

This returns `Query has complexity of 101, which exceeds max complexity of 100` which is the expected behavior.

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report. I agree it should somehow behave differently if a custom value is configured. 

This behavior is happening because connection fields get special handling for complexity, coming from here: 

https://github.com/rmosolgo/graphql-ruby/blob/33bc196023e471b602d97d7f82aa8f16b6159d40/lib/graphql/schema/field.rb#L463

I think this is where it should check for a defined complexity value: 

https://github.com/rmosolgo/graphql-ruby/blob/33bc196023e471b602d97d7f82aa8f16b6159d40/lib/graphql/schema/field.rb#L501-L502

And for reference, here's the "normal" behavior which _does_ check for a defined value: 

https://github.com/rmosolgo/graphql-ruby/blob/33bc196023e471b602d97d7f82aa8f16b6159d40/lib/graphql/schema/field.rb#L505-L520
