### ISSUE TITLE
GraphQL 2.2.10 + GraphQL Pro operation store nil reference error

### ISSUE THREAD

**Issue by notarize-tgall** [rmosolgo/graphql-ruby#4852]
**Describe the bug**

With GraphQL 2.2.10, and GraphQL Pro persisted query store, I'm receiving nil reference exceptions when attempting to run queries.

**Versions**

`graphql` version: 2.2.10
`rails` (or other framework): 7.0.8
other applicable versions (`graphql-batch`, etc) `graphql-pro` version 1.26.3

**GraphQL schema**

**Steps to reproduce**
_Working through this still, I will update with more information as I continue digging_

Critically, I believe queries that are registered when GraphQL 2.2.10 is present behave ok, but queries that were registered on an older version but are being invoked by the new version are causing this exception.

**Expected behavior**

Queries registered with previous versions of graphql to operate correctly on new version

**Actual behavior**

Received nil reference exception

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
graphql (2.2.10) lib/graphql/language/printer.rb in print_variable_definition at line 211
graphql (2.2.10) lib/graphql/language/printer.rb in block in print_operation_definition at line 188
graphql (2.2.10) lib/graphql/language/printer.rb in each at line 187
graphql (2.2.10) lib/graphql/language/printer.rb in each_with_index at line 187
graphql (2.2.10) lib/graphql/language/printer.rb in print_operation_definition at line 187
graphql (2.2.10) lib/graphql/language/printer.rb in print_node at line 490
graphql (2.2.10) lib/graphql/language/printer.rb in block in print_document at line 71
graphql (2.2.10) lib/graphql/language/printer.rb in each at line 70
graphql (2.2.10) lib/graphql/language/printer.rb in each_with_index at line 70
graphql (2.2.10) lib/graphql/language/printer.rb in print_document at line 70
graphql (2.2.10) lib/graphql/language/printer.rb in print_node at line 466
graphql (2.2.10) lib/graphql/language/printer.rb in print at line 57
graphql (2.2.10) lib/graphql/language/nodes.rb in to_query_string at line 83
graphql (2.2.10) lib/graphql/query.rb in query_string at line 175
graphql-pro (1.26.3) lib/graphql/pro/operation_store.rb in populate_operation at line 221
graphql-pro (1.26.3) lib/graphql/pro/operation_store.rb in check_operation_store at line 312
graphql-pro (1.26.3) lib/graphql/pro/operation_store.rb in initialize at line 307
graphql (2.2.10) lib/graphql/execution/interpreter.rb in new at line 28
graphql (2.2.10) lib/graphql/execution/interpreter.rb in block in run_all at line 28
graphql (2.2.10) lib/graphql/execution/interpreter.rb in map at line 25
graphql (2.2.10) lib/graphql/execution/interpreter.rb in run_all at line 25
graphql (2.2.10) lib/graphql/schema.rb in multiplex at line 1274
graphql (2.2.10) lib/graphql/schema.rb in execute at line 1250
```

</details>

**Additional context**

Note the exception is being thrown on code introduced via https://github.com/rmosolgo/graphql-ruby/pull/4847

**Comment by notarize-tgall** [comment]
I'm still working on a minimal reproduction case, but reverting has resolved my issue. 

We had upgraded graphql pro and graphql at the same time, from 1.26.2 to 1.26.3 and 2.2.8 to 2.2.10, respectively. After reverting back to 1.2.6.2 and 2.2.8 the errors are no longer occurring.

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this and sharing the backtrace -- that's very helpful. In 2.2.10, I added support for directives on variable definitions -- but I must have missed a spot updating the printer! I'll work up a patch soon and follow up back here :+1:

**Comment by notarize-tgall** [comment]
Thanks! I'll stop digging on a repro case for now, but please let me know if more details would help.

**Comment by rmosolgo** [comment]
I thought I would be able to find a place where `GraphQL::Language::Nodes::VariableDefinition` objects were being created with `directives: nil` instead of `directives: []`, which would lead to the error described above. 

But, I checked the two places where these nodes are created, but both of them use an empty Array. Here's the Ruby parser: 

https://github.com/rmosolgo/graphql-ruby/blob/2f062fb405c687486a5bdf7fe7feb74906ecef87/lib/graphql/language/parser.rb#L124-L134


And the C Parser: 

https://github.com/rmosolgo/graphql-ruby/blob/2f062fb405c687486a5bdf7fe7feb74906ecef87/graphql-c_parser/ext/graphql_c_parser_ext/parser.y#L367-L369

Another thought I had was, if you were using the C parser, maybe it was an old version that didn't handle the new VariableDefinition directives properly. But I tested it locally, and using the old version (1.0.7) failed with a different error (There was already a bug report for that: #4851).

I also remembered that OperationStore does some language-level work itself, to normalize definitions before saving them. So I reviewed that, but realized it was unrelated: it creates strings, not ASTs, and besides, it's only used for `sync` operations, not for running queries.

Is there anywhere in your app that works with AST nodes? Maybe a `GraphQL::Language::Visitor` or a call to `Nodes::VariableDefinition.new`? 

Another interesting thing in the backtrace is that the call to `query.query_string` is going to GraphQL::Language::Printer. This means that the query was executed from an already-parsed `document: ...`. Is that right? Do you mind sharing the context on that, for example, where is the query string parsed, and how is it passed to `YourSchema.execute(...)`?

**Comment by notarize-tgall** [comment]
You're a wizard!

Yes, in our integration environment we let some code automation bypass the persisted queries. This flow caches the result of `GraphQL.parse(...)` in redis, and that's supplied via the `document` param of `execute`.
I'm looking through logs, and all the failure cases I've looked at actually did hit this flow, so this is very likely the issue.

I'm assuming the cached version from 2.2.8 is missing critical information required in 2.2.10?

**Comment by rmosolgo** [comment]
> critical information 

Well, 2.2.10 added a `directives: []` argument to `VariableDefinition#initialize`, but if nothing is provided, then the default value of `[]` is used:

```ruby
GraphQL::Language::Nodes::VariableDefinition.new
# => #<GraphQL::Language::Nodes::VariableDefinition:0x000000012813f500
#  @col=nil,
#  @default_value=nil,
#  @definition_pos=nil,
#  @directives=[],
#  @filename=nil,
#  @line=nil,
#  @name=nil,
#  @pos=nil,
#  @source_string=nil,
#  @type=nil>
```

That value would work here (since it's an array, not `nil`). But somehow in the backtrace above, `@directives` is `nil` instead of `[]`. Is it possible that the cache is injecting `directives: nil` instead? Or, if it's using `Marshal.load`, then it would create `VariableDefinition`s without a `@directives` ivar at all, which would be the same as if it were defined as `nil`.

**Comment by rmosolgo** [comment]
Hey, just checking in on this -- were you able to find anything else about where this error was coming from?

**Comment by rmosolgo** [comment]
Please let me know if you're still running into this error, otherwise I'll assume you found a solution on your side :+1:

**Comment by frostevent** [comment]
> Hey, just checking in on this -- were you able to find anything else about where this error was coming from?

Hi, confirming this issue is specific to our usage of the library, not the library itself. We do:
```
Rails.cache.fetch(key) { GraphQL.parse(query) }
```
which under the hoods does a `Marshal.dump` of the `GraphQL::Language::Nodes::Document` returned by the `GraphQL.parse` call.

When we upgrade the gem version to 2.2.10 and reboot our app, the next request to our backend will do a `Marshal.load` of the previously parsed query.

`Marshal.load` will not populate the `@directives` instance variable because it's not using the `initialize` method of `GraphQL::Language::Nodes::VariableDefinition` to create the object.

Thanks for the help!

**Comment by rmosolgo** [comment]
Interesting -- thanks for sharing what you found! I guess a fix would be to add a `"-v2"` to the `key` so that Rails would rebuild the cache. Sorry for the trouble with this!

**Comment by frostevent** [comment]
No worries, this actually shed the light on some unnecessary home made caching that wasn't needed anymore, so we ended up removing dead code :)
