### ISSUE TITLE
Add timestamp to subscription updates

### ISSUE THREAD

**Issue by sobrinho** [rmosolgo/graphql-ruby#4883]
**Is your feature request related to a problem? Please describe.**

Depending on the transport, messages might arrive out of order to the final user.

Pusher is one example, they don't guarantee that messages will be delivered in the same order they were sent to them to the user.

**Describe the solution you'd like**

Adding a timestamp on the message we can design a implementation on the front-end to discard old messages if needed.

**Describe alternatives you've considered**

We are monkey patching the gem to have the timestamp but it's brittle since it needs to revisited on every upgrade:

```ruby
def trigger(event_name, args, object, scope: nil, timestamp: nil)
  # ... copy entire method from the gem ...

  execute_all(event, object, timestamp)
end

def execute_all(event, object, timestamp)
  each_subscription_id(event) do |subscription_id|
    execute(subscription_id, event, object, timestamp)
  end
end

def execute(subscription_id, event, object, timestamp)
  # ... copy entire method from the gem ...

  deliver(subscription_id, result, context, timestamp)
end

def deliver(subscription_id, result, context, timestamp)
  payload = JSON.dump(result.to_h.merge(timestamp: timestamp))
  Pusher.trigger(subscription_id, 'update', payload)
end
```

What happens here is that we add a timestamp on the call to `trigger` and when the message is delivered to the user, we can check on that subscription if the timestamp is greater than the last received message.

Contrived example (real world we have different background jobs publishing):

```ruby
# Initial state, let's say
object.update(something: false)

# Trigger one time
RootSchema.subscriptions.trigger(:my_subscription, { id: object.id })

# Do something that eventually updates that object
object.update(something: true)

# Trigger again
RootSchema.subscriptions.trigger(:my_subscription, { id: object.id })
```

When that happens too quickly, user might receive the second trigger first and then the first trigger (out of order) causing the UI to be stale.

Even worse, the interface will render the updated data and then render the stale data, sometimes it's perceived by the user.

When we have the timestamp, we can keep track of it on the front-end and discard stale messages, example:

```javascript
const lastReceiveds = {};

onReceivedMessageFromPusher(message => {
  const lastReceived = lastReceiveds[subscription.id]

  if (lastReceived && lastReceived > message.timestamp) {
    return
  }

  lastReceiveds[subscription.id] = message.timestamp
  subscription.observer.onNext({ data: message })
})
```

**Additional context**

The example uses the timestamp of `trigger` and pass it around since it's when the trigger is called that matters, not when the message is sent to Pusher.

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed description and suggestion. I'm hesitant to build this transport-specific concern into the subscriptions system, so I'd like to consider a couple of alternatives: 

- Instead of building this into `trigger`, how about building it into `PusherSubscriptions#prepare_payload`? (You could `bundle open graphql-pro` to check out this method.) That way, it's always there when you need it, and it doesn't complicate the system for transports which don't need this. 
- Less appealing IMO, but also possible, would to include the timestamp in the schema itself, so that subscribers _request_ a `timestamp` field in the subscription, then use that value when they receive updates. It requires a little more from each client, but the upside is that it doesn't require any changes to the library. (A similar approach might be to include `object { updatedAt }` or similar, so that if the client receives an update with a stale `updatedAt`, it ignores it.) 
- Much bigger-picture: some people use Ably instead because it's way more robust. It stores messages and you can even rewind and play back things in case you lose connectivity. Depending on your use case (and how many little edge cases need to be addressed...), it might be worth switching! 

I'm glad you found a solution so far -- what do you think of those approaches?

**Comment by sobrinho** [comment]
We are not actually using the graphql-pro, instead we made our own Pusher implementation.

I'm not sure if the pro implementation suffers from that out of order issues but since it's Pusher specific, it might be.

Also, I don't see any guarantees on Ably saying that messages are delivered in the order we send them from back-end, do they?

**Comment by rmosolgo** [comment]
> delivered in the order we send them from back-end

Oh, I guess that's true -- I'm assuming they deliver them in the order they _received_, but depending on the network, they may not be _received_ in the order that they're sent. So maybe Ably's replay feature wouldn't do any good here.

**Comment by sobrinho** [comment]
It could help, we simple have to discard stale messages whenever they arrive.

If we send:

```
message one
message two
message three
```

And we receive

```
message three
message one
message two
```

All we have to do is dicard `one` since it's older than `three` and `two` since it's also older.

Using something like `createdAt` or `updatedAt` is not always feasible since not every model is backed by an ActiveRecord model or a kind of data that have that info.

**Comment by rmosolgo** [comment]
:+1: Cool, I think this can either be addressed in your custom subscriptions backend in or the schema and application, so I'm not planning on baking anything into GraphQL-Ruby.
