### ISSUE TITLE
Fragments querying same field with args not merging results

### ISSUE THREAD

**Issue by peterhorne** [rmosolgo/graphql-ruby#55]
Querying with multiple fragments on the same field (same arguments, different attributes) results in only the last fragment's attributes being returned.

```
query Routes {
  viewer {
    id,
    ...__RelayQueryFragment3mkv3m6
  }
}

fragment __RelayQueryFragment4axva8b on Viewer {
  entity(profile_name:"foobar") {
    id,
    name,
    profile_name
  },
  id
}

fragment __RelayQueryFragment5o39n4b on Viewer {
  entity(profile_name:"foobar") {
    id,
    biography,
    default_tags
  },
  id
}

fragment __RelayQueryFragment3mkv3m6 on Viewer {
  id,
  ...__RelayQueryFragment4axva8b,
  ...__RelayQueryFragment5o39n4b
}
```

(The original query generated by Relay aliased both fields with the same key, but even without the aliases the problem occurs)

Response:

```json
{
  "data": {
    "viewer": {
      "id": "...",
      "entity": {
        "id": "...",
        "biography": "",
        "default_tags": []
      }
    }
  }
}
```

I expect to also see `name` and `profile_name` fields in the response.

**Comment by rmosolgo** [comment]
Thanks for all the info about the failing case! I guess something here is failing:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/serial_execution/selection_resolution.rb#L21-L31

I wonder if it would be better to pre-process the query. Instead of merging the fields at execution-time, merge them _before_ starting to run the query. I bet you could do the same thing with variables, which would remove a lot of complexity from the execution path itself.

**Comment by rmosolgo** [comment]
Ok, I think it's fixed on master with 4f3f6b6, could you give it a try when you get a chance and let me know if it looks good to you?

**Comment by peterhorne** [comment]
Amazing! Works perfectly. Thanks :heart:

**Comment by rmosolgo** [comment]
Glad to hear it, thanks for reporting & trying it out
