### ISSUE TITLE
custom pagination

### ISSUE THREAD

**Issue by anazar** [rmosolgo/graphql-ruby#564]
It appears that the resolve method needs to return the entire resultset and then graphql will paginate.  Is there an option to set the pagination information instead of having it automatically calculated from resolve?

Here is an example of my use case:
```
connection :users, UserType.connection_type do
  resolve ->(post, args, ctx) {
    # method will return user array
    # pagination will be done in the user operation
    # operation will return pagination data and results
    results = Operations::Users.get(args)
    # pagination info would be in results[:pageInfo]
    results[:data]
  }
end
```

If querying and paginating data is being done inside of a separate method... what would be the best way to pass this pagination information through to pageInfo in graphql?

**Comment by rmosolgo** [comment]
When creating fields with the `connection ...` helper, we match the returned object with a "Connection Implementation", which is a class that implements the required methods for a connection type. 

This library includes two connections: ArrayConnection and RelationConnection. They work by accepting an not-yet-paginated collection, then paginating them according to the arguments. They do the pagination themselves so that they can fulfill the `pageInfo` fields (`hasNextPage`, etc).

To accomplish your goal, you'll can create your own connection implementation. I'm sorry it's [not well documented](https://rmosolgo.github.io/graphql-ruby/relay/connections#custom-connections), but you can find the example classes in `/lib/graphql/relay`. 

When it's implemented, you can assign it to handle resolved objects with `register_connection_implementation` (in the docs above).

Want to give it a try? Let me know how it goes!
