### ISSUE TITLE
mutation return type

### ISSUE THREAD

**Issue by jazzdragon** [rmosolgo/graphql-ruby#615]
Hi,
Thanks for your work on this.
I'm implementing a graphql server that talks to an apollo front-end.
Queries work well, but I'm encountering some issues with Mutations.
I'm trying to create an addUser mutation, following the example in the docs. My code:
```
UserMutationType = GraphQL::InputObjectType.define do
  name "UserMutationType"
  description "user mutation"

  argument :username, !types.String do
    description "username"
  end

  argument :email, types.String do
    description "email"
  end

  argument :password, types.String do
    description "password"
  end
end

MutationRoot = GraphQL::ObjectType.define do
  name "Mutation"

  field :addUser, User do
    description "Registers a user."

    argument :user, UserMutationType
    resolve ->(t, args, c) {
      username = args['user']['username']
      email = args['user']['email']
      password = args['user']['password']
      User.create(
        username: username,
        email: email,
        password: password,
        password_confirmation: password
      )
    }
  end
end

Schema = GraphQL::Schema.define do
  query QueryRoot
  mutation MutationRoot
end
```

I'm getting:
```
"exception": "#<GraphQL::Schema::InvalidTypeError: Mutation is invalid: field \"addUser\" type must return GraphQL::BaseType, not Class (User(id: integer, username: string, email: string...
```

not sure what to do here...

Also, if I put these mutation definitions in a separate folder (e.g. `mutations`) I get `MutationRoot not defined` error. Looks like a load order issue to me, but I'm not a rails expert to be honest...

**Comment by rmosolgo** [comment]
Hi! Sorry about the error. 

My first guess is to change the second argument to `field ...` from `User` (whose definition is not shown above) to `UserMutationType` (the input type defined above):

```diff 
-   field :addUser, User do
+   field :addUser, UserMutationType do
```

What happens when you switch that? 

Rails expects folder names to match namespace, so if you add a file to `mutations/`, you'll have to prefix the Ruby constant with `Mutations::`. For example, if the file is `mutations/mutation_root.rb`, you should call it `Mutations::MutationRoot = ...` in the Ruby code.

**Comment by jazzdragon** [comment]
Bingo!
Thank you kind sir.
