### ISSUE TITLE
Response keys are not ordered

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#623]
The GraphQL spec says that serialized responses should order their key-value pairs to match the incoming query. This implementation has never complied with that specification. 

This is because all around, hashes are used to represent selection sets, and they are merged willy-nilly, resulting in unordered collections. The fix would be to introduce a proper ordered collection which tracks `key` and `value` on each item instead of using hashes for that purpose.

Nobody has requested this feature, but it bugs me to be out of spec, so I thought I'd open this issue in case someone comes looking for it!

**Comment by mvgijssel** [comment]
Just upgraded from 1.4.4 to 1.5.4 and we now have some test failures because of changed approvals [Approvals](https://github.com/kytrinyx/approvals). We test the output of our JSON api, which uses GraphQL internally, because we want to be sure nothing changes (possibly breaking client integrations). 

Note this is a minor annoyance. Can't imagine client integration breaking on a slightly different ordering.

**Comment by rmosolgo** [comment]
I just re-read your comment and followed the link to Approvals! I would love to read a blogpost about how you use that for testing 😉  I've been thinking about adding snapshot testing to GraphQL, but I think I'll try out that gem instead.

**Comment by rmosolgo** [comment]
Besides the minor annoyance, this doesn't seem to bother anyone, so I'm closing it. We can reopen (or open a new issue) if this does break something, someday.
