### ISSUE TITLE
Runtime error mutating lazy method map on JRuby

### ISSUE THREAD

**Issue by tjsousa** [rmosolgo/graphql-ruby#628]
While using `graphql-ruby` with JRuby 9.1.0.7 we're seeing what it looks like a concurrency issue (only happens randomly but it is frequent enough to become problematic) when calling `Graphql.execute` inside the lib's code (and before executing any application-specific code).

I'll try to dig a bit deeper into this, but at first sight [it doesn't look like this code is thread-safe](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/lazy/lazy_method_map.rb#L12-L19). The problem is that multiple threads can be calling this code concurrently and while one is iterating (`each` and `each_key` are called in this class), another may be mutating the hash.

Here's a simpler snippet that reproduces the error
```ruby
irb(main):057:0>  $hash = Hash.new do |h, key|
irb(main):058:1*   value = h.each_key.find { |key| sleep 1 }
irb(main):059:1>   if value.nil?
irb(main):060:2>     h[key] = nil
irb(main):061:2>   else
irb(main):062:2*     h[key] = value
irb(main):063:2>   end
irb(main):064:1> end
irb(main):112:0> 100.times do
irb(main):113:1*    Thread.new do
irb(main):114:2*      begin
irb(main):115:3*        $hash[rand()]
irb(main):116:3>     rescue => e
irb(main):117:3>       puts e
irb(main):118:3>     end
irb(main):119:2>   end
irb(main):120:1> end
=> 100
irb(main):082:0> can't add a new key into hash during iteration
can't add a new key into hash during iteration
can't add a new key into hash during iteration
can't add a new key into hash during iteration
can't add a new key into hash during iteration
...
irb(main):122:0* $hash.size
=> 4
```

Exception trace:
<img width="1231" alt="screen shot 2017-03-22 at 13 48 13" src="https://cloud.githubusercontent.com/assets/389917/24200841/410f0c96-0f06-11e7-9310-59834ac8baa2.png">

**Comment by tjsousa** [comment]
My question here is if the `Schema` is supposed to be thread-safe, or should I have one per thread anyway?

Using a [`Concurrent::Hash`](http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Hash.html) should be enough to solve this in the lib:

```ruby
irb(main):056:0> require 'concurrent'
irb(main):057:0>  $hash = Concurrent::Hash.new do |h, key|
irb(main):058:1*   value = h.each_key.find { |key| sleep 1 }
irb(main):059:1>   if value.nil?
irb(main):060:2>     h[key] = nil
irb(main):061:2>   else
irb(main):062:2*     h[key] = value
irb(main):063:2>   end
irb(main):064:1> end
irb(main):112:0> 100.times do
irb(main):113:1*    Thread.new do
irb(main):114:2*      begin
irb(main):115:3*        $hash[rand()]
irb(main):116:3>     rescue => e
irb(main):117:3>       puts e
irb(main):118:3>     end
irb(main):119:2>   end
irb(main):120:1> end
=> 100
irb(main):122:0* $hash.size
=> 100
```

I'll open a PR with the fix.

**Comment by rmosolgo** [comment]
It _should_ be threadsafe! I thought I was ok since, even if different threads were working on that hash, they would always put the same values in it. But I didn't know about the "can't modify while mutating" issue! 

Thanks for all the details here, that's so helpful. 

I wonder, could we make that code threadsafe by manually looking up ancestors instead of iterating over the hash? For example, 

```diff 
-            registered_superclass = h.each_key.find { |lazy_class| value_class < lazy_class }
+            registered_superclass = lazy_class.ancestors.find { |parent_class| h[parent_class] }
```

Do you think that would do the trick?

**Comment by rmosolgo** [comment]
Hmm, there's still an `#each` method there, I wonder why that is needed ...

**Comment by rmosolgo** [comment]
I haven't tried to replicate the bug yet but I was thinking of an approach like this:

https://github.com/rmosolgo/graphql-ruby/compare/threadsafe-lazy-method-map

**Comment by ivoanjo** [comment]
Hello there! I wanted to add two notes from my own experience:

* This issue is also reproducible on MRI
* I believe that getting read of the `each` probably makes this "safe enough" on MRI, but not on JRuby, as you'll still have multiple threads writing to the hash at the same time, which can lead to issues (for instance when resizing the backing data structures). I would still suggest either a concurrent map or a lock is used when writing to the hash.

**Comment by rmosolgo** [comment]
Oh, thanks for those details! I'm trying to decide whether to add a dependency on `concurrent-ruby` or whether to make it optional, ie, detect whether it is present and use it if it's available. Or, I wonder if I can add a JRuby-only dependency... 

I think concurrent-ruby is a fair dependency to add, especially since it's used by recent Rails versions already.

**Comment by rmosolgo** [comment]
Wow, Concurrent::Hash's [implementation](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/hash.rb#L4-L24) is quite simple, I wouldn't mind doing something similar in this library. 

Perhaps another option would be to synchronize access with a mutex. Anyhow, we can't fix what we can't see, I guess the first step is to get a failing test together! (And get the travis running on JRuby.)

**Comment by ivoanjo** [comment]
There's also a `Concurrent::Map` which is basically a hash with a slightly enhanced interface that has better performance on JRuby as it is backed by a [`ConcurrentHashMap`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html) instance.

But I think just locking would be more than enough to make this go away :)

**Comment by rmosolgo** [comment]
I've pushed a change here: https://github.com/rmosolgo/graphql-ruby/pull/631

But I'm a bit out of my depth. Would anyone mind taking a look there and giving me a review?

**Comment by ivoanjo** [comment]
Thanks for the quick feedback @rmosolgo I'll take a look asap!

**Comment by tjsousa** [comment]
Thanks for the quick response @rmosolgo ! I'll also take a look.
