### ISSUE TITLE
Let return_type decide how to resolve data inside mutation

### ISSUE THREAD

**Issue by developer88** [rmosolgo/graphql-ruby#683]
i have a complex type for query that has several fields and thus several resolvers. i am working on mutation and would like to return this type back to the user. Since there are many resolvers inside the type i would like this type to execute necessary resolvers based for the fields that user requests.

meanwhile i still need to execute resolve function of the mutation itself.

```
SimpleMigration = GraphQL::Relay::Mutation.define do
    name 'SimpleMigration'

    return_type ComplexType

    resolve ->(_, inputs, ctx) {
       # do mutation
       # let ComplexType decide what and how to resolve
    }
end


ComplexType = GraphQL::ObjectType.define do
  name "ComplexType"

  field  :one, !types.Boolean do
    resolve(...)
  end

  field  :two, !types.Boolean do
    resolve(...)
  end

  field  :three, !types.Boolean do
    resolve(...)
  end
end
```

Each resolver here is not just map data from the response of one API call, but do some multiple calls to different endpoints.

**Comment by rmosolgo** [comment]
Hi there! I think it should work as you're describing. Can you help me understand why you opened this issue? Did you try it, and you found some unexpected behavior? Or are you requesting a new feature?

**Comment by developer88** [comment]
@rmosolgo This is a call for help.

This part ` # let ComplexType decide what and how to resolve` is unknown how to solve.

**Comment by rmosolgo** [comment]
Hmmm, I expect that: 

- Use `return_type` to specify the return type (like you did above)
- Mutation's `resolve` returns an object 
- That object is passed to `return_type`'s resolvers, based on the user request

That way, all the resolvers on `ComplexType` receive the `obj` which was returned from `SimpleMigration`.  How does that sound?

**Comment by developer88** [comment]
@rmosolgo partially yes. What object should mutation return?

**Comment by rmosolgo** [comment]
It's "up to you" 😆 

I mean, consider what data is required for the `resolve` functions of `ComplexType`. If it requires arguments from the mutation, you could return an object containing those arguments. If it requires the query's `root_value:` (which is `obj` in the mutation), you could return an object which exposes that value. 

You might write a custom Ruby class for this use, just something whose instance variables store the data which is required by child resolve functions. 

But, I can't really answer, because I don't know the purpose of the mutation or the purpose of `ComplexType`'s resolve functions! 

How does that sound?

**Comment by rmosolgo** [comment]
Hope that was helpful! Please feel free to reopen if there's more to do here.

**Comment by developer88** [comment]
@rmosolgo thanks for your help. The main difficulty for me in the end was that i had to return at least empty key for every field inside the payload.

```ruby
OpenStruct.new({
  one: {},
  two: {},
  three: {}
})
```

Now, it looks like it works :)
