### ISSUE TITLE
Arguments#to_h with Symbol Keys?

### ISSUE THREAD

**Issue by timscott** [rmosolgo/graphql-ruby#858]
[`Arguments#[]`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/arguments.rb#L23) has indifferent access (string or symbol key). I generally prefer to use symbols for keys. But I often find it necessary to break apart the args in order to use `#delete` or `#extract`, so I call [`#to_h`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/arguments.rb#L37), which returns a deep hash with string keys.  So my code ends up a confusing mix of symbol and string keys. Or just as bad, repeated calls to `#sybmolize_keys` or `#with_indifferent_access`

Is there some reason to prefer only string keys? If not, I would request to add an option, perhaps in config, or maybe an optional param on `#to_h` or a different method that returns symbol keys.

**Comment by rmosolgo** [comment]
I chose strings from the start because this represents user input and we support Rubies which don't garbage-collect Symbols. So, if I had chosen symbols, we could be vulnerable to a DOS vulnerability. 

However, it's worth a look at whether these strings could be replaced by symbols. All arguments are whitelisted by the GraphQL schema, so we _might_ be able to switch to symbols without exposing that vulnerability. 

The one spot I'm not sure of is the static validation step: does it construct a `GraphQL::Arguments` instance _before_ validating the arguments? We have to make sure it doesn't, otherwise it could be a problem.

Alternatively, we could drop support for Ruby 2.1. I suppose it's [not officially supported anymore](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/), so it seems fair, but at the same time, I wouldn't want to cut someone off who depends on 2.1 for whatever reason!

**Comment by rmosolgo** [comment]
1.8 will drop support for Ruby 2.1, then we can take a look at redoing the internals here.

**Comment by rmosolgo** [comment]
In 1.8.3, arguments are passed as symbolized keywords and calling `#to_h` on an input object returns symbolized, underscore-keyed hash, so I think this works nicer in the class-based API!
