### ISSUE TITLE
resolve_type not working when querying

### ISSUE THREAD

**Issue by jordac67** [rmosolgo/graphql-ruby#867]
I've run into an issue where I'm questioning whether or not resolve_type is actually working. I noticed it when I started using interfaces in my project. From my understanding, `resolve_type` is responsible for mapping certain objects to specific types, but should fail when it can't find a match. I tried testing it out with faulty types and also tried raising a error
```
Schema = GraphQL::Schema.define do
  query QueryType
   resolve_type ->(type, obj, ctx) {
       raise "ERROR"
  }
end
```
However, the queries still go through and return a valid result, which makes me wonder if the lambda is doing anything at all. Is this the intended behavior?

**Comment by rmosolgo** [comment]
Can you share some info about your schema? 

For example, could you share a query which you expect to call `resolve_type`, and share the definitions involved with that query?

**Comment by jordac67** [comment]
Sure thing, here is a sample of a query that we're using. Also even when only raising an error in the `resolve_type` lambda, the query still executes perfectly fine.

##Schema.rb
```
Schema = GraphQL::Schema.define do
  resolve_type ->(type, obj, ctx) {
    case obj
    when NationalCrossSection
      NationalCrossSectionType
    else
      raise 'error'
    end
  }
  query QueryType
end
```
##QueryType
```
QueryType = GraphQL::ObjectType.define do
  name 'QueryType'
  description 'The root query'

  field :forecastedCumulativeReturns do
    type ForecastedCumulativeReturnsType
    argument :zip, !types.String
    resolve ForecastedCumulativeReturnsResolver.new
  end
end
```
##ForecastedCumulativeReturnType
```
ForecastedCumulativeReturnsType = GraphQL::ObjectType.define do
  name 'ForecastedCumulativeReturns'
  description 'description'

  field :nationalCrossSection do
    type NationalCrossSectionType
    description 'description'
    resolve NationalCrossSectionResolver.new
  end
end
```
##NationalCrossSectionType
```
NationalCrossSectionType = GraphQL::ObjectType.define do
  name 'NationalCrossSection'
  description 'description'

  field :id, !types.ID do
    description 'The id of the record'
  end

  field :recordedAt, !DateType, property: :recorded_at do
    description 'description'
  end
end
```

**Comment by rmosolgo** [comment]
`resolve_type` is only used for fields that return `UnionType` and `IntefaceType`. 

When a field returns an `ObjectType`, we don't need to call `resolve_type`, because we can use the type definition from the schema. We already know what type to use! 

So, `resolve_type` is not used with your schema because there aren't any unions or interfaces. 

Does that help?

**Comment by jordac67** [comment]
I'm sorry, the `type` I posted was wrong. I had removed the interface because of the issue, but this is how I had the `NationalCrossSectionType` before when i defined an interface:
**NationalCrossSectionType**
NationalCrossSectionType = GraphQL::ObjectType.define do
  name 'NationalCrossSection'
  description 'Provides nationwide cross section data'
  interfaces [ForecastedCumulativeReturnsInterface]
end

**ForecastedCumulativeReturnsInterface**
```
ForecastedCumulativeReturnsInterface = GraphQL::InterfaceType.define do
  name 'interface'
  description 'description'

  field :id, !types.ID do
    description 'The id of the record'
  end

  field :recordedAt, !DateType, property: :recorded_at do
    description 'The date a record was imported'
  end
end
```

**Comment by rmosolgo** [comment]
Thanks for those details, could you share a query that doesn't work as expected?

**Comment by jordac67** [comment]
Thanks for the response! This is the query we are using: 
```
forecastedCumulativeReturns(zip: "92305") {
    nationalCrossSection {
      id
    }
  }
```
The query goes through fine and returns the expected value, so that part is good. The confusing part that i mentioned previously was that `resolve_type` doesn't do anything regardless of what code i put in there, such as `raise "error"`. It seems the interface only looks to see if the `resolve_type` lambda is defined, but doesn't actually care what is inside the block. The only reason we're bothering trying to figure this out is because we want to make sure we understand 100% what `resolve_type` is doing before we use it in production. I hope this makes sense.

**Comment by rmosolgo** [comment]
Thanks for sharing a query! 

> forecastedCumulativeReturns(zip: "92305")

Does this correspond to this field? 

> ```ruby 
> field :forecastedCumulativeReturns do
>     type ForecastedCumulativeReturnsType
>     argument :zip, !types.String
>     resolve ForecastedCumulativeReturnsResolver.new
>  end
```

That field returns `ForecastedCumulativeReturnsType`, which is an object type: 

> ForecastedCumulativeReturnsType = GraphQL::ObjectType.define do

The next field returns `NationalCrossSectionType` which is also an object type: 

> NationalCrossSectionType = GraphQL::ObjectType.define do

Since none of the fields return interfaces, `resolve_type` is not called. 

I think there is some confusion between

```ruby
ForecastedCumulativeReturnsType = GraphQL::ObjectType.define do
```

which is returned by the field, and 

```
ForecastedCumulativeReturnsInterface = GraphQL::InterfaceType.define do
```

which is implemented by `NationalCrossSectionType`, but is not referenced in the query. 

Since all the graphql types in the query above are known ahead of type, `resolve_type` is not called! How does that sound?

**Comment by spectator** [comment]
This makes total sense, confusing part was that as soon as you have an interface in your object type you must provide `resolve_type` otherwise "schema contains Interfaces or Unions, so you must define a resolve_type" error is raised, so we were questioning our understanding of this -- `resolve_type` is required but not used :) Do you suggest to simply provide empty proc object in that case?

**Comment by rmosolgo** [comment]
Yes, an empty proc would be fine :) 

Sorry for the confusion, and I see your point. The library could be improved so that `resolve_type` is only required when a field _returns_ an Interface type, then this confusion would be addressed! I guess my first implementation was too heavy-handed 😬

**Comment by spectator** [comment]
Thanks a lot for explaining everything!

**Comment by jordac67** [comment]
@rmosolgo makes sense, thank you!
