### ISSUE TITLE
Idea: automated batch mutation generation from single mutation

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#886]
On a semi-regular basis I have a desire for a mutation that works identically to an existing mutation in the schema, but whos input object type is a list of the original mutations input. A contrived example:

```ruby
Types::MutationType = GraphQL::ObjectType.define do
  field :addReview, field: Mutations::AddReview.field
  field :batchAddReviews, field: Mutations::AddReviews.field
end

Mutations::AddReview = GraphQL::Relay::Mutation.define do
  name "AddReview"
  input_field :review, !types.String
  return_field :result, !types.Boolean
end

Mutations::AddReviews = GraphQL::Relay::Mutation.define do
  name "AddReviews"
  input_field :inputs, !types[Mutations::AddReviews.input_type]
  return_field :returns, !types[Mutations::AddReviews.return_type]
end
```

It seems like the creation of `AddReviews` could be trivially automated, perhaps even accessed simply with:
```ruby
field :batchAddReviews, field: Mutations::AddReviews.batch_field
# or for overriding field names with something less generic...
field :batchAddReviews, field: Mutations::AddReviews.batch_field(input_field: :reviews, return_field: :results)
```

**Comment by rmosolgo** [comment]
Sorry for the late response! It's hard for me to imagine building this into GraphQL-Ruby because of the performance considerations. It sounds like a way that N+1s might be introduced. I wonder if going the _other_ way, from a plural mutation -> singular mutation might avoid that. (In that case, the singular mutation is "just" a special case of the plural mutation: a case where each list has exactly 1 entry.) Then, all the application logic would be prepared for handling _n_ entries and could hopefully avoid DB access issues. 

Anyhow, if you're still pursuing this issue, maybe a good next step would be to share some example code as a gist or gem!
