### ISSUE TITLE
Field#resolve evaluates the @resolve_proc by Proc#call

### ISSUE THREAD

**Issue by karloku** [rmosolgo/graphql-ruby#89]
in lib/graphql/field.rb#L60
```ruby
  def resolve(object, arguments, context)
    @resolve_proc.call(object, arguments, context)
  end
```

Field instance evaluates the ```@resolve_proc``` by ```Proc#call```. This makes the execution context an instance of ```GraphQL::DefinitionHelpers::DefinedByConfig::DefinitionConfig```(where I defined the lambda). In this case, if I want to include helper methods that would be called by the ```@resolve_proc```, I have to add them into ```DefinitionConfig```. This seems odd to me.

It might be better if the ```@resolve_proc``` is called by ```#instance_exec(*args, &block)```, which makes the execution context to be the Field instance i defined. Thus I can include the helper methods into ```GraphQL::Field```

**Comment by rmosolgo** [comment]
Eh... I'm torn. I agree with your point that it's hard to extend `resolve` proc behavior. It's very weird that the `self` is the config object, not the `Field`. 

But, I really don't like messing with `self` when I can avoid it. It strikes me as one of those overly Ruby-ish tricks that seems fun and clever at the start, but ends up being hard to maintain. (The `.define` block messes with self, but that's only after a lot of hemming and hawing, and see what a weird situation it causes! It used to `yield(self)`).

I can think of a few other ways to provide helpers to field resolves:

 - Use helper modules directly: 

    ```ruby 
    resolve -> (obj, args, ctx) { 
      MyModule.helper_function(obj) + 1 
    } 
    ```

- Use other classes to implement resolve behaviors: 

   ```ruby 
   resolve -> (obj, args, ctx) { 
     resolution = MyFieldResolution.new(obj, args, ctx)
     resolution.value 
   }
   ``` 

  Of course, that custom class can have any extension you can imagine.

- Decorate the resolve proc:

   ```ruby 
   resolve MyModule.modify_proc(-> (obj, args, ctx) { obj })
   ```

    You can grab the proc and wrap it in another proc which contains extra logic. (This is how connection fields work in `graphql-relay-ruby`). 

Also, I don't like the idea of extending `GraphQL::Field`. It's a building block of the library, how should we prevent naming conflicts? (Or, _future_ naming conflicts?) I think it's better if `GraphQL::Field`'s API is _closed_ and modifying that class not supported. 

Here's one more idea: I was going to suggest _extending_ `GraphQL::Field`, but I realized that wouldn't do any good because `GraphQL::Field` is hardcoded into the library. What about changing that? For example, adding a module attribute `GraphQL.field_class` which _defaults_ to `GraphQL::Field`, but you could assign a custom implementation? That way users _could_ extend `GraphQL::Field` and use that extension in the library.

You could also make it Type-specific, so, for a given `ObjectType`, it would use a certain Field class.

**Comment by kliuless** [comment]
I agree w/ @rmosolgo - it seems best to use a module or class for helper methods.
To keep the method closer to the proc, you can define the method on the `ObjectType` instance:
```ruby
MyType = GraphQL::ObjectType.define do
  field :someField, types.String do
    resolve ->(obj, args, ctx) do
      MyType.some_helper(...)
    end
  end
end

# add a singleton method (note that MyType is not a class)
def MyType.some_helper(...)
  # helper code
end
```

Another technique (not tested):
Create a module like this:
```ruby
module MyModule
  extend self # or, module_function
  def resolve(obj, args, ctx)
    # resolver code now has access to MyModule
    helper(...)
  end
  def helper(...)
    # helper code
  end
end
```

Now you can reference that resovler in your `ObjectType` definition:
```ruby
field ... do
  resolve MyModule.method(:resolve)
end
```

**Comment by karloku** [comment]
Thank you @rmosolgo @kliuless .
I was convinced by the idea that ```GraphQL::Field``` and other base codes of the library should keep closed.  It seems that wrapping the helper codes in individual modules and calling them would be a better approach to refer the codes.

**Comment by rmosolgo** [comment]
Glad one of those will work for you!
