### ISSUE TITLE
Guide: Generators

### ISSUE THREAD

**Issue by skovy** [rmosolgo/graphql-ruby#937]
It may be helpful to add a note in the documentation about skipping GraphiQL in API only Rails apps? I had to re-run the generators to see the following output as to why GraphiQL was not automatically setup.

```
Skipped graphiql, as this rails project is API only
  You may wish to use GraphiQL.app for development: https://github.com/skevy/graphiql-app
```

**Comment by thefliik** [comment]
@Skovy  I must be using an older version of graphql-ruby, because in my rails api app GraphiQL was set up with the generator.

Everything about it worked fine (because its a Rails engine which, if I understand correctly, is basically a stand alone app) except it's assets weren't being served because there was no rails asset pipeline. Specifically, it expected `/javascripts/graphiql/rails/application.js` and `/stylesheets/graphiql/rails/application.css` files which weren't being served (course those files together are probably, basically, the whole GraphiQL app). To get around this, I composed the files myself from source and uploaded them to GitHub as Gists. Then, using [rawgit](https://rawgit.com) (which is necessary because of something like the mime/type Github serves gists with--I forget exactly--did this a while ago), I added a redirect to my routes so that `/javascripts/graphiql/rails/application.js` actually loads the rawgit gist. The end result is that GraphiQL works fine in dev mode in my rails api only app (even though I don't have the asset pipeline). 

This may be an easier solution than using GraphiQL.app for development?

The needed Gists

- [/javascripts/graphiql/rails/application.js](https://gist.github.com/thefliik/f360539533a64d9c1f806b09f04c2f6e)
- [/stylesheets/graphiql/rails/application.css](https://gist.github.com/thefliik/530cc796203fee0b3238a8f2f5770a85)

Even without GraphQL-Ruby's generators, you should be able to replicate this by adding the graphiql gem to your gemfile like so
```
gem 'graphiql-rails', group: :development
```
And updating your routes config like so:
```
if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"

    # Workaround for --API mode
    # rawgit is used to work around github's use of text/plain MIME types'

    get "/javascripts/graphiql/rails/application.js", to: redirect("') # <--insert link from rawgit
    get "/stylesheets/graphiql/rails/application.css", to: redirect("") # <--insert link from rawgit
end
```
Note, in the above routes config, you'll need to go to rawgit and copy and paste my gist file urls in to get your own link. I suspect rawgit monitors traffic based in some part on the link being used, so I don't want to share the link I'm using.

**Comment by thefliik** [comment]
Of course, one downside to this approach is the graphiql assets are not being updated. But at the moment, for development, its not a problem.

**Comment by rmosolgo** [comment]
thanks for sharing your solution, see also #1051  for a suggestion on how graphiql could be used in any Rack app. Feel free to open a PR to the docs if you think they need improvement!
